### ISSUE TITLE
Convert pth.tar to ONNX

### ISSUE THREAD

**Issue by PegAldernine** [mozilla/TTS#101]
Hi, I am trying to convert the trained model from torch into ONNX.
The conversion script target to run this function "torch.onnx.export". Most of the forward functions seems to run (when I call onnx.export) except the "forward" for "Decoder" from layer.tacotron.
Questions:
1. Can this model be converted to onnx? (Do you know is some layers are not currently supported?)
2. Do you know what am I doing wrong in the conversion script? (code and warnings/error below)
3. Is there an already converted model to onnx and if so from where can I download it?
Thanks in advance!

**Script:**

import torch
import torch.onnx
from models.tacotron import Tacotron
from layers.tacotron import Prenet

device_cuda = torch.device("cuda:0")
model = Tacotron().to(device_cuda)
state_dict = torch.load("F:/TTS_mozilla/TTS-master/best_model_v1.pth.tar")
just_model_dict = state_dict["model"]
model.load_state_dict(just_model_dict)
dummy_input = torch.randint(0, 24, (8, 128)).long().to(device_cuda)
torch.onnx.export(model, dummy_input, "onnx_model_name.onnx", verbose=True)

**Warnings:**

 | > Number of characters : 149
F:\TTS_mozilla\TTS-master\layers\tacotron.py:217: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if x.size(-1) == self.in_features:
F:\TTS_mozilla\TTS-master\layers\tacotron.py:227: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert x.size(1) == self.conv_bank_features * len(self.conv1d_banks)
F:\TTS_mozilla\TTS-master\layers\tacotron.py:234: TracerWarning: There are 2 live references to the data region being modified when tracing in-place operator add_. This might cause the trace to be incorrect, because all other views that also reference this data will not not reflect this change in the trace! On the other hand, if all other views use the same memory chunk, but are disjoint (e.g. are outputs of torch.split), this might still be safe.
  x += inputs
F:\TTS_mozilla\TTS-master\layers\tacotron.py:396: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  initial_memory = inputs.data.new(B, self.memory_dim * self.r).zero_()
F:\TTS_mozilla\TTS-master\layers\tacotron.py:401: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  attention_rnn_hidden = inputs.data.new(B, 256).zero_()
F:\TTS_mozilla\TTS-master\layers\tacotron.py:404: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  for _ in range(len(self.decoder_rnns))
F:\TTS_mozilla\TTS-master\layers\tacotron.py:406: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  current_context_vec = inputs.data.new(B, self.in_features).zero_()
F:\TTS_mozilla\TTS-master\layers\tacotron.py:408: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  attention = inputs.data.new(B, T).zero_()
F:\TTS_mozilla\TTS-master\layers\tacotron.py:409: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  attention_cum = inputs.data.new(B, T).zero_()

**Error:**

Traceback (most recent call last):
  File "_convert2onnx.py", line 14, in <module>
    torch.onnx.export(model, dummy_input, "onnx_model_name.onnx", verbose=True)
  File "C:\anaconda\envs\tts_env\lib\site-packages\torch\onnx\__init__.py", line 27, in export
    return utils.export(*args, **kwargs)
  File "C:\anaconda\envs\tts_env\lib\site-packages\torch\onnx\utils.py", line 104, in export
    operator_export_type=operator_export_type)
  File "C:\anaconda\envs\tts_env\lib\site-packages\torch\onnx\utils.py", line 281, in _export
    example_outputs, propagate)
  File "C:\anaconda\envs\tts_env\lib\site-packages\torch\onnx\utils.py", line 224, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "C:\anaconda\envs\tts_env\lib\site-packages\torch\onnx\utils.py", line 192, in _trace_and_get_graph_from_model
    trace, torch_out = torch.jit.get_trace_graph(model, args, _force_outplace=True)
  File "C:\anaconda\envs\tts_env\lib\site-packages\torch\jit\__init__.py", line 196, in get_trace_graph
    return LegacyTracedModule(f, _force_outplace)(*args, **kwargs)
  File "C:\anaconda\envs\tts_env\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\anaconda\envs\tts_env\lib\site-packages\torch\jit\__init__.py", line 251, in forward
    out = self.inner(*trace_inputs)
  File "C:\anaconda\envs\tts_env\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "C:\anaconda\envs\tts_env\lib\site-packages\torch\nn\modules\module.py", line 478, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "F:\TTS_mozilla\TTS-master\models\tacotron.py", line 37, in forward
    encoder_outputs, mel_specs, mask)
  File "C:\anaconda\envs\tts_env\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "C:\anaconda\envs\tts_env\lib\site-packages\torch\nn\modules\module.py", line 478, in _slow_forward
    result = self.forward(*input, **kwargs)
  **File "F:\TTS_mozilla\TTS-master\layers\tacotron.py", line 438, in forward**
    inputs, attention_cat, mask, t)
  File "C:\anaconda\envs\tts_env\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "C:\anaconda\envs\tts_env\lib\site-packages\torch\nn\modules\module.py", line 465, in _slow_forward
    input_vars = tuple(torch.autograd.function._iter_tensors(input))
  File "C:\anaconda\envs\tts_env\lib\site-packages\torch\autograd\function.py", line 284, in _iter
    for var in _iter(o):
  File "C:\anaconda\envs\tts_env\lib\site-packages\torch\autograd\function.py", line 293, in _iter
    if condition_msg else ""))
ValueError: Auto nesting doesn't know how to process an input object of type int. Accepted types: Tensors, or lists/tuples of them

**Comment by erogol** [comment]
I don't think ONNX supports dynamic loop unrolling, which is necessary for the Decoder.

Feel free to reopen if you need more.

**Comment by tsungruihon** [comment]
@mazzzystar @PegAldernine  same questions.
