### ISSUE TITLE
Where to pass text argument(Question)

### ISSUE THREAD

**Issue by dokuzbir** [mozilla/TTS#105]
I installed current master branch of `mozilla TTS`  and  `LJSpeech-1.1 `. Everything looks perfect except one step. From terminal what i need to excute to pass my text argument? I dont see usage documents

**Comment by erogol** [comment]
@dokuzbir you mean to run the code?

**Comment by dokuzbir** [comment]
I mean after `python train.py --config_path config.json --data_path ../LJSpeech-1.1/ | tee training.log` what should i do to get some outputs. More general how to use `mozilla TTS` after install

**Comment by erogol** [comment]
@dokuzbir you wait until your model satisfyingly trained and meanwhile you can check tensorboard for your model status. Then you use ```notebooks/Benchmark...``` to test your model.
