### ISSUE TITLE
Size mismatch for embedding.weight

### ISSUE THREAD

**Issue by BlueTaurus** [mozilla/TTS#110]
i am training it with my Arabic data set
i had set the parameter "text_cleaner": "basic_cleaners" in config.json with PyTorch = 1.0.1.post2 & Python =3.6.8
After 20000 steps i tried to take it on a run but it gives the following error

` > Loading model ...
 | > model config:  /home/muhammadali/current-TTS/TTS2/test/TTS-master/keep/TTS-dev-tweb-February-19-2019_06+55PM-2528864/config.json
 | > model file:  /home/muhammadali/current-TTS/TTS2/test/TTS-master/keep/TTS-dev-tweb-February-19-2019_06+55PM-2528864/checkpoint_20000.pth.tar
 > Setting up Audio Processor...
 | > fft size: 2048, hop length: 275, win length: 1102
 | > Audio Processor attributes.
   | > bits:None
   | > sample_rate:22050
   | > num_mels:80
   | > min_level_db:-100
   | > frame_shift_ms:12.5
   | > frame_length_ms:50
   | > ref_level_db:20
   | > num_freq:1025
   | > power:1.5
   | > preemphasis:0.97
   | > griffin_lim_iters:60
   | > signal_norm:True
   | > symmetric_norm:False
   | > mel_fmin:0
   | > mel_fmax:None
   | > max_norm:1.0
   | > clip_norm:True
   | > do_trim_silence:True
   | > n_fft:2048
   | > hop_length:275
   | > win_length:1102
 | > Number of characters : 149
Traceback (most recent call last):
  File "server/server.py", line 16, in <module>
    config.model_config, config.use_cuda)
  File "/home/muhammadali/current-TTS/TTS2/test/TTS-master/server/synthesizer.py", line 34, in load_model
    self.model.load_state_dict(cp['model'])
  File "/home/muhammadali/anaconda3/envs/mozilla3/lib/python3.6/site-packages/torch-1.0.1.post2-py3.6-linux-x86_64.egg/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Tacotron:
	size mismatch for embedding.weight: copying a param with shape torch.Size([179, 256]) from checkpoint, the shape in current model is torch.Size([149, 256]).`

**Comment by tsungruihon** [comment]
the same error as yours.

**Comment by wmute** [comment]
Also running into a size mismatch error with the latest model and the example server provided in the repository.

**Comment by gnosly** [comment]
I had got the same problem. I solved putting 
```
-        self.model = Tacotron(config.embedding_size, self.ap.num_freq, self.ap.num_mels, config.r)
+        self.model = Tacotron(149,config.embedding_size, self.ap.num_freq, self.ap.num_mels, config.r)

```
inside server/synthesizer.py.

It seems that a new first parameter was added into Tacotron but its call was not updated consequentially.

**Comment by BlueTaurus** [comment]
you are right @gnosly size mismatch was occurring due to addition of few characters

**Comment by tsungruihon** [comment]
@BlueTaurus @gnosly solved it too. thanks a lot.

**Comment by ice16** [comment]
@gnosly I use your method can solve but when I test at website I get this error
```RuntimeError: index out of range at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:191```

Do you know how to solve it?
