### ISSUE TITLE
Full dictionary is not installed for 'zh'

### ISSUE THREAD

**Issue by tsungruihon** [mozilla/TTS#112]
i have install `phonemizer` and `espeak` following `https://github.com/bootphon/phonemizer#languages`, i have set `"use_phonemes": true,
    "phoneme_language": "zh"`.
Then while the training process, it output `Full dictionary is not installed for 'zh'`

**Comment by erogol** [comment]
@tsungruihon sorry no idea, it is not about TTS. I guess you need something to install for espeak.

**Comment by gelodefaultbrain** [comment]
This something you need to configure with espeak. Hi! have you found the solution tho? Thanks @tsungruihon

**Comment by erogol** [comment]
you need to use espeak-ng for zh. I also updated the docs to suggest using it.
