### ISSUE TITLE
TypeError: stonemask() got an unexpected keyword argument 'fft_size'

### ISSUE THREAD

**Issue by tsungruihon** [mozilla/TTS#118]
I ran the code under branch `world-new`, named `extract_world.py`, trying to extract world features, then output an error, said `TypeError: stonemask() got an unexpected keyword argument 'fft_size'`

**Comment by tsungruihon** [comment]
which `pyworld` version that you used @erogol

**Comment by tsungruihon** [comment]
@erogol It seems that we should changed 

```
- f0_h = pw.stonemask(x, _f0_h, t_h, fs, fft_size=FFT_SIZE)
+ f0_h = pw.stonemask(x, _f0_h, t_h, fs)
```

**Comment by tsungruihon** [comment]
and it seems that we also need to change `f0`, `sp`, `ap` to `lf0`, `mgc` and `bap` using `merlin`. So that we can feed to the `NN`.

**Comment by erogol** [comment]
It's been a really long while I've not touched World vocoder hence I don't really remember the version if it is not written in ```setup.py```.  Pyworld may have some updates in the meantime.

You might also find this useful https://gist.github.com/erogol/92cdeca0e12c9ea3e79e518111b354c7

**Comment by tsungruihon** [comment]
@erogol thanks erogol. Looks like people is trying to use `LPCNet` mentioned at `https://github.com/mozilla/TTS/issues/9`.

**Comment by erogol** [comment]
@tsungruihon yeah I saw that. It is great people trying different things. I stick with WaveRNN for now with good results.

**Comment by erogol** [comment]
feel free to open again if you need it

**Comment by tsungruihon** [comment]
@erogol glad to hear that. Would you please share the relevant code of `tts` with `wavernn` or  tutorial?

**Comment by erogol** [comment]
@tsungruihon waiting for experiments. Soon to be merged here.
