### ISSUE TITLE
where could we find instruction about `audio_lws.py`

### ISSUE THREAD

**Issue by tsungruihon** [mozilla/TTS#122]
where could we find instruction about python file `audio_lws.py` ?

**Comment by erogol** [comment]
@tsungruihon it is not in use anymore, but mostly the same with audio.py and its parameters are explained in config.json.

**Comment by tsungruihon** [comment]
@erogol thanks a lot. I modified the `config.json` file and found that using `audio_lws.py` file could accelerate the `GL` speed. But the audio quality seems worse.

**Comment by erogol** [comment]
@tsungruihon it has some limitation for hop_lengths and so. Therefore, I give up on this.  But you can also implement GL on Pytorch and get GPU in use.

**Comment by tsungruihon** [comment]
@erogol thanks my friend.
