### ISSUE TITLE
force the audio sample rate to 48000 would harm the alignment or not

### ISSUE THREAD

**Issue by tsungruihon** [mozilla/TTS#124]
I am training a new Chinese datasets using `TTS`. The audios' sample are quite different. Some are 48000kHz and some are 44120kHz, even some are 22050kHz. 
Then i changed all the audios sample to 48000kHz using `pydub`, aimed to use `config.json` parameters. The transform code is below

```
from pydub import AudioSegment 

test_audio = AudioSegment.from_wav(src + src_wav_name)
test_audio = test_audio.set_frame_rate(48000)
test_audio.export(dst + src_wav_name, format='wav')
```

But the alignment seems not good.

![screen shot 2019-03-07 at 11 02 33 am](https://user-images.githubusercontent.com/11624203/53929387-92150a00-40c8-11e9-874c-8dfdbde91518.png)
![screen shot 2019-03-07 at 11 02 16 am](https://user-images.githubusercontent.com/11624203/53929389-92ada080-40c8-11e9-8b89-eb0f31ecbe67.png)

**Comment by erogol** [comment]
I don't think 44khz makes a big difference given the extra computation time it needs. So 44khz means longer audio signals to be reconstructed by the network. Therefore, it reduces the max batch size you can use and elongate each iteration.

But it looks above training well. One thing I see is that your spectrograms look very noisy. You might like to play with the audio parameters to reduce the base noise. I suggest you to check https://github.com/mozilla/TTS/wiki/Dataset
