### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by faaip** [mozilla/TTS#125]
Hey all!

Sorry that this might turn into setup help, but I'd love to get this running properly. After assistance I had the colab.google.com example up and running and I am now trying on an external GPU cluster machine. This is running in python3.6.3. 

I have followed all the same steps as in the example.ipynb, but when it comes to training I run into the following issues:

` > Using CUDA:  False
 > Number of GPUs:  0
 > Git Hash: 0a3dba4
 > Experiment folder: /work/kumulti/models/ljspeech_models/queue-March-07-2019_03+39PM-0a3dba4
 > Setting up Audio Processor...
 | > bits:None
 | > sample_rate:22050
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:12.5
 | > frame_length_ms:50
 | > ref_level_db:20
 | > num_freq:1025
 | > power:1.5
 | > preemphasis:0.98
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:False
 | > mel_fmin:0
 | > mel_fmax:None
 | > max_norm:1.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > n_fft:2048
 | > hop_length:275
 | > win_length:1102

 > Model has 7062290 parameters
Traceback (most recent call last):
  File "train.py", line 563, in <module>
    main(args)
  File "train.py", line 474, in main
    ap, epoch)
  File "train.py", line 79, in train
    data_loader = setup_loader(is_val=False, verbose=(epoch==0))
  File "train.py", line 62, in setup_loader
    verbose=verbose)
  File "/gpfs/gss1/work/kumulti/mozilla_tts/colab_script/TTS/datasets/TTSDataset.py", line 55, in __init__
    self.items = preprocessor(root_path, meta_file)
  File "/gpfs/gss1/work/kumulti/mozilla_tts/colab_script/TTS/datasets/preprocess.py", line 96, in ljspeech
    for line in ttf:
  File "/opt/sys/apps/python-intel/3.6.3/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 5699: ordinal not in range(128)
 ! Run is removed from /work/kumulti/models/ljspeech_models/queue-March-07-2019_03+39PM-0a3dba4`

I guess unicode errors are usually connected to some overlap between python2 and 3, but I'm not sure where to start with this. Do you have any idea on what the problem might be?

Thanks!

**Comment by erogol** [comment]
@faaip I need to update the colab example. There are many changes probably invalidating it.

**Comment by erogol** [comment]
probably will be solved with #132
