### ISSUE TITLE
Implement truncated inference for longer texts

### ISSUE THREAD

**Issue by erogol** [mozilla/TTS#126]
If you give a large piece of text, it needs to be split into memory friendly pieces and continuously processed by the network with separate batches by keeping the network states for the next batch.

**Comment by erogol** [comment]
done!

**Comment by tsungruihon** [comment]
@erogol hey erogol, does it now have been updated in the master branch ? thanks for answering.

**Comment by erogol** [comment]
@tsungruihon not yet. You can see when was the last update on the main page.

**Comment by tsungruihon** [comment]
@erogol thanks for your patience.
