### ISSUE TITLE
The first few syllables are cutoff

### ISSUE THREAD

**Issue by geneing** [mozilla/TTS#130]
Synthesized speech is always missing the first few syllables. 

For example run the benchmark notebook.  The first sentence "It took me quite a long time to develop a voice...", is missing "It". Or "Scientists at the CERN laboratory..." sounds like "ientists..."

This looks like a padding issue.

**Comment by erogol** [comment]
It is more about silence trimming. I don't know which model you use but the last model needs to be retrained with a higher silence threshold. Since the threshold is too low, sentences starts with a skipped syllable and ditto model learns to skip.
