### ISSUE TITLE
Setup a new language and new voice for mozilla tts

### ISSUE THREAD

**Issue by GERMANOCARELLA** [mozilla/TTS#131]
Hi,
I'm Germano from Italy.
I'm interested in your mozilla tts project.
I want to setup a new voice in italian language, by using my own voice.
I'm wondering if mozilla tts can perform this taks and, in case, how can I get started.
I'm under windows 10, using python 3.6 with anaconda3.
Thanks!

**Comment by erogol** [comment]
- Download and check LJSpeech dataset. Create a dataset similar to it.
- Follow https://github.com/mozilla/TTS/wiki

**Comment by GabrieleRisso** [comment]
@GERMANOCARELLA hello Germano. Did you made progress?
