### ISSUE TITLE
Get Error when "python3 server.py -c conf.json"

### ISSUE THREAD

**Issue by peter05010402** [mozilla/TTS#136]
(tensorflow-GPU) xjm@node-dev5:/mnt1/Peter/new_en/best_one/public_tts/wavs_v1.0/TTS-master/server$ python3 server.py -c conf.json
 > Loading model ...
 | > model config:  /mnt1/Peter/new_en/best_one/public_tts/wavs_v1.0/TTS-master/config.json
 | > model file:  /mnt1/Peter/new_en/best_one/public_tts/wavs_v1.0/TTS-master/best_model.pth.tar
 > Setting up Audio Processor...
 | > bits:None
 | > sample_rate:22050
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:12.5
 | > frame_length_ms:50
 | > ref_level_db:20
 | > num_freq:1025
 | > power:1.5
 | > preemphasis:0.98
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:False
 | > mel_fmin:0
 | > mel_fmax:None
 | > max_norm:1.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > n_fft:2048
 | > hop_length:275
 | > win_length:1102
Traceback (most recent call last):
  File "server.py", line 16, in <module>
    config.model_config, config.use_cuda)
  File "/mnt1/Peter/new_en/best_one/public_tts/wavs_v1.0/TTS-master/server/synthesizer.py", line 40, in load_model
    self.model.load_state_dict(cp['model'])
  File "/home/xjm/tensorflow-GPU/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Tacotron:
        size mismatch for embedding.weight: copying a param with shape torch.Size([61, 256]) from checkpoint, the shape in current model is torch.Size([129, 256]).
        size mismatch for decoder.proj_to_mel.weight: copying a param with shape torch.Size([160, 256]) from checkpoint, the shape in current model is torch.Size([400, 256]).
        size mismatch for decoder.proj_to_mel.bias: copying a param with shape torch.Size([160]) from checkpoint, the shape in current model is torch.Size([400]).
        size mismatch for decoder.stopnet.linear.weight: copying a param with shape torch.Size([1, 416]) from checkpoint, the shape in current model is torch.Size([1, 656]).

**Comment by erogol** [comment]
be sure you use the right commit version of TTS for the checkpoint you use. Reopen if the problem persists.

**Comment by peter05010402** [comment]
@erogol Thank you for your reply!
<img width="495" alt="屏幕快照 2019-03-22 下午11 32 40" src="https://user-images.githubusercontent.com/42974031/54834395-0b347400-4cfb-11e9-8c24-a14c21b6844e.png">
I git pull db7f3d3 and download iter-185k
Do you think is it OK?

**Comment by peter05010402** [comment]
It's latest error

Traceback (most recent call last):
  File "server/server.py", line 16, in <module>
    config.model_config, config.use_cuda)
  File "/mnt1/Peter/6_GST_Tacotron/speed_up-down_Trump_v0.0/best_one_v1.1/TTS/server/synthesizer.py", line 47, in load_model
    self.model.load_state_dict(cp['model'])
  File "/home/xjm/tensorflow-GPU/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Tacotron:
        Missing key(s) in state_dict: "decoder.attention_rnn_init.weight", "decoder.memory_init.weight", "decoder.decoder_rnn_inits.weight". 
        Unexpected key(s) in state_dict: "decoder.stopnet.rnn.weight_ih", "decoder.stopnet.rnn.weight_hh", "decoder.stopnet.rnn.bias_ih", "decoder.stopnet.rnn.bias_hh". 
        size mismatch for embedding.weight: copying a param with shape torch.Size([149, 256]) from checkpoint, the shape in current model is torch.Size([129, 256]).
        size mismatch for decoder.stopnet.linear.weight: copying a param with shape torch.Size([1, 400]) from checkpoint, the shape in current model is torch.Size([1, 656]).

**Comment by ice16** [comment]
@peter05010402 I have same problem. Are you able to solve the error?
