### ISSUE TITLE
 size mismatch for embedding.weight

### ISSUE THREAD

**Issue by peter05010402** [mozilla/TTS#138]
> Loading model ...
 | > model config:  /mnt1/Peter/test123/EN_TTS/mozilla/nansheng/TTS/config.json
 | > model file:  /mnt1/Peter/test123/EN_TTS/mozilla/nansheng/TTS/best_model.pth.tar
 > Setting up Audio Processor...
 | > bits:None
 | > sample_rate:22050
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:12.5
 | > frame_length_ms:50
 | > ref_level_db:20
 | > num_freq:1025
 | > power:1.5
 | > preemphasis:0.98
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:False
 | > mel_fmin:0
 | > mel_fmax:None
 | > max_norm:1.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > n_fft:2048
 | > hop_length:275
 | > win_length:1102
Traceback (most recent call last):
  File "server/server.py", line 16, in <module>
    config.model_config, config.use_cuda)
  File "/mnt1/Peter/test123/EN_TTS/mozilla/nansheng/TTS/server/synthesizer.py", line 41, in load_model
    self.model.load_state_dict(cp['model'])
  File "/home/xjm/tensorflow-GPU/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Tacotron:
        Missing key(s) in state_dict: "decoder.attention_rnn_init.weight", "decoder.memory_init.weight", "decoder.decoder_rnn_inits.weight". 
        size mismatch for embedding.weight: copying a param with shape torch.Size([149, 256]) from checkpoint, the shape in current model is torch.Size([129, 256]).

**Comment by peter05010402** [comment]
what's wrong？
could you help me?

**Comment by erogol** [comment]
Use the right commit checkpoint if you try to use a released checkpoint. Your checkpoint and the code has size mismatch.

**Comment by peter05010402** [comment]
@erogol  Thank you!
Then could you tell me Where Could I got the right checkpoint?

**Comment by peter05010402** [comment]
@erogol Thank you!
Then could you tell me Where Could I got the right checkpoint?

**Comment by erogol** [comment]
so do you use the corresponding commit ?

```git checkout  db7f3d3 ```

**Comment by erogol** [comment]
if not, pls use that commit. If yes, that's a bug, but alas you are on your own to fix it until I find some time to go over it.

**Comment by peter05010402** [comment]
@erogol thank you for your reply!
I do clone db7f3d3 and got the same error

**Comment by gnosly** [comment]
Hi @erogol, 
there is a misalignment between the git revision and the trained model.
I've created a fork with the fix. If you create a branch for db7f3d3 commit I can submit the MR.
Anyway you can take a look at my branch https://github.com/gnosly/TTS/tree/fix_185k_model

**Comment by peter05010402** [comment]
@gnosly   Thank you!!!

**Comment by erogol** [comment]
@gnosly here you go https://github.com/mozilla/TTS/tree/fix_db7f3d3

**Comment by peter05010402** [comment]
@erogol and @gnosly 
the db7f3d3 commit could run；
but the beginning of the generate wav lost:
“welcome"→”elcome“

**Comment by gnosly** [comment]
Yep. it is a problem training the model, right @erogol? 
As workaround you could add an exclamation mark before the sentence you want synthesize and later remove from the output audio the first samples corresponding to the word “exclamation mark”

Fabrizio

**Comment by erogol** [comment]
Yes it is about the model and a bit aggressive silence trimming silence trimming. You can try to retrain for a while with a beginning character with no silence trimming. Right now I use ~ as a sentence beginning char.

**Comment by peter05010402** [comment]
Thanks for reply!
the generate speed is a little slow on P100 GPU;
How to speed up?
