### ISSUE TITLE
synthesize a batch of sentences

### ISSUE THREAD

**Issue by tsungruihon** [mozilla/TTS#140]
I noticed that maybe long text could be split into several independent parts, and then let the `text2mel` model generate corresponding `mel` simultaneously, and finally concatenate them as one part .  Is it available for synthesizing batch sentences simultaneously using `TTS` ?

**Comment by tsungruihon** [comment]
it seems that in tensorflow version [TTS](https://github.com/begeekmyfriend/Tacotron-2/blob/mandarin-griffin-lim/tacotron/models/helpers.py), it predicts when to stop by judging whether `stop token probability` is bigger than 0.5. While in `TTS`, it not only just consider `stop token probability`, but also consider the `attention` part. 

Tensorflow version

```
def next_inputs(self, time, outputs, state, sample_ids, stop_token_prediction, name=None):
	'''Stop on EOS. Otherwise, pass the last output as the next input and pass through state.'''
	with tf.name_scope('TacoTestHelper'):
		#A sequence is finished when the output probability is > 0.5
		finished = tf.cast(tf.round(stop_token_prediction), tf.bool)

		#Since we are predicting r frames at each step, two modes are
		#then possible:
		#	Stop when the model outputs a p > 0.5 for any frame between r frames (Recommended)
		#	Stop when the model outputs a p > 0.5 for all r frames (Safer)
		#Note:
		#	With enough training steps, the model should be able to predict when to stop correctly
		#	and the use of stop_at_any = True would be recommended. If however the model didn't
		#	learn to stop correctly yet, (stops too soon) one could choose to use the safer option
		#	to get a correct synthesis
		if self.stop_at_any:
			finished = tf.reduce_any(tf.reduce_all(finished, axis=0)) #Recommended
		else:
			finished = tf.reduce_all(tf.reduce_all(finished, axis=0)) #Safer option

		# Feed last output frame as next input. outputs is [N, output_dim * r]
		next_inputs = outputs[:, -self._output_dim:]
		next_state = state
		return (finished, next_inputs, next_state)
```

```
Mozilla TTS version

            if memory is not None:
                if t >= T_decoder:
                    break
            else:
                if t > inputs.shape[1] / 4 and (stop_token > 0.6 or
                                                attention[:, -1].item() > 0.6):
                    break
                elif t > self.max_decoder_steps:
                    print("   | > Decoder stopped with 'max_decoder_steps")
                    break
```

**Comment by tsungruihon** [comment]
it’s a bit strange that use batch strategy to predict online.. 

If it is said that batch prediction is to split a very large piece of text into different parts and then generate each part, but the combination of different parts after splitting is also a problem because the combination of different parts back to a voice may cause the pause in it, which may sound not very natural.

**Comment by erogol** [comment]
@tsungruihon what I do is to split text into sentences and run each sentence then merge the results. I've also tried to pass states between sentences. It works sometimes good and sometimes bad that way. It is not pushed I guess yet but will be there after I am ready to release the latest work. Sorry for the wait.

**Comment by tsungruihon** [comment]
@erogol  can't wait to experience it. Thanks erogol.!

**Comment by tsungruihon** [comment]
@erogol May i ask how could you split text into sentences and run each sentence as a batch ?

**Comment by erogol** [comment]
```
for sentence in text.split('.'):
    # give sentence to TTS
# concat wav results
```
