### ISSUE TITLE
little problem in text process

### ISSUE THREAD

**Issue by EinsQiang** [mozilla/TTS#141]
https://github.com/mozilla/TTS/blob/5acc9db4ac95bb014fa04fdeb473c6d8ad09fb23/utils/text/__init__.py#L33

If the text only have one punctuation and not in the end of text. For example, "Mrs. Markham", it will out "'m|ɪ|s|ɪ|z| |\nm|ɑːɹ|k|æ|m| |t|oʊ|l|d| |p|oʊ| |'",  the ph will still have "\n" in it.

The one solution may be this:

```
if len(punctuations) == 1 and text[-1] != punctuations[-1]:
    ph = ph.replace('| | ', '|'+punct+'| |', 1)
else:
    for punct in punctuations[:-1]:
        ph = ph.replace('| | ', '|'+punct+'| |', 1)
        try:
            ph = ph[:-1] + punctuations[-1]
        except:
            print(text)
```

And if text contain "?", it still have "\n" in it. For example, "What are you doing here? asked his lordship.", will out "w|ʌ|t| |ɑːɹ| |j|uː| |d|uː|ɪ|ŋ| |h|ɪɹ| |\næ|s|k|t| |h|ɪ|z| |l|ɔːɹ|d|ʃ|ɪ|p| ."

https://github.com/mozilla/TTS/blob/5acc9db4ac95bb014fa04fdeb473c6d8ad09fb23/utils/text/__init__.py#L20

May be change this line to:

```
pat = r'['+_phoneme_punctuations+']+'
```

**Comment by erogol** [comment]
@EinsQiang thx for pointing. Fixed but not merged yet.
