### ISSUE TITLE
Generate Speed a little low

### ISSUE THREAD

**Issue by peter05010402** [mozilla/TTS#142]
on P100 GPU, It takes 1 second to generate 1 second wav file;
And GPU only occupy less than 1GB?
How to speed up?

**Comment by erogol** [comment]
@peter05010402 using GPU for Tacotron model does not make much of a difference. There are not much alternative without more engineering. You can go for pytorch c++ API or improve the model execution with inspecting model performance with a profiling tool.

**Comment by peter05010402** [comment]
@erogol  Thank you for your reply
