### ISSUE TITLE
EspeakBackend for Miniconda3 Windows 10

### ISSUE THREAD

**Issue by DrHaqkiem** [mozilla/TTS#148]
Hi !
I really really really want to know if there is any way i can install Espeakbackend for Windows.

I got the error:

RuntimeError: <function EspeakBackend.name at 0x7f4db349df28> not installed on your system

if im on ubuntu, i can simply 'sudo apt-get install espeak' .

But how about windows? 

Really need to know this. Hope you can help me with this issue 🙏

**Comment by erogol** [comment]
Use can use WSL on windows to run ubuntu backend. http://www.erogol.com/using-windows-wsl-for-deep-learning-development/

**Comment by PasaOpasen** [comment]
> Hi !
> I really really really want to know if there is any way i can install Espeakbackend for Windows.
> 
> I got the error:
> 
> RuntimeError: <function EspeakBackend.name at 0x7f4db349df28> not installed on your system
> 
> if im on ubuntu, i can simply 'sudo apt-get install espeak' .
> 
> But how about windows?
> 
> Really need to know this. Hope you can help me with this issue 🙏

Have u found a way? I have similar problem and cannot use the way by WSL

**Comment by nmstoker** [comment]
Have you tried the MSI installer from espeak-ng?

I know some people prefer installing espeak over espeak-ng, but realistically it's not great to be using code that's been unmaintained for 5+ years (as espeak has).
Espeak-ng is a drop in replacement, that *is* maintained (although the repo/community has a few oddities too)

Anyway, check out the **Assets** section for the MSI here: https://github.com/espeak-ng/espeak-ng/releases/tag/1.50

**NB:** I haven't tried this myself as I don't have a suitable Windows machine to install on, but it seems like a plausible approach. YMMV as they say! :slightly_smiling_face: 

Would be great if you could update people on your progress (positive or negative)

**Comment by lokkelvin2** [comment]
@PasaOpasen This is an environment path issue with phonemizer. See [#44](https://github.com/bootphon/phonemizer/issues/44).

**Comment by GuntaButya** [comment]
Binaries for espeak-ng:
https://chromium.googlesource.com/chromiumos/third_party/espeak-ng/#binaries

**Comment by GuntaButya** [comment]
Download and install the Windows version of espeak: http://espeak.sourceforge.net/download.html

If you are unable to run this command in the Command Prompt (cmd.exe):

`espeak "text"`

From the Command Prompt, you need to run this command, in the Command Prompt (cmd.exe), may need to Run As Administrator, by Right Clicking. 

![ComWindows10](https://user-images.githubusercontent.com/24576124/102962412-8a8b5300-4532-11eb-889e-654439a73305.png)


Run:

`set PATH=%PATH%;C:\Program Files (x86)\eSpeak\command_line\`

and Restart your Computer. Run the same command again from the Command Prompt (cmd.exe):

`espeak "text"`

This should work! At this point, your python TTS Code should work if everything else is ok! Python is looking for the espeak path, in your Path Environment Variable, its not here by default. Good Luck!

**Comment by Jzow** [comment]
@GuntaButya @nmstoker hi guys , I refer to this setting but still report an error. Can you check it for me? Thank you very much for my issue: #742

**Comment by nmstoker** [comment]
Hi @Jzow - I think you must have not noticed but this repo isn't being maintained. As you'll see, there have been no commits in 12 months.
Best to look at https://github.com/coqui-ai/TTS
