### ISSUE TITLE
Runtime error: CUDA out of Memory

### ISSUE THREAD

**Issue by DrHaqkiem** [mozilla/TTS#149]
Hi. Thank you for your response on my previous issues. I really appreciate it. Im progressing very much due to your response. I got few more to ask. 

I'm running your codes on NVIDIA GEFORCE 940MX with 32 batch size-  (**_No. of GPU: 1_**).
Ubuntu 18.04, CUDA version 10.1.

However, during the **_0/1000 epoch_**,  I was getting the error as stated below:

**`**`cuda out of memory. tried to allocate 78.88 mib (gpu 0; 3.95 gib total capacity; 2.99 gib already allocated; 74.44 mib free; 557.82 mib cached)`**`**

I add the below modification on the **train.py**:
- **_setting up Variable(volatile=true) on the input variable_**

But the same error occur.

My question is:

1. Why is that happening ?
2. How exactly i'm going to overcome such Runtime erorr ?
3. I reduce the batch size from 32bs to 16bs. It work but i only observed until 3/1000 epoch then 
    I stop. Assuming that it will go well for the next epoch until 1000th.
    But is it good to reduce the batch size ?
4. As stated on the config.json file - **_Lower values than 32 might cause hard to learn attention_**.
  What is it mean by **cause hard to learn attention** ? and what is **learn attention** ?
5. Do I really need to run the training with **_1000 epoch_** ? 
    What will happen when i run less than **1000 epoch** ?

-------------------------------------------------------------------------------------------------------

6. Why can't I initialize my CUDA GPU while I'm on WSL environment? 
    Can't even install the NVIDIA driver.

**Comment by erogol** [comment]
This is why its happening "cuda out of memory == your GPU memory is not enough". Try smaller batch sizes.
