### ISSUE TITLE
 Error(s) in loading state_dict for Tacotron: 	size mismatch for embedding.weight

### ISSUE THREAD

**Issue by ice16** [mozilla/TTS#155]
I use the best model that share in here. (best_model.pth.tar.)
When I run
```python server/server.py -c server/conf.json```

I get the error:

```
RuntimeError: Error(s) in loading state_dict for Tacotron:
	size mismatch for embedding.weight: copying a param with shape torch.Size([61, 256]) from checkpoint, the shape in current model is torch.Size([129, 256]).
```
Can I know how to solve it?

**Comment by erogol** [comment]
use the right commit version for the chekcpoint

**Comment by ice16** [comment]
How can I know which one is right version? I download the link your given at website

**Comment by erogol** [comment]
given here https://github.com/mozilla/TTS#checkpoints-and-audio-samples column commit

**Comment by ice16** [comment]
sorry, I follow already column commit but still have same error

**Comment by joshuadeisenberg** [comment]
I'm having this same issue, but with the db7f3d3 commit (which is the Best: iter-185K model). This seems to be the same problem as https://github.com/mozilla/TTS/issues/154  and https://github.com/mozilla/TTS/issues/150

Are there any models that don't have this issue?

**Comment by erogol** [comment]
https://github.com/mozilla/TTS/issues/154#issuecomment-483165079
