### ISSUE TITLE
ValueError: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by Silerqin** [mozilla/TTS#161]
I have error ```Error: INTERNAL SERVER ERROR```when I press speak button in html. I get this error in terminal:

```       return ufunc.reduce(obj, axis, dtype, out, **passkwargs)```
```ValueError: zero-size array to reduction operation maximum which has no identity```

**Comment by DrHaqkiem** [comment]
1. Check your audio dataset, makesure the file is not empty.
2. Make sure you have train.csv and valid.csv splitted from metadata.csv

those mentioned above solved my problem regarding zero-size array.
