### ISSUE TITLE
why are some synthsized sentences incomplete?

### ISSUE THREAD

**Issue by NewEricWang** [mozilla/TTS#170]
Hi, I use my dataset to train model. When synthesizing, some synthesized sentences are incomplete. Their latter parts can not be synthesized. Any guidance will be appreciated.

**Comment by erogol** [comment]
https://github.com/mozilla/TTS/issues/171#issuecomment-486236218

**Comment by NewEricWang** [comment]
@erogol ， Thanks for your answer. I agree with you that it is problem of attention. Especially, the stop token of the sentence is predicted incorrectly by the attention network in decoder. 
I try set windowing=true, but it is no help for the problem. 
Could you tell me how to force the decoder to output whole sentence？ 
Or how to detect the stop position in input sentence before the decoder stop working? If I can get the position, I will split the sentence into multiple sentences as input.

**Comment by erogol** [comment]
let me see the attention plot for that sentence

**Comment by NewEricWang** [comment]
@erogol,
Two alignment plots are as follows:
/home/hlw74/Downloads/mzl_tts/chnby_v1/t250k_dmdtest_v2_2/plots/alignment-2_checkpoint_250000.pth.tar.png
/home/hlw74/Downloads/mzl_tts/chnby_v1/t250k_dmdtest_v2_2/plots/alignment-11_checkpoint_250000.pth.tar.png

Could you tell me: 
1、What does stop_tokens outputted from model.forward mean? Its length? Its value above 0.5?
2、How does stop_tokens correspond to the alignment?

**Comment by erogol** [comment]
You need to work your way out by checking the source code to find out these. Basically, model outputs top token per prediction to decide if it is the end of the sentence or not. However, in benchmark notebook, it shows stop token output with the visualizations. It also looks like you do not trim silence in your dataset. Set ```trim_silence: true``` in config.json. 

Is it tacotron or tacotron2?

**Comment by NewEricWang** [comment]
Thanks!
It is default setup in mazzila_tts. I think it is tacotron.
I set trim_silence=false because I find it is easy to trimmed at sentence begin and end. 
After checking the source code, I find predicted stop_tokens score is above 0.6 in these trimmed sentence.

**Comment by erogol** [comment]
You can play with the threshold if it saves the case. But I guess your problem is more about the alignment and my guess is to use trim silence. Hope it helps.

**Comment by NewEricWang** [comment]
@erogol, Thank you very much!
I change the stop_token's threshold from 0.6 to 0.9, the problem disappears. But I know its risk is the decoder can't stop at the end of some sentences in some cases.  The modified code is as follows: 

{{
if t > inputs.shape[1] / 4 and (stop_token > 0.9 or
                                                attention[:, -1].item() > 0.6):
}}

Could you tell me how to get the character or phoneme that each  predicted stop_token is mapped to for each times?
Or is it impossible at all?

**Comment by NewEricWang** [comment]
@erogol ,
Ok! I fix it! Thank for your generous help!

**Comment by zainmujahid** [comment]
@NewEricWang please let me know how you solved this issue? I am having a same issue with 2 of my custom datasets.
