### ISSUE TITLE
Training time with LJSpeech

### ISSUE THREAD

**Issue by nmstoker** [mozilla/TTS#181]
_(sorry not strictly an issue, but hope someone can advise!)_

What's a typical range for training time for LJSpeech on a single GPU (GTX 1080Ti) with an averagely spec'd PC?

I ask as I've been running it using [these instructions](https://gist.github.com/erogol/97516ad65b44dbddb8cd694953187c5b) from the [README](https://github.com/mozilla/TTS#training-and-fine-tuning-lj-speech) and although it has been running much of today, the number of epochs reached is low (currently showing 5 but I'd done maybe 10 before I had to restart for an unrelated reason).  The audio does just recently have a hint of sound that's ever so slightly like (very) distorted speech, but am just hoping this isn't going to need ages more, eg a whole week?

Originally I had been trying to train with a large private set of recorded data I produced myself (~10hr of recordings I'd read) but that was taking even longer with no sign of progress (had been going from Friday night till early today with just odd noise in the audio output). I did prune out bad recordings and some of the short ones so that it's more balanced (hoping to follow the advice in the wiki and those two notebooks on analysis and spectrograms) but I figured I'd best see if I can walk before I run (ie try to get LJ Speech working first) :slightly_smiling_face: 

**Probably a newbie question, but can I confirm:** where the output says "GlobalStep" that is the same as iterations isn't it? I'm at 11k on that basis now and given the figures shown for the models in the README are in the ~185k range, that would suggest I'd need several more days to get close - does that sound right?

**Comment by erogol** [comment]
yes you need around 100K to have a good result and after 30K it should be reasonable for LJSpeech but for a new dataset, I cannot guess. You should run https://github.com/mozilla/TTS/tree/master/dataset_analysis before training to see if your dataset is good. And pls check the wiki there are some notes for a good dataset.

**Comment by nmstoker** [comment]
Thanks for getting back to me Eren. V helpful. The dataset_analysis notebook was useful

Thanks also for this project itself - it's really impressive 🙂
