### ISSUE TITLE
Missing documentation on usage

### ISSUE THREAD

**Issue by Whytehorse** [mozilla/TTS#182]
I'm completely new to this project and I'd like to test it out but there's no man page or documentation on usage. Maybe add something to the readme.md like:
```
command <argument>
example: command arg1 file input output
```

you know, just how to use it for new people.

**Comment by erogol** [comment]
check the wiki

**Comment by Whytehorse** [comment]
Thanks! I checked the wiki and found instructions on running a web server. Is there a command-line version like 
python textTospeech.py "some text"

**Comment by erogol** [comment]
there isn't. You can write one (the best case) or you can use a benchmark notebook.
