### ISSUE TITLE
TTS performance in relation to other solutions.

### ISSUE THREAD

**Issue by erogol** [mozilla/TTS#186]
![image](https://user-images.githubusercontent.com/1402048/58020313-155ecd00-7b08-11e9-9ed7-18c2f598b8a9.png)

Above you can see the figure comparing TTS with the other commercial and non-commercial solutions. Comparison has been made by asking ~500 human participants after they listen to the same article from all these solutions. 

TLDR; It is not the best (yet) but good to see an open-source project is comparable with big commercial solutions!

Models are defined as follows:
Mozilla TTS Nancy2: Tacotron2 + WaveRNN 
Mozilla TTS Nancy: Tacotron
Mozilla TTS LJSpeech: Tacotron

Note that .\<name\> are real people reading the same article.

**Comment by tsungruihon** [comment]
Glad to see that.! Could we train `TTS` (tacotron2 version) using `dev-tacotron2` branch?

**Comment by mrgloom** [comment]
What is Nancy 2 dataset?

**Comment by PetrochukM** [comment]
What article did you ask the 500 participants to read?

**Comment by erogol** [comment]
Added
