### ISSUE TITLE
Extract timing of phonemes and words from synthesized speech

### ISSUE THREAD

**Issue by joshuadeisenberg** [mozilla/TTS#188]
Hey all!

Thankfully I have been able to get the pre-trained model up and running, and producing great synthesized speech. 

I am wondering if there is a way to get the start and stop times of each word in the synthesized WAV file? I really want the start and stop time of each phoneme of each word. I'm wondering if this is something that is already part of the library, and if it's not I was wondering if anyone knew what part of the library I should modify to calculate these timings.

I know I could use an acoustic model to calculate this, but this is overkill, and I thought it would be better to find a solution that's already in the TTS library.

Some context: I want to animate a face / mouth to speak while the synthesized audio is playing. In order to do this I need the start and stop time of each phoneme in the synthesized speech.

Any advice will be greatly appreciated.

Thanks!

Josh

**Comment by erogol** [comment]
there is no way to do it with TTS library. But you can try to extract timing information by using the attention map. Don't know exactly how but this is my best guess. Also, it is better to post there next time, since this is not a real issue. https://discourse.mozilla.org/c/tts

**Comment by joshuadeisenberg** [comment]
Awesome. Thanks for the hint. Will report back / post on discourse for this type of question.

TTHANKS

**Comment by pierz** [comment]
> 
Did u get anywhere with this issue?
