### ISSUE TITLE
Implement Griffin-Lim on Pytorch after Pytorch 4.0 release

### ISSUE THREAD

**Issue by erogol** [mozilla/TTS#19]
http://pytorch.org/docs/master/torch.html?highlight=stft#torch.stft still waiting unstable.

**Comment by erogol** [comment]
https://github.com/pseeth/pytorch-stft seems useful

**Comment by erogol** [comment]
Now I try to adapt the above repo. It seems slower in training but much faster in on GPU test time .

**Comment by tsungruihon** [comment]
@erogol could you show some example that using  [https://github.com/pseeth/pytorch-stft](https://github.com/pseeth/pytorch-stft)

**Comment by erogol** [comment]
@tsungruihon I don't have related files anymore. But should be easy for you to try it. Just replace things with https://github.com/pseeth/pytorch-stft .

Or if you like to test the runtime speed, just compare it with librosa with random vectors.

**Comment by tsungruihon** [comment]
Thanks erogol. @erogol

**Comment by tsungruihon** [comment]
Now i have figured out the normal audio sound. But it seems that the [PyTorch griffin lim](https://github.com/NVIDIA/tacotron2/blob/master/audio_processing.py#L59) time is much longer than the [tensorflow version](https://github.com/keithito/tacotron/blob/master/util/audio.py#L78).

```
signal_norm = True
symmetric_norm = False
clip_norm = True
max_norm = 1
min_level_db = -100
ref_level_db = 20
preemphasis = 0.98

def apply_inv_preemphasis(x):
    if preemphasis == 0:
        raise RuntimeError(" !! Preemphasis is applied with factor 0.0. ")
    return signal.lfilter([1], [1, -preemphasis], x)

def _denormalize(S):
    """denormalize values"""
    S_denorm = S
    if signal_norm:
        if symmetric_norm:
            if clip_norm:
                S_denorm = np.clip(S_denorm, -max_norm, max_norm) 
            S_denorm = ((S_denorm + max_norm) * -min_level_db / (2 * max_norm)) + min_level_db
            return S_denorm
        else:
            if clip_norm:
                S_denorm = np.clip(S_denorm, 0, max_norm)
            S_denorm = (S_denorm * -min_level_db /
                max_norm) + min_level_db
            return S_denorm
    else:
        return S
    
def _db_to_amp(x):
    return np.power(10.0, x * 0.05)

spec = np.load('spec_test_1_48000.npy')
spec = _denormalize(spec.T)
spec = _db_to_amp(spec + ref_level_db)
spec = spec ** 1.5
spec = torch.from_numpy(spec).unsqueeze(0)

spec = spec.cuda()

stft_fn = STFT(filter_length=4096, 
               hop_length=600, 
               win_length=2400)

stft_fn_cuda = stft_fn.cuda()
y = griffin_lim(spec, stft_fn_cuda, n_iters=40)
y_data = y.data.cpu().numpy()
y_data = apply_inv_preemphasis(y_data)
```

**Comment by mrgloom** [comment]
@tsungruihon This code should be applied to `postnet_output.T` directly?

**Comment by tsungruihon** [comment]
@mrgloom  yes i guess so.
