### ISSUE TITLE
size mismatch

### ISSUE THREAD

**Issue by goandrei** [mozilla/TTS#190]
Hi,

I'm trying to do an inference on the latest model, but I get this error:
_size mismatch for embedding.weight: copying a param with shape torch.Size([61, 256]) from checkpoint, the shape in current model is torch.Size([256, 256])._

I read all the related posts but nothing helped. I am running the notebook on fix_db7f3d3. Changing the num_chars to 61 works, but the result is quite bad(just some random noise).
Also I can't run all examples using num_chars=61 due to the lack of embedding for some characters.
What can I do in order to make it work? Thank you!

**Comment by erogol** [comment]
I don't think you use the right commit version of the repository for that checkpoint you use. 
```git checkout fix_db7f3d3``` before you run anything.

**Comment by goandrei** [comment]
Actually I do. I figured out that the problem with the embedding layer mismatch was solved only on the server application. I was using the notebook from notebooks directory which used other functions for tts
