### ISSUE TITLE
SymbolsTest broken

### ISSUE THREAD

**Issue by twerkmeister** [mozilla/TTS#193]
Seems the uniqueness test for symbols is broken. The space symbol appears twice in the phonemes, once inside the `_phonemes` array and once in `punctuation`. Not sure what was originally planned here

**Comment by erogol** [comment]
which file are you pointing exactly?

**Comment by twerkmeister** [comment]
Sorry my bad, nevermind, my IDE found the test from the master branch of the repo, because I have both my fork and the original repo open in the same project. 😩
