### ISSUE TITLE
Quality of the dataset

### ISSUE THREAD

**Issue by DrHaqkiem** [mozilla/TTS#199]
hi @erogol. I'm currently using your code to try on Malaysia-TTS. But i got a few question to ask:

1. Is it necessary for me to develop a corpus that contains **all Malay words** ?

2. Does a **good voice intonation** will help to get a better model and human like sound? 

3. If my corpus **contains many repeated words**, will the model becomes good?

4. Let say i have **a word** that can be found in many audio file of my dataset. But that **one particular word** from each of the audio file has **different intonation**.

**How can the model generalize** the different voice intonation when it comes to text to speech ?

5. Why we need the metadata.csv alongside the audio dataset? Is the audio file itself not enough to make a successful tts ?

**Comment by erogol** [comment]
Post this on discourse. This is not really TTS related.
