### ISSUE TITLE
Tacotron2 fails for short sentences

### ISSUE THREAD

**Issue by mrgloom** [mozilla/TTS#201]
I'm testing tacotron2+wavernn from dev-tacotron2 branch and it seems that tacotron2 performs poorly for short sentences.

Models:
```
pretrained_models/
├── ljspeech-260k
│   ├── checkpoint_260000.pth.tar
│   └── config.json
└── mold_ljspeech_best_model
    ├── checkpoint_433000.pth.tar
    └── config.json
```

Code based on `Benchmark.ipynb`:
```
model.eval()
model.decoder.max_decoder_steps = 2000
sentence =  "Hello!"
align, spec, stop_tokens, wav = tts(model, sentence, CONFIG, use_cuda, ap, use_gl=use_gl, figures=True)
```

<img width="548" alt="Screenshot 2019-05-20 at 12 46 19" src="https://user-images.githubusercontent.com/4003908/58012507-4f76a180-7afd-11e9-8581-20ac8e121f4b.png">

[Hello.wav.zip](https://github.com/mozilla/TTS/files/3197263/Hello.wav.zip)

Why tacotron2 have this limitations? How it can be fixed?

**Comment by erogol** [comment]
Train with a dataset with shorter sentences. You can also enable attention windowing.

**Comment by mrgloom** [comment]
Looks like this suggestion is also mentioned here in tips and tricks section:
`The second trick is to force monotonic attention during inference using a fixed size window`
https://nvidia.github.io/OpenSeq2Seq/html/speech-synthesis/centaur.html#tips-and-tricks
Is there any paper where it described in more detail?

**Comment by erogol** [comment]
it is already implemented just set it true.

**Comment by mrgloom** [comment]
BTW `CONFIG.windowing = True` was set in this example.
