### ISSUE TITLE
Transformer TTS

### ISSUE THREAD

**Issue by WhiteFu** [mozilla/TTS#203]
Have you considered trying to add transformer TTS repo?  The result in the article is great and the convergence speed is 4-5 times faster than tacotron.
The URL is as follow:
https://arxiv.org/abs/1809.08895

**Comment by erogol** [comment]
Thx for pointing out. Has been a while that I read this. 

The transformer is a memory monster. If you look at the paper in detail, they could not even train it with a single GPU which they call it unstable. Therefore, I don't think transformer is the right architecture for us. We intentionally keep things small and simple for everyone to use. 

Being said that, any pull request is always welcome.
