### ISSUE TITLE
Training WaveRNN

### ISSUE THREAD

**Issue by mrgloom** [mozilla/TTS#208]
Is [WaveRNN](https://github.com/erogol/WaveRNN) trained on ground truth data and data should be prepared with [extract_features.py](https://github.com/erogol/WaveRNN/blob/master/extract_features.py) or it should be trained on data produced by tacotron2 and data should be prepared with [ExtractTTSpectrogram.ipynb](https://github.com/erogol/WaveRNN/blob/master/notebooks/ExtractTTSpectrogram.ipynb) ?

**Comment by erogol** [comment]
the latter

**Comment by mrgloom** [comment]
From where `METADATA_FILE = "prompts_train.data"` should come from?

**Comment by mrgloom** [comment]
For ljspeech:
`METADATA_FILE = "prompts_train.data"` -> `METADATA_FILE = "metadata.csv"`

`dataset = MyDataset(DATA_PATH, METADATA_FILE, C.r, C.text_cleaner, ap, nancy, use_phonemes=C.use_phonemes,  phoneme_cache_path=C.phoneme_cache_path)` -> `dataset = MyDataset(DATA_PATH, METADATA_FILE, C.r, C.text_cleaner, ap, ljspeech, use_phonemes=C.use_phonemes,  phoneme_cache_path=C.phoneme_cache_path)`

https://github.com/erogol/WaveRNN/blob/master/notebooks/ExtractTTSpectrogram.ipynb
