### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by AminUCo** [mozilla/TTS#21]
I want use pretrained network so I  used the Notebook under notebooks folder.
but:
ModuleNotFoundError: No module named 'torchviz'
I use conda and pip for install 'torchviz' but : 
  "Could not find a version that satisfies the requirement torchviz (from versions: )
No matching distribution found for torchviz"

# solve:
pip install git+https://github.com/szagoruyko/pytorchviz

**Comment by erogol** [comment]
You can just remove it. It is not necessary anymore. It is gonna be scraped by the next update.
