### ISSUE TITLE
Bus error (core dumped)

### ISSUE THREAD

**Issue by MuruganR96** [mozilla/TTS#211]
sir i was try to run tacotron-2 tts model. but it was shown,]
**Bus error (core dumped)**

```
python3 server/server.py -c server/conf.json
Bus error (core dumped)
```
i think it is Memory issue. 
my system have 24 GB RAM, 4 GB GPU.
but it was not running. 

how much memory we need to run on tacotron-2 model.?

**Comment by erogol** [comment]
I've no idea what it is about. 4GBis more than enough for inference.But people already complained about server.py not being compatible with T2 model. I'll fix it soon.
