### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'mulaw'

### ISSUE THREAD

**Issue by MuruganR96** [mozilla/TTS#217]
I tried for Tacotron-2 TTS.

```
git clone https://github.com/mozilla/TTS.git
cd TTS
git checkout -b 824c091

pip install -r requirements.txt

git clone https://github.com/erogol/WaveRNN.git
cd WaveRNN
git checkout -b 8a1c152

pip install -r requirements.txt
pip install soundfile

```
and i was downloaded **LJSpeech_model and WaveRNN-MOLD** Models.
 
Like this.
WaveRNN-MOLD:
https://drive.google.com/drive/folders/1Xvx7Ce7STSLCr79gxo0Ou9sZ6b8pyQu9

LJSpeech_model Tacotron-2:
https://drive.google.com/drive/folders/1FJRjGDAqWIyZRX4CsppaIPEW8UWXCWzF

when i run this server,
`python3 server/server.py -c server/conf.json`

it was given error.
```
Traceback (most recent call last):
  File "server/server.py", line 3, in <module>
    from synthesizer import Synthesizer
  File "/home/dell/Murugan_R/17-06-2019/TTS/server/synthesizer.py", line 3
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax
```
i resolved this one. but again occurred some issues, 

`AttributeError: 'AttrDict' object has no attribute 'prenet_dropout'`

`AttributeError: 'AttrDict' object has no attribute 'location_attn'`

`AttributeError: 'AttrDict' object has no attribute 'separate_stopnet'`

arguments missing in pretrained model **config.json** .

then i was added,
```
"prenet_dropout": false,
"location_attn": true,
"separate_stopnet": false,
```
that error was gone.
but then shape mismatch error occured.
```
RuntimeError: Error(s) in loading state_dict for Tacotron2:
	size mismatch for embedding.weight: copying a param with shape torch.Size([62, 512]) from checkpoint, the shape in current model is torch.Size([130, 512]).
```
actually,
if "use_phonemes": true means **TTS phonemes 130.** returned defaultly. [130, 512]

but pretrained model showing [62, 512] size.

so i was defaultly assigned TTS phonemes as 62.

that  error also gone.

again one more error was occurred.
`TypeError: __init__() missing 1 required positional argument: 'mulaw'`

arguments missing in pretrained WaveRNN-MOLD model **config.json** .

this time can't find anything, because 

```
self.wavernn = Model(
                rnn_dims=512,
                fc_dims=512,
                mode=self.wavernn_config.mode,
                **mulaw = self.mulaw**,
                pad=2,
                upsample_factors=self.wavernn_config.upsample_factors,  # set this depending on dataset
                feat_dims=80,
                compute_dims=128,
                res_out_dims=128,
                res_blocks=10,
                hop_length=self.ap.hop_length,
                sample_rate=self.ap.sample_rate,
            ).cuda()
```
**mulaw** attribute missing in config.json.

i was referred this one.
https://github.com/erogol/WaveRNN/blob/master/config.json

but no use. how to rectify this issue sir,
is this correct way or not?

if i am wrong means, please correct me. and give me some suggestions sir.

Thank you sir.

**Comment by erogol** [comment]
server.py is not compatible with the latest TTS. will be fixed later on.

**Comment by MuruganR96** [comment]
**TTS/notebooks/Benchmark.ipynb**
it is also won't work. 
i think **it is also not compatible with the latest TTS**.
```
 > Using model: Tacotron2
 > Setting up Audio Processor...
 | > bits:None
 | > sample_rate:22050
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:12.5
 | > frame_length_ms:50
 | > ref_level_db:20
 | > num_freq:1025
 | > power:1.5
 | > preemphasis:0.98
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:False
 | > mel_fmin:0.0
 | > mel_fmax:8000.0
 | > max_norm:1.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > n_fft:2048
 | > hop_length:275
 | > win_length:1102
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-16-f4f55a7fc932> in <module>
     20 
     21 # load the model
---> 22 model.load_state_dict(cp['model'])
     23 if use_cuda:
     24     model.cuda()

~/Murugan_R/17-06-2019/TTS/env/lib/python3.6/site-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict)
    775         if len(error_msgs) > 0:
    776             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
--> 777                                self.__class__.__name__, "\n\t".join(error_msgs)))
    778         return _IncompatibleKeys(missing_keys, unexpected_keys)
    779 

RuntimeError: Error(s) in loading state_dict for Tacotron2:
	size mismatch for embedding.weight: copying a param with shape torch.Size([62, 512]) from checkpoint, the shape in current model is torch.Size([130, 512]).
```

pretrained model incompatible for latest TTS.
am I correct or wrong? 
sir any suggestions how to run Tacotron-2 model and get inference?

Thank you so much for your awesome reply @erogol  sir. :)

**Comment by erogol** [comment]
Pretrained models need to be used with the given commit versions. Latest TTS has a larger begging layer so it does not match the pretrained model.

**Comment by MuruganR96** [comment]
Sir but I was used given commit only.☺️

**Comment by erogol** [comment]
you should run ```git checkout 824c091```

with ```-b``` probably you create a new branch and therefore it does not work. I checked now and the right branch works just fine.

**Comment by MuruganR96** [comment]
sir i am getting **size mismatch for embedding.weight** issue.
but 
**arguments missing in pretrained WaveRNN-MOLD model config.json .**

```
TypeError                                 Traceback (most recent call last)
<ipython-input-7-e8d79930f6cb> in <module>
     15             res_blocks=10,
     16             hop_length=ap.hop_length,
---> 17             sample_rate=ap.sample_rate,
     18         ).cuda()
     19 

TypeError: __init__() missing 1 required positional argument: 'mulaw'
```

**Comment by MuruganR96** [comment]
WaveRNN model function.
```
 model = Model(
        rnn_dims=512,
        fc_dims=512,
        mode=CONFIG.mode,
        mulaw=CONFIG.mulaw,
        pad=CONFIG.pad,
        upsample_factors=CONFIG.upsample_factors,
        feat_dims=80,
        compute_dims=128,
        res_out_dims=128,
        res_blocks=10,
        hop_length=ap.hop_length,
        sample_rate=ap.sample_rate,
    ).cuda()
```

**Comment by MuruganR96** [comment]
Really Sorry sir. that is my fault.
we need to checkout **WaveRNN-mold** commit.

Thanks a lot.:)

**Comment by allianceai** [comment]
I am experiencing the same error as @MuruganR96. I performed a `git checkout` on [824c091](https://github.com/mozilla/TTS/commit/824c09120b6e6bf4be99d03cc07e611ecbf140fe) and a `git checkout `on [mold](https://github.com/erogol/WaveRNN/tree/mold) and am getting the TypeError: __init__() missing 1 required positional argument: 'mulaw' at the same position as @MuruganR96 .  Is there a default value for mulaw that should be set in config.json @erogol ? @MuruganR96 , would you mind clarifying what steps you took to resolve this error on your side? Thank you!

**Comment by MuruganR96** [comment]
**git clone https://github.com/mozilla/TTS.git
cd TTS

git checkout 824c091
git clone https://github.com/erogol/WaveRNN.git
cd WaveRNN
git checkout mold** 


I tried these steps only. It's worked for me.

**Comment by allianceai** [comment]
@MuruganR96  I followed these same steps as well. I was able to make the code run properly with a tiny modification to the wavernn.py script. In my case, I simply substituted 

`from utils.distribution import sample_from_gaussian, sample_from_discretized_mix_logistic`

for

`from WaveRNN.utils.distribution import sample_from_gaussian, sample_from_discretized_mix_logistic`

Thank you @erogol  and @MuruganR96

**Comment by harshalDharpure** [comment]
TypeError                                 Traceback (most recent call last)
<ipython-input-8-524336d060f4> in <module>()
     64     pretrained_model=config.model_type,
     65     max_pieces=config.max_seq_len,
---> 66     do_lowercase=True,
     67  )
     68 

TypeError: __init__() missing 1 required positional argument: 'model_name'

**Comment by harshalDharpure** [comment]
#!/usr/bin/env python
# coding: utf-8

# In[1]:


import torch
import pandas as pd
import numpy as np
from pathlib import Path
from typing import *
import matplotlib.pyplot as plt
get_ipython().run_line_magic('matplotlib', 'inline')


# In[2]:


class Config(dict):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        for k, v in kwargs.items():
            setattr(self, k, v)
    
    def set(self, key, val):
        self[key] = val
        setattr(self, key, val)
        
config = Config(
    model_type="bert-base-uncased",
    max_seq_len=128,
)


# In[3]:


T = TypeVar('T')
def flatten(x: List[List[T]]) -> List[T]:
    return [item for sublist in x for item in sublist]


# In[4]:


from allennlp.common.util import get_spacy_model
from spacy.attrs import ORTH
from spacy.tokenizer import Tokenizer

nlp = get_spacy_model("en_core_web_sm", pos_tags=False, parse=True, ner=False)
nlp.tokenizer.add_special_case("[MASK]", [{ORTH: "[MASK]"}])
def spacy_tok(s: str):
    return [w.text for w in nlp(s)]


# In[5]:


from allennlp.data.tokenizers.spacy_tokenizer import SpacyTokenizer
from allennlp.data.token_indexers import PretrainedTransformerIndexer
from allennlp.data.tokenizers import Token

token_indexer = PretrainedTransformerIndexer(
    pretrained_model=config.model_type,
    max_pieces=config.max_seq_len,
    do_lowercase=True,
 )

# apparently we need to truncate the sequence here, which is a stupid design decision
def tokenize(x: str) -> List[Token]:
        return [Token(w) for w in flatten([
                token_indexer.wordpiece_tokenizer(w)
                for w in spacy_tok(x)]
        )[:config.max_seq_len]]


# In[6]:


from pytorch_pretrained_bert import BertConfig, BertForMaskedLM
model = BertForMaskedLM.from_pretrained(config.model_type)


# In[7]:


from allennlp.data import Vocabulary

vocab = Vocabulary()
token_indexer._add_encoding_to_vocabulary(vocab)


# In[8]:


def get_logits(input_sentence: str) -> torch.Tensor:
    input_toks = tokenize(input_sentence)
    batch = token_indexer.tokens_to_indices(input_toks, vocab, "tokens")
    token_ids = torch.LongTensor(batch["tokens"]).unsqueeze(0)
    with torch.no_grad():
        out_logits = model(token_ids).squeeze(0)
    return out_logits.detach().cpu().numpy()


# In[9]:


full_vocab = {v:k for k, v in token_indexer.vocab.items()}

def indices_to_words(indices: Iterable[int]) -> List[str]:
    return [full_vocab[x] for x in indices]









# Measuring difference

# In[17]:


male_logits = get_logits("he is very [MASK].")[4, :]
female_logits = get_logits("she is very [MASK].")[4, :]


# In[18]:


def softmax(x, axis=0, eps=1e-9):
    e = np.exp(x)
    return e / (e.sum(axis, keepdims=True) + eps)


# In[19]:


male_probs = softmax(male_logits)
female_probs = softmax(female_logits)


# In[20]:


msk = ((male_probs >= 1e-6) & (female_probs >= 1e-6))
male_probs = male_probs[msk]
female_probs = female_probs[msk]


# In[21]:


[(pos + 1, full_vocab[i]) for i, pos in enumerate((male_probs / female_probs).argsort()) if pos < 10]


# In[22]:


[(pos + 1, full_vocab[i]) for i, pos in enumerate((female_probs / male_probs).argsort()) if pos < 10]


# In[ ]:





# # Construct measure of bias

# In[23]:


input_sentence = "[MASK] is intelligent"


# In[24]:


def _get_mask_index(toks: Iterable[Token]) -> int:
    for i, t in enumerate(toks):
        if t.text == "[MASK]":
            return i + 1 # take the [CLS] token into account
    raise ValueError("No [MASK] token found")


# In[25]:


def get_logits(input_sentence: str, n_calc: int=10) -> np.ndarray:
    """
    n_calc: Since the logits are non-deterministic, 
    computing the logits multiple times might be better
    """
    input_toks = tokenize(input_sentence)
    batch = token_indexer.tokens_to_indices(input_toks, vocab, "tokens")
    token_ids = torch.LongTensor(batch["tokens"]).unsqueeze(0)
    
    logits = None
    for _ in range(n_calc):
        with torch.no_grad():
            out_logits = model(token_ids).squeeze(0)
        if logits is None: logits = np.zeros(out_logits.shape)
        logits += out_logits.detach().cpu().numpy()
    return logits / n_calc


# In[26]:


def get_logit_scores(input_sentence: str, words: int) -> Dict[str, float]:
    out_logits = get_logits(input_sentence)
    input_toks = tokenize(input_sentence)
    i = _get_mask_index(input_toks)
    return {w: out_logits[i, token_indexer.vocab[w]] for w in words}

def get_log_odds(input_sentence: str, word1: str, word2: str) -> float:
    scores = get_logit_scores(input_sentence, (word1, word2))
    return scores[word1] - scores[word2]

**Comment by harshalDharpure** [comment]
I want to run this file but it is showing an error TypeError: init() missing 1 required positional argument: 'model_name'
