### ISSUE TITLE
Vocoder comparison

### ISSUE THREAD

**Issue by fuchini** [mozilla/TTS#219]
Hi, just wanted to know what's the state of the different vocoders. I have several questions:

1. From my tests, I've seen LWS is 10x faster than GL. Is this correct? 

2. To implement LWS would it be enough to calculate the mel and specs using LWS and use it also to invert them?

3. How would GL and LWS compare with WaveRNN in quality and inference time?

4. Is there any update on the WORLD vocoder?

Thanks a lot.

**Comment by erogol** [comment]
1. LWS has some parameter constraints like window size and hop-size for a given sample rate.
2. LWS works with the same inputs as GL
3. Bad in quality, much faster in run-time.
4. Alas, no.

Good luck.

**Comment by mrgloom** [comment]
https://github.com/r9y9/deepvoice3_pytorch uses LWS and (maybe subjective) but I think it have better quality then GL.

**Comment by mrgloom** [comment]
Also here is my test for WORLD vocoder i.e. what it will sound like if smoothed features will be predicted.
https://github.com/mozilla/TTS/issues/9#issuecomment-497303645
