### ISSUE TITLE
about LPCnet support

### ISSUE THREAD

**Issue by gudwns1215** [mozilla/TTS#223]
Hi! thanks for sharing this great code!

I tried to synthesize with taco2+wavernn and it takes a bit time. I think the vocoder takes time to synthesize.

and I saw https://github.com/mozilla/LPCNet . which takes 2 sec to synth 20 sec audio. which is amazingly fast.

is there any plan to create LPCNet compatible version of TTS?

**Comment by erogol** [comment]
not for now but maybe in the future. 

In any case, It needs to be reimplemented in pytorch for better integration and keeping dependencies smaller.
