### ISSUE TITLE
how many steps after Tacotron-2 model will adapt? 

### ISSUE THREAD

**Issue by MuruganR96** [mozilla/TTS#224]
i did training for tweb-dataset tacotron-2. it is completed now 76k steps( it took 6 days). but still no improvement.
may be if i know the approximate step will adapt means, i will extend my hardware resource.

thank you sir.

**Comment by MuruganR96** [comment]
@erogol, I was tried previously for a tacotron with TWEB male voice dataset. audio I am getting feel good like a tacotron-2 female voice.

@erogol, I tried 300k steps for tacotron-2 + TWEB dataset. still, it is not giving  good results.

[300179.zip](https://github.com/mozilla/TTS/files/3425293/300179-20190724T052236Z-001.zip)

May I combine with different speakers datasets and train. what will be the results come? 
like TWEB + MAILABs male audios. (Multi-Speakers TTS)

(or)

hyper-parameter tuning I will do and get results? what are the major hyper-parameters we need to tune?
this is my TWEB-train tacotron-2 config file.

[config.json](https://github.com/mozilla/TTS/files/3425329/config.json.zip)

Thank you.

**Comment by erogol** [comment]
TWEB is a very low quality dataset. That might be the reason.
