### ISSUE TITLE
Potential use of espeak-ng as backend

### ISSUE THREAD

**Issue by nmstoker** [mozilla/TTS#232]
I was wondering whether it would be worth considering recommending people use [espeak-ng](https://github.com/espeak-ng/espeak-ng) as the backend over [espeak](http://espeak.sourceforge.net/)? Or if not _recommending_, clarifying that it's an option :slightly_smiling_face: 

It's a near drop-in replacement with TTS (_see below for some relevant known differences_)

Given that espeak is no longer being developed (_since 2015_) it's likely to be worth moving to espeak-ng.

It appears easier to install on Windows (although I haven't personally tried this), the language coverage is greater (espeak's **69** languages/accents goes up to **100** under espeak-ng) and there's potential for developer improvements/issue resolution (eg if some security bug comes up, it's hard to know how that'll be handled with espeak).

I wrote a simple script to show the output from text2phone() and ran it first under my existing espeak install and then replaced it with espeak-ng.  There were a few differences but it is only a few characters and I suspect they may actually be improvements.

```` python
from TTS.utils.text import text2phone
from time import gmtime, strftime

default_backend = 'espeak'
backend = input(f'enter backend [or press return to accept default: {default_backend}]')
if len(backend) == 0 :
    backend = default_backend

default_language = 'en-uk-rp'
language = input(f'enter language [or press return to accept default: {default_language}]')
if len(language) == 0 :
    language = default_language

timestamp = strftime("%Y-%m-%d_%H-%M-%S", gmtime())
output_filename = f'output_{backend}_{language}_{timestamp}.txt'
print(f'\nOutput filename is: {output_filename}\n')
with open(output_filename, 'w') as output:
    with open('sentence_list.txt', 'r') as sentence_list:
        for sentence in sentence_list:
            output.write(text2phone(sentence, language) + '\n')
print('\nDone!\n')
````
**Examples of the diff output:**
```
< ð|eɪ| |h|æ|v| |ɐ| |t|uː| |ɡ|ɐ|ɹ|ɑː|ʒ| |h|oʊ|m| |
---
> ð|eɪ| |h|æ|v| |ɐ| |t|uː| |ɡ|ɚ|ɹ|ɑː|ʒ| |h|oʊ|m| |
31c31
< w|ɪ|ð| |aɪ|z| |ɑː|n| |t|ɑːɹ|ɡ|ɪ|t| ,
---
> w|ɪ|ð| |aɪ|z| |ɔ|n| |t|ɑːɹ|ɡ|ɪ|t| ,

```

The one change which would impact people using TTS for British English is that the language codes are now en-gb-... rather than en-uk-... In my case I've been using en-uk-rp, so I simply updated my config.json to be en-gb-x-rp and it was fine.

Running a test with the Demo Server, I detected no deterioration in the output.  The only point I would mention, but which appears to have had no impact, was that the Demo Server did report a warning:

> OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.

If it does prove easier for Windows users to install (as there are compiled installers for both 32- & 64-bit), it looks like that would address #148.  It was easy to install the [package on Arch](https://www.archlinux.org/packages/community/x86_64/espeak-ng/) and is available on [Debian](https://salsa.debian.org/a11y-team/espeak-ng) and [Ubuntu](https://launchpad.net/ubuntu/+source/espeak-ng) as well as having clear instructions on [building it](https://github.com/espeak-ng/espeak-ng#linux-mac-bsd).

Anyway, if this is okay @erogol I would happily put together to few lines for a PR to document it as an option in the README (espeak itself is not currently mentioned as a depedency, but is referenced in a few issues and three points in the code) or I'm happy to leave that to you if you prefer?

**Comment by erogol** [comment]
Thx for noting it down. We might consider switching to that. I see that it is also available to ```apt```. 

It is better if you could send a PR covering the related [tests](https://github.com/mozilla/TTS/blob/master/tests/test_text_processing.py) and the updates. I can also train and test if it makes any difference, better or worse.

**Comment by erogol** [comment]
@twerkmeister maybe you could try ```speak-ng``` for german if it solves the problems you told.

**Comment by twerkmeister** [comment]
will have a look! Thanks

**Comment by nmstoker** [comment]
I'll take a deeper look into espeak-ng and at the tests as you suggested (I have should some time on Monday)

Just to confirm: Phonemiser definitely supports both, specifically mentioning this near the top of the [README](https://github.com/bootphon/phonemizer/blob/master/README.md):

> espeak-ng is a text-to-speech software supporting multiple languages and IPA (Internatinal Phonetic Alphabet) output. See https://github.com/espeak-ng/espeak-ng. Alternatively you can use the orginal espeak program (espeak-ng is a fork of espeak supporting much more languages and significant improvements).

I haven't (_yet_) done a complete training test with it, my tests were only when doing inference on a previously trained model (trained with espeak) so I agree it makes sense to check that for impact.

**Comment by twerkmeister** [comment]
unfortunately, espeak-ng does not solve the problem with german umlauts. On top of that I had some question marks in the output.

Sentence: Angela Merkel ist als Klimakanzlerin gestartet. Dann vernachlässigte sie das Thema. Nun, kurz vor dem Ende, will sie damit noch einmal neu anfangen.

phonemizer with Espeak-ng:
anɡəlɑː mɛɾkəl ɪst als kliːmakantslərɪn ɡəʃtaɾtət. dan fɛɾnaxlasɪçtə ziː das teːmɑː. nuːn, **k??ts** fɔɾ deːm ɛndə, vɪl ziː dɑːmɪt nɔx aɪnmɑːl nɔø anfaŋən.

phonemizer with espeak:
anɡəlɑː mɛɾkəl ɪst als kliːmakantslərɪn ɡəʃtaɾtət. dan fɛɾnaxlasɪçtə ziː das teːmɑː. nuːn, **kʊɐts** fɔɾ deːm ɛndə, vɪl ziː dɑːmɪt nɔx aɪnmɑːl nɔø anfaŋən.

both get fɛɾnaxlasɪçtə wrong which should be fɛɾnaxlɛsɪçtə

**Comment by m-toman** [comment]
Wonder if this is an encoding issue, just tried from the python repl:

```
phonemize("Schöne Grüße aus Österreich", strip=False, njobs=1, backend='espeak', language="de")
'ʃøːnə ɡryːsə aʊs œstɜraɪç '

```
Also, your sentence @twerkmeister 
```
phonemize("Angela Merkel ist als Klimakanzlerin gestartet. Dann vernachlässigte sie das Thema. Nun, kurz vor dem Ende, will sie damit noch einmal neu anfangen.", strip=False, njobs=1, backend='espeak', language="de")
'anɡəlɑː mɛɾkəl ɪst als kliːmakantslərɪn ɡəʃtaɾtət \ndan fɛɾnaxlɛsɪçtə ziː das teːmɑː \nnuːn \nkʊɐts fɔɾ deːm ɛndə \nvɪl ziː dɑːmɪt nɔx  aɪnmɑːl nɔø anfaŋən ''ʃøːnə ɡryːsə aʊs œstɜraɪç '

```

Then installed espeak-ng (phonemizer is a bit unclear here, it searches for espeak-ng and uses the classic espeak as fallback, yet the is_espeak_ng function does not work correctly at the moment)

```
phonemizer.backend.EspeakBackend.espeak_exe()
'/usr/bin/espeak-ng'

phonemize("Angela Merkel ist als Klimakanzlerin gestartet. Dann vernachlässigte sie das Thema. Nun, kurz vor dem Ende, will sie damit noch einmal neu anfangen.", strip=False, njobs=1, backend='espeak', language="de")
'anɡəlɑː mɛɾkəl ɪst als kliːmakantslərɪn ɡəʃtaɾtət \ndan fɛɾnaxlɛsɪçtə ziː das teːmɑː \nnuːn \nkʊɐts fɔɾ deːm ɛndə \nvɪl ziː dɑːmɪt nɔx aɪnmɑːl nɔø anfaŋən '
```

**Comment by twerkmeister** [comment]
hmm could be! Also, interesting that you get the proper **ɛ** in `fɛɾnaxlɛsɪçtə` (vernachlässigte) with both solutions, and I didn't get it with either

**Comment by twerkmeister** [comment]
maybe my installation of espeak and espeak-ng on macos is outdated or messed up in some way. Will double check inside a ubuntu docker container

**Comment by m-toman** [comment]
Ah, I tested in Debian.

**Comment by twerkmeister** [comment]
on my ubuntu server I am also getting the proper result, just tested with espeak so far

**Comment by twerkmeister** [comment]
What's interesting is that the espeak under ubuntu removes all punctuation. This is a bit of a pity as it would certainly be important information for pauses in the speech or for intonation (questions vs statements).
Here's what I learned about this issue so far: 
1. Unfortunately, right now there is no command line option for espeak to keep the punctuation as in the source text (https://github.com/espeak-ng/espeak-ng/issues/275)
2. There is a command line option `--punct` that leads to punctuation being pronounced explicitly, i.e `, -> comma`. It would certainly be possible to use this and then have a use a regex on the resulting pattern. Possibly enclosing punctuation in other rare symbols to make the result more unique, e.g. `@,@`.
3. Apart from that I saw that the phonemizer module removes stress marks from the resulting phoneme sequence. I wonder wether this is desirable or if we should actually keep those.

**Comment by m-toman** [comment]
I also looked at this just now. 
There is this workaround:
https://github.com/mozilla/TTS/blob/b1657d70b160c097be7ac24290514a9aed010452/utils/text/__init__.py#L33

I wonder if it would be beneficial to not have diacritics etc as separate symbols. Also diphones are split at the moment.

**Comment by twerkmeister** [comment]
Ah great, so this is already being taken care of. That explains why I saw the punctuation in the notebooks before! Thanks for double checking :+1:

**Comment by nmstoker** [comment]
Is there a preference towards supporting just one version (ie original espeak or espeak-ng) or both?

It shouldn't be _that_ hard to handle both, just the tests would need to be able to take it into account (they differ in their phoneme output) and it does provide one more thing to confuse people (but the counter point is that one or other may be easier to install depending on the environment people are using, thus being more helpful to end users)
