### ISSUE TITLE
testing server not working

### ISSUE THREAD

**Issue by massimo1980** [mozilla/TTS#240]
root@burp:/opt/TTS# python server/server.py -c server/conf.json
Traceback (most recent call last):
  File "server/server.py", line 3, in <module>
    from synthesizer import Synthesizer
  File "/opt/TTS/server/synthesizer.py", line 9, in <module>
    from utils.generic_utils import load_config, setup_model
ImportError: cannot import name 'setup_model'

once managed to solve the library issue:
root@burp:/opt/TTS# python server/server.py -c server/conf.json
 > Loading TTS model ...
 | > model config:  /opt/keep/mozilla-it-July-19-2019_02+21PM-0470dd4/config.json
 | > model file:  checkpoint_3000.pth.tar
 > Setting up Audio Processor...
 | > sample_rate:16000
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:12.5
 | > frame_length_ms:50
 | > ref_level_db:20
 | > num_freq:1025
 | > power:1.5
 | > preemphasis:0.98
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:False
 | > mel_fmin:0
 | > mel_fmax:8000.0
 | > max_norm:1.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > n_fft:2048
 | > hop_length:200
 | > win_length:800
Traceback (most recent call last):
  File "server/server.py", line 14, in <module>
    synthesizer = Synthesizer(config)
  File "/opt/TTS/server/synthesizer.py", line 28, in __init__
    self.load_tts(self.config.tts_path, self.config.tts_file, self.config.tts_config, config.use_cuda)
  File "/opt/TTS/server/synthesizer.py", line 47, in load_tts
    self.tts_model = setup_model(self.input_size, c=self.tts_config) #FIXME: missing num_speakers argument to setup_model
TypeError: setup_model() missing 1 required positional argument: 'num_speakers'

**Comment by japita-se** [comment]
Try to pass an object. Try to change the line 47
`self.tts_model = setup_model(self.input_size, < number of speakers>, c=AttrDict(self.tts_config))`

I suppose `number of speakers` to be 1.

**Comment by erogol** [comment]
now it should work. If you try to use one of the released models, you need to checkout the right version of the repo anyways.
