### ISSUE TITLE
Broken link for TWEB under Wiki/Datasets

### ISSUE THREAD

**Issue by JRMeyer** [mozilla/TTS#241]
![tweb](https://user-images.githubusercontent.com/8389864/61582689-b525e080-aae2-11e9-9229-d088e9132a81.png)

**Comment by erogol** [comment]
works for me?

**Comment by JRMeyer** [comment]
in firefox, on ubuntu 18.04, I rightclick and "open link in new tab" or "open link in new window" takes me here:

`http://www.https.com//www.kaggle.com/bryanpark/the-world-english-bible-speech-dataset`

If I just do a regular click on it, I go here:

`http://https//www.kaggle.com/bryanpark/the-world-english-bible-speech-dataset`

Is there a `https` prefix that's acting up?

**Comment by reuben** [comment]
Fixed.
