### ISSUE TITLE
Special symbol for silence?

### ISSUE THREAD

**Issue by mrgloom** [mozilla/TTS#242]
Is any special symbol for silence exist? i.e. if I want to generate a text like
`text = [silence symbol] * 10 + 'Hello how are you?' `

**Comment by erogol** [comment]
no there is not. AFAIK datasets have no annotations for the silences. But it is actually a good idea, if possible with the given dataset.

**Comment by mrgloom** [comment]
Maybe https://pypi.org/project/webrtcvad/ can be used? i.e. voice / unvoice -> silence / not silence.

**Comment by erogol** [comment]
it looks over-engineering to me but possible.
