### ISSUE TITLE
AttributeError: 'AttrDict' object has no attribute 'use_speaker_embedding'

### ISSUE THREAD

**Issue by Vino-git** [mozilla/TTS#246]
I am getting the below error when I train the model in Nvidia Jetson Nano device. Please confirm whether it is possible to train the model in Nvidia Jetson nano. If so, how can i fix the below issue?

CUDA_VISIBLE_DEVICES="0,1,4" python3 distribute.py --config_path config.json --data_path LJSpeech-1.1/
 > Git Hash: b1657d7
 > Experiment folder: output/mozilla-tacotron-tagent-bn-July-25-2019_07+14AM-b1657d7
['train.py', '--restore_path=', '--config_path=config.json', '--group_id=group_2019_07_25-071435', '--data_path=LJSpeech-1.1/', '--output_path=output/mozilla-tacotron-tagent-bn-July-25-2019_07+14AM-b1657d7', '--rank=0']
 > Using CUDA:  True
 > Number of GPUs:  1
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:12.5
 | > frame_length_ms:50
 | > ref_level_db:20
 | > num_freq:1025
 | > power:1.5
 | > preemphasis:0.98
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:False
 | > mel_fmin:0
 | > mel_fmax:8000.0
 | > max_norm:1.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > n_fft:2048
 | > hop_length:275
 | > win_length:1102
 ! Run is removed from output/mozilla-tacotron-tagent-bn-July-25-2019_07+14AM-b1657d7/
Traceback (most recent call last):
  File "train.py", line 623, in <module>
    main(args)
  File "train.py", line 444, in main
    if c.use_speaker_embedding:
AttributeError: 'AttrDict' object has no attribute 'use_speaker_embedding'

**Comment by erogol** [comment]
add use_speaker_embedding to your config.json file and set it true or false depending on your use case.
