### ISSUE TITLE
server.py throws missing key(s) in state_dicts

### ISSUE THREAD

**Issue by Vino-git** [mozilla/TTS#249]
Hi,
Thanks for your support.

I have followed the updated steps as it is mentioned in #154 but still, I am getting the same error as many people reported. I could catch the point of how those issues were closed. Please assist me to get it run. Below the issues, while I execute the server.py. It would be great if you share the pre-trained model available to ready to run also.

FYI - After the master repo cloned. I check out the db7f3d3.

/TTS$ python3 server/server.py -c server/conf.json
 > Loading model ...
 | > model config:  ljspeech_models/queue-July-26-2019_06+26PM-2b970c5/config.json
 | > model file:  ljspeech_models/queue-July-26-2019_06+26PM-2b970c5/checkpoint_272976.pth.tar
 > Setting up Audio Processor...
 | > fft size: 2048, hop length: 275, win length: 1102
 | > Audio Processor attributes.
   | > bits:None
   | > sample_rate:22050
   | > num_mels:80
   | > min_level_db:-100
   | > frame_shift_ms:12.5
   | > frame_length_ms:50
   | > ref_level_db:20
   | > num_freq:1025
   | > power:1.5
   | > preemphasis:0.98
   | > griffin_lim_iters:60
   | > signal_norm:True
   | > symmetric_norm:False
   | > mel_fmin:0
   | > mel_fmax:None
   | > max_norm:1.0
   | > clip_norm:True
   | > do_trim_silence:True
   | > n_fft:2048
   | > hop_length:275
   | > win_length:1102
 | > Number of characters : 61
Traceback (most recent call last):
  File "server/server.py", line 16, in <module>
    config.model_config, config.use_cuda)
  File "/home/danata/TTS/server/synthesizer.py", line 34, in load_model
    self.model.load_state_dict(cp['model'])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 771, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Tacotron:
	Missing key(s) in state_dict: "encoder.cbhg.cbhg.conv1d_banks.0.conv1d.weight", "encoder.cbhg.cbhg.conv1d_banks.0.bn.weight", "encoder.cbhg.cbhg.conv1d_banks.0.bn.bias", "encoder.cbhg.cbhg.conv1d_banks.0.bn.running_mean", "encoder.cbhg.cbhg.conv1d_banks.0.bn.running_var", "encoder.cbhg.cbhg.conv1d_banks.1.conv1d.weight", "encoder.cbhg.cbhg.conv1d_banks.1.bn.weight", "encoder.cbhg.cbhg.conv1d_banks.1.bn.bias", "encoder.cbhg.cbhg.conv1d_banks.1.bn.running_mean", "encoder.cbhg.cbhg.conv1d_banks.1.bn.running_var", "encoder.cbhg.cbhg.conv1d_banks.2.conv1d.weight", "encoder.cbhg.cbhg.conv1d_banks.2.bn.weight", "encoder.cbhg.cbhg.conv1d_banks.2.bn.bias", "encoder.cbhg.cbhg.conv1d_banks.2.bn.running_mean", "encoder.cbhg.cbhg.conv1d_banks.2.bn.running_var", "encoder.cbhg.cbhg.conv1d_banks.3.conv1d.weight", "encoder.cbhg.cbhg.conv1d_banks.3.bn.weight", "encoder.cbhg.cbhg.conv1d_banks.3.bn.bias", "encoder.cbhg.cbhg.conv1d_banks.3.bn.running_mean", "encoder.cbhg.cbhg.conv1d_banks.3.bn.running_var", "encoder.cbhg.cbhg.conv1d_banks.4.conv1d.weight", "encoder.cbhg.cbhg.conv1d_banks.4.bn.weight", "encoder.cbhg.cbhg.conv1d_banks.4.bn.bias", "encoder.cbhg.cbhg.conv1d_banks.4.bn.running_mean", "encoder.cbhg.cbhg.conv1d_banks.4.bn.running_var", "encoder.cbhg.cbhg.conv1d_banks.5.conv1d.weight", "encoder.cbhg.cbhg.conv1d_banks.5.bn.weight", "encoder.cbhg.cbhg.conv1d_banks.5.bn.bias", "encoder.cbhg.cbhg.conv1d_banks.5.bn.running_mean", "encoder.cbhg.cbhg.conv1d_banks.5.bn.running_var", "encoder.cbhg.cbhg.conv1d_banks.6.conv1d.weight", "encoder.cbhg.cbhg.conv1d_banks.6.bn.weight", "encoder.cbhg.cbhg.conv1d_banks.6.bn.bias", "encoder.cbhg.cbhg.conv1d_banks.6.bn.running_mean", "encoder.cbhg.cbhg.conv1d_banks.6.bn.running_var", "encoder.cbhg.cbhg.conv1d_banks.7.conv1d.weight", "encoder.cbhg.cbhg.conv1d_banks.7.bn.weight", "encoder.cbhg.cbhg.conv1d_banks.7.bn.bias", "encoder.cbhg.cbhg.conv1d_banks.7.bn.running_mean", "encoder.cbhg.cbhg.conv1d_banks.7.bn.running_var", "encoder.cbhg.cbhg.conv1d_banks.8.conv1d.weight", "encoder.cbhg.cbhg.conv1d_banks.8.bn.weight", "encoder.cbhg.cbhg.conv1d_banks.8.bn.bias", "encoder.cbhg.cbhg.conv1d_banks.8.bn.running_mean", "encoder.cbhg.cbhg.conv1d_banks.8.bn.running_var", "encoder.cbhg.cbhg.conv1d_banks.9.conv1d.weight", "encoder.cbhg.cbhg.conv1d_banks.9.bn.weight", "encoder.cbhg.cbhg.conv1d_banks.9.bn.bias", "encoder.cbhg.cbhg.conv1d_banks.9.bn.running_mean", "encoder.cbhg.cbhg.conv1d_banks.9.bn.running_var", "encoder.cbhg.cbhg.conv1d_banks.10.conv1d.weight", "encoder.cbhg.cbhg.conv1d_banks.10.bn.weight", "encoder.cbhg.cbhg.conv1d_banks.10.bn.bias", "encoder.cbhg.cbhg.conv1d_banks.10.bn.running_mean", "encoder.cbhg.cbhg.conv1d_banks.10.bn.running_var", "encoder.cbhg.cbhg.conv1d_banks.11.conv1d.weight", "encoder.cbhg.cbhg.conv1d_banks.11.bn.weight", "encoder.cbhg.cbhg.conv1d_banks.11.bn.bias", "encoder.cbhg.cbhg.conv1d_banks.11.bn.running_mean", "encoder.cbhg.cbhg.conv1d_banks.11.bn.running_var", "encoder.cbhg.cbhg.conv1d_banks.12.conv1d.weight", "encoder.cbhg.cbhg.conv1d_banks.12.bn.weight", "encoder.cbhg.cbhg.conv1d_banks.12.bn.bias", "encoder.cbhg.cbhg.conv1d_banks.12.bn.running_mean", "encoder.cbhg.cbhg.conv1d_banks.12.bn.running_var", "encoder.cbhg.cbhg.conv1d_banks.13.conv1d.weight", "encoder.cbhg.cbhg.conv1d_banks.13.bn.weight", "encoder.cbhg.cbhg.conv1d_banks.13.bn.bias", "encoder.cbhg.cbhg.conv1d_banks.13.bn.running_mean", "encoder.cbhg.cbhg.conv1d_banks.13.bn.running_var", "encoder.cbhg.cbhg.conv1d_banks.14.conv1d.weight", "encoder.cbhg.cbhg.conv1d_banks.14.bn.weight", "encoder.cbhg.cbhg.conv1d_banks.14.bn.bias", "encoder.cbhg.cbhg.conv1d_banks.14.bn.running_mean", "encoder.cbhg.cbhg.conv1d_banks.14.bn.running_var", "encoder.cbhg.cbhg.conv1d_banks.15.conv1d.weight", "encoder.cbhg.cbhg.conv1d_banks.15.bn.weight", "encoder.cbhg.cbhg.conv1d_banks.15.bn.bias", "encoder.cbhg.cbhg.conv1d_banks.15.bn.running_mean", "encoder.cbhg.cbhg.conv1d_banks.15.bn.running_var", "encoder.cbhg.cbhg.conv1d_projections.0.conv1d.weight", "encoder.cbhg.cbhg.conv1d_projections.0.bn.weight", "encoder.cbhg.cbhg.conv1d_projections.0.bn.bias", "encoder.cbhg.cbhg.conv1d_projections.0.bn.running_mean", "encoder.cbhg.cbhg.conv1d_projections.0.bn.running_var", "encoder.cbhg.cbhg.conv1d_projections.1.conv1d.weight", "encoder.cbhg.cbhg.conv1d_projections.1.bn.weight", "encoder.cbhg.cbhg.conv1d_projections.1.bn.bias", "encoder.cbhg.cbhg.conv1d_projections.1.bn.running_mean", "encoder.cbhg.cbhg.conv1d_projections.1.bn.running_var", "encoder.cbhg.cbhg.highways.0.H.weight", "encoder.cbhg.cbhg.highways.0.H.bias", "encoder.cbhg.cbhg.highways.0.T.weight", "encoder.cbhg.cbhg.highways.0.T.bias", "encoder.cbhg.cbhg.highways.1.H.weight", "encoder.cbhg.cbhg.highways.1.H.bias", "encoder.cbhg.cbhg.highways.1.T.weight", "encoder.cbhg.cbhg.highways.1.T.bias", "encoder.cbhg.cbhg.highways.2.H.weight", "encoder.cbhg.cbhg.highways.2.H.bias", "encoder.cbhg.cbhg.highways.2.T.weight", "encoder.cbhg.cbhg.highways.2.T.bias", "encoder.cbhg.cbhg.highways.3.H.weight", "encoder.cbhg.cbhg.highways.3.H.bias", "encoder.cbhg.cbhg.highways.3.T.weight", "encoder.cbhg.cbhg.highways.3.T.bias", "encoder.cbhg.cbhg.gru.weight_ih_l0", "encoder.cbhg.cbhg.gru.weight_hh_l0", "encoder.cbhg.cbhg.gru.bias_ih_l0", "encoder.cbhg.cbhg.gru.bias_hh_l0", "encoder.cbhg.cbhg.gru.weight_ih_l0_reverse", "encoder.cbhg.cbhg.gru.weight_hh_l0_reverse", "encoder.cbhg.cbhg.gru.bias_ih_l0_reverse", "encoder.cbhg.cbhg.gru.bias_hh_l0_reverse", "decoder.attention_rnn.alignment_model.loc_conv.1.weight", "decoder.attention_rnn.alignment_model.loc_linear.weight", "decoder.attention_rnn.alignment_model.loc_linear.bias", "decoder.attention_rnn_init.weight", "decoder.memory_init.weight", "decoder.decoder_rnn_inits.weight", "postnet.cbhg.conv1d_banks.0.conv1d.weight", "postnet.cbhg.conv1d_banks.0.bn.weight", "postnet.cbhg.conv1d_banks.0.bn.bias", "postnet.cbhg.conv1d_banks.0.bn.running_mean", "postnet.cbhg.conv1d_banks.0.bn.running_var", "postnet.cbhg.conv1d_banks.1.conv1d.weight", "postnet.cbhg.conv1d_banks.1.bn.weight", "postnet.cbhg.conv1d_banks.1.bn.bias", "postnet.cbhg.conv1d_banks.1.bn.running_mean", "postnet.cbhg.conv1d_banks.1.bn.running_var", "postnet.cbhg.conv1d_banks.2.conv1d.weight", "postnet.cbhg.conv1d_banks.2.bn.weight", "postnet.cbhg.conv1d_banks.2.bn.bias", "postnet.cbhg.conv1d_banks.2.bn.running_mean", "postnet.cbhg.conv1d_banks.2.bn.running_var", "postnet.cbhg.conv1d_banks.3.conv1d.weight", "postnet.cbhg.conv1d_banks.3.bn.weight", "postnet.cbhg.conv1d_banks.3.bn.bias", "postnet.cbhg.conv1d_banks.3.bn.running_mean", "postnet.cbhg.conv1d_banks.3.bn.running_var", "postnet.cbhg.conv1d_banks.4.conv1d.weight", "postnet.cbhg.conv1d_banks.4.bn.weight", "postnet.cbhg.conv1d_banks.4.bn.bias", "postnet.cbhg.conv1d_banks.4.bn.running_mean", "postnet.cbhg.conv1d_banks.4.bn.running_var", "postnet.cbhg.conv1d_banks.5.conv1d.weight", "postnet.cbhg.conv1d_banks.5.bn.weight", "postnet.cbhg.conv1d_banks.5.bn.bias", "postnet.cbhg.conv1d_banks.5.bn.running_mean", "postnet.cbhg.conv1d_banks.5.bn.running_var", "postnet.cbhg.conv1d_banks.6.conv1d.weight", "postnet.cbhg.conv1d_banks.6.bn.weight", "postnet.cbhg.conv1d_banks.6.bn.bias", "postnet.cbhg.conv1d_banks.6.bn.running_mean", "postnet.cbhg.conv1d_banks.6.bn.running_var", "postnet.cbhg.conv1d_banks.7.conv1d.weight", "postnet.cbhg.conv1d_banks.7.bn.weight", "postnet.cbhg.conv1d_banks.7.bn.bias", "postnet.cbhg.conv1d_banks.7.bn.running_mean", "postnet.cbhg.conv1d_banks.7.bn.running_var", "postnet.cbhg.conv1d_projections.0.conv1d.weight", "postnet.cbhg.conv1d_projections.0.bn.weight", "postnet.cbhg.conv1d_projections.0.bn.bias", "postnet.cbhg.conv1d_projections.0.bn.running_mean", "postnet.cbhg.conv1d_projections.0.bn.running_var", "postnet.cbhg.conv1d_projections.1.conv1d.weight", "postnet.cbhg.conv1d_projections.1.bn.weight", "postnet.cbhg.conv1d_projections.1.bn.bias", "postnet.cbhg.conv1d_projections.1.bn.running_mean", "postnet.cbhg.conv1d_projections.1.bn.running_var", "postnet.cbhg.pre_highway.weight", "postnet.cbhg.highways.0.H.weight", "postnet.cbhg.highways.0.H.bias", "postnet.cbhg.highways.0.T.weight", "postnet.cbhg.highways.0.T.bias", "postnet.cbhg.highways.1.H.weight", "postnet.cbhg.highways.1.H.bias", "postnet.cbhg.highways.1.T.weight", "postnet.cbhg.highways.1.T.bias", "postnet.cbhg.highways.2.H.weight", "postnet.cbhg.highways.2.H.bias", "postnet.cbhg.highways.2.T.weight", "postnet.cbhg.highways.2.T.bias", "postnet.cbhg.highways.3.H.weight", "postnet.cbhg.highways.3.H.bias", "postnet.cbhg.highways.3.T.weight", "postnet.cbhg.highways.3.T.bias", "postnet.cbhg.gru.weight_ih_l0", "postnet.cbhg.gru.weight_hh_l0", "postnet.cbhg.gru.bias_ih_l0", "postnet.cbhg.gru.bias_hh_l0", "postnet.cbhg.gru.weight_ih_l0_reverse", "postnet.cbhg.gru.weight_hh_l0_reverse", "postnet.cbhg.gru.bias_ih_l0_reverse", "postnet.cbhg.gru.bias_hh_l0_reverse", "last_linear.0.weight", "last_linear.0.bias". 
	Unexpected key(s) in state_dict: "encoder.cbhg.conv1d_banks.0.conv1d.weight", "encoder.cbhg.conv1d_banks.0.bn.weight", "encoder.cbhg.conv1d_banks.0.bn.bias", "encoder.cbhg.conv1d_banks.0.bn.running_mean", "encoder.cbhg.conv1d_banks.0.bn.running_var", "encoder.cbhg.conv1d_banks.1.conv1d.weight", "encoder.cbhg.conv1d_banks.1.bn.weight", "encoder.cbhg.conv1d_banks.1.bn.bias", "encoder.cbhg.conv1d_banks.1.bn.running_mean", "encoder.cbhg.conv1d_banks.1.bn.running_var", "encoder.cbhg.conv1d_banks.2.conv1d.weight", "encoder.cbhg.conv1d_banks.2.bn.weight", "encoder.cbhg.conv1d_banks.2.bn.bias", "encoder.cbhg.conv1d_banks.2.bn.running_mean", "encoder.cbhg.conv1d_banks.2.bn.running_var", "encoder.cbhg.conv1d_banks.3.conv1d.weight", "encoder.cbhg.conv1d_banks.3.bn.weight", "encoder.cbhg.conv1d_banks.3.bn.bias", "encoder.cbhg.conv1d_banks.3.bn.running_mean", "encoder.cbhg.conv1d_banks.3.bn.running_var", "encoder.cbhg.conv1d_banks.4.conv1d.weight", "encoder.cbhg.conv1d_banks.4.bn.weight", "encoder.cbhg.conv1d_banks.4.bn.bias", "encoder.cbhg.conv1d_banks.4.bn.running_mean", "encoder.cbhg.conv1d_banks.4.bn.running_var", "encoder.cbhg.conv1d_banks.5.conv1d.weight", "encoder.cbhg.conv1d_banks.5.bn.weight", "encoder.cbhg.conv1d_banks.5.bn.bias", "encoder.cbhg.conv1d_banks.5.bn.running_mean", "encoder.cbhg.conv1d_banks.5.bn.running_var", "encoder.cbhg.conv1d_banks.6.conv1d.weight", "encoder.cbhg.conv1d_banks.6.bn.weight", "encoder.cbhg.conv1d_banks.6.bn.bias", "encoder.cbhg.conv1d_banks.6.bn.running_mean", "encoder.cbhg.conv1d_banks.6.bn.running_var", "encoder.cbhg.conv1d_banks.7.conv1d.weight", "encoder.cbhg.conv1d_banks.7.bn.weight", "encoder.cbhg.conv1d_banks.7.bn.bias", "encoder.cbhg.conv1d_banks.7.bn.running_mean", "encoder.cbhg.conv1d_banks.7.bn.running_var", "encoder.cbhg.conv1d_banks.8.conv1d.weight", "encoder.cbhg.conv1d_banks.8.bn.weight", "encoder.cbhg.conv1d_banks.8.bn.bias", "encoder.cbhg.conv1d_banks.8.bn.running_mean", "encoder.cbhg.conv1d_banks.8.bn.running_var", "encoder.cbhg.conv1d_banks.9.conv1d.weight", "encoder.cbhg.conv1d_banks.9.bn.weight", "encoder.cbhg.conv1d_banks.9.bn.bias", "encoder.cbhg.conv1d_banks.9.bn.running_mean", "encoder.cbhg.conv1d_banks.9.bn.running_var", "encoder.cbhg.conv1d_banks.10.conv1d.weight", "encoder.cbhg.conv1d_banks.10.bn.weight", "encoder.cbhg.conv1d_banks.10.bn.bias", "encoder.cbhg.conv1d_banks.10.bn.running_mean", "encoder.cbhg.conv1d_banks.10.bn.running_var", "encoder.cbhg.conv1d_banks.11.conv1d.weight", "encoder.cbhg.conv1d_banks.11.bn.weight", "encoder.cbhg.conv1d_banks.11.bn.bias", "encoder.cbhg.conv1d_banks.11.bn.running_mean", "encoder.cbhg.conv1d_banks.11.bn.running_var", "encoder.cbhg.conv1d_banks.12.conv1d.weight", "encoder.cbhg.conv1d_banks.12.bn.weight", "encoder.cbhg.conv1d_banks.12.bn.bias", "encoder.cbhg.conv1d_banks.12.bn.running_mean", "encoder.cbhg.conv1d_banks.12.bn.running_var", "encoder.cbhg.conv1d_banks.13.conv1d.weight", "encoder.cbhg.conv1d_banks.13.bn.weight", "encoder.cbhg.conv1d_banks.13.bn.bias", "encoder.cbhg.conv1d_banks.13.bn.running_mean", "encoder.cbhg.conv1d_banks.13.bn.running_var", "encoder.cbhg.conv1d_banks.14.conv1d.weight", "encoder.cbhg.conv1d_banks.14.bn.weight", "encoder.cbhg.conv1d_banks.14.bn.bias", "encoder.cbhg.conv1d_banks.14.bn.running_mean", "encoder.cbhg.conv1d_banks.14.bn.running_var", "encoder.cbhg.conv1d_banks.15.conv1d.weight", "encoder.cbhg.conv1d_banks.15.bn.weight", "encoder.cbhg.conv1d_banks.15.bn.bias", "encoder.cbhg.conv1d_banks.15.bn.running_mean", "encoder.cbhg.conv1d_banks.15.bn.running_var", "encoder.cbhg.conv1d_projections.0.conv1d.weight", "encoder.cbhg.conv1d_projections.0.bn.weight", "encoder.cbhg.conv1d_projections.0.bn.bias", "encoder.cbhg.conv1d_projections.0.bn.running_mean", "encoder.cbhg.conv1d_projections.0.bn.running_var", "encoder.cbhg.conv1d_projections.1.conv1d.weight", "encoder.cbhg.conv1d_projections.1.bn.weight", "encoder.cbhg.conv1d_projections.1.bn.bias", "encoder.cbhg.conv1d_projections.1.bn.running_mean", "encoder.cbhg.conv1d_projections.1.bn.running_var", "encoder.cbhg.pre_highway.weight", "encoder.cbhg.highways.0.H.weight", "encoder.cbhg.highways.0.H.bias", "encoder.cbhg.highways.0.T.weight", "encoder.cbhg.highways.0.T.bias", "encoder.cbhg.highways.1.H.weight", "encoder.cbhg.highways.1.H.bias", "encoder.cbhg.highways.1.T.weight", "encoder.cbhg.highways.1.T.bias", "encoder.cbhg.highways.2.H.weight", "encoder.cbhg.highways.2.H.bias", "encoder.cbhg.highways.2.T.weight", "encoder.cbhg.highways.2.T.bias", "encoder.cbhg.highways.3.H.weight", "encoder.cbhg.highways.3.H.bias", "encoder.cbhg.highways.3.T.weight", "encoder.cbhg.highways.3.T.bias", "encoder.cbhg.gru.weight_ih_l0", "encoder.cbhg.gru.weight_hh_l0", "encoder.cbhg.gru.bias_ih_l0", "encoder.cbhg.gru.bias_hh_l0", "encoder.cbhg.gru.weight_ih_l0_reverse", "encoder.cbhg.gru.weight_hh_l0_reverse", "encoder.cbhg.gru.bias_ih_l0_reverse", "encoder.cbhg.gru.bias_hh_l0_reverse", "decoder.stopnet.rnn.weight_ih", "decoder.stopnet.rnn.weight_hh", "decoder.stopnet.rnn.bias_ih", "decoder.stopnet.rnn.bias_hh", "postnet.conv1d_banks.0.conv1d.weight", "postnet.conv1d_banks.0.bn.weight", "postnet.conv1d_banks.0.bn.bias", "postnet.conv1d_banks.0.bn.running_mean", "postnet.conv1d_banks.0.bn.running_var", "postnet.conv1d_banks.1.conv1d.weight", "postnet.conv1d_banks.1.bn.weight", "postnet.conv1d_banks.1.bn.bias", "postnet.conv1d_banks.1.bn.running_mean", "postnet.conv1d_banks.1.bn.running_var", "postnet.conv1d_banks.2.conv1d.weight", "postnet.conv1d_banks.2.bn.weight", "postnet.conv1d_banks.2.bn.bias", "postnet.conv1d_banks.2.bn.running_mean", "postnet.conv1d_banks.2.bn.running_var", "postnet.conv1d_banks.3.conv1d.weight", "postnet.conv1d_banks.3.bn.weight", "postnet.conv1d_banks.3.bn.bias", "postnet.conv1d_banks.3.bn.running_mean", "postnet.conv1d_banks.3.bn.running_var", "postnet.conv1d_banks.4.conv1d.weight", "postnet.conv1d_banks.4.bn.weight", "postnet.conv1d_banks.4.bn.bias", "postnet.conv1d_banks.4.bn.running_mean", "postnet.conv1d_banks.4.bn.running_var", "postnet.conv1d_banks.5.conv1d.weight", "postnet.conv1d_banks.5.bn.weight", "postnet.conv1d_banks.5.bn.bias", "postnet.conv1d_banks.5.bn.running_mean", "postnet.conv1d_banks.5.bn.running_var", "postnet.conv1d_banks.6.conv1d.weight", "postnet.conv1d_banks.6.bn.weight", "postnet.conv1d_banks.6.bn.bias", "postnet.conv1d_banks.6.bn.running_mean", "postnet.conv1d_banks.6.bn.running_var", "postnet.conv1d_banks.7.conv1d.weight", "postnet.conv1d_banks.7.bn.weight", "postnet.conv1d_banks.7.bn.bias", "postnet.conv1d_banks.7.bn.running_mean", "postnet.conv1d_banks.7.bn.running_var", "postnet.conv1d_projections.0.conv1d.weight", "postnet.conv1d_projections.0.bn.weight", "postnet.conv1d_projections.0.bn.bias", "postnet.conv1d_projections.0.bn.running_mean", "postnet.conv1d_projections.0.bn.running_var", "postnet.conv1d_projections.1.conv1d.weight", "postnet.conv1d_projections.1.bn.weight", "postnet.conv1d_projections.1.bn.bias", "postnet.conv1d_projections.1.bn.running_mean", "postnet.conv1d_projections.1.bn.running_var", "postnet.pre_highway.weight", "postnet.highways.0.H.weight", "postnet.highways.0.H.bias", "postnet.highways.0.T.weight", "postnet.highways.0.T.bias", "postnet.highways.1.H.weight", "postnet.highways.1.H.bias", "postnet.highways.1.T.weight", "postnet.highways.1.T.bias", "postnet.highways.2.H.weight", "postnet.highways.2.H.bias", "postnet.highways.2.T.weight", "postnet.highways.2.T.bias", "postnet.highways.3.H.weight", "postnet.highways.3.H.bias", "postnet.highways.3.T.weight", "postnet.highways.3.T.bias", "postnet.gru.weight_ih_l0", "postnet.gru.weight_hh_l0", "postnet.gru.bias_ih_l0", "postnet.gru.bias_hh_l0", "postnet.gru.weight_ih_l0_reverse", "postnet.gru.weight_hh_l0_reverse", "postnet.gru.bias_ih_l0_reverse", "postnet.gru.bias_hh_l0_reverse", "last_linear.weight", "last_linear.bias". 
	size mismatch for embedding.weight: copying a param with shape torch.Size([149, 256]) from checkpoint, the shape in current model is torch.Size([61, 256]).
	size mismatch for decoder.attention_rnn.alignment_model.query_layer.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([128, 256]).
	size mismatch for decoder.attention_rnn.alignment_model.query_layer.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for decoder.attention_rnn.alignment_model.annot_layer.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([128, 256]).
	size mismatch for decoder.attention_rnn.alignment_model.annot_layer.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for decoder.attention_rnn.alignment_model.v.weight: copying a param with shape torch.Size([1, 256]) from checkpoint, the shape in current model is torch.Size([1, 128]).
	size mismatch for decoder.proj_to_mel.weight: copying a param with shape torch.Size([400, 256]) from checkpoint, the shape in current model is torch.Size([160, 256]).
	size mismatch for decoder.proj_to_mel.bias: copying a param with shape torch.Size([400]) from checkpoint, the shape in current model is torch.Size([160]).
	size mismatch for decoder.stopnet.linear.weight: copying a param with shape torch.Size([1, 400]) from checkpoint, the shape in current model is torch.Size([1, 416]).

**Comment by simomo** [comment]
Hi,
I think I figure out the trick.

1. Code: checkout to the branch fix_db7f3d3
2. Download the model whose `commit` is `db7f3d3` from [Released-Models](https://github.com/mozilla/TTS/wiki/Released-Models)
3. Update the `model_path`, `model_name` and `model_config` in the file `server/conf.json`
4. Start! `python server.py -c conf.json`

Thanks a lot to erogol's hardworking and dedication on this open source project, it really helps me a lot!



1.

**Comment by o1lo01ol1o** [comment]
The above works for db7f3d3, but are there instructions for any of the more recent models?  I couldn't get any combination of commits and models to work for Tacotron2-iter-260K

**Comment by erogol** [comment]
https://github.com/mozilla/TTS/issues/210#issuecomment-521662366
