### ISSUE TITLE
Include a demo server

### ISSUE THREAD

**Issue by stevemurr** [mozilla/TTS#25]
Hi, is there interest to include a demo server similar to the one in [https://github.com/keithito/tacotron](https://github.com/keithito/tacotron) ?  If so I can prepare a pull request.

**Comment by kdavis-mozilla** [comment]
@stevemurr I know @reuben started work on such a demo server.

Maybe you can work together or, if you have something already, you could create a PR and @reuben could review it?

**Comment by stevemurr** [comment]
Sounds good!  I have a modified version of the server I use for various TTS models.  I'll begin to integrate it with this repo later today unless I hear something from @reuben .

**Comment by erogol** [comment]
done!! https://github.com/mozilla/TTS/tree/server
