### ISSUE TITLE
pytorch 1.2.0 breaks TTS

### ISSUE THREAD

**Issue by JRMeyer** [mozilla/TTS#259]
@erogol --- I'm fine-tuning the best released Taco2 model from commit `824c091`, and if I have pytorch `1.2.0`, training crashes with the following error:

```
RuntimeError: Subtraction, the - operator, with a bool tensor is not supported.
If you are trying to invert a mask, use the ~ or bitwise_not() operator instead.
```

When I uninstall `1.2.0`, and re-install `1.0.0`, then training works fine.

Here's another GitHub issue on the same problem: https://github.com/OpenNMT/OpenNMT-py/issues/1524

**Comment by erogol** [comment]
It is fixed in dev branch. just an update on the pytorch side

**Comment by mrgloom** [comment]
Same error `RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported.` on commit b1657d70b160c097be7ac24290514a9aed010452 maybe it's better to specify precise version of pytorch? https://github.com/mozilla/TTS/blob/master/requirements.txt#L2

**Comment by mrgloom** [comment]
BTW
https://github.com/librosa/librosa/issues/826

**Comment by mrgloom** [comment]
BTW
Using `numpy==1.14.3` is crucial:
https://github.com/mozilla/TTS/blob/master/requirements.txt#L1
https://github.com/librosa/librosa/issues/826

For me `conda install pytorch=1.1.0 cuda100 -c pytorch` worked.
