### ISSUE TITLE
utils g++

### ISSUE THREAD

**Issue by waydumbs** [mozilla/TTS#260]
from home
$ cd /Git/TTS
$ sudo nvidia-docker run -it -rm -p 5002:5002 mozilla-tts
ModuleNotFoundError: No module named ‘utils’

tried:
export PYTHONPATH="~/Git/TTS"
export PYTHONPATH="~/Git/"

$ python setup.py develop
error: setup script exited with error: command ‘g++’ failed with exit status 1

gcc 9.1.0-2 (base-devel) installed
gcc 8.3.0-2

**Comment by erogol** [comment]
you might need to install python-dev. And we use python >3.0 . But it is not a TTS error.
