### ISSUE TITLE
Installing with pip under Anaconda

### ISSUE THREAD

**Issue by dubreuia** [mozilla/TTS#261]
Hello,

I'm using Mozilla TTS for a project where I have a python app that synthesize text to audio. So I'm using Mozilla TTS as a lib, I need to import it in my app. Right now I'm installing using:

```bash
pip install --no-dependencies "git+git://github.com/mozilla/TTS.git@2b970c5eefcf6fd0a9a8a8f165734849bfc1838a"
```

But the project isn't made to be packaged, so I end up having Mozilla TTS root folders in my "site-packages" like: "models", "utils", "tests". Which is very wrong. By chance it works, since there are no name clash, but it means I cannot have a "utils" file in my app else Python gets confused.

My current usage is: `from models.tacotron import Tacotron`, but should be `from mozilla_tts.models.tacotron import Tacotron`

Is there another way of doing this? I am willing to make a PR to fix that, but I'll probably have to move everything in a mozilla_tts folder, regarding setup.py guidelines. Also this will be a pain to backport to every branch.

Let me know what you think

**Comment by erogol** [comment]
do you use conda by any chance?

**Comment by dubreuia** [comment]
@erogol Yes

**Comment by erogol** [comment]
it is about conda not about TTS. I don't know the solution, unfortunately. If you find something, I'd like to know as well.

**Comment by dubreuia** [comment]
No if you do `pip install` it has nothing to do with `conda`, it will install the lib improperly as described above, using conda or not as an environment manager. You have to follow the setuptools convention for this to work: https://pythonhosted.org/an_example_pypi_project/setuptools.html#directory-structure.

As mentioned I can make a PR, but it will change a lot of code and will be hard to backport into all branches. Your call.

**Comment by reuben** [comment]
@dubreuia I've made an attempt at fixing this in a less invasive way in #262. Can you test if it works for you?
