### ISSUE TITLE
no module named TTS in the notebooks

### ISSUE THREAD

**Issue by Palipoor** [mozilla/TTS#264]
I ran `python3 setup.py develop` and it finished without an issue. When I use my python3 interpreter on terminal, I can do `import TTS` without a problem, but when I use notebooks ([this](https://github.com/mozilla/TTS/blob/dev/notebooks/CheckSpectrograms.ipynb) or [this](https://github.com/mozilla/TTS/blob/master/dataset_analysis/AnalyzeDataset.ipynb)) I get:
`ModuleNotFoundError: No module named 'TTS'`

Any ideas what should I do?

**Comment by MuruganR96** [comment]
Mam. I think you will try to insert path of TTS module in notebook.

import sys
sys.path.insert(path of TTS module)

**Comment by reuben** [comment]
If you're using the latest dev version with installable TTS, then you need to import TTS in the notebooks. Previously they all assumed sys.path modification.
