### ISSUE TITLE
TTS + MelNet Can we try?

### ISSUE THREAD

**Issue by MuruganR96** [mozilla/TTS#265]
[MelNet Paper](https://arxiv.org/pdf/1906.01083.pdf)
[MelNet Pytorch Code](https://github.com/fatchord/MelNet/blob/master/model.py)
[MelNet Voice example](https://sjvasquez.github.io/blog/melnet/)

Awesome. voice more realistic. i want more interesting to implement this.
Please anyone can initiate me. where i need to start process? 
Thank you all

**Comment by erogol** [comment]
It's more about the runtime. I'd guess due to its complex computation, it is way slower than what we have here. Therefore it is not as practical. However, if you like to try, I can help you with that as you have any questions.

**Comment by MuruganR96** [comment]
Yes. now corrected it last link @erogol sir.

@erogol . here my questions,

1) how do we build MelNet model like this[WaveNet Mol model](https://github.com/erogol/WaveRNN)?   
2) if i replace WaveRNN to MelNet code, which part to start and do stuff?

i am a beginner for all this. my way of understanding i am asking this sir.
continuously i am researching it. i will ask more doubts about MelNet. please pink me with our [TTS Forum](https://discourse.mozilla.org/c/tts) sir.

Thank you

**Comment by erogol** [comment]
taken on the forum
