### ISSUE TITLE
How do I create a Turkish voice model like Soundcloud examples

### ISSUE THREAD

**Issue by duman** [mozilla/TTS#273]
I've successfully installed the project and tested the server over port 5002 with latest checkpoint from https://drive.google.com/drive/folders/1FJRjGDAqWIyZRX4CsppaIPEW8UWXCWzF, naturally the model was in English.

I have also seen these tracks in Turkish: https://soundcloud.com/user-565970875/sets/tts-turkish they're absolutely beautiful. In the repository I couldn't find anything about this.

All suggested datasets seems to be in English, I'm willing to read hours and hours of text and create it by myself as well if needed but I'm pretty lost and unsure about where to start.

What should I do to create a voice like in tts-turkish Soundcloud link?
Thank you for creating this project!

**Comment by erogol** [comment]
Turkish dataset and the model is not released and probably won't. Basically, I collected the dataset with a professional voice talent. Soundcloud examples are only showing the capabilities of TTS.

**Comment by tkduman** [comment]
I think you missed my point, I don't want the dataset directly from you. I will create it by myself like you did but I don't know where to start about training the model. What should I do? Can you provide me some guidance? That's what I'm asking for.

**Comment by erogol** [comment]
https://github.com/mozilla/TTS/wiki
