### ISSUE TITLE
can't use the notebook to validate the dataset.

### ISSUE THREAD

**Issue by albluc24** [mozilla/TTS#274]
Hi.
I am training Tacotron2 on a tesla k80 with the italian m-ailabs speech dataset.
I wanted to adjust the hiperparameters in the json file, but i found that using the notebook tool to discover the appropriate parameters is quite impossible, as there are majour accessibility issues in the notebook interface that make it difficult to read the thing by a screen reader.
By the way, I'm blind so i can't see any spectrograms either, if that's something to consider when running the demo. I'm also running this ona vps, so i had to do some ssh port forwarding to get this to work.
Additionally, when i started the training with phonemes hoping that adjusting the frequence(hz) parameter along with the others regarding the paths would be enough, after 4000 steps i got testing files that where just some wite noise and something else, sadly I don't know how to include the files in the issue, if you're interested I can share something like a onedrive link or such.
Can someone please give me directions on how to proceed about dataset hiperparams?
Oh and, if this is of any relevance, i have merged all the wave files for the books in one folder and created an unique metadata.csv, avoiding having to use the m-ailabs loader and used the simpler ljspeech one instead, but as this is just data loading and doesn't have any inference regarding the hiperparams, don't know if it makes any difference.
Thanks for your time, have a good day!

**Comment by erogol** [comment]
which parameters you are referring to? Are these audio processing values?

Notebooks mostly created for LJSpeech dataset. Therefore, they might need a bit of coding adapting to another dataset. So basically the idea to find the right audio processing parameters is to use different values and compare the voice resynthesis results with Griffin-Lim and pick the best parameters.

**Comment by albluc24** [comment]
Hi.
Yes, I am referring to the audio processing parameters, as I think these are the faulty ones.
Can you please explain in more depth the procedure to replicate the procedure stated in notebooks for an other dataset and without using notebooks?
So if I understood correctly it's all about feeding the audio to griffin lim with the parameters and hearing the results, but i do not understand what inference it could have in tacotron 2, which if i'm not wrong uses wavenet as the vocoder.
Is there something I'm missing?
Thanks.

**Comment by erogol** [comment]
The assumption is that if parameters work well with Griffin Lim , they also work well with other methods. Maybe it is wrong but a practical one since we cannot test all the audio parameters on a neural vocoder. Hope it makes sense.

So the procedure is as I explained above. Try different parameters and test voice quality after Griffin-Lim.
