### ISSUE TITLE
preprocess.py can't load M-AILABS dataset

### ISSUE THREAD

**Issue by massimo1980** [mozilla/TTS#275]
Hi,
actually preprocess.py can't load meta_files from M-AILABS dataset.
in my config.json i didn't set the meta_files values and running train.py gives me this error:
ValueError: zero-size array to reduction operation maximum which has no identity

csv_files variable is empy

the only way i can make it work is to change line 76 of file datasets/preprocess.py 
from:
if meta_files is None:

to:
if not meta_files:

Best regards
Massimo

**Comment by albluc24** [comment]
Hi.
I'm not a contributor of this project, but i'm also using this speech dataset.
From your name I think you're italian like I am, and so probably we're using the same dataset portion
Instead of using the m-AIlabs loader to load this, i just adjusted the samplerate in the json file and merged the metadata file for all the books in a singol one, then did the same with all the wavs, and in that case the ljspeech loader worked and didn't trow any errors.
Hope this helps.

**Comment by massimo1980** [comment]
Hi and thanks for the reply. ( and yes..i'm italian )
As i wrote, i managed to solve the issue changing a line of code in file preprocess.py. I opened this thread only for let the developers known about this "possible" issue.
My problem is that after 400 steps of the first Epoch it rise an error: CUDA out of memory
( actually i'm training this dataset on my i7 6600K with a GTX 1070 8Gb )
i still can't understand if there's some parameters to adjust or if i'm doing something wrong...
Hope that you have more luck than me!
Regards

**Comment by albluc24** [comment]
Hi.
They say, in the requirements, that with batch size 32 you need like 9.1 gb of memory, so i think you could try reducing the batch size, i'm not sure about the 32 though because i can't read  the exact thing now, so don't take my words as granted.
I am training my model on a tesla k80 wich has like 22 gb of memory, so I didn't have this issue, i'm using it in an azure vm.
By the way, just out of curiosity, are you training with Riccardo Fasol?
I find his voice really awesome, so I'm training with his data in hope to produce a really great italian voice to read audiobooks!
Anyway, hope this helps, have a good day.

**Comment by erogol** [comment]
@massimo1980 you need to set meta_files field in config.json as '''null''. I guess you missed that and therefore it did not work.

**Comment by massimo1980** [comment]
@erogol 
Hi,
i'm sorry if i'm bother you ( i'm using this thread without opening a new one ). Just for curiosity:
I've successfully trained italian dataset of M-AILABS to 115K steps. Just for testing pourposes, i was tryin to use the trained model on a Raspberry Pi. My goal is to implement the use of a neural stick to see the response time.
If i try to run the server i got this errors:

**Comment by lauraadalmolin** [comment]
I am facing the same problem as @massimo1980. Any updates?

**Comment by WeberJulian** [comment]
> @massimo1980 you need to set meta_files field in config.json as '''null''. I guess you missed that and therefore it did not work.

I don't think that's the problem.
I'm training on the french portion of the dataset and I got the same problem even with both meta_files values to null.

```
"datasets":   // List of datasets. They all merged and they get different speaker_ids.
        [
            {
                "name": "mailabs",
                "path": "../mailabs",
                "meta_file_train": null,
                "meta_file_val": null
            }
        ]
```

and I got 

`ValueError: zero-size array to reduction operation maximum which has no identity`

**Comment by kr6k3n** [comment]
> > @massimo1980 you need to set meta_files field in config.json as '''null''. I guess you missed that and therefore it did not work.
> 
> @erogol I don't think that's the problem.
> I'm training on the french portion of the dataset and I got the same problem even with both meta_files values to null.
> 
> ```
> "datasets":   // List of datasets. They all merged and they get different speaker_ids.
>         [
>             {
>                 "name": "mailabs",
>                 "path": "../mailabs",
>                 "meta_file_train": null,
>                 "meta_file_val": null
>             }
>         ]
> ```
> 
> and I got
> 
> `ValueError: zero-size array to reduction operation maximum which has no identity`
> 
> EDIT: I just realised that I have the same error but not the same problem since the variable csv_files is not empty
> 
> EDIT2: It was the speaker_regex that wasn't right for me, it's working fine now

Have you successfully trained your model on french?

**Comment by WeberJulian** [comment]
Yeah, It's not perfect though. I still have problems with ponctuation and some special letters and combination of letters ("ç", "echo"...). I'm gonna try to train a character based model.

**Comment by kr6k3n** [comment]
Nice, would you mind sharing the resulting model? I have been trying to find a trained model since I can't afford any good gpu to train TTS on french mailabs. I would also suggest patching specific syllables ie. "ç" becomes "ss".

**Comment by WeberJulian** [comment]
Yeah sure, I'll wait for the release of [this](https://github.com/mozilla/TTS/issues/501#issuecomment-695195474) first because I haven't successfully trained a vocoder for this speaker yet.

**Comment by george-roussos** [comment]
Do you guys use the correct function for phonemes? basic_cleaner.

**Comment by WeberJulian** [comment]
> Do you guys use the correct function for phonemes? basic_cleaner.

What's "basic_cleaner" ? I can't find a mention of it in the TTS project

**Comment by george-roussos** [comment]
`basic_cleaners` in `cleaners.py`. It does not turn special characters to ASCII. You set it in the [config.json](url) in the `cleaners` field. Alternatively, you can write your own function.

**Comment by WeberJulian** [comment]
Oh yeah I completely overlook this part. This is gonna be great for number normalization as well (for now I have to write them in full). Thanks, I'm gonna look into that !
