### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Tacotron: 	size mismatch for embedding.weight: copying a param with shape torch.Size([61, 256]) from checkpoint, the shape in current model is torch.Size([256, 1025]).

### ISSUE THREAD

**Issue by iotnikhil** [mozilla/TTS#276]
Hello,
I am being trying to Run TTS Web service example but i am getting the following run-time error 

"RuntimeError: Error(s) in loading state_dict for Tacotron:
	size mismatch for embedding.weight: copying a param with shape torch.Size([61, 256]) from checkpoint, the shape in current model is torch.Size([256, 1025])."

I am using "best_model.pth.tar"  and  "config.json" model which you provides in below link :

"https://drive.google.com/drive/folders/1GU8WGix98WrR3ayjoiirmmbLUZzwg4n0"

my server "conf.json" file contains : 

```
 _{
     "model_path":"",
     "model_name":"best_model.pth.tar",
     "model_config":"config.json",
     "port": 5002,
     "use_cuda": false
 }_

```
commit i am using:
 

> git checkout db7f3d3

Any help will be appreciated, Thanks in advance! :)

**Comment by erogol** [comment]
check here to find the right branch. The one on master is outdated soon to be updated. 

https://github.com/mozilla/TTS/wiki/Released-Models
