### ISSUE TITLE
Memory leak on flask server

### ISSUE THREAD

**Issue by fuchini** [mozilla/TTS#277]
Hello, I'm having two weird memory errors:

1) I can train a model normally but when I try to re-train with exactly the same config I get CUDA OOM errors and I have to lower the batch size.
2) Using the flask server on CPU the memory usage starts to rise constantly after several requests until I get "Cannot Allocate Memory"

Thanks a lot

**Comment by erogol** [comment]
@fuchini how far it goes in memory usage if you train it from the beginning.

**Comment by fuchini** [comment]
With batch_size=32 and 2 V100's it uses around 10gb-12gb on each one.

**Comment by fuchini** [comment]
Don't know if its related but I see something like this with nvidia-smi training from the beginning:
`+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1644      C   python3                                    11377MiB |
|    1      1645      C   python3                                    12363MiB |
+-----------------------------------------------------------------------------+`

When retraining I get:

`+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2783      C   python3                                     5105MiB |
|    0      2784      C   python3                                     1413MiB |
|    1      2784      C   python3                                     7263MiB |
+-----------------------------------------------------------------------------+`

**Comment by erogol** [comment]
So does it mean there are 3 processes for retraining and 2 for normal training?

**Comment by fuchini** [comment]
It seems so but two of them have the same pid.

**Comment by erogol** [comment]
is it possible that one of the processes stalled after the first run

**Comment by fuchini** [comment]
I don't know, but wouldn't it have a different id?

**Comment by fuchini** [comment]
On the flask server I've tried manually deleting some objects and doing garbage collection manually but it doesn't seem to work.

**Comment by erogol** [comment]
I need to check in detail if it is something with the server. I'll let you know once I do it.

**Comment by erogol** [comment]
I can't really replicate it. It might be about your computer setup for some reason.
