### ISSUE TITLE
Missing keys in State Dictionary

### ISSUE THREAD

**Issue by pshah123** [mozilla/TTS#28]
When running both with and without CUDA, using either pretrained model, I get the following error:

![image](https://user-images.githubusercontent.com/6960204/39830762-4b426f1a-53ba-11e8-9f75-a1c001ceed9d.png)

```
RuntimeError: Error(s) in loading state_dict for Tacotron:
	Missing key(s) in state_dict: "decoder.stopnet.1.weight", "decoder.stopnet.1.bias". 
```

The state dict has keys for `decoder.prenet` but **not** `decoder.stopnet`. Is there a workaround to this other than training my own model from scratch?

**Comment by pshah123** [comment]
For anyone else stumbling across this issue, a workaround I found is to revert to `e00bc66`:

```
git checkout e00bc66
```

I also removed the `torchviz` dependency in the notebook from this commit as I have no use for it.

**Comment by erogol** [comment]
@pshah123 thx for your return. The workaround is the right way to run the checkpoint. This repo is currently in a very rush development process with no beta or alpha release yet. That said, we change things very fast and update the repo without any release cycle. Therefore, the master branch is most likely to have updates which are not available at the time of checkpoint. In your case, it is stop token prediction.
