### ISSUE TITLE
[Experiment] Multi-Head attention 

### ISSUE THREAD

**Issue by erogol** [mozilla/TTS#280]
As an alternative, I try multi-head attention with 3 heads currently. The idea is to bolster the attention module which is quite sensitive without the help of forward attention at inference.

[X] implement multi-head attention
[X] train 3 head multi-head attention model
[ ] try orthogonal initialization among the heads.

**Comment by alexdemartos** [comment]
Really interesting experiment. Please keep us updated if you achieve higher inference robustness using multi-head attention :) Location Sensitive is indeed pretty weak for not-as-easy-as-LJSpeech corpora.

**Comment by erogol** [comment]
These are the different heads learned by the initial Tacotron model using 3 attention heads. 

![image](https://user-images.githubusercontent.com/1402048/65521296-46ea0980-dee9-11e9-8ffa-fba1cf8c97d8.png)

**Comment by WhiteFu** [comment]
Good Job!
I'm very interested in this experiment(multi-head), but I can't find it in dev. Will you continue to update relevant progress?
