### ISSUE TITLE
[Experiment] Try to predict encoder durations as in FastSpeech

### ISSUE THREAD

**Issue by erogol** [mozilla/TTS#281]
Train a small network to predict encoder durations that might replace the attention module, as in https://arxiv.org/pdf/1905.09263.pdf

[x] implement duration predictor
[x] train a simple duration predictor separately with TTS model by using attention output as label
[X] train duration predictor in parallel with TTS model.
[  ] find a way to resolve the distribution problem. (described below)

**Comment by erogol** [comment]
This method works to replace the attention module. However, due to distribution differences between thee two methods that occur on the decoder side, the final result is not better than the normal model. 

Here is a simple alignment plot created by the durations predicted by an external duration network.

![image](https://user-images.githubusercontent.com/1402048/65520785-73e9ec80-dee8-11e9-9cb0-100cf55167ca.png)

**Comment by te0006** [comment]
An interesting paper, had noticed as well. 
Can you elaborate on what you understand by "more robust"? If it means that outliers with badly wrong timing could be completely ruled out (or made to occur only exceptionally rarely), I think that would be quite a valuable improvement. But perhaps I don't understand the price to be paid clearly enough. 
How severe are the negative effects of the "distribution problem" you mentioned in practice?

**Comment by erogol** [comment]
Duration prediction is robust in a sense it does not fall apart completely if there is something wrong at a single step. However, it is the case for normal attention.

Duration prediction works like hard attention and it decreases the naturalness of the speech leading to a very edgy, directive speech.

**Comment by geneing** [comment]
I don't think duration prediction is compatible with style tokens, so we lose the ability to adjust speaking style.

**Comment by geneing** [comment]
@erogol are these changes available in github repo? Could you push them to github for those who want to try more experiments along these lines.

**Comment by erogol** [comment]
@geneing you can find here https://github.com/erogol/TTS_experiments/tree/duration-train
