### ISSUE TITLE
Which Released Models is for branch Master and Errors for Tacotron2-iter-260K with Master code

### ISSUE THREAD

**Issue by Pin-Jui** [mozilla/TTS#284]
Hi,
I would like to know what is the released models for branch Master.
I used Tacotron2-iter-260K but got torch.size mismatch Errors like:

![image](https://user-images.githubusercontent.com/16241485/65388303-8d6f2500-dd7e-11e9-9735-d7082aeefa09.png)

Thanks!

Best regards,
Paul

**Comment by erogol** [comment]
Nothing is for the master branch for now. You need to check out the right history before using the model. The right checkout point is given right next to the model on the table.
