### ISSUE TITLE
Mislearning problem

### ISSUE THREAD

**Issue by duman** [mozilla/TTS#286]
Hello,

I've recorded a dataset on my own and started the training. I was getting some warnings and mentioned them in this issue: https://github.com/mozilla/TTS/issues/282

Erogol's respond was "Nan is about the multi GPU training. Since there is padding in sequences, when you distribute them on GPUs, some GPUs might have only the padded part. So they produce NaN gradients."

I have also received NaN warning with a single GPU and I believe attention got better over the time as I started to hear meaningful words instead of random noises however those meaningful words are always the same things repeating itself over and over.

As an example I copy pasted this sentence for synthesis "Milliyetçi Hareket Partisi Lideri Devlet Bahçeli hastaneye kaldırıldı. Bahçeli'nin sağlık durumu hakkında henüz resmi bir açıklama gelmezken rutin kontroller nedeniyle hastaneye gittiği öğrenildi." however the sentence I heard back was "Kıbrıs harekatının düzenlenmesi ile ilgili..." and some silence afterwards.

Synthesized sentences are always 12 seconds long and even on the synthesis page I'm getting "Decoder stopped with 'max_decoder_steps"" and I believe it's something related to that.

Currently I'm around 82000+ global steps. Here are some images for better understanding of the situation.

<img width="753" alt="image" src="https://user-images.githubusercontent.com/22964050/65414077-95b97580-ddfb-11e9-98e5-aa8e73e67a32.png">

<img width="862" alt="image" src="https://user-images.githubusercontent.com/22964050/65414148-c26d8d00-ddfb-11e9-94b4-4b241b68896e.png">

<img width="748" alt="image" src="https://user-images.githubusercontent.com/22964050/65414323-23956080-ddfc-11e9-9e13-c5baf706d49a.png">

<img width="759" alt="image" src="https://user-images.githubusercontent.com/22964050/65414355-3445d680-ddfc-11e9-9dd6-b384ba12b895.png">

<img width="778" alt="image" src="https://user-images.githubusercontent.com/22964050/65414381-3e67d500-ddfc-11e9-81c7-49119acd595f.png">

Eval audio also gives a sentence which is clearly synthesized from my voice and it's a meaningful and different sentence, however test audios are completely random and garbage. 0-audio being the "Kıbrıs" one.

<img width="766" alt="image" src="https://user-images.githubusercontent.com/22964050/65414483-80911680-ddfc-11e9-901c-8260de0a67ff.png">

<img width="789" alt="image" src="https://user-images.githubusercontent.com/22964050/65414574-b2a27880-ddfc-11e9-8175-d4e108802a56.png">

<img width="760" alt="image" src="https://user-images.githubusercontent.com/22964050/65414594-bcc47700-ddfc-11e9-916e-13ee16daae0b.png">

My question is what went wrong here? Dataset is recorded by me in a silent environment with a pretty decent microphone. (Arctis 5 2019 edition) It's around 6 hours long, and prepared in the format of LJSpeech dataset, only for Turkish.

You can see my settings in /issues/282.

**Comment by erogol** [comment]
Can you share at least a couple of examples from your dataset?

**Comment by erogol** [comment]
You can also try to reduce LR looking at the jiggling eval plots.

**Comment by erogol** [comment]
There is also a huge padding for the test examples. Make sure things are in similar lengths given your dataset is small.

**Comment by duman** [comment]
Sure thing, I'm currently on my way home. As soon as I get to home I'll send a sample (about 20 voices and the metadata for it) for you to examine.

Thank you for making this project possible.

**Comment by duman** [comment]
Hello @erogol, I've added an example of my recordings.

20 voice files in raw format, stereo 44100 Hz.
20 voice files in converted format, mono 22050 Hz. (in convert folder)
metadata.csv which includes 20 sentences in the format of LJSpeech dataset.

[TTS.zip](https://github.com/mozilla/TTS/files/3643968/TTS.zip)

I know that I don't have the most angelic voice out there but I do believe that it's fairly good and cropped just fine.

Let me know if you need something else.
Thanks yet another time.

**Comment by erogol** [comment]
Kayitlar guzel geliyor kulaga ama bir hayli echo var arkada. Bir de biraz daha yavas konusmayi deneye bilirsin. Ayrica yukarda soylediklerime de bir goz at. Eger uzunluk farklari cok fazla ise kisa kayilari arkaarkaya ekleyerek uzatabilirsin.

**Comment by duman** [comment]
Teşekkür ederim cevabınız için. Sesleri nasıl kaydetmem gerektiğine dair fikir vermesi için sizin de küçük bir sample paylaşmanız mümkün mü acaba? (NaN vercek mi vs. gibi uyarıları kontrol etmek için) İpuçları için teşekkür ederim, gerekli geliştirmeleri söylediklerinize göre yapacağım.

**Comment by erogol** [comment]
Nancy dataset'ine bakarsan oradaki kayit kalitesi bir hayli iyi. Mumkun oldugunca arka tarafta eko olmamasina dikkat et ve tane tane konusmaya calis, eger kendin kaydetmeye devam etmek istersen :)

**Comment by duman** [comment]
Tamam öyle yapayım, teşekkür ederim tekrardan.
Yine öğrenmede güçlük yaşar veya yeni bir problemle karşılaşırsam issue açarım.

İlginiz için sağolun.
İyi çalışmalar. :)
