### ISSUE TITLE
Will multiple GPU solve CUDA out of memory issue?

### ISSUE THREAD

**Issue by vcjob** [mozilla/TTS#290]
Hello everyone!

With rtx2080ti I face with CUDA OOM issue with batch size 32 (which is recommended, right?).
My question is, if I extend my server with a second rtx2080ti, will I be able to run distributed training with batch size 32? Or the memory is not going to sum up?
Are there only two ways to run with 32 batch size: change GPU to another with a bigger capacity, or use another dataset with shorter instances?
Thank you a lot!

**Comment by erogol** [comment]
It is not about TTS dev, use discourse pls.
