### ISSUE TITLE
ModuleNotFoundError: No module named 'WaveRNN'

### ISSUE THREAD

**Issue by massimo1980** [mozilla/TTS#291]
Hi there,
actually i'm tryin to test the TTS server with my checkpoint using also my WaveRNN training.

`root@genesis-desktop:/opt/TTS# python3 server/server.py -c server/conf.json
 > Loading TTS model ...
 | > model config:  /opt/TTS/results/mailabs-September-15-2019_02+26PM-f08b31f/config.json
 | > model file:  checkpoint_133000.pth.tar
 > Setting up Audio Processor...
 | > sample_rate:16000
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:12.5
 | > frame_length_ms:50
 | > ref_level_db:20
 | > num_freq:2049
 | > power:1.5
 | > preemphasis:0.98
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:False
 | > mel_fmin:0
 | > mel_fmax:8000.0
 | > max_norm:1.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > n_fft:4096
 | > hop_length:200
 | > win_length:800
 > Using model: Tacotron2
Traceback (most recent call last):
  File "server/server.py", line 14, in <module>
    synthesizer = Synthesizer(config)
  File "/opt/TTS/server/synthesizer.py", line 32, in __init__
    self.load_wavernn(config.wavernn_lib_path, config.wavernn_path, config.wavernn_file, config.wavernn_config, config.use_cuda)
  File "/opt/TTS/server/synthesizer.py", line 71, in load_wavernn
    from WaveRNN.models.wavernn import Model
ModuleNotFoundError: No module named 'WaveRNN'

root@genesis-desktop:/opt/TTS# python3
Python 3.6.8 (default, Aug 20 2019, 17:12:48) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print (sys.path)
['', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/dist-packages', '/usr/local/lib/python3.6/dist-packages/tensorboardX-1.8-py3.6.egg', '/usr/local/lib/python3.6/dist-packages/protobuf-3.10.0rc1-py3.6.egg', '/usr/local/lib/python3.6/dist-packages/WaveRNN-0.0.1+7c52874-py3.6.egg', '/usr/local/lib/python3.6/dist-packages/TTS-0.0.1-py3.6.egg', '/usr/lib/python3/dist-packages', '/usr/lib/python3.6/dist-packages']
>>> 
`
both TTS and WaveRNN installed ( using easy_install )
Actually, using my TTS training ( italian dataset 130K steps ) and using GL for speech synthesis, my jetson nano takes about 15 seconds with a short simple phrase
In terms of "timing", how differ in using the WaveRNN model instead of the GriffinLim?

Regards
Massimo

**Comment by erogol** [comment]
try ```export PYTHONPATH="/path/to/WaveRNN"``` before running the code
