### ISSUE TITLE
CUDA OOM while indeed there is plenty of memory left!

### ISSUE THREAD

**Issue by vcjob** [mozilla/TTS#292]
Hello everyone!

I try to train Tacotron2 Model. First tried with dev branch, now with master. Closely to end of the 1st epoch I got error:

Traceback (most recent call last):
  File "train.py", line 647, in <module>
    main(args)
  File "train.py", line 554, in main
    ap, global_step, epoch)
  File "train.py", line 153, in train
    text_input, text_lengths, mel_input, speaker_ids=speaker_ids)
  File "/opt/mozilla-tts/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/mozilla-tts/lib/python3.6/site-packages/TTS-0.0.1+53d658f-py3.6.egg/TTS/models/tacotron2.py", line 54, in forward
    mel_outputs_postnet = self.postnet(mel_outputs)
  File "/opt/mozilla-tts/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/mozilla-tts/lib/python3.6/site-packages/TTS-0.0.1+53d658f-py3.6.egg/TTS/layers/tacotron2.py", line 45, in forward
    x = layer(x)
  File "/opt/mozilla-tts/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/mozilla-tts/lib/python3.6/site-packages/TTS-0.0.1+53d658f-py3.6.egg/TTS/layers/tacotron2.py", line 27, in forward
    output = self.net(x)
  File "/opt/mozilla-tts/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/mozilla-tts/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/opt/mozilla-tts/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/mozilla-tts/lib/python3.6/site-packages/torch/nn/modules/activation.py", line 292, in forward
    return torch.tanh(input)
RuntimeError: CUDA out of memory. Tried to allocate 51.62 MiB (GPU 0; 10.73 GiB total capacity; 6.36 GiB already allocated; 7.25 MiB free; 137.09 MiB cached)

The thing is, no other processes use GPU, except for the only one python3 with training. Server has no GUI, just console. 
Only 6.36 gb were used, and python3 could not allocate 51.65 Mb extra? (Its RTX2080ti with 10.9 GB).
What could it be? Driver issues? 
CUDA 10.0. NVIDIA_SMI 410.93
Thank you!

**Comment by massimo1980** [comment]
Hi there.
i'm not a contributor of this project but i faced the same problem. 
It depends on how big is your dataset and the batch_size . for example M-AILABS italian dataset with a batch size of 32, it required 9.1 Gb of memory.
Try reducing the batch size.

**Comment by vcjob** [comment]
> Hi there.
> i'm not a contributor of this project but i faced the same problem.
> It depends on how big is your dataset and the batch_size . for example M-AILABS italian dataset with a batch size of 32, it required 9.1 Gb of memory.
> Try reducing the batch size.

Thank you for the reply!
In fact, I used different batch sizes, and that problem started to happen recently, not sure what after, but maybe because I updated version of TTS from repository. Before that I used to be able to run Tacotron2 for more than 2 epoch with no problem and even with slightly bigger batch size. Anyway, the memory usage was around 7 gb by 1000nd step of 1027. So, amount of memory was sufficient for sure.
Well, now I updated the CUDA to 10.1 and trying to see if it helps.

**Comment by massimo1980** [comment]
I have also tried to update TTS from repository....but after upgrade i can't use the checkpoint anymore.
always there errors:

RuntimeError: Error(s) in loading state_dict for Tacotron2:
       Missing key(s) in state_dict: "decoder.attention.query_layer.linear_layer.weight", "decoder.attention.inputs_layer.linear_layer.weight", "decoder.attention.v.linear_layer.weight", "decoder.attention.v.linear_layer.bias".
       Unexpected key(s) in state_dict: "decoder.attention_layer.query_layer.linear_layer.weight", "decoder.attention_layer.inputs_layer.linear_layer.weight", "decoder.attention_layer.v.linear_layer.weight", "decoder.attention_layer.v.linear_layer.bias".
       size mismatch for embedding.weight: copying a param with shape torch.Size([130, 512]) from checkpoint, the shape in current model is torch.Size([129, 512]).

**Comment by vcjob** [comment]
With a newer version of driver and CUDA 10.1 now I clearly see how memory is being used. it goes up to 10.9, then drops half to ~6gb, then again rise consumption to ~10GB. Probably, CUDA 10.0 should now be used anymore.

**Comment by vcjob** [comment]
> I have also tried to update TTS from repository....but after upgrade i can't use the checkpoint anymore.
> always there errors:
> 
> RuntimeError: Error(s) in loading state_dict for Tacotron2:
> Missing key(s) in state_dict: "decoder.attention.query_layer.linear_layer.weight", "decoder.attention.inputs_layer.linear_layer.weight", "decoder.attention.v.linear_layer.weight", "decoder.attention.v.linear_layer.bias".
> Unexpected key(s) in state_dict: "decoder.attention_layer.query_layer.linear_layer.weight", "decoder.attention_layer.inputs_layer.linear_layer.weight", "decoder.attention_layer.v.linear_layer.weight", "decoder.attention_layer.v.linear_layer.bias".
> size mismatch for embedding.weight: copying a param with shape torch.Size([130, 512]) from checkpoint, the shape in current model is torch.Size([129, 512]).

I haven't faced that issue, probably since I have no older checkpoint to use with newer version of the repository. 
I actually faced with something similar to _size mismatch for embedding.weight: copying a param with shape torch.Size([130, 512]) from checkpoint, the shape in current model is torch.Size([129, 512])._ . As I understood, the reason was in the utils/text/symbols.py file. I changed not only __characters_ , but __punctuations_ as well, which led to size mismatch problem. Did you change it by any chance as well?

**Comment by massimo1980** [comment]
i'll give it a tryin as soon as possible!
tnx for the advice!
