### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by rishi454** [mozilla/TTS#293]
While training the TTS model i am getting this error. Can you help me to solve this.

Traceback (most recent call last):
  File "train.py", line 614, in <module>
    c = load_config(args.config_path)
  File "/home/jadi/tts/TTS/utils/generic_utils.py", line 22, in load_config
    with open(config_path, "r") as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by erogol** [comment]
you need to provide a config.json file.

python train.py --config_path config.json

**Comment by rishi454** [comment]
Thank you @erogol 
It is solved but I am getting another error that is as below.

 > Using model: Tacotron
 ! Run is removed from /home/jadi/tts/TTS/../keep/ljspeech-October-01-2019_02+44PM-0000000
Traceback (most recent call last):
  File "train.py", line 646, in <module>
    main(args)
  File "train.py", line 480, in main
    print(" | > Num output units : {}".format(ap.num_freq), flush==True)
NameError: name 'flush' is not defined
