### ISSUE TITLE
NameError: name 'flush' is not defined

### ISSUE THREAD

**Issue by rishi454** [mozilla/TTS#294]
I am getting another error that is as below.

Using model: Tacotron
! Run is removed from /home/jadi/tts/TTS/../keep/ljspeech-October-01-2019_02+44PM-0000000
Traceback (most recent call last):
File "train.py", line 646, in
main(args)
File "train.py", line 480, in main
print(" | > Num output units : {}".format(ap.num_freq), flush==True)
NameError: name 'flush' is not defined

**Comment by erogol** [comment]
```
flush==True -> flush=true 
```
