### ISSUE TITLE
Error(s) in loading state_dict for Tacotron

### ISSUE THREAD

**Issue by rishi454** [mozilla/TTS#297]
Help me to solve the this error:

RuntimeError: Error(s) in loading state_dict for Tacotron:
	Missing key(s) in state_dict: "speaker_embedding.weight". 
	size mismatch for decoder.prenet.layers.0.linear_layer.weight: copying a param with shape torch.Size([256, 80]) from checkpoint, the shape in current model is torch.Size([256, 35]).
	size mismatch for decoder.proj_to_mel.weight: copying a param with shape torch.Size([560, 256]) from checkpoint, the shape in current model is torch.Size([7175, 256]).
	size mismatch for decoder.proj_to_mel.bias: copying a param with shape torch.Size([560]) from checkpoint, the shape in current model is torch.Size([7175]).

**Comment by erogol** [comment]
You changed the model size somewhere in the code before training and things does not match after the training. I can't know exactly what the problem is but checking out another branch might help.
