### ISSUE TITLE
Synthesized audios is too long and all audio durations are the same...

### ISSUE THREAD

**Issue by zhjy8827** [mozilla/TTS#299]
I am using this project to train a Mandarin Chinese TTS model. Its train effect is very good right now. But there was something wrong with the synthesis.
I use synthesize.py file to synthesis audio.The synthesized audio is too long(There is a long silence at the end),but the beginning of the sound is very clear.
And the audios length I synthesized is exactly the same!
I don't know what happened....
Any suggestions from you will help me thx!

`xxx@ubuntu:~/TTS$ CUDA_VISIBLE_DEVICES=7 python synthesize.py "zhong1 guo4 di4 zhi4 da4 xue2 da4 xue2 ji4 suan4 ji1 xie2 hui4" ./config.json ./training_outputs/training_outputs/checkpoint_130000.pth.tar ../data --use_cuda true
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:12.5
 | > frame_length_ms:50
 | > ref_level_db:20
 | > num_freq:1025
 | > power:1.5
 | > preemphasis:0.98
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:8000.0
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > n_fft:2048
 | > hop_length:275
 | > win_length:1100
 > Using model: Tacotron2
 > Text: zhong1 guo4 di4 zhi4 da4 xue2 da4 xue2 ji4 suan4 ji1 xie2 hui4
   | > Decoder stopped with 'max_decoder_steps
 >  Run-time: 70.51012110710144
 > Saving output to ../data/zhong1_guo4_di4_zhi4_da4_xue2_da4_xue2_ji4_suan4_ji1_xie2_hui4.wav
[zhong1_guo4_di4_zhi4_da4_xue2_da4_xue2_ji4_suan4_ji1_xie2_hui4.wav.zip](https://github.com/mozilla/TTS/files/3710508/zhong1_guo4_di4_zhi4_da4_xue2_da4_xue2_ji4_suan4_ji1_xie2_hui4.wav.zip)
`

![individualImage](https://user-images.githubusercontent.com/38745522/66539240-f0700280-eb59-11e9-9260-425c00a83ef1.png)
![individualImage (2)](https://user-images.githubusercontent.com/38745522/66539243-f1a12f80-eb59-11e9-9a83-8d9cc2620c3a.png)
![individualImage (1)](https://user-images.githubusercontent.com/38745522/66539245-f2d25c80-eb59-11e9-82f4-cd80789eefc2.png)
[config.json.zip](https://github.com/mozilla/TTS/files/3710503/config.json.zip)

[zhong1_guo4_nong2_ye4_da4_xue2.wav.zip](https://github.com/mozilla/TTS/files/3710495/zhong1_guo4_nong2_ye4_da4_xue2.wav.zip)

**Comment by puppyapple** [comment]
@zhjy8827 Hello, I have met the same situation as you described here. Have you found the reason for this issue? Thanks!

**Comment by zhjy8827** [comment]
@puppyapple More training may be resolved , or  using model is Tacotron than Tacotron2....
