### ISSUE TITLE
How can I install it and is it pre-trained?

### ISSUE THREAD

**Issue by sajjadsaleem** [mozilla/TTS#30]
I want to use this mozilla TTS for my text to speech application. How can I install it on ubuntu? and is it per-trained?

**Comment by kdavis-mozilla** [comment]
It's currently in development and not (yet) ready to be used in applications.

**Comment by kdavis-mozilla** [comment]
We are working full steam ahead, but we've no release date. We want quality over alacrity.

**Comment by m3m3-chan** [comment]
Hi,
I too want to use the model for my python project. is the pretrained model still not out? & where to find the release checkpoints & How  to use it?

thanks,

**Comment by MuruganR96** [comment]
Please visit this page. they update their readme. 
pretrained models with code here.
[Pretrained model](https://github.com/mozilla/TTS/wiki/Released-Models)
