### ISSUE TITLE
Incorporate a better hyperparameter management?

### ISSUE THREAD

**Issue by PetrochukM** [mozilla/TTS#305]
Looks like all the hyperparameters are all in a global namespace. This can cause issues like:
- It's not clear how or if a hyperparameter is being used
- The namespace is cluttered with more than 80+ hyperparameters
- The code needs extra documentation to ensure clarity and readability
- A configuration needs to be passed around as a dependency that everything is dependent on.

I had the same problems so I built a small utility called [HParams](https://github.com/PetrochukM/HParams). Is this helpful?

**Comment by erogol** [comment]
I agree the current setup is not optimal. If you could send me a PR, I'd check the possibilities.

**Comment by PetrochukM** [comment]
I don't have more time for open source contributions for this month, I just released HParams and PyTorch-NLP 0.5.0. I might be able to help later but no promises!

**Comment by erogol** [comment]
I direct this issue to #236, let us continue there.
