### ISSUE TITLE
how to deploy tacotron or tacotron2 on aws t2.large so that it can perform multiprocessing ?

### ISSUE THREAD

**Issue by dimanshu** [mozilla/TTS#309]

**Comment by erogol** [comment]
multiprocessing for ?

**Comment by dimanshu** [comment]
to serve multiple requests at one time. 
nothing happend with gunicorn and nginx (serving only 30 request in 60 seconds )

**Comment by erogol** [comment]
I guess server-side needs a bit of engineering to be optimized. On the other hand, I am not quite familiar with AWS. Therefore, my comment might be limited. I hope someone else could help. But it sould be a better place to post it on discourse since it is not dev related.

**Comment by erogol** [comment]
you can move it to discourse if you like.
