### ISSUE TITLE
Type error in setup_model

### ISSUE THREAD

**Issue by rishi454** [mozilla/TTS#312]
TypeError                                 Traceback (most recent call last)
<ipython-input-8-ef237752c850> in <module>()
      4 # load the model
      5 num_chars = len(phonemes) if CONFIG.use_phonemes else len(symbols)
----> 6 model = setup_model(num_chars, CONFIG)
      7 
      8 # load the audio processor

TypeError: setup_model() missing 1 required positional argument: 'c'

**Comment by erogol** [comment]
not enough info
