### ISSUE TITLE
Error in TTS setup_model.

### ISSUE THREAD

**Issue by rishi454** [mozilla/TTS#313]
# This is the code for TTS mode load.

#LOAD TTS MODEL
from utils.text.symbols import symbols, phonemes

#load the model
num_chars = len(phonemes) if CONFIG.use_phonemes else len(symbols)
model = setup_model(num_chars, CONFIG)

#load the audio processor
ap = AudioProcessor(**CONFIG.audio)         

#load model state
if use_cuda:
    cp = torch.load(MODEL_PATH)
else:
    cp = torch.load(MODEL_PATH, map_location=lambda storage, loc: storage)

#load the model
model.load_state_dict(cp['model'])
if use_cuda:
    model.cuda()
model.eval()
print(cp['step'])l

# Here is the error when I run the TTS model testing , I am getting following type error:

TypeError                                 Traceback (most recent call last)
<ipython-input-6-ef237752c850> in <module>()
      4 # load the model
      5 num_chars = len(phonemes) if CONFIG.use_phonemes else len(symbols)
----> 6 model = setup_model(num_chars, CONFIG)
      7 
      8 # load the audio processor

TypeError: setup_model() missing 1 required positional argument: 'c'

**Comment by erogol** [comment]
Is it a model you trained, or do you try to use one of our released models?

**Comment by rishi454** [comment]
it is my trained TTS model

**Comment by erogol** [comment]
is it the latest master branch?

**Comment by erogol** [comment]
and what do you use for testing? Is it the notebook, or synthesize.py?

**Comment by erogol** [comment]
You should give all these info beforehand. We cannot foresee them.

**Comment by rishi454** [comment]
thanks @erogol .
 I am my own TTS model for this I am using LJ data set , for testing I am using benchmark notebook.

**Comment by MRS-OBAMA** [comment]
I had the same problem,i believe i fixed it by adding TTS. before local imports such as 
`from TTS.models.tacotron import Tacotron
from TTS.layers import *`
