### ISSUE TITLE
multi-speaker/gst models

### ISSUE THREAD

**Issue by k-sokolov** [mozilla/TTS#315]
The "speaker encoder" section of the wiki says 
"There is also a released model trained on LibriTTS dataset with ~1000 speakers in Released Models page."
However, no such model is given there. Is there any model trained on multi-speaker datasets and/or in a gst fashion?

**Comment by nmstoker** [comment]
The model is there, in the second table, it has the name Speaker-Encoder-iter25k

It's for the speaker encoding project though (not gst) so sounds like it isn't quite what you're after.
