### ISSUE TITLE
Even simpler packaging with model embedded in wheel file

### ISSUE THREAD

**Issue by reuben** [mozilla/TTS#316]
The current simplified packaging option ships the model (checkpoint + config.json) as well as the server configuration separate from the Python wheel. But I was thinking that the model can be included as package data, like we include the server HTML template. Then the remaining server configuration options can be made into command line parameters, or environment variables for WSGI deployment, and the steps to run the TTS server could be as simple as:

```bash
pip install https://whatever/TTS-blah-blah.whl
python -m TTS.server.server
```

`server.py` would check if the package has a model included, and use that by default, or otherwise rely on the same flag as we have currently, `-c`.

**Comment by nmstoker** [comment]
Tried testing in my lunch break and ran out of time, but this seems a good idea and will try further later.

One point I noticed was there are a few dependencies that look like they're possibly only needed for dev and I wondered if there was a way to strip them out for this simplified packaging approach?

Eg I'm guessing these aren't strictly needed to run it for inference:
- tensorboardX
- matplotlib
- Pillow
- tqdm

**Comment by reuben** [comment]
That's right, but we use the same `setup.py` for development (ie with `pip install -e /path/to/tts/checkout`). Maybe we could have a separate `setup.py` for the inference package...

**Comment by reuben** [comment]
I have prototyped the method described in this issue and it seems to work. Need to clean it up a bit and make sure tests are working.

**Comment by reuben** [comment]
PR here: https://github.com/mozilla/TTS/pull/317

**Comment by erogol** [comment]
done?
