### ISSUE TITLE
Segmentation fault in synthesizer.py

### ISSUE THREAD

**Issue by DerJesko** [mozilla/TTS#320]
I built the docker image as detailed in the documentation and when starting running it I'm getting a segmentation fault. 
I've already looked into it a bit and it seems that inside the docker container as soon as I import `librosa` in version 0.6.2 and `torch` in version 1.3.1 then python3.6 segfaults.

**Comment by shad94** [comment]
Hi, I got almost the same problem. It is better described at discourse.mozilla.org/t/how-to-train-a-model, if it's the problem you talk about.

**Comment by IveJ** [comment]
Hi freind,

Try comply to requirement.txt to install, as recommended in implement via
container.

https://github.com/mozilla/TTS/blob/master/server/README.md

**Comment by DerJesko** [comment]
You are right, the installed version is not the one from the requirements.txt .
The building of the docker container runs `python setup.py develop`. In there other version numbers of the libaries are specified. Is that intentional?
