### ISSUE TITLE
ModuleNotFoundError: No module named 'TTS' on docker run

### ISSUE THREAD

**Issue by ng2dev** [mozilla/TTS#321]
Hello I was running these commands:

    docker build -t mozilla-tts .
    nvidia-docker run -it --rm -p 5002:5002 mozilla-tts

and ended up with this error:

    File "/srv/app/server/synthesizer.py", line 8, in <module>
    from TTS.utils.audio import AudioProcessor
    ModuleNotFoundError: No module named 'TTS'

Why could that be and how can I fix the path/to/parent_tts ?
Thanks

**Comment by IveJ** [comment]
Hi freind,

Plz check
tts_namespace <https://github.com/mozilla/TTS/tree/master/tts_namespace>/
README.md

**Comment by ng2dev** [comment]
Thanks for the reply I had to replace your personal system specific hard coded paths in server/config.json:

 from "tts_path":"/media/erogol/data_ssd/Models/libri_tts/5049/"  
 to "tts_path":"/srv/app/tts/",  // tts model root folder

Further had to add/change these lines to the Dockerfile

COPY tts_namespace/TTS /srv/app/tts
RUN pip install -r requirements.txt -e /srv/app/tts

Luckily I found this article that explained where to download a file called  
"tts_file":"best_model.pth.tar"

For some reason it then started to actually run something somehow - immediately terminating with this error however:

Traceback (most recent call last):
  File "server/server.py", line 14, in <module>
    synthesizer = Synthesizer(config)
  File "/srv/app/server/synthesizer.py", line 30, in __init__
    self.load_tts(self.config.tts_path, self.config.tts_file, self.config.tts_config, config.use_cuda)
  File "/srv/app/server/synthesizer.py", line 57, in load_tts
    self.tts_model.load_state_dict(cp['model'])
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Tacotron:
        Missing key(s) in state_dict: "encoder.prenet.layers.0.linear_layer.weight", "encoder.prenet.layers.0.linear_layer.bias", "encoder.prenet.layers.1.linear_layer.weight", "encoder.prenet.layers.1.linear_layer.bias", "decoder.prenet.layers.0.linear_layer.weight", "decoder.prenet.layers.0.linear_layer.bias", "decoder.prenet.layers.1.linear_layer.weight", "decoder.prenet.layers.1.linear_layer.bias", "decoder.attention_rnn.weight_ih", "decoder.attention_rnn.weight_hh", "decoder.attention_rnn.bias_ih", "decoder.attention_rnn.bias_hh", "decoder.attention.query_layer.linear_layer.weight", "decoder.attention.inputs_layer.linear_layer.weight", "decoder.attention.v.linear_layer.weight", "decoder.attention.v.linear_layer.bias", "decoder.attention.location_layer.location_conv.weight", "decoder.attention.location_layer.location_dense.linear_layer.weight", "last_linear.weight", "last_linear.bias". 
        Unexpected key(s) in state_dict: "encoder.prenet.layers.0.weight", "encoder.prenet.layers.0.bias", "encoder.prenet.layers.1.weight", "encoder.prenet.layers.1.bias", "decoder.attention_rnn_init.weight", "decoder.memory_init.weight", "decoder.decoder_rnn_inits.weight", "decoder.prenet.layers.0.weight", "decoder.prenet.layers.0.bias", "decoder.prenet.layers.1.weight", "decoder.prenet.layers.1.bias", "decoder.attention_rnn.rnn_cell.weight_ih", "decoder.attention_rnn.rnn_cell.weight_hh", "decoder.attention_rnn.rnn_cell.bias_ih", "decoder.attention_rnn.rnn_cell.bias_hh", "decoder.attention_rnn.alignment_model.loc_conv.1.weight", "decoder.attention_rnn.alignment_model.loc_linear.weight", "decoder.attention_rnn.alignment_model.loc_linear.bias", "decoder.attention_rnn.alignment_model.query_layer.weight", "decoder.attention_rnn.alignment_model.query_layer.bias", "decoder.attention_rnn.alignment_model.annot_layer.weight", "decoder.attention_rnn.alignment_model.annot_layer.bias", "decoder.attention_rnn.alignment_model.v.weight", "last_linear.0.weight", "last_linear.0.bias". 
        size mismatch for embedding.weight: copying a param with shape torch.Size([61, 256]) from checkpoint, the shape in current model is torch.Size([129, 256]).
        size mismatch for decoder.proj_to_mel.weight: copying a param with shape torch.Size([160, 256]) from checkpoint, the shape in current model is torch.Size([560, 256]).
        size mismatch for decoder.proj_to_mel.bias: copying a param with shape torch.Size([160]) from checkpoint, the shape in current model is torch.Size([560]).
        size mismatch for decoder.stopnet.linear.weight: copying a param with shape torch.Size([1, 416]) from checkpoint, the shape in current model is torch.Size([1, 816]).

I am not sure whats going on here. Did you ever try to run this stuff in docker?
Also this symbolic link on tts_namespace creates some infinite recursion in my file explorer 
as in tts_namespace/TTS/tts_namespace/TTS/tts_namespace/TTS/tts_namespace/TTS...
and so on.

**Comment by IveJ** [comment]
Hi issuer,

I think you should check docs carefully before modify and try again step by
step.

**Comment by erogol** [comment]
I close this since it is not docker anymore.

**Comment by githtz** [comment]
> I close this since it is not docker anymore.

So is there any solution on how to get the docker container up and running, or is docker not supported anymore at all?
