### ISSUE TITLE
Finding appropriate checkpoint

### ISSUE THREAD

**Issue by roholazandie** [mozilla/TTS#323]
Hi,
I am trying to run the notebook for testing, as mentioned in the notebook I have to load the right commit and related model, but none of the checkpoints that are provided runs on the latest commit. They all give me size mismatch errors. Can you help and provide me with the latest best checkpoint that works with the last commit of the master branch?

**Comment by reuben** [comment]
I don't think we have any pre-trained checkpoints that work on master. All the released models have a corresponding commit in the wiki page with releases: https://github.com/mozilla/TTS/wiki/Released-Models
