### ISSUE TITLE
how to deploy  tacotron1 on aws lambda ?

### ISSUE THREAD

**Issue by dimanshu** [mozilla/TTS#324]
i want to decrease the size of the packages and model

**Comment by erogol** [comment]
Check one of the latest PRs handling the packaging.

**Comment by reuben** [comment]
If the lambda package size limit is really 50MB as listed here, then neither Tacotron or Tacotron 2 are deployable there. The checkpoint alone is bigger than that.

[0] https://docs.aws.amazon.com/lambda/latest/dg/limits.html

**Comment by dimanshu** [comment]
tacotron1 is not serving parallel requests is there any memory leakage in tacotron1 or tacotron2

**Comment by erogol** [comment]
not that I know of

**Comment by dimanshu** [comment]
ERROR:tts:Error Occured while sending file :, e=The size of tensor a (45) must match the size of tensor b (40) at non-singleton dimension 1,  text: modi minaben ashok kumar Darshini


Tacotron1 is not performing multiprocessing .

**Comment by erogol** [comment]
This error message does not mean anything to me. Do you have more traceback?

What do you mean by multiprocessing exactly?

**Comment by dimanshu** [comment]
two parallel request should at the same time
like for one request it is taking around 2.5sec
and when I'm sending two requests parallelly (simultaneously) it is taking 5sec but idealy it should perform 2 or more parallel requests in 2.5sec

**Comment by reuben** [comment]
If you follow the instructions in the wiki to deploy the server behind nginx/uWSGI it should work fine. Is that what you are doing?

**Comment by dimanshu** [comment]
no im using gunicorn with nginx

**Comment by erogol** [comment]
gunicorn might be the culprit. AFAIK @reuben is able to run on ngunx with mp support.

**Comment by reuben** [comment]
Yes, it's something in the deployment part. Check if Gunicorn has an equivalent setting as uWSGI's "processes" setting to control number of concurrent workers.

**Comment by dimanshu** [comment]
so what should i use ? nginx with uwsgi ?

**Comment by shourya1997** [comment]
What will be the best config to deploy tacotron1 ? would compiling pytorch from binary result in better response time ? @dimanshu

**Comment by shourya1997** [comment]
> so what should i use ? nginx with uwsgi ?

+1

**Comment by reuben** [comment]
Everything is documented here, it even includes configuration files for nginx/uWSGI.

**Comment by dimanshu** [comment]
where? I'm not able to find it

**Comment by nmstoker** [comment]
> where? I'm not able to find it

@dimanshu take a look at the README in /server under the Dev branch (the details aren't in master yet):

https://github.com/mozilla/TTS/tree/dev/server

**Comment by dimanshu** [comment]
I ran this command on t2 medium server  **(uwsgi --socket 0.0.0.0:5000 --protocol=http -w wsgi --processes=10  --wsgi-disable-file-wrapper)**

and send 10 parallel request 
outcome= first request took 32 sec(than what's the meaning of parallel processing ?)


worker4 Took : 31.6306238174 : sonu kumar Redmfsasfi MI fUSB
worker1 Took : 31.6983029842 : NAsLIpoasu   iopasfi apoifaosfaoif
worker6 Took : 33.2373559475 : modi minaben ashok kumar Darshini
worker0 Took : 34.5897979736 : shashirekha.c trendio store Blue Cotton
worker3 Took : 34.9364080429 : modi minaben ashok kumar Darshini
worker8 Took : 35.1537160873 : sonu kumar Redmfsasfi MI fUSB
worker5 Took : 36.0654420853 : mufeed Prp Collections SE-5050 Car
worker7 Took : 37.1678180695 : mufeed Prp Collections SE-5050 Car
worker2 Took : 38.565527916 : mufeed Prp Collections SE-5050 Car

**Comment by erogol** [comment]
@dimanshu try to run single process first and see how it performans. I'd guess 2 CPUs are not enough to run TTS in real time.

**Comment by dimanshu** [comment]
single process is taking 2-2.5sec per request. how many CPUs wil be sufficient for 30-40 parallel rquests .(30-40 requests in 3-4sec )
