### ISSUE TITLE
Segmentation fault (core dumped) in train.py

### ISSUE THREAD

**Issue by fatihkiralioglu** [mozilla/TTS#328]
Hi,

In the file train.py, we get a segmentation fault in the line:

> for num_iter, data in enumerate(data_loader): 

For a batch size of 32, after extracting 32 npy files, we get the segmentation fault. Setting number of workers parameter to 0 did not solve the issue either.

I suspect that this is a compatibility issue between the python packages. So,
 I have attached the conda package list in the attachment.
[condapackages.txt](https://github.com/mozilla/TTS/files/3961435/condapackages.txt)

Any help is appreciated.

**Comment by erogol** [comment]
I don't see anything like segmentation error. You can further debug with ```gdb```. It is better to test the dataloader in isolation.  

You might be OOM as well. Check the system memory as you run the code. If it is increasing constantly per iteration, there might be something wrong.

Also, check if all the files of your dataset exist. 

Feel free to reopen.
