### ISSUE TITLE
Sound samples redirect to mycroft's mimic and mimic2

### ISSUE THREAD

**Issue by Motherboard** [mozilla/TTS#33]
They have their own implementation on a different git repository, is it representative of how the currently available trained model here sounds?

**Comment by erogol** [comment]
I guess you imply the links on the Notebook. The reason I include these links is to have a comparison between your trained model with TTS and the ones on that website. Beside this, you can reach some of the TTS audio examples from README https://github.com/mozilla/TTS#checkpoints-and-audio-samples

**Comment by Motherboard** [comment]
I meant to the link you provide at the top of that reference you've just posted:

> Checkout [here](https://mycroft.ai/blog/available-voices/#the-human-voice-is-the-most-perfect-instrument-of-all-arvo-part) to compare the samples (except the first) below.

**Comment by erogol** [comment]
@Motherboard ahh yeah, it is my fault I guess. What I meant is the given audio samples below for the models are comparable with the given page (except the first checkpoint sample). So I just try to give audio samples next to our checkpoints that you might compare with other known TTS systems.
