### ISSUE TITLE
Demo server.py : GPU usage for _griffin_lim() function

### ISSUE THREAD

**Issue by fatihkiralioglu** [mozilla/TTS#330]
Hi,
While experimenting with server.py script, we have realized that _griffin_lim() function does not utilize GPU's because librosa stft() and istft() methods don't run on GPU. 

Is there a separate branch or modification addressing this issue?

Thanks.

**Comment by erogol** [comment]
It has never used GPU. It uses librosa for GriffinLim which is faster on CPU and instance based processing. However you can implement the same with pytorch.

**Comment by fatihkiralioglu** [comment]
I have come across cupy project:
https://github.com/cupy/cupy
Here is some benchmark results:
https://gist.github.com/f0k/0e50729c169114fdc6cb41be013a499f
I wonder if there is any possible problem while using such a CUDA accelerated library for stft and istft functions, I can give it a shot.
Thanks.

**Comment by erogol** [comment]
@fatihkiralioglu there is stft implementation in pytorch now. However, use of GPU does not give an improvement unless you batch multiple instances. If this is the case for you, then better to try GPU. You can use any GPU based implementation you like, but it is probably convenient to use PyTorch implementation.
