### ISSUE TITLE
To aux or not to aux?

### ISSUE THREAD

**Issue by macarbonneau** [mozilla/TTS#332]
Hello!
          First of all thank you for the repo. I tried to train my own universal WavRNN, but cannot get it to generate quality samples. I used the config file that is provided here: https://github.com/erogol/WaveRNN

However, here https://github.com/mozilla/TTS/issues/221#issuecomment-507635545 I can download a trained model and peek at the configuration.

In the latter case, the aux_net and upsamling net from Fatchord is used. In the former case, these augmentations are not used. 

Here is my question: Is it possible to train a universal WavRNN without the upsampling and auxiliary networks?

**Comment by erogol** [comment]
In my case, it was not possible to remove any of these. If you remove, the quality degrades much. One option for upsampling net is to estimate its output's mean value and just deterministically upsample reaching the same mean in inference time. 

All these comments regarding LJSpeech dataset. I did not try any of these with a multi speaker dataset.
