### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by divasecomp** [mozilla/TTS#334]
Excellent work.
Which files do i need to update to change training parameters? I'm using it for other languages.
Can you also elaborate the training process.
Plz.It would be a great help.

**Comment by shad94** [comment]
Hi! I highly recommend using DISCOURSE.MOZILLA.ORG for such topics, but if you are looking for immediate answer:
1. config.json in the main /TTS folder. 
2. best_model_config.json (sampling frequency)

**Comment by erogol** [comment]
You need to setup:

I suggest you to use the notebooks under dataset_analysis before training to check dataset quality and find right audio processing parameters. Check also https://github.com/mozilla/TTS/wiki/Dataset 

After you are sure...

1. config.json considering the comments (smapling_rate, min max frequencies, phoneme language etc.)
2. you might need to write your own text cleaner in cleaners.py
3. if you have a dataset in a different format code your own preprocessor in datasets/preprocessors.py
or format your dataset as LJSpeech
