### ISSUE TITLE
Tacotron2: bad test synthesis results while a new configuration apart from issue 340

### ISSUE THREAD

**Issue by fatihkiralioglu** [mozilla/TTS#342]
Hello,
I have tried another training with a little different configuration using the same custom voice database.
Unfortunately, the test synthesis results are much worse than the previous training and only 2 out of 4 test synthesis records are intelligible.
I guess that there is a very basic error causing this behavior but I couldn't figure it out.
I have attached test synthesis files belonging to global step 431853 and configuration and log files.

Any help is appreciated.
Best Regards.

[431853.zip](https://github.com/mozilla/TTS/files/4115777/431853.zip)

[tacotron2_conf_and_logs.zip](https://github.com/mozilla/TTS/files/4115772/tacotron2_conf_and_logs.zip)

**Comment by erogol** [comment]
please direct such questions to discourse for more help.
