### ISSUE TITLE
Text with multiple sentences and no trailing punctuation is truncated

### ISSUE THREAD

**Issue by ianb** [mozilla/TTS#348]
I've only tested this with the server.

If I enter the text `This is a test. Testing` it will only produce "This is a test". If I add `This is a test. Testing.` (note the trailing period) then it will say the full two sentences. 

With one sentence this isn't an issue (i.e., `This is a test` works fine)

**Comment by erogol** [comment]
with the server means which model exactly?

**Comment by reuben** [comment]
moz-model branch, it's from the server package with the internal model.

**Comment by erogol** [comment]
I guess it is about stop conditioning. One option is to totally ditch stopnet and use attention alignment to stop generation. It works better in practice but its need to be tuned per model. If it is a common problem I can handle it.

**Comment by reuben** [comment]
I think it may just be the sentence splitting logic in the synthesizer.

**Comment by erogol** [comment]
It might also be about stop condition. Since all the sentences in the training set have punctuations in the end. 

Also, server should be printing split sentences on the console. So if there is something broken, it should be seen there.

**Comment by ianb** [comment]
Here's the server console for the two examples:

``` > Model input: sentence one. sentence two
sentence one.
sɛntəns wʌn.
[INFO] 127.0.0.1 - - [07/Feb/2020 16:38:51] "GET /api/tts?text=sentence%20one.%20sentence%20two HTTP/1.1" 200 -
 > Model input: sentence one. sentence two.
sentence one.
sɛntəns wʌn.
sentence two.
sɛntəns tuː.
[INFO] 127.0.0.1 - - [07/Feb/2020 16:38:56] "GET /api/tts?text=sentence%20one.%20sentence%20two. HTTP/1.1" 200 -
```

I'm guessing it's just something simple with sentence splitting.

**Comment by erogol** [comment]
This is fixed by now.
