### ISSUE TITLE
Notebook Sample Generation results in a RuntimeError

### ISSUE THREAD

**Issue by HueyPretilaASMS** [mozilla/TTS#35]
I have begun training TTS on the en_UK corpus released by M-AILABS. However, I doubt that the behaviour I experienced is related to the latter.

Essentially, I followed the notebooks given (and placed it into a python script `generate.py`) and both have resulted in the following error:

    RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got CUDAIntTensor instead (while checking arguments for embedding)

It seems to trace back to either the model or the create_speech function.

Are the notebooks just outdated or is this unusual behaviour?

**Comment by erogol** [comment]
It is unusual. Are you sure to use Pytorch 0.4 ?

**Comment by HueyPretilaASMS** [comment]
Yes, I'm using Pytorch 0.4 with cuda 9.0 on the latest commit of the repo. However, I have only tried it on a Windows 10 machine - I'm currently checking if the error occurs in a Linux environment.

**Comment by erogol** [comment]
Ohh Windows 10 is currently out of warrant but a friend has issues with it lately. Probably you have the same.

**Comment by erogol** [comment]
I close this issue for now, pls reopen it if necessary.
