### ISSUE TITLE
speed up tacotron2 changing the architecture? 

### ISSUE THREAD

**Issue by vcjob** [mozilla/TTS#351]
Hello everyone!

Has anyone tried to speed up tacotron2 model? It runs slower than real time on cpu (i7-7700hq) even if we do not take into account vocoder inference time. (well, maybe just around RT). The desired results - multiple RT. 

Has anyone tried to reduce the model size, change it?

**Comment by erogol** [comment]
Have you tried Tacotron. It runs fast enough ans it is much smaller. And I don't think the perfomarmance is not that different.

**Comment by vcjob** [comment]
> Have you tried Tacotron. It runs fast enough ans it is much smaller. And I don't think the perfomarmance is not that different.

Yes, I have, it's visible that quality is lower. It may be worthy to use it for low resolution though? Maybe I should give it a go. Thank you.
