### ISSUE TITLE
Malaysia TEXT-TO-SPEECH progress 

### ISSUE THREAD

**Issue by haqkiemdaim** [mozilla/TTS#358]

**Comment by erogol** [comment]
do you also plan to release the model?

**Comment by haqkiemdaim** [comment]
> do you also plan to release the model?

@erogol yeah i'am planning to release it once i achieve a much better model soon 👌

**Comment by erogol** [comment]
great let us know. If you like we can host your model here attributed to you.

**Comment by haqkiemdaim** [comment]
> great let us know. If you like we can host your model here attributed to you.

Okay 👌
