### ISSUE TITLE
Monophonic sound error when trying custom dataset

### ISSUE THREAD

**Issue by george-roussos** [mozilla/TTS#360]
Hi there,

Apologies if I should've posted this in the discourse forum, but saw nothing similar. 

I am trying to train using my own custom dataset, which is pretty large and good quality. I thought that I would LJSpeech it, so I transcribed it, split it in sentences, threw away all silences and did the metadata.csv. I can confirm it works, however I cannot get it to be applied to the Mozilla code, because it throws the error
`librosa.util.exceptions.ParameterError: Invalid shape for monophonic audio: ndim=2, shape=(28666, 2)`

I tried both with Pydub and ffmpeg to turn the the sample size to 16 and the sample_rate to 22050, and the number of channels to 2, which matches the LJSpeech attributes, however it just isn't working. I am on the master branch. Would anyone have any tips? Also, isn't it 2?

Thanks!

**Comment by erogol** [comment]
Your audio is two channels. Reduce it to one channel and convert all the dataset.

**Comment by george-roussos** [comment]
That was it. Thank you so much!

**Comment by omkarade** [comment]
@erogol  how Reduce it to one channel and convert all the dataset?
