### ISSUE TITLE
How many Tesla K80s are recommended when training Tacotron?

### ISSUE THREAD

**Issue by george-roussos** [mozilla/TTS#363]
Right now I am training on an instance with 8 GPUS, but they are not full while the model is training. 

![image](https://user-images.githubusercontent.com/25833833/75119862-0a346100-5687-11ea-8424-29a170a76327.png)

Does that mean they are underutilized and 4 GPUs would give me the same results in the same amount of time? If so, I would really like to cut down costs.

**Comment by erogol** [comment]
you would just need a single GPU with 12 GB memory. If you use phoneme based training, the first epoch would be slow and underutilized since it caches phonemes.
