### ISSUE TITLE
She is drunk

### ISSUE THREAD

**Issue by benbucksch** [mozilla/TTS#365]
This must be the funniest bug report I ever made.

### Reproduction:
* Linux
* git clone TTS
* virtualenv
* build
* `pip install -U pip setuptools wheel`
* `pip install -U https://github.com/reuben/TTS/releases/download/ljspeech-fwd-attn-pwgan/TTS-0.0.1+92aea2a-py3-none-any.whl` -> `Successfully installed TTS-0.0.1+92aea2a h5py-2.10.0 librosa-0.7.2 parallel-wavegan-0.2.9 phonemizer-2.1`
* `python -m TTS.server.server`
* Go to http://localhost:5002 with Firefox
* Enter `I support a lot of servers, s like to have stations that work at the same leve`
* Enter `I support a lot of servers, so I like to have stations that work at the same level`

### Actual result:
* Text: `I support a lot of servers, s like to have stations that work at the same leve`
  * Result: https://www.bucksch.org/xfer/tts-same-level-of-wine.mp3
  * She's clearly drunk. Reminds me terribly of https://youtu.be/6lzQxjGL9S0?t=615 -- You must see this video to appreciate this bug report.

* Text: `I support a lot of servers, so I like to have stations that work at the same level`
  * Result: https://www.bucksch.org/xfer/tts-same-level-singing.mp3
  * With correct words, she's in better shape, but still singing / rapping and still drunk at the end, albeit less so.

Download:
* [same-level.zip](https://github.com/mozilla/TTS/files/4247799/same-level.zip)

**Comment by erogol** [comment]
try this.

open model config.json and `set use_forward_attn = True` and see how it works.

**Comment by benbucksch** [comment]
She seems to have a problem with the comma. "Lift me up my friend" works, whereas "Lift me up, my friend" causes her to stutter.

**Comment by erogol** [comment]
This model did not see punctuations due to a bug in used phonemizer.

**Comment by shad94** [comment]
> This model did not see punctuations due to a bug in used phonemizer.

So, which phonemizer is recommended to work within punctuation? I would like to obtain the most human- like output 🤔

**Comment by erogol** [comment]
problem is fixed you can use TTS as it is
