### ISSUE TITLE
Crash on certain text in pytorch with scratchpad_ being null

### ISSUE THREAD

**Issue by benbucksch** [mozilla/TTS#366]
This must be the funniest bug report I ever made.

### Reproduction:
* Ryzen 7 3700 with 8 cores, 32 GB RAM
* Linux 64bit
* git clone TTS
* virtualenv
* build
* `pip install -U pip setuptools wheel`
* `pip install -U https://github.com/reuben/TTS/releases/download/ljspeech-fwd-attn-pwgan/TTS-0.0.1+92aea2a-py3-none-any.whl` -> `Successfully installed TTS-0.0.1+92aea2a h5py-2.10.0 librosa-0.7.2 parallel-wavegan-0.2.9 phonemizer-2.1`
* `python -m TTS.server.server`
* Go to http://localhost:5002 with Firefox
* Enter:
"standup: Landing top_paths not 1 PR * API changes for DeepSpeech v1.0 * Create metadata file with model export  * Analyzing the speech proxy data dump & DeepSpeech results in Firefox Voice * Evaluating impact of LMs * PR reviews * Writing some guidance for contributors in issue 2773 * QuartzNet explorations"

### Actual result:
In the browser: "Error: NetworkError when attempting to fetch resource."

On the console:
```
[INFO]  * Running on http://0.0.0.0:5002/ (Press CTRL+C to quit)
 > Model input: standup: Landing top_paths not 1 PR * API changes for DeepSpeech v1.0 * Create metadata file with model export  * Analyzing the speech proxy data dump & DeepSpeech results in Firefox Voice * Evaluating impact of LMs * PR reviews * Writing some guidance for contributors in issue 2773 * QuartzNet explorations 
['standup: Landing top_paths not 1 PR * API changes for DeepSpeech v1.', '0 * Create metadata file with model export  * Analyzing the speech proxy data dump & DeepSpeech results in Firefox Voice * Evaluating impact of LMs * PR reviews * Writing some guidance for contributors in issue 2773 * QuartzNet explorations']
   | > Decoder stopped with 'max_decoder_steps
python: /pytorch/third_party/ideep/mkl-dnn/src/common/scratchpad.cpp:63: mkldnn::impl::global_scratchpad_t::global_scratchpad_t(size_t): Assertion `scratchpad_ != nullptr' failed.
Core dumped
```
and the process stopped. I.e. crashed.

This is reproducible.

**Comment by reuben** [comment]
This is very likely just an out of memory error with a not so obvious error message.

**Comment by benbucksch** [comment]
This system has 32 GB RAM, of which 20 GB are free. So, it's not the system memory. I cannot tell whether there are per-process limits or even python RAM limitations.
I ran it while watching `htop`, and the python server process uses less than 1 GB resident RAM, but 14 GB virtual RAM. The RAM usage seemed stable (not dramatically increasing) when it crashed. The RAM (both resident and virtual) is grabbed fairly at the beginning (a few seconds in) and the crash happens much later, 30-60 seconds after the RAM is allocated.
So, from an outside look, without knowing the code, it does not look like an OOM situation.

**Comment by reuben** [comment]
The error comes from two levels down in our dependencies. It's in MKL-DNN, which is a dependency of PyTorch. The file listed there (scratchpad.cpp) only does memory allocation. My initial idea is that it's either OOM or memory corruption. I guess running a debugger is needed to identify what's happening here for sure, but I won't be able to get to that any time soon, as I'm going on vacation tomorrow.

**Comment by erogol** [comment]
you can try to recompile pytorch without MKL and see if the problem is with MKL

**Comment by benbucksch** [comment]
> The file listed there (scratchpad.cpp) only does memory allocation

Makes sense
