### ISSUE TITLE
problem in synthesizing audio

### ISSUE THREAD

**Issue by Fahim-F** [mozilla/TTS#369]
Hi,
I have tried training with Tacotron2 for the Persian language with the attached configuration

[config.txt](https://github.com/mozilla/TTS/files/4268428/config.txt)

The quality of the synthesized voice is good but the sentence has been repeated two times or one and half times in the synthesized audio.  In other words, sometimes at the end of synthesized audio, the sentence has been repeated. 

Any advice is appreciated.

Fahim

**Comment by erogol** [comment]
This needs to go to discourse.
