### ISSUE TITLE
How to control  pause between phonemes by  pause  token

### ISSUE THREAD

**Issue by wwxm0523** [mozilla/TTS#372]
How to implemented the inference with pause token

**Comment by erogol** [comment]
which means?

**Comment by wwxm0523** [comment]
> which means?

For example,"I want to stay especially with you",a noticeable pause will be added after "especially",that is "I want to stay especially | with you".

**Comment by erogol** [comment]
It is not possible to do so with the current architecture. You can do it with FastSpeech model. But I don't have it ready to release yet.

However, one easy trick is to use the alignments and add the pause manually after the speech synthesis.

**Comment by wwxm0523** [comment]
> It is not possible to do so with the current architecture. You can do it with FastSpeech model. But I don't have it ready to release yet.
> 
> However, one easy trick is to use the alignments and add the pause manually after the speech synthesis.

yes, i want to. add the pause manually .can you give me a egs .Thanks
