### ISSUE TITLE
Mismatch error occuring when using latest commit

### ISSUE THREAD

**Issue by lauraadalmolin** [mozilla/TTS#381]
I am working with this [example](https://colab.research.google.com/github/tugstugi/dl-colab-notebooks/blob/master/notebooks/Mozilla_TTS_WaveRNN.ipynb) and it was running fine, but it presented some issues regarding to punctuation and the beginning and end of sentences being cut off. That's when I realized maybe I could update to the latest commit and see if things got solved.

After I pulled from the repo and ran setup.py again some errors started showing up, such as a parameter error (setup_model now has a new attribute, which I would gladly thank you if it could be cleared out since I only set it to zero to keep things going).

I am using the same models as in the mentioned notebook and the config.json file from the latest commit. 

I would really appreciate any help,

Thanks in advance.

In this link you can find my [code](https://github.com/lauraadalmolin/at-home-tts/blob/master/working_example.py) and here follows the error:

`python3 working_example.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
torch.cuda.is_available()=True
 > Using model: Tacotron2
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > num_freq:1025
 | > power:1.5
 | > preemphasis:0.98
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:8000.0
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > sound_norm:False
 | > hop_length:256
 | > win_length:1024
 | > n_fft:2048
Traceback (most recent call last):
  File "working_example.py", line 139, in <module>
    model.load_state_dict(cp['model'])
  File "/home/at-home/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Tacotron2:
	Missing key(s) in state_dict: "decoder.attention.query_layer.linear_layer.weight", "decoder.attention.inputs_layer.linear_layer.weight", "decoder.attention.v.linear_layer.weight", "decoder.attention.v.linear_layer.bias". 
	Unexpected key(s) in state_dict: "decoder.attention_layer.query_layer.linear_layer.weight", "decoder.attention_layer.inputs_layer.linear_layer.weight", "decoder.attention_layer.v.linear_layer.weight", "decoder.attention_layer.v.linear_layer.bias", "decoder.attention_layer.location_layer.location_conv.weight", "decoder.attention_layer.location_layer.location_dense.linear_layer.weight", "decoder.attention_rnn_init.weight", "decoder.go_frame_init.weight", "decoder.decoder_rnn_inits.weight", "decoder.prenet.layers.0.bn.weight", "decoder.prenet.layers.0.bn.bias", "decoder.prenet.layers.0.bn.running_mean", "decoder.prenet.layers.0.bn.running_var", "decoder.prenet.layers.0.bn.num_batches_tracked", "decoder.prenet.layers.1.bn.weight", "decoder.prenet.layers.1.bn.bias", "decoder.prenet.layers.1.bn.running_mean", "decoder.prenet.layers.1.bn.running_var", "decoder.prenet.layers.1.bn.num_batches_tracked". 
	size mismatch for embedding.weight: copying a param with shape torch.Size([62, 512]) from checkpoint, the shape in current model is torch.Size([129, 512]).
	size mismatch for decoder.linear_projection.linear_layer.weight: copying a param with shape torch.Size([80, 1536]) from checkpoint, the shape in current model is torch.Size([560, 1536]).
	size mismatch for decoder.linear_projection.linear_layer.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([560]).
	size mismatch for decoder.stopnet.1.linear_layer.weight: copying a param with shape torch.Size([1, 1104]) from checkpoint, the shape in current model is torch.Size([1, 1584]).
`

**Comment by erogol** [comment]
you need to use the commit version given in the notebook. The project is in active development and new versions might not be compatible with the old models.
