### ISSUE TITLE
WaveRNN trained result sound strange

### ISSUE THREAD

**Issue by tsungruihon** [mozilla/TTS#382]
I have tried to train [erogol wavernn](https://github.com/erogol/WaveRNN) using TTS gta result, which is generated by this [notebook]

 (https://github.com/erogol/WaveRNN/blob/master/notebooks/ExtractTTSpectrogram.ipynb)  
After training in a quite long time, i used WaveRNN model checkpoint(which has been trained 876000 steps with loss 4.018) with my trained tacotron2 model. The result seem strange, Could you give me some advice? Thanks. @erogol 

[WaveRNN_result.zip](https://github.com/mozilla/TTS/files/4317531/WaveRNN_result.zip)

**Comment by erogol** [comment]
Could you pass this to discourse?

**Comment by tsungruihon** [comment]
@erogol  okay. Please have a look at it if you feel free,  thanks a lot.

**Comment by ricktjwong** [comment]
> I have tried to train [erogol wavernn](https://github.com/erogol/WaveRNN) using TTS gta result, which is generated by this [notebook]
> 
> (https://github.com/erogol/WaveRNN/blob/master/notebooks/ExtractTTSpectrogram.ipynb)
> After training in a quite long time, i used WaveRNN model checkpoint(which has been trained 876000 steps with loss 4.018) with my trained tacotron2 model. The result seem strange, Could you give me some advice? Thanks. @erogol
> 
> [WaveRNN_result.zip](https://github.com/mozilla/TTS/files/4317531/WaveRNN_result.zip)

Hi @tsungruihon Did you have any luck fixing your problems? I have been trying both 10 bit and MOLD mode as well could you share which worked better for you in the end and the final loss for that result? Appreciate it!

**Comment by tsungruihon** [comment]
@ricktjwong I have moved to   [Fatchord repo](https://github.com/fatchord/WaveRNN) now.

**Comment by ricktjwong** [comment]
Thanks, did you get better results with that repo?

**Comment by tsungruihon** [comment]
@ricktjwong Yes, it seems better.
