### ISSUE TITLE
Is there an easy way to estimate approximate amount of time for training for a given set of dataset?

### ISSUE THREAD

**Issue by yilmazay74** [mozilla/TTS#386]
Hi,
I checked all open and closed issues as well as FAQs. But none of them gave me a clue.
So, I decided to create this issue. Although it is a question and asking questions is discouraged here, however, this is more than a simple question, actually it is a very fundemantal problem.
I used to do TTS with a traditional GMM framework. Recently we decided to go with TTS with DNN, and I found Tacotron and then finally Tacotron2, so I ended up here.
Naturally I want to estimate an approximate time for a given set of audio files for traning. 
I see that there are bunch of parameters in config.json and all those differs accordign to the my input training set. 
However, I believe that there must be a way to approximately estimate how much time it will take for training.
For example in my case, I started with a very small amount of audio data, 180 audios of between 10 sec and 20 seconds, total length of the audios is about 43 minutes. I know that is too few,
but I wanted to test the training with a small amount at first to  be able to estimate the amount of time for training for larger datasets.
Can anyone please give me some hints about how to make an estimation ?
I use mostly the default configs.
I use 1 K80 GPU.
180 files    10 sec <= audio length <= 20sec
Total length 43 minutes
Language = Turkish

Looking forward to your guidance and recommendations as well.
Best Regards

**Comment by yilmazay74** [comment]
Hi,
In my case, there are 1000 epochs, it says epch time is about 3 secs. Although it takes about 75 seconds for each epoch.
So can I assume that it will stop after 1000'th epoch the training will stop? 
In that case the total training time would about 75 x 1000 = 75000 seconds ~= 20 hours 
Isn't this too much for just a small sent of only 43 minutes ?
Am I doing something wrong in my calculations ?
I will appreciae any guidance on this issue ?
Regards

**Comment by erogol** [comment]
Please direct this to discourse as it is explained in the issue template.
