### ISSUE TITLE
UnboundLocalError: local variable 'mel_input' referenced before assignment

### ISSUE THREAD

**Issue by mwx2006** [mozilla/TTS#391]
! Run is removed from /root/Trainings/ljspeech-stft_params-April-07-2020_10+27AM-fab74dd
Traceback (most recent call last):
File "train.py", line 724, in
main(args)
File "train.py", line 641, in main
val_loss = evaluate(model, criterion, criterion_st, ap, global_step,
File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/torch/autograd/grad_mode.py
", line 49, in decorate_no_grad
return func(*args, **kwargs)
File "train.py", line 434, in evaluate
idx = np.random.randint(mel_input.shape[0])
UnboundLocalError: local variable 'mel_input' referenced before assignment

**Comment by mwx2006** [comment]
! Run is removed from /root/Trainings/ljspeech-stft_params-April-07-2020_10+27AM-fab74dd
Traceback (most recent call last):
  File "train.py", line 724, in <module>
    main(args)
  File "train.py", line 641, in main
    val_loss = evaluate(model, criterion, criterion_st, ap, global_step,
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/torch/autograd/grad_mode.py
", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "train.py", line 434, in evaluate
    idx = np.random.randint(mel_input.shape[0])
UnboundLocalError: local variable 'mel_input' referenced before assignment

**Comment by erogol** [comment]
just pasting your error messages does not help for a thing

**Comment by mwx2006** [comment]
system:Linux version 4.15.0-1075-azure (buildd@lcy01-amd64-018) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12))

Python 3.8.2

config.json:
```json
{
    "model": "Tacotron2",          // one of the model in models/
    "run_name": "ljspeech-stft_params",
    "run_description": "tacotron2 cosntant stf parameters",

    // AUDIO PARAMETERS
    "audio":{
        // Audio processing parameters
        "num_mels": 80,         // size of the mel spec frame.
        "num_freq": 1025,       // number of stft frequency levels. Size of the linear spectogram frame.
        "sample_rate": 48000,   // DATASET-RELATED: wav sample-rate. If different than the original data, it is resampled.
        "win_length": 1024,     // stft window length in ms.
        "hop_length": 256,      // stft window hop-lengh in ms.
        "frame_length_ms": null,  // stft window length in ms.If null, 'win_length' is used.
        "frame_shift_ms": null,   // stft window hop-lengh in ms. If null, 'hop_length' is used.
        "preemphasis": 0.98,    // pre-emphasis to reduce spec noise and make it more structured. If 0.0, no -pre-emphasis.
        "min_level_db": -100,   // normalization range
        "ref_level_db": 20,     // reference level db, theoretically 20db is the sound of air.
        "power": 1.5,           // value to sharpen wav signals after GL algorithm.
        "griffin_lim_iters": 60,// #griffin-lim iterations. 30-60 is a good range. Larger the value, slower the generation.
        // Normalization parameters
        "signal_norm": true,    // normalize the spec values in range [0, 1]
        "symmetric_norm": true, // move normalization to range [-1, 1]
        "max_norm": 4.0,          // scale normalization to range [-max_norm, max_norm] or [0, max_norm]
        "clip_norm": true,      // clip normalized values into the range.
        "mel_fmin": 0.0,         // minimum freq level for mel-spec. ~50 for male and ~95 for female voices. Tune for dataset!!
        "mel_fmax": 8000.0,        // maximum freq level for mel-spec. Tune for dataset!!
        "do_trim_silence": true,  // enable trimming of slience of audio as you load it. LJspeech (false), TWEB (false), Nancy (true)
        "trim_db": 60          // threshold for timming silence. Set this according to your dataset.
    },

    // VOCABULARY PARAMETERS
    // if custom character set is not defined,
    // default set in symbols.py is used
    "characters":{
        "pad": "_",
        "eos": "~",
        "bos": "^",
        "characters": "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!'(),-.:;? ",
        "punctuations":"!'(),-.:;? ",
        "phonemes":"iyɨʉɯuɪʏʊeøɘəɵɤoɛœɜɞʌɔæɐaɶɑɒᵻʘɓǀɗǃʄǂɠǁʛpbtdʈɖcɟkɡqɢʔɴŋɲɳnɱmʙrʀⱱɾɽɸβfvθðszʃʒʂʐçʝxɣχʁħʕhɦɬɮʋɹɻjɰlɭʎʟˈˌːˑʍwɥʜʢʡɕʑɺɧɚ˞ɫ"
    },

    // DISTRIBUTED TRAINING
    "distributed":{
        "backend": "nccl",
        "url": "tcp:\/\/localhost:54321"
    },

    "reinit_layers": [],    // give a list of layer names to restore from the given checkpoint. If not defined, it reloads all heuristically matching layers.

    // TRAINING
    "batch_size": 32,       // Batch size for training. Lower values than 32 might cause hard to learn attention. It is overwritten by 'gradual_training'.
    "eval_batch_size":16,
    "r": 7,                 // Number of decoder frames to predict per iteration. Set the initial values if gradual training is enabled.
    "gradual_training": [[0, 7, 64], [1, 5, 64], [50000, 3, 32], [130000, 2, 32], [290000, 1, 32]], //set gradual training steps [first_step, r, batch_size]. If it is null, gradual training is disabled. For Tacotron, you might need to reduce the 'batch_size' as you proceeed.
    "loss_masking": true,         // enable / disable loss masking against the sequence padding.

    // VALIDATION
    "run_eval": true,
    "test_delay_epochs": 10,  //Until attention is aligned, testing only wastes computation time.
    "test_sentences_file": null,  // set a file to load sentences to be used for testing. If it is null then we use default english sentences.

    // OPTIMIZER
    "noam_schedule": false,        // use noam warmup and lr schedule.
    "grad_clip": 1.0,                // upper limit for gradients for clipping.
    "epochs": 1000,                // total number of epochs to train.
    "lr": 0.0001,                  // Initial learning rate. If Noam decay is active, maximum learning rate.
    "wd": 0.000001,         // Weight decay weight.
    "warmup_steps": 4000,          // Noam decay steps to increase the learning rate from 0 to "lr"
    "seq_len_norm": false,         // Normalize eash sample loss with its length to alleviate imbalanced datasets. Use it if your dataset is small or has skewed distribution of sequence lengths.

    // TACOTRON PRENET
    "memory_size": -1,              // ONLY TACOTRON - size of the memory queue used fro storing last decoder predictions for auto-regression. If < 0, memory queue is disabled and decoder only uses the last prediction frame.
    "prenet_type": "original",     // "original" or "bn".
    "prenet_dropout": true,        // enable/disable dropout at prenet.

    // ATTENTION
    "attention_type": "original",  // 'original' or 'graves'
    "attention_heads": 4,          // number of attention heads (only for 'graves')
    "attention_norm": "sigmoid",   // softmax or sigmoid. Suggested to use softmax for Tacotron2 and sigmoid for Tacotron.
    "windowing": false,            // Enables attention windowing. Used only in eval mode.
    "use_forward_attn": false,      // if it uses forward attention. In general, it aligns faster.
    "forward_attn_mask": false,    // Additional masking forcing monotonicity only in eval mode.
    "transition_agent": false,     // enable/disable transition agent of forward attention.
    "location_attn": false,        // enable_disable location sensitive attention. It is enabled for TACOTRON by default.
    "bidirectional_decoder": false,  // use https://arxiv.org/abs/1907.09006. Use it, if attention does not work well with your dataset.

    // STOPNET
    "stopnet": true,               // Train stopnet predicting the end of synthesis.
    "separate_stopnet": true,     // Train stopnet seperately if 'stopnet==true'. It prevents stopnet loss to influence the rest of the model. It causes a better model, but it trains SLOWER.

    // TENSORBOARD and LOGGING
    "print_step": 25,       // Number of steps to log traning on console.
    "save_step": 10000,      // Number of training steps expected to save traninpg stats and checkpoints.
    "checkpoint": true,     // If true, it saves checkpoints per "save_step"
    "tb_model_param_stats": false,     // true, plots param stats per layer on tensorboard. Might be memory consuming, but good for debugging.

    // DATA LOADING
    "text_cleaner": "phoneme_cleaners",
    "enable_eos_bos_chars": false, // enable/disable beginning of sentence and end of sentence chars.
    "num_loader_workers": 4,        // number of training data loader processes. Don't set it too big. 4-8 are good values.
    "num_val_loader_workers": 4,    // number of evaluation data loader processes.
    "batch_group_size": 0,  //Number of batches to shuffle after bucketing.
    "min_seq_len": 6,       // DATASET-RELATED: minimum text length to use in training
    "max_seq_len": 150,     // DATASET-RELATED: maximum text length

    // PATHS
    "output_path": "/root/Trainings/",

    // PHONEMES
    "phoneme_cache_path": "mozilla_us_phonemes_2_1",  // phoneme computation is slow, therefore, it caches results in the given folder.
    "use_phonemes": true,           // use phonemes instead of raw characters. It is suggested for better pronounciation.
    "phoneme_language": "zh",     // depending on your target language, pick one from  https://github.com/bootphon/phonemizer#languages

    // MULTI-SPEAKER and GST
    "use_speaker_embedding": false,     // use speaker embedding to enable multi-speaker learning.
    "style_wav_for_test": null,          // path to style wav file to be used in TacotronGST inference.
    "use_gst": false,       // TACOTRON ONLY: use global style tokens

    // DATASETS
    "datasets":   // List of datasets. They all merged and they get different speaker_ids.
        [
            {
                "name": "ljspeech",
                "path": "/root/TTS/data/allmj/",
                "meta_file_train": "metadata.csv",
                "meta_file_val": null
            }
        ]

}

```
metadata.csv
```
1|重新发一个吧|重新发一个吧
2|重新发一个重新发一个|重新发一个重新发一个
3|管理员不要拿啊|管理员不要拿啊
4|两个红包大家随便抢|两个红包大家随便抢
5|呵呵|呵呵
6|发了啊|发了啊
7|别他妈刷了 谢谢你们啊|别他妈刷了 谢谢你们啊
8|发完了|发完了
9|发完了我现在还不知道唱什么歌|发完了我现在还不知道唱什么歌
10|又炸了|又炸了
11|又唱绝帝 每次都唱绝帝 妈的 操|又唱绝帝 每次都唱绝帝 妈的 操
12|我还没想好唱什么歌|我还没想好唱什么歌
13|不过有一说一我们|不过有一说一我们
14|五月天的翻唱|五月天的翻唱
15|然后是我自己重新编曲的|然后是我自己重新编曲的
16|敬请期待|敬请期待
17|这不算剧透 我们都快做好了都|这不算剧透 我们都快做好了都
18|巨牛逼|巨牛逼
19|找伴奏嘛|找伴奏嘛
20|欸没有伴奏|欸没有伴奏
21|我用一下小启跟 我用一下小启跟 那个 谁 谁 谁 谁 谁写的|我用一下小启跟 我用一下小启跟 那个 谁 谁 谁 谁 谁写的
22|中文版歌词|中文版歌词
23|没办法 日文对咱实在是|没办法 日文对咱实在是
24|看得我又想玩了 诶呦 有点想|看得我又想玩了 诶呦 有点想
25|鸡儿其实特别硬的|鸡儿其实特别硬的
26|两个人在玩动森|两个人在玩动森
27|额 三个人在玩生化|额 三个人在玩生化
28|生化三|生化三
29|然后 他妈的|然后他妈的
30|然后|然后
31|我也不知道该我也不知道该直播什么 这生化三打完跟没打似的我感觉 一点 一点意思都没有|我也不知道该我也不知道该直播什么 这生化三打完跟没打似的我感觉 一点 一点意思都没有
```

**Comment by mwx2006** [comment]
File "train.py", line 352,“for”Code block not executed

**Comment by erogol** [comment]
I can't reproduce the problem in either dev and master branch

**Comment by mwx2006** [comment]
This is my entire TTS directory file

[TTS.7z](https://mailsysueducn-my.sharepoint.com/:u:/g/personal/liyijie_mail_sysu_edu_cn/EQniJU8pUCpDsB2oA2Wr9YsBjUniJn8rtn5ckobNTn4i-A?e=ROEdvm)

**Comment by mwx2006** [comment]
Maybe it's my fault
I clone the Repository again
and then it is working

**Comment by mwx2006** [comment]
I'm sorry to bother you
And thankyou very much

**Comment by Sadam1195** [comment]
I am facing the same issue. I cloned repo again but it did not work. Does number of odd file has to do with anything? @erogol

**Comment by Sadam1195** [comment]
`
 > Using CUDA:  False
 > Number of GPUs:  0
 > Git Hash: f320992
 > Experiment folder: /home/sadam/Projects/Italian_TTS/TTS/Models/LJSpeech/ljspeech-June-05-2020_06+53PM-f320992
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > num_freq:513
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:8000.0
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > stats_path:None
 | > hop_length:256
 | > win_length:1024
 | > n_fft:1024
 > Using model: Tacotron2
 | > Num output units : 513

 > Model has 28921234 parameters

 > EPOCH: 0/1000

 > Number of output frames: 7

 > DataLoader initialization
 | > Use phonemes: True
   | > phoneme language: it
 | > Number of instances : 75
 | > Max length sequence: 380
 | > Min length sequence: 2
 | > Avg length sequence: 139.69333333333333
 | > Num. instances discarded by max-min (max=153, min=6) seq limits: 30
 | > Batch group size: 0.

 > TRAINING (2020-06-05 18:53:25) 

   --> TRAIN PERFORMACE -- EPOCH TIME: 0 sec -- GLOBAL_STEP: 1
     | > avg_postnet_loss: 6.72998
     | > avg_decoder_loss: 4.72298
     | > avg_stopnet_loss: 0.70530
     | > avg_align_error: 0.99250
     | > avg_step_time: 17.22977
     | > avg_loader_time: 1.13409
     | > avg_ga_loss: 0.02929

 > EVALUATION 

Traceback (most recent call last):
  File "train.py", line 676, in <module>
    main(args)
  File "train.py", line 592, in main
    eval_avg_loss_dict = evaluate(model, criterion, ap, global_step, epoch)
  File "/home/sadam/anaconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "train.py", line 390, in evaluate
    idx = np.random.randint(mel_input.shape[0])
UnboundLocalError: local variable 'mel_input' referenced before assignment
 ! Run is removed from /home/sadam/Projects/Italian_TTS/TTS/Models/LJSpeech/ljspeech-June-05-2020_06+53PM-f320992
`
@erogol

**Comment by erogol** [comment]
can you post config file

**Comment by Sadam1195** [comment]
> can you post config file

`{
    "model": "Tacotron2",
    "run_name": "ljspeech",
    "run_description": "tacotron2",

    // AUDIO PARAMETERS
    "audio":{
        // stft parameters
        "num_freq": 513,         // number of stft frequency levels. Size of the linear spectogram frame.
        "win_length": 1024,      // stft window length in ms.
        "hop_length": 256,       // stft window hop-lengh in ms.
        "frame_length_ms": null, // stft window length in ms.If null, 'win_length' is used.
        "frame_shift_ms": null,  // stft window hop-lengh in ms. If null, 'hop_length' is used.

        // Audio processing parameters
        "sample_rate": 22050,   // DATASET-RELATED: wav sample-rate. If different than the original data, it is resampled.
        "preemphasis": 0.0,     // pre-emphasis to reduce spec noise and make it more structured. If 0.0, no -pre-emphasis.
        "ref_level_db": 20,     // reference level db, theoretically 20db is the sound of air.

        // Silence trimming
        "do_trim_silence": true,// enable trimming of slience of audio as you load it. LJspeech (false), TWEB (false), Nancy (true)
        "trim_db": 60,          // threshold for timming silence. Set this according to your dataset.

        // Griffin-Lim
        "power": 1.5,           // value to sharpen wav signals after GL algorithm.
        "griffin_lim_iters": 60,// #griffin-lim iterations. 30-60 is a good range. Larger the value, slower the generation.

        // MelSpectrogram parameters
        "num_mels": 80,         // size of the mel spec frame.
        "mel_fmin": 0.0,        // minimum freq level for mel-spec. ~50 for male and ~95 for female voices. Tune for dataset!!
        "mel_fmax": 8000.0,     // maximum freq level for mel-spec. Tune for dataset!!

        // Normalization parameters
        "signal_norm": true,    // normalize spec values. Mean-Var normalization if 'stats_path' is defined otherwise range normalization defined by the other params.
        "min_level_db": -100,   // lower bound for normalization
        "symmetric_norm": true, // move normalization to range [-1, 1]
        "max_norm": 4.0,        // scale normalization to range [-max_norm, max_norm] or [0, max_norm]
        "clip_norm": true,      // clip normalized values into the range.
        "stats_path": null    // DO NOT USE WITH MULTI_SPEAKER MODEL. scaler stats file computed by 'compute_statistics.py'. If it is defined, mean-std based notmalization is used and other normalization params are ignored
    },

    // VOCABULARY PARAMETERS
    // if custom character set is not defined,
    // default set in symbols.py is used
    // "characters":{
    //     "pad": "_",
    //     "eos": "~",
    //     "bos": "^",
    //     "characters": "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!'(),-.:;? ",
    //     "punctuations":"!'(),-.:;? ",
    //     "phonemes":"iyɨʉɯuɪʏʊeøɘəɵɤoɛœɜɞʌɔæɐaɶɑɒᵻʘɓǀɗǃʄǂɠǁʛpbtdʈɖcɟkɡqɢʔɴŋɲɳnɱmʙrʀⱱɾɽɸβfvθðszʃʒʂʐçʝxɣχʁħʕhɦɬɮʋɹɻjɰlɭʎʟˈˌːˑʍwɥʜʢʡɕʑɺɧɚ˞ɫ"
    // },

    // DISTRIBUTED TRAINING
    "distributed":{
        "backend": "nccl",
        "url": "tcp:\/\/localhost:54321"
    },

    "reinit_layers": [],    // give a list of layer names to restore from the given checkpoint. If not defined, it reloads all heuristically matching layers.

    // TRAINING
    "batch_size": 32,       // Batch size for training. Lower values than 32 might cause hard to learn attention. It is overwritten by 'gradual_training'.
    "eval_batch_size":16,
    "r": 7,                 // Number of decoder frames to predict per iteration. Set the initial values if gradual training is enabled.
    "gradual_training": [[0, 7, 64], [1, 5, 64], [50000, 3, 32], [130000, 2, 32], [290000, 1, 32]], //set gradual training steps [first_step, r, batch_size]. If it is null, gradual training is disabled. For Tacotron, you might need to reduce the 'batch_size' as you proceeed.
    "loss_masking": true,         // enable / disable loss masking against the sequence padding.
    "ga_alpha": 10.0,        // weight for guided attention loss. If > 0, guided attention is enabled.

    // VALIDATION
    "run_eval": true,
    "test_delay_epochs": 10,  //Until attention is aligned, testing only wastes computation time.
    "test_sentences_file": null,  // set a file to load sentences to be used for testing. If it is null then we use default english sentences.

    // OPTIMIZER
    "noam_schedule": false,        // use noam warmup and lr schedule.
    "grad_clip": 1.0,              // upper limit for gradients for clipping.
    "epochs": 1000,                // total number of epochs to train.
    "lr": 0.0001,                  // Initial learning rate. If Noam decay is active, maximum learning rate.
    "wd": 0.000001,                // Weight decay weight.
    "warmup_steps": 4000,          // Noam decay steps to increase the learning rate from 0 to "lr"
    "seq_len_norm": false,         // Normalize eash sample loss with its length to alleviate imbalanced datasets. Use it if your dataset is small or has skewed distribution of sequence lengths.

    // TACOTRON PRENET
    "memory_size": -1,             // ONLY TACOTRON - size of the memory queue used fro storing last decoder predictions for auto-regression. If < 0, memory queue is disabled and decoder only uses the last prediction frame.
    "prenet_type": "original",     // "original" or "bn".
    "prenet_dropout": true,        // enable/disable dropout at prenet.

    // ATTENTION
    "attention_type": "original",  // 'original' or 'graves'
    "attention_heads": 4,          // number of attention heads (only for 'graves')
    "attention_norm": "sigmoid",   // softmax or sigmoid. Suggested to use softmax for Tacotron2 and sigmoid for Tacotron.
    "windowing": false,            // Enables attention windowing. Used only in eval mode.
    "use_forward_attn": false,     // if it uses forward attention. In general, it aligns faster.
    "forward_attn_mask": false,    // Additional masking forcing monotonicity only in eval mode.
    "transition_agent": false,     // enable/disable transition agent of forward attention.
    "location_attn": true,         // enable_disable location sensitive attention. It is enabled for TACOTRON by default.
    "bidirectional_decoder": false,  // use https://arxiv.org/abs/1907.09006. Use it, if attention does not work well with your dataset.

    // STOPNET
    "stopnet": true,               // Train stopnet predicting the end of synthesis.
    "separate_stopnet": true,      // Train stopnet seperately if 'stopnet==true'. It prevents stopnet loss to influence the rest of the model. It causes a better model, but it trains SLOWER.

    // TENSORBOARD and LOGGING
    "print_step": 25,       // Number of steps to log traning on console.
    "print_eval": false,     // If True, it prints intermediate loss values in evalulation.
    "save_step": 10000,      // Number of training steps expected to save traninpg stats and checkpoints.
    "checkpoint": true,     // If true, it saves checkpoints per "save_step"
    "tb_model_param_stats": false,     // true, plots param stats per layer on tensorboard. Might be memory consuming, but good for debugging.

    // DATA LOADING
    "text_cleaner": "phoneme_cleaners",
    "enable_eos_bos_chars": false, // enable/disable beginning of sentence and end of sentence chars.
    "num_loader_workers": 4,        // number of training data loader processes. Don't set it too big. 4-8 are good values.
    "num_val_loader_workers": 4,    // number of evaluation data loader processes.
    "batch_group_size": 0,  //Number of batches to shuffle after bucketing.
    "min_seq_len": 6,       // DATASET-RELATED: minimum text length to use in training
    "max_seq_len": 153,     // DATASET-RELATED: maximum text length

    // PATHS
    "output_path": "/home/sadam/Projects/Italian_TTS/TTS/Models/LJSpeech/",

    // PHONEMES
    "phoneme_cache_path": "/home/sadam/Projects/Italian_TTS/TTS/mozilla_us_phonemes_3",  // phoneme computation is slow, therefore, it caches results in the given folder.
    "use_phonemes": true,           // use phonemes instead of raw characters. It is suggested for better pronounciation.
    "phoneme_language": "it",     // depending on your target language, pick one from  https://github.com/bootphon/phonemizer#languages

    // MULTI-SPEAKER and GST
    "use_speaker_embedding": false,     // use speaker embedding to enable multi-speaker learning.
    "style_wav_for_test": null,          // path to style wav file to be used in TacotronGST inference.
    "use_gst": false,       // TACOTRON ONLY: use global style tokens

    // DATASETS
    "datasets":   // List of datasets. They all merged and they get different speaker_ids.
        [
            {
                "name": "ljspeech",
                "path": "/home/sadam/Projects/Italian_TTS/LJSpeech-1.1/",
                "meta_file_train": "metadata.csv",
                "meta_file_val": null
            }
        ]

}

`

**Comment by Sadam1195** [comment]
Can any of you guys help?
@reuben @nmstoker @twerkmeister

**Comment by reuben** [comment]
Don't ping multiple people, this isn't your personal support agent. And remember it's a weekend.

**Comment by Sadam1195** [comment]
> Don't ping multiple people, this isn't your personal support agent. And remember it's a weekend.

I saw you guys as the active contributors and Eren wasn't replying so I thought....

**Comment by erogol** [comment]
you have not enough samples. You should have > 100.

**Comment by Sadam1195** [comment]
> you have not enough samples. You should have > 100.

Thank you for clearing that up. :)
