### ISSUE TITLE
[HELP] Share your trained TTS models?

### ISSUE THREAD

**Issue by erogol** [mozilla/TTS#395]
Please consider sharing your pre-trained models in any language (If the licenses allow that). We can include them in our model catalog for public use by referencing your name (website, company etc.). 

That would enable more people experiment together and coordinate, instead of individual efforts to achieve similar goals. That is also a good chance to make your work more visible.

**Comment by thorstenMueller** [comment]
Great idea.
I'll provide a free to use german tts model of my own voice (tacotron v1 and v2). Training is currently running. After it's finished i'll publish download links on my github project page.

Samples of my original recording voice and "training-in-progress"-samples are here:
https://soundcloud.com/thorsten-mueller-395984278/sets/thorsten-de-german-tts-model
(currently just tacotron1 training on step 100k)

https://github.com/thorstenMueller/deep-learning-german-tts/
https://discourse.mozilla.org/t/contributing-my-german-voice-for-tts/

**Comment by erogol** [comment]
I added your great work into the list https://github.com/mozilla/TTS/wiki/Dataset

**Comment by davidak** [comment]
It is not a model, but a german dataset: https://www.kaggle.com/bryanpark/german-single-speaker-speech-dataset

**Comment by thorstenMueller** [comment]
I'd like to keep this issue open due i think it's important to collect available tts models centrally.

**Comment by r-dh** [comment]
Both my Dutch (nl-BE) dataset as well as several trained models: https://github.com/r-dh/dutch-vl-tts

**Comment by thorstenMueller** [comment]
Thanks for sharing your dataset and model.
Your Taco2 + DDC has same robotic/metalic voice we encountered too.

German samples:
https://community.mycroft.ai/t/free-german-tts-voice-for-mycroft-sneak-preview/9458?u=thorsten

**Comment by ysujiang** [comment]
> Thanks for sharing your dataset and model.
> Your Taco2 + DDC has same robotic/metalic voice we encountered too.
> 
> German samples:
> https://community.mycroft.ai/t/free-german-tts-voice-for-mycroft-sneak-preview/9458?u=thorsten

can you share some generated voices?

**Comment by thorstenMueller** [comment]
Hello @ysujiang .
The samples of generated voice are posted in the link above, but to summarize it up:

* [Es ist im Moment klarer Himmel bei 18 Grad.](https://drive.google.com/file/d/1cDIq4QG6i60WjUYNT6fr2cpEjFQIi8w5/view?usp=sharing)
* [Ich verstehe das nicht, aber ich lerne jeden Tag neue Dinge.](https://drive.google.com/file/d/1kja_2RsFt6EmC33HTB4ozJyFlvh_DTFQ/view?usp=sharing)
* [Ich bin jetzt bereit.](https://drive.google.com/file/d/1GkplGH7LMJcPDpgFJocXHCjRln_ccVFs/view?usp=sharing)
* [Bitte warte einen Moment, bis ich fertig mit dem Booten bin.](https://drive.google.com/file/d/19Td-F14n_05F-squ3bNlt2BDE-NMFaq1/view?usp=sharing)
* [Mein Name ist MyCroft und ich bin funky.](https://drive.google.com/file/d/1dbyOyE7Oy8YdAsYqQ4vz4VJjiWIyc8oV/view?usp=sharing)

**Comment by Wingtail** [comment]
Hi, I would like to share my Tacotron 2 model in the Korean language. It's currently training using forward attention. I've yet to do the vocoder, but I'm 200k steps in now and it's the sound is great. 

Samples of generated voices in 200k step training:
[https://soundcloud.com/brian-kim-278776560/sets/korean-tacotron-2-forward-attention-200k-steps](url)

**Comment by erogol** [comment]
You can either list in ```.models.json``` if you already keep it on GDrive or if you share the model I can handle the rest. 

> Hi, I would like to share my Tacotron 2 model in the Korean language. It's currently training using forward attention. I've yet to do the vocoder, but I'm 200k steps in now and the sound is great.
> 
> Samples of generated voices in 200k step training:
> [https://soundcloud.com/brian-kim-278776560/sets/korean-tacotron-2-forward-attention-200k-steps](url)

You can either list in ```.models.json``` if you already keep it on GDrive or if you share the model I can handle the rest.

**Comment by erogol** [comment]
> Both my Dutch (nl-BE) dataset as well as several trained models: https://github.com/r-dh/dutch-vl-tts

would you like to add it to our ```.models.json ``` as the first Dutch model?

**Comment by erogol** [comment]
> Hi, I would like to share my Tacotron 2 model in the Korean language. It's currently training using forward attention. I've yet to do the vocoder, but I'm 200k steps in now and the sound is great.
> 
> Samples of generated voices in 200k step training:
> [https://soundcloud.com/brian-kim-278776560/sets/korean-tacotron-2-forward-attention-200k-steps](url)

Any updates on that? It'd be great to have Korean capabilities in TTS.

**Comment by Wingtail** [comment]
> > Hi, I would like to share my Tacotron 2 model in the Korean language. It's currently training using forward attention. I've yet to do the vocoder, but I'm 200k steps in now and the sound is great.
> > Samples of generated voices in 200k step training:
> > [https://soundcloud.com/brian-kim-278776560/sets/korean-tacotron-2-forward-attention-200k-steps](url)
> 
> Any updates on that? It'd be great to have Korean capabilities in TTS.

Hi, sorry for taking quite a long time. I've been prepping for midterms. I'll upload the trained model as soon as I'm done with it.

**Comment by snakers4** [comment]
Hi,

Please see our TTS models here - https://github.com/snakers4/silero-models#text-to-speech (corresponding article https://habr.com/ru/post/549482/)

**Comment by stefan-reich** [comment]
> Hello @ysujiang .
> The samples of generated voice are posted in the link above, but to summarize it up:
> 
> * [Es ist im Moment klarer Himmel bei 18 Grad.](https://drive.google.com/file/d/1cDIq4QG6i60WjUYNT6fr2cpEjFQIi8w5/view?usp=sharing)
> * [Ich verstehe das nicht, aber ich lerne jeden Tag neue Dinge.](https://drive.google.com/file/d/1kja_2RsFt6EmC33HTB4ozJyFlvh_DTFQ/view?usp=sharing)
> * [Ich bin jetzt bereit.](https://drive.google.com/file/d/1GkplGH7LMJcPDpgFJocXHCjRln_ccVFs/view?usp=sharing)
> * [Bitte warte einen Moment, bis ich fertig mit dem Booten bin.](https://drive.google.com/file/d/19Td-F14n_05F-squ3bNlt2BDE-NMFaq1/view?usp=sharing)
> * [Mein Name ist MyCroft und ich bin funky.](https://drive.google.com/file/d/1dbyOyE7Oy8YdAsYqQ4vz4VJjiWIyc8oV/view?usp=sharing)

Is there a pretrained model to download? Would love to use this.

**Comment by thorstenMueller** [comment]
Sure @stefan-reich. If you've a python 3.6 - 3.9 environment ready it's really simple (_see my github repo README_):
https://github.com/thorstenMueller/deep-learning-german-tts/#quick-steps-for-synthesizing-voice

* pip install -U pip TTS
* tts-server --model_name tts_models/de/thorsten/tacotron2-DCA
* Open web-browser on http://localhost:5002

**Comment by stefan-reich** [comment]
> Sure @stefan-reich. If you've a python 3.6 - 3.9 environment ready it's really simple (_see my github repo README_):
> https://github.com/thorstenMueller/deep-learning-german-tts/#quick-steps-for-synthesizing-voice
> 
> * pip install -U pip TTS
> * tts-server --model_name tts_models/de/thorsten/tacotron2-DCA
> * Open web-browser on http://localhost:5002

Ah, I'm dumb (uh, well, just sometimes ^^). Your model is literally in --list_models, I just hadn't checked out the international voices yet. Thanks. My only remaining desire is to have a female German voice because I may want to combine English and German words sometimes.

**Comment by thorstenMueller** [comment]
Sorry, but i "just" can provide a male voice :laughing:.

**Comment by stefan-reich** [comment]
> Sorry, but i "just" can provide a male voice .

Is it a regeneration of your own voice? (Sorry, last question, I'll stop cluttering the thread.)

**Comment by thorstenMueller** [comment]
Yes, i am the speaker of the "Thorsten" dataset and i trained the models based on it.
See: https://github.com/thorstenMueller/deep-learning-german-tts/

**Comment by Vis5** [comment]
@Wingtail Hello, are you wiling to share your model if it's finalized? if not, can you point me in the direction of where you got your dataset?

**Comment by souvikg544** [comment]
> Please consider sharing your pre-trained models in any language (If the licenses allow that). We can include them in our model catalog for public use by referencing your name (website, company etc.).
> 
> That would enable more people experiment together and coordinate, instead of individual efforts to achieve similar goals. That is also a good chance to make your work more visible.

To create your own models first of all you need a dataset . Presenting you with my easy to use colab based tts dataset maker - https://github.com/souvikg544/TTS_Data_Maker

If you like it do give it a star. Any problem you can share on issues.

**Comment by romanzkhanmrromanz-wq** [comment]
Duplicate of #790
