### ISSUE TITLE
Male Voice?

### ISSUE THREAD

**Issue by jmrichardson** [mozilla/TTS#396]
Hi,  I am very new to TTS and came across this amazing tool.  I was wondering if there is a way to have a male voice?  I noticed that the LJSpeech training data is female.  I was going to try out this self contained packaged listed here but not sure how to make it male:

`https://github.com/mozilla/TTS/wiki/Released-Models#simple-packaging---self-contained-package-that-runs-an-http-api-for-a-pre-trained-tts-model`

Thanks in advance!

**Comment by reuben** [comment]
The self contained package is meant as a simple way to deploy/use a pretrained model, it is not useful for training a new voice.

**Comment by reuben** [comment]
If you want a voice different than LJSpeech you'll need an appropriate dataset, and then you'll have to train a model on that dataset.

**Comment by jmrichardson** [comment]
That makes perfect sense and appreciate the pretrained model.  Dare I ask if someone has or knows where to find a male dataset that preferably works with this package?  I would imagine that annotations and prepossessing would need to be done to fit the workflow?  Or perhaps someone has already started this type of effort to extend to a male voice?  Thank you for your quick feedback.

**Comment by jmrichardson** [comment]
I found this page on the wiki:

https://github.com/mozilla/TTS/wiki/Dataset

I think I will be sticking with the Female voice for now.  :)
