### ISSUE TITLE
Problem training in multi GPU scenario

### ISSUE THREAD

**Issue by kannadaraj** [mozilla/TTS#397]
I have 8 GPUs.  I want to train 2 different variations of Tacotron. First variation in GPUs 1-4 and second in 5-8. 

1. I was able to start training using first 4 GPUs by limiting the gpus in multiproc.py. 
2. My i am not able to start train using 5-8 GPUs only. I did the following modifications in the code.
  ```
   1.  Changed num_gpus in config and train.py to 4.
   2. CUDA_VISIBLE_DEVICES=4,5,6,7 python -m multiproc train.py --output_directory=outdir --log_directory=logdir --hparams=distributed_run=True,fp16_run=True
```
the training program starts and hangs after distributed initialization. I am not sure what more i need to change in the code. this is the logs i see..

```
['train.py', '--output_directory=outdir', '--log_directory=logdir', '--hparams=distributed_run=True,fp16_run=True', '--n_gpus=4', '--group_name=group_2020_04_19-003226', '--rank=4]
['train.py', '--output_directory=outdir', '--log_directory=logdir', '--hparams=distributed_run=True,fp16_run=True', '--n_gpus=4', '--group_name=group_2020_04_19-003226', '--rank=5']
['train.py', '--output_directory=outdir', '--log_directory=logdir', '--hparams=distributed_run=True,fp16_run=True', '--n_gpus=4', '--group_name=group_2020_04_19-003226', '--rank=6']
['train.py', '--output_directory=outdir', '--log_directory=logdir', '--hparams=distributed_run=True,fp16_run=True', '--n_gpus=4', '--group_name=group_2020_04_19-003226', '--rank=7']

...
...

FP16 Run: True
Dynamic Loss Scaling: True
Distributed Run: True
cuDNN Enabled: True
cuDNN Benchmark: False
Initializing Distributed
Done initializing distributed
W0419 00:32:32.122517 140183680481088 module_wrapper.py:139] From /workspace/tacotrongst/hparams.py:122: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.

```

I just struck here for ever.. It doesn't start training. 

Please can someone help.. 

Thanks
Kannadaraj.

**Comment by reuben** [comment]
Usually with `CUDA_VISIBLE_DEVICES` you don't change application code at all. To the program, it'll look like there are only 4 GPUs installed.

**Comment by erogol** [comment]
Are you sure this is Mozilla TTS the code you run?

**Comment by erogol** [comment]
Closing this if you need, reopen pls

**Comment by nmstoker** [comment]
You were right @erogol - it was code from another repo :slightly_smiling_face: 
https://github.com/NVIDIA/tacotron2/issues/339
