### ISSUE TITLE
Decoder stopped with 'max_decoder_steps On Local server

### ISSUE THREAD

**Issue by mightmay** [mozilla/TTS#400]
After building according to the instruction here:
https://github.com/mozilla/TTS/wiki/Build-instructions-for-server

I open it and type something in the text box on my   http://localhost:5002 
after waiting for a while I gotten the error:
`Decoder stopped with 'max_decoder_steps`

What could be causing this problem ? 
Is it because I train for only 100 epoch ? Or is it because I trained on Colab, and running server on my computer with Only CPU, and no CUDA
I am using the LJSpeech dataset.

**Comment by haqkiemdaim** [comment]
yes i think you gonna need to train them with more epoch. 100 is not enough i guess. You can also check  the alignment which i bet still not properly aligned by the time your model reach 100 epoch.

**Comment by erogol** [comment]
I close this due to inactivity.
