### ISSUE TITLE
TypeError: can't convert cuda:0 device type tensor to numpy.

### ISSUE THREAD

**Issue by Ryuukishi** [mozilla/TTS#401]
When I run the following code I get an error. Any idea how to solve this. I'm running on Manjaro and Python 3.7.6. Thanks.

`python /home/ryu/TTS/train.py --config_path config.json`

 > Using CUDA:  True
 > Number of GPUs:  1
 > Git Hash: 2e2221f
 > Experiment folder: TTS/data4/rw/home/Trainings/ljspeech-stft_params-April-30-2020_01+14PM-2e2221f
 > Setting up Audio Processor...
 | > sample_rate:48000
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > num_freq:1025
 | > power:1.5
 | > preemphasis:0.98
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:50.0
 | > mel_fmax:8000.0
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > sound_norm:False
 | > hop_length:256
 | > win_length:1024
 | > n_fft:2048
 > Using model: Tacotron2
 | > Num output units : 1025

 > Model has 28915154 parameters
 > Number of outputs per iteration: 7

 > DataLoader initialization
 | > Use phonemes: True
   | > phoneme language: en-us
 | > Number of instances : 550
 | > Max length sequence: 208
 | > Min length sequence: 4
 | > Avg length sequence: 48.68363636363637
 | > Num. instances discarded by max-min (max=150, min=1) seq limits: 4
 | > Batch group size: 0.

 > Epoch 0/1000
/opt/conda/conda-bld/pytorch_1587428266983/work/torch/csrc/utils/python_arg_parser.cpp:756: UserWarning: This overload of add is deprecated:
        add(Number alpha, Tensor other)
Consider using one of the following signatures instead:
        add(Tensor other, *, Number alpha)
 ! Run is removed from TTS/data4/rw/home/Trainings/ljspeech-stft_params-April-30-2020_01+14PM-2e2221f
Traceback (most recent call last):
  File "/home/ryu/TTS/train.py", line 724, in <module>
    main(args)
  File "/home/ryu/TTS/train.py", line 640, in main
    global_step, epoch)
  File "/home/ryu/TTS/train.py", line 202, in train
    grad_norm, grad_flag = check_update(model, c.grad_clip, ignore_stopnet=True)
  File "/home/ryu/TTS/tts_namespace/TTS/utils/generic_utils.py", line 160, in check_update
    if np.isinf(grad_norm):
  File "/home/ryu/miniconda3/lib/python3.7/site-packages/torch/tensor.py", line 492, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by Ryuukishi** [comment]
Found out this was fixed after pull 398 was merged.

**Comment by repodiac** [comment]
> Found out this was fixed after pull 398 was merged.

What PR / commit on which branch do you mean? I experienced the same problem (only if using a GPU btw., CPU works obviously) and the current master branch, latest commit is `2e2221f146f1ca301a3b2b547d8f26b9009676de`

I could fix the problem myself... but of course wondering if this is only a hacky workaround or a real fix.

I changed
`if np.isinf(grad_norm):` [Line 160] in utils/generic_utils.py
into
`if np.isinf(grad_norm.cpu()):`
and added further below also
`device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
 grad_norm.to(device)`
in order to enable to push back the tensor to the GPU.

**Comment by Ryuukishi** [comment]
Sorry, seems I was mistaken. Doesn't seem like it has been merged yet. Here's the link.

https://github.com/mozilla/TTS/pull/398

**Comment by repodiac** [comment]
oh, thanks :)
