### ISSUE TITLE
Prebuild TTS image with non-working numpy version on Ubuntu 20.04

### ISSUE THREAD

**Issue by benbucksch** [mozilla/TTS#402]
Reproduction:
* Ubuntu 20.04
* ... which has Python 3.8
* `virtualenv .`
* `source bin/activate`
* `pip install https://github.com/reuben/TTS/releases/download/ljspeech-fwd-attn-pwgan/TTS-0.0.1+92aea2a-py3-none-any.whl` (as given on the [Released Models](https://github.com/mozilla/TTS/wiki/Released-Models) page)
* `python -m TTS.server.server`

Actual result:
* `ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'` ...
* `ImportError: numpy.core.multiarray failed to import`
* Stack: `TTS/utils/audio.py` imports `librosa` imports `scipy.ndimage`

Expected result:
* TTS server startds

Fix:
* `pip uninstall numpy` -> `Uninstalling numpy-1.15.4`
* `pip install numpy` -> `Successfully installed numpy-1.18.4`
* But, it also says:
```
ERROR: tts 0.0.1+92aea2a has requirement numpy==1.15.4, but you'll have numpy 1.18.4 which is incompatible.
ERROR: parallel-wavegan 0.2.9 has requirement numpy==1.15.4, but you'll have numpy 1.18.4 which is incompatible.
```
(Note that `tts` and `parallel-wavegan` specifically require a specific version of numpy, which is now outdated and apparently is no longer compatible with Python 3.8. That's what this bug is about.)
* Ignore that error
* `python -m TTS.server.server` -> `Loading TTS model ...` -> It runs

**Comment by reuben** [comment]
This is why the docs also specify creating a Python 3.6 virtualenv. Future server releases might bump the deps, and the supported Python version. If your distro doesn't have 3.6 packages, there is pyenv: https://github.com/pyenv/pyenv
