### ISSUE TITLE
Dead link in README.md

### ISSUE THREAD

**Issue by combs** [mozilla/TTS#410]
Just a quickie, this link in the README.md doesn't seem to exist anymore:

```
If you are new, you can also find [here](http://www.erogol.com/text-speech-deep-learning-architectures/) a brief post about TTS architectures and their comparisons.
```

I had a quick look on that domain for similar pages and couldn't find a new URL for it, so maybe it was blackholed. 

Thanks--appreciate this project!

**Comment by erogol** [comment]
it was not the link but my blog broken. now fixed. Thx for the flag.
