### ISSUE TITLE
Adding initial support for FastSpeech

### ISSUE THREAD

**Issue by erogol** [mozilla/TTS#432]
Fast Speech model uses pretrained TTS model to learn the phoneme durations with a duration regulator. It also uses a non auto regressive architecture thus ultimately provides faster inference run.

**Comment by davidak** [comment]
This is still planned.

**Comment by erogol** [comment]
Are you working on that because I am not?

**Comment by davidak** [comment]
No, but it is in To Do for v0.0.4 milestone.

**Comment by erogol** [comment]
I'll probably skip for this round unless someone is willing to help.

**Comment by davidak** [comment]
i guess this is still needed?

**Comment by davidak** [comment]
I couldn't save this issue. The bots are too strong with their consistency, crushing us weak humans.

RIP
