### ISSUE TITLE
Configurable TTS model outputs

### ISSUE THREAD

**Issue by erogol** [mozilla/TTS#433]
Right now, Tacotron model outpus linear spectrograms and Tacotron2 outputs melspectrograms. The plan is to make this configurable so that both models can compute the desired output.

**Comment by repodiac** [comment]
btw. I just filed an issue regarding general audio processing: https://github.com/mozilla/TTS/issues/436

**Comment by erogol** [comment]
is your issue related to this issue?

**Comment by repodiac** [comment]
somehow, it could use a GPU accelerated version, as well

**Comment by erogol** [comment]
this issues had nothing to do with that. I meant here the output dimensions of the models. Sorry if it is not clear.
