### ISSUE TITLE
Replace librosa audio processing with native pytorch functionality

### ISSUE THREAD

**Issue by repodiac** [mozilla/TTS#436]
Mozilla TTS still uses **CPU-only** audio processing functionality from `librosa` lib, for instance for creating STFT or Mel spectrograms and so forth.

All the functionality needed here is a mature part of pytorch - which may enable **GPU acceleration** if available:

https://pytorch.org/audio/transforms.html

So I suggest to replace librosa code with pytorch native implementations where necessary.

**Comment by erogol** [comment]
As I experimented before, GPU version is not faster on CPU by any means and does not help for training since dataloader handles each item separatly. 

However, I would welcome any PR using GPU STFT for inference only.

**Comment by repodiac** [comment]
Can you detail on that? I don't understand what this has to do with dataloader.

Dominik (https://discourse.mozilla.org/u/dkreutz/) is currently working on accelerating STFT and Mel specs - he achieved a 30% increase with CuPy alone (instead of Numpy).

So I expect it being faster really... maybe pytorch isn't but other lib like CuPy can obviously speed up things significantly.

**Comment by erogol** [comment]
because I stft mainly used by the dataloader and at inference since we generate a single voice sample GPU implementation is not faster. For utilizing GPU we need batch inference which is not implemented. Hope it make sense?

**Comment by repodiac** [comment]
well, without knowing enough about the code (yet), I will leave it like this - let's see how it evolves
