### ISSUE TITLE
Why config.json is not following the Json rules?

### ISSUE THREAD

**Issue by multinucliated** [mozilla/TTS#442]
Hello,

In the project folder , config.json file is not proper and why ?

why its not following the sets of rule for the properly json formatted code.
https://www.json.org/json-en.html

**Comment by erogol** [comment]
because we need to commend

**Comment by multinucliated** [comment]
So, can me make any reference file for "config.json" instead of adding comment to that file itself ?
and is there any draft version for commending or shall we make it as a Wiki ?

**Comment by erogol** [comment]
why do we need strickly use formal json format? So far we do not use it for something more than instructing the model.

However, a wiki entry would be good but it is hard to maintain it as we change things quite swiftly.

**Comment by multinucliated** [comment]
Correct , for a time being when everyone is comfortable with Json formatting and understanding , can we use (add) [https://commentjson.readthedocs.io/en/latest/ ](url) in TTS project for loading and maintaining the actual file with comments.

Only we need to add this in our requirement.txt file and  load the json file with the help of this library.

and for sure, maintaining the another Wiki page for parameters  information will be a extra task.

**Comment by erogol** [comment]
Nice suggestion. We already use a custom patch of code to handle comments in config file. I am not fond of adding more dependencies. However, if you have any other concerns requiring this module let me know.

**Comment by multinucliated** [comment]
No, Thanks for the help and time .
