### ISSUE TITLE
Handling Phonemized Dates and Numbers

### ISSUE THREAD

**Issue by erogol** [mozilla/TTS#443]
If you use phonemizer with dates, numbers are converted as they are called but the pronunciation is different in the dataset (LJSpeech)

For instance if you say: "I came here in 1948 but I didn't like it"  

date is converted to "one thousand nine hundred ...." however model reads as "nineteen hundred forty eight". This problem makes things harder at training to learn the attention and at inference, it causes the following skipping attention plots. Strangely, the model is able to read the date correctly despite the wrong phoneme conversion.

![image](https://user-images.githubusercontent.com/1402048/85391103-0be53700-b54a-11ea-8205-45431f567a58.png)

**Comment by dathudeptrai** [comment]
@erogol if this behavior is consistent the model can be learn to correct wrong phoneme :)).

**Comment by erogol** [comment]
I think it is better to keep the numbers without converting them to phonemes.

**Comment by dathudeptrai** [comment]
but how many samples include numbers?, it's very hard for model to speak directly from number unless there are so many number samples and it cover all case.

**Comment by erogol** [comment]
in LJspeech >1400

**Comment by george-roussos** [comment]
In my datasets, I manually expand numbers before training, based on how the speakers reads them. Then it learns the phonemes and at inference time if the normalizer expands in different form the model is still able to read it.

It also solves cases where a number has different pronunciations, e.g. in Swedish 25 can either be read as "tjugofem or tjufem" and is entirely up to the speaker. So I always think it is nice for the transcription to match completely. It is time consuming, but it helps my models a great lot.

**Comment by erogol** [comment]
I fix this with a new number expander for the moment.
