### ISSUE TITLE
Vocoder data loading difficulties with short wav files

### ISSUE THREAD

**Issue by nmstoker** [mozilla/TTS#450]
I am trying to use the new vocoder in dev, but seem to be running into problems with short wav files.  I see the code makes an attempt to pad the files ([here](https://github.com/mozilla/TTS/blob/c7296b342368c2672b4de12a69e372d2935531d4/vocoder/datasets/gan_dataset.py#L103)) but it seems like it fails with files of short length, such as a few that I have with a single word (example file below is 32kb)

In the script output below, showing training crashing as it attempts the first epoch, I have added some print statements to vocoder/datasets/gan_datasets.py, but this was merely to let me zero in on the specific problem wav files and i made no other code changes.
 
```
(tts_ddc1) [neil@ramandu TTS]$ CUDA_VISIBLE_DEVICES='1' python vocoder/train.py --config_path ../models/neil17/config_vocoder_neil17_A.json 
 > Using CUDA:  False
 > Number of GPUs:  0
 > Git Hash: b1935c9
 > Experiment folder: /home/neil/main/Projects/TTSJul2020/models/neil17/multiband-melgan-July-09-2020_10+41PM-b1935c9
 > Loading wavs from: /home/neil/data/Projects/NeilTTS/neil16/wavs/
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > num_mels:80
 | > min_level_db:-90
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:25
 | > fft_size:1024
 | > power:None
 | > preemphasis:0.0
 | > griffin_lim_iters:None
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:40.0
 | > mel_fmax:8000.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > stats_path:/home/neil/main/Projects/TTSJul2020/models/neil17/scale_stats.npy
 | > hop_length:256
 | > win_length:1024
 > Generator Model: multiband_melgan_generator
 > Discriminator Model: melgan_multiscale_discriminator
 > Generator has 2539448 parameters
 > Discriminator has 4354998 parameters

 > EPOCH: 0/10000

 > TRAINING (2020-07-09 22:41:15) 
computing features from wav
/home/neil/data/Projects/NeilTTS/neil16/wavs/p225_25113.wav
computing features from wav
/home/neil/data/Projects/NeilTTS/neil16/wavs/p225_30350.wav
computing features from wav
/home/neil/data/Projects/NeilTTS/neil16/wavs/p225_28075.wav
computing features from wav
/home/neil/data/Projects/NeilTTS/neil16/wavs/p225_12633.wav
computing features from wav
/home/neil/data/Projects/NeilTTS/neil16/wavs/p225_19891.wav
computing features from wav
/home/neil/data/Projects/NeilTTS/neil16/wavs/p225_9142.wav
Padding short wav
computing features from wav
/home/neil/data/Projects/NeilTTS/neil16/wavs/p225_29241.wav
 ! Run is removed from /home/neil/main/Projects/TTSJul2020/models/neil17/multiband-melgan-July-09-2020_10+41PM-b1935c9
Traceback (most recent call last):
  File "vocoder/train.py", line 648, in <module>
    main(args)
  File "vocoder/train.py", line 552, in main
    epoch)
  File "vocoder/train.py", line 101, in train
    for num_iter, data in enumerate(data_loader):
  File "/home/neil/.conda/envs/tts_ddc1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/neil/.conda/envs/tts_ddc1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/neil/.conda/envs/tts_ddc1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/neil/.conda/envs/tts_ddc1/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/neil/.conda/envs/tts_ddc1/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/neil/.conda/envs/tts_ddc1/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/neil/.conda/envs/tts_ddc1/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/neil/main/Projects/TTSJul2020/TTS/tts_namespace/TTS/vocoder/datasets/gan_dataset.py", line 72, in __getitem__
    item2 = self.load_item(idx2)
  File "/home/neil/main/Projects/TTSJul2020/TTS/tts_namespace/TTS/vocoder/datasets/gan_dataset.py", line 119, in load_item
    mel_start = random.randint(0, max_mel_start)
  File "/home/neil/.conda/envs/tts_ddc1/lib/python3.6/random.py", line 221, in randint
    return self.randrange(a, b+1)
  File "/home/neil/.conda/envs/tts_ddc1/lib/python3.6/random.py", line 199, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,-5, -5)

computing features from wav
/home/neil/data/Projects/NeilTTS/neil16/wavs/p225_3113.wav
computing features from wav
/home/neil/data/Projects/NeilTTS/neil16/wavs/p225_14619.wav
Padding short wav
(tts_ddc1) [neil@ramandu TTS]$ aplay /home/neil/data/Projects/NeilTTS/neil16/wavs/p225_9142.wav 
Playing WAVE '/home/neil/data/Projects/NeilTTS/neil16/wavs/p225_9142.wav' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
(tts_ddc1) [neil@ramandu TTS]$ ls -lah /home/neil/data/Projects/NeilTTS/neil16/wavs/p225_9142.wav 
-rw-r--r-- 1 neil users 34K Apr 23 00:39 /home/neil/data/Projects/NeilTTS/neil16/wavs/p225_9142.wav

```
I'll keep looking and see what I can figure out to resolve it but wanted to flag it in case others ran into this.
My config is attached too (merely with .txt suffix to get it uploaded here) - I hope i've chosen sensible values and no obvious mistakes - it's very close to the version in the vocoders folder anyway.

[config_vocoder_neil17_A_json.txt](https://github.com/mozilla/TTS/files/4899727/config_vocoder_neil17_A_json.txt)

I am running training with just the audio files and that seems to be what the README recommends.  I did see the file **compute_tts_features.py** which seems like it would let me preprocess the audio into features but it's currently a blank file, so I've stuck to just the audio files.

The errors appear slightly out of order due to the multiprocessing but it seems to be the file right before the "Padding short wav" comment is printed, in this case p225_9142.wav in my dataset, which after the crash I then play to determine it is indeed short and then I list the size.  The file from my dataset that triggers this varies as the dataloader order is randomised and I have a selection of fairly short(ish) files.

My suspicion is I may need to try something with **seq_len** or **pad_short**, I'm just hesitant to give it a go, only to find it was a mistake after a four day run! :slightly_smiling_face: 

On a related note, I haven't yet done it, but I am assuming that I could dump both my validation wav and training wavs together into the folder I use for the vocoder since it is not asking for a split and I believe it just tries to learn to reproduce the input snippets (so it measures against the input, right?)

**Comment by nmstoker** [comment]
**Quick update:** I believe I've found the issue: with short audio clips, because the mel spectogram is being worked out from the audio before it is padded, the calculation for max_mel_start is going negative.

It is late so I will need to follow up further tomorrow evening, but a simple change in the order of the code to put the audio padding part before the call to ap.melspectogram [here](https://github.com/mozilla/TTS/blob/c7296b342368c2672b4de12a69e372d2935531d4/vocoder/datasets/gan_dataset.py#L90) seems like it fixes it and it is (_apparently_) running happily now.

If this makes sense to others I'll try to get a PR ready over the weekend for it.

**Comment by erogol** [comment]
I think [this](https://github.com/mozilla/TTS/blob/c7296b342368c2672b4de12a69e372d2935531d4/vocoder/datasets/gan_dataset.py#L102) part should have been earlier in the code. After loading the audio but before computing the mel.
