### ISSUE TITLE
UnicodeDecodeError in Colab: DDC-TTS_and_MultiBand_MelGAN_Example

### ISSUE THREAD

**Issue by lokkelvin2** [mozilla/TTS#454]
I tried running the [DDC-TTS CPU inference](https://colab.research.google.com/drive/1u_16ZzHjKYFn1HNVuA4Qf_i2MMFB9olY?usp=sharing) notebook locally on my Windows 10 machine and encountered this error during setup:
`UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 3058: character maps to <undefined>`

The error traces back to line 16 of TTS\utils\io.py, `with open(config_path, "r") as f:`
The solution is described [here](https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character). Basically, we need to declare utf-8 encoding, otherwise windows reverts to CP-1252 encoding.

To fix, replace `with open(config_path, "r") as f:` with `with open(config_path, "r", encoding = "utf-8") as f:` in TTS\utils\io.py.

Hope this helps the rare Windows users.

**Comment by erogol** [comment]
how about sending a pr for this easy fix?

**Comment by lokkelvin2** [comment]
The colab notebook uses commit `b1935c97` so anyone using the colab's code to run a local notebook may have to be aware of this issue on windows 10.
