### ISSUE TITLE
Implement ParallelWaveGAN

### ISSUE THREAD

**Issue by erogol** [mozilla/TTS#457]
Adding ParallelWaveGAN vocoder to the vocoder module.

**Comment by davidak** [comment]
Wow, that sounds perfect! https://r9y9.github.io/demos/projects/icassp2020/

**Comment by tsungruihon** [comment]
@erogol Would you mind sharing the repo? Thanks erogol.

**Comment by dathudeptrai** [comment]
@tsungruihon https://github.com/kan-bayashi/ParallelWaveGAN

**Comment by tsungruihon** [comment]
@dathudeptrai thanks a lot. Actually i would like to know which PWG repo is suitable for TTS repo.

**Comment by SanjaESC** [comment]
@tsungruihon They are currently supported in the [dev branch](https://github.com/mozilla/TTS/tree/dev)

**Comment by tsungruihon** [comment]
@SanjaESC Thanks a lot.

**Comment by erogol** [comment]
done in dev
