### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by ngthuong45** [mozilla/TTS#473]
> Using CUDA:  True
 > Number of GPUs:  1
 > Git Hash: 599c2db
 > Experiment folder: /home/ngthuong/Desktop/LJSpeech/ljspeech-July-31-2020_09+38AM-599c2db
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > num_freq:513
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:8000.0
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > stats_path:None
 | > hop_length:256
 | > win_length:1024
 | > n_fft:1024
 > Using model: Tacotron2
 | > Num output units : 513

 > Model has 28947858 parameters

 > EPOCH: 0/1000

 > Number of output frames: 7

 > DataLoader initialization
 | > Use phonemes: False
 | > Number of instances : 12969
 | > Max length sequence: 187
 | > Min length sequence: 5
 | > Avg length sequence: 98.3403500655409
 | > Num. instances discarded by max-min (max=153, min=6) seq limits: 476
 | > Batch group size: 0.

 > TRAINING (2020-07-31 09:38:21) 
Traceback (most recent call last):
  File "train.py", line 676, in <module>
    main(args)
  File "train.py", line 589, in main
    train_avg_loss_dict, global_step = train(model, criterion, optimizer,
  File "train.py", line 180, in train
    loss_dict = criterion(postnet_output, decoder_output, mel_input,
  File "/home/ngthuong/Desktop/my_projects/AI/TTS/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ngthuong/Desktop/my_projects/AI/TTS/layers/losses.py", line 231, in forward
    ga_loss = self.criterion_ga(alignments, input_lens, alignment_lens)
  File "/home/ngthuong/Desktop/my_projects/AI/TTS/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ngthuong/Desktop/my_projects/AI/TTS/layers/losses.py", line 145, in forward
    ga_masks = self._make_ga_masks(ilens, olens).to(att_ws.device)
  File "/home/ngthuong/Desktop/my_projects/AI/TTS/layers/losses.py", line 141, in _make_ga_masks
    ga_masks[idx, :olen, :ilen] = self._make_ga_mask(ilen, olen, self.sigma)
  File "/home/ngthuong/Desktop/my_projects/AI/TTS/layers/losses.py", line 155, in _make_ga_mask
    return 1.0 - torch.exp(-(grid_y / ilen - grid_x / olen) ** 2 / (2 * (sigma ** 2)))
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

How to fix it?

**Comment by SanjaESC** [comment]
I checked the error message and it seems like [torch.arange](https://pytorch.org/docs/master/generated/torch.arange.html) returns the tensor mapped to cpu even though the input was passed as gpu?
https://github.com/mozilla/TTS/blob/599c2dbcff757582092975369705e71da42ae3a0/layers/losses.py#L153 


You could go ahead an try to make the following changes to the line
`grid_x, grid_y = torch.meshgrid(torch.arange(olen, device=olen.device), torch.arange(ilen, device=ilen.device))`
This should map the tensor to the currently used device.

**Comment by erogol** [comment]
You need to give system defition always as you create an issue. For example pytorch version?

**Comment by jyegerlehner** [comment]
I just setup TTS for the first time in a new virtual environment and also saw this error with the same stack trace.

```
ubuntu 18.04
conda 4.8.3
pytorch 1.6.0
cudatoolkit 10.1.243
```
I tried  @SanjaESC suggestion and it resolved the problem. I'll submit it as a PR.

**Comment by jyegerlehner** [comment]
I see instructions say to submit PRs against dev, but it looks like a dramatically different code base than master such that the PR is no longer applicable. There is another such prospective PR against master in the branch [here ](https://github.com/mozilla/TTS/compare/master...jyegerlehner:fix-scipy.io.wavfile-import) that I think fixes another runtime error. Don't know what you would want me to do.

**Comment by erogol** [comment]
Please send a PR to the dev branch.

**Comment by erogol** [comment]
this should be fixed with #476

**Comment by WeberJulian** [comment]
Hi, I just pulled dev and I have the same problem. I don't think #476 solved the issue.

**Comment by WeberJulian** [comment]
forcing `device='cuda'` solves the issue but it's obviously not a valid fix.

``` python
grid_x, grid_y = torch.meshgrid(torch.arange(olen, device='cuda'), torch.arange(ilen, device='cuda'))
```

**Comment by jyegerlehner** [comment]
I'm new to torch, but I'm guessing this must mean that `ilen` and `olen` were on different devices coming in to` _make_ga_mask`. One could check by printing out the device:
```
        print("grid_y.device={}".format(grid_y.device))
        print("grid_x.device={}".format(grid_x.device))
        print("olen.device={}".format(olen.device))
        print("ilen.device={}".format(ilen.device))
        return 1.0 - torch.exp(-(grid_y / ilen - grid_x / olen) ** 2 / (2 * (sigma ** 2)))
```

In which case I see 
```
grid_y.device=cuda:0
grid_x.device=cuda:0
olen.device=cuda:0
ilen.device=cuda:0

```
and in your case they are not all on the same device.

But I imagine a work around might be, instead of setting the `arange` results passed to `meshgrid` to the device of ilen and olen, just choose one of them and use it's device, e.g.:

`grid_x, grid_y = torch.meshgrid(torch.arange(olen, device=ilen.device), torch.arange(ilen, device=ilen.device))
`
But it does seems like a hack that shouldn't be necessary considering the code that produces them. And perhaps a performance hit since it's going to be moving stuff between CPU and GPU mem. 

If it's not too much trouble maybe you could go up the call stack and see which line  causes ilen and olen to end up on different devices.

**Comment by WeberJulian** [comment]
I'm sorry it's really weird, I can't get it to crash again... I tried this and even starting a new train from scratch.

```python 
    @staticmethod
    def _make_ga_mask(ilen, olen, sigma):
        if ilen.device != olen.device:
            pdb.set_trace()
        grid_x, grid_y = torch.meshgrid(torch.arange(olen, device=olen.device), torch.arange(ilen, device=ilen.device))
        grid_x, grid_y = grid_x.float(), grid_y.float()
        return 1.0 - torch.exp(-(grid_y / ilen - grid_x / olen) ** 2 / (2 * (sigma ** 2)))
```

I reverted all the changes and it still works

**Comment by erogol** [comment]
so there is not problem ?

**Comment by WeberJulian** [comment]
Not anymore, I didn't reset the phoneme cash between the runs but I don't think it matters
