### ISSUE TITLE
any experience of unstable tacotron?

### ISSUE THREAD

**Issue by xinqipony** [mozilla/TTS#48]
first, thank you for this amazing source and hard work!
I really love it.

I met some bad case like skipping word, unstopped case, repeat word, any insight or trying on this topic?

**Comment by xinqipony** [comment]
no, I use another repro, any insight how to fix?

**Comment by erogol** [comment]
Attention is the vital part of the model. If it does not align well, it causes all the problems you pointed above. So i'd suggest to change the attention method you use. Or just use TTS :)
