### ISSUE TITLE
what is meaning that alignment_score in tensorboard?

### ISSUE THREAD

**Issue by tsungruihon** [mozilla/TTS#484]
It seems that `alignment_score` is equal to `avg_align_error` which presented in `train.py`. And the `avg_align_score` is computed by using the formula `1 - alignment_diagonal_score(alignments)`. 

So whether the `alignment_score` lower, the model alignment effect is better ?  

Thanks.

**Comment by erogol** [comment]
the higher the score, the better the alignment 

the lower the error, the better the alignment

in the dev branch there is no score anymore. It is changed to alignment_error.

**Comment by tsungruihon** [comment]
@erogol thanks erogol. Have a good day.
