### ISSUE TITLE
Fix code

### ISSUE THREAD

**Issue by asmodaay** [mozilla/TTS#487]
Hello, if i enable bidirectional decoder training script drops eror.
There is in train.py line 185
`            keep_avg.update_values({'avg_decoder_b_loss': loss_dict['decoder_backward_loss'].item(),
`
need to change on 
`            keep_avg.update_values({'avg_decoder_b_loss': loss_dict['decoder_b_loss'].item(),
`

**Comment by erogol** [comment]
you can try the dev branch. It should be fixed there. You can also send a PR to master to fix this issue.
