### ISSUE TITLE
Voice quality about mel2gl vs linearspec2gl

### ISSUE THREAD

**Issue by tsungruihon** [mozilla/TTS#488]
I just found that there is a quite big difference quality result that using mel and linear_spec as griffin lim vocoder input. 

As we know that if we want to invert mel to wave, that we have to convert mel to linear_spec first using `_mel_to_linear( )` function.  But the final results tell me intuitively that, the wave gl quality which using mel as input is kind of loose and unstable, whereas the wave gl quality which using linear_spec sounds much kind of solid.

Here's the two audio samples. Please feel free to enlighten me. 

[samples.zip](https://github.com/mozilla/TTS/files/5026984/samples.zip)

**Comment by erogol** [comment]
It is normal since linear spec has a better resolution.
