### ISSUE TITLE
How to generate silence using TTS

### ISSUE THREAD

**Issue by tsungruihon** [mozilla/TTS#490]
I found that if i try to batch inference using TTS, it would generate some unexpected sound like trembling sound etc in the short sentence. 
let say there is a batch contains two sentence, a long one and the short one. The long one could be successfully synthesized. But the short one not only synthesize the part it should be, but also came after some trembling sound.
I tried to use `pad = 0` or `pad = 1` in batch sentence, but it could not generate silence. Hopefully someone could give me a hint, thanks.

**Comment by erogol** [comment]
trembling sound can be removed by the ap.trim_silence then you can merge results together.

**Comment by tsungruihon** [comment]
@erogol you mean that i need to set `ap.trim_silence = true` ?

**Comment by erogol** [comment]
so what is the problem in the above spectrum? I don't understand the problem exactly.
