### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'aux_context_window'

### ISSUE THREAD

**Issue by tsungruihon** [mozilla/TTS#503]
When i tried to use `dev` branch to train `parallel_wavegan`, it came up the below error.

```
Traceback (most recent call last):
  File "mozilla_voice_tts/bin/train_vocoder.py", line 657, in <module>
    main(args)
  File "mozilla_voice_tts/bin/train_vocoder.py", line 469, in main
    model_gen = setup_generator(c)
  File "/home/data/tts_vocoder/TTS/mozilla_voice_tts/vocoder/utils/generic_utils.py", line 86, in setup_generator
    upsample_factors=c.generator_model_params['upsample_factors'])
TypeError: __init__() got an unexpected keyword argument 'aux_context_window'
```

**Comment by erogol** [comment]
did you pull the latest dev?

**Comment by tsungruihon** [comment]
@erogol thanks erogol. I have pull the latest dev and now the training process is on its way. 

But i have another question that why we do not need to generate `metadata.txt` first like we trained `Parallel_WaveGAN` before, which is aimed to adapt to our TTS trained model ? 

Thanks.

**Comment by erogol** [comment]
it just takes all the wav files in a folder. that way it is easier to use with different datasets. that's the reason.

**Comment by tsungruihon** [comment]
Thanks erogol. But i wonder how that could adapt to trained TTS model ? It seems like that it is trained based on original wavs, but not GTA.

**Comment by erogol** [comment]
True that I train model with original wavs and it works for me.

**Comment by tsungruihon** [comment]
@erogol  thanks erogol. I will try it. Thanks again.
