### ISSUE TITLE
Web server giving empty audio for most of unseen input text

### ISSUE THREAD

**Issue by Sadam1195** [mozilla/TTS#505]
I have developed TTS model on some custom dataset with 100k epochs trained model. 
After everything I executed `python -m TTS.server.server` and opened the url, provided few input texts.
For some inputs it is giving a valid audio output but for many inputs **audio is empty** of 0 seconds. Why this kind of behavior happen, any idea? Is this could be a bug or my trained dataset does not have a good wide coverage of texts inputs therefore model being not generalized enough to synthesize audio?

Maybe this could help in understanding the problem. I tried running larger texts and shorter texts. With larger texts it is generating empty audio and for shorter texts like "**uno**" it is generating 2 second audio and for shorter texts like "**uno?**" with just addition of question mark, it is generating audio of 7 seconds long.

I am using Griffin Lim as default while synthesizing audio.

**Comment by erogol** [comment]
I need the exact error log to say something. 

But debugging the text processing for the problematic sentences would be useful. Check how the text is formated just before giving it to the server. If there is an empty string after sentence separation, that might cause an error.

**Comment by Sadam1195** [comment]
> I need the exact error log to say something.
> 
> But debugging the text processing for the problematic sentences would be useful. Check how the text is formated just before giving it to the server. If there is an empty string after sentence separation, that might cause an error.

As I said, No errors occurred hence I can't provide logs. Hmm, that makes sense. I will look into how text is formatted. 
Thank you :)

**Comment by erogol** [comment]
I close this for now.
