### ISSUE TITLE
[Feature Request]Android app

### ISSUE THREAD

**Issue by Oymate** [mozilla/TTS#506]

**Comment by WeberJulian** [comment]
I don't see the appeal of an app that does just TTS but you can, I think, use the TF converter in the dev branch to convert your model to Tensorflow and then use the [Tensorflow lite](https://www.tensorflow.org/lite) API to run it on your android phone.

**Comment by Oymate** [comment]
@WeberJulian  I would like to replace Google tts engine to allow for using this tts engine. Kónele has done another app, but it uses internet. I would like to use this one.

**Comment by dathudeptrai** [comment]
@Oymate maybe useful for you (https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/android)

**Comment by erogol** [comment]
If anyone is willing to make a PR, it is great but Android is above my head.

**Comment by Oymate** [comment]
Activity

**Comment by erogol** [comment]
@Oymate do you work on that?

**Comment by Oymate** [comment]
No, but I would like to have this as an installable app.
