### ISSUE TITLE
Parallel_wavegan tensorboard results weird

### ISSUE THREAD

**Issue by tsungruihon** [mozilla/TTS#508]
I used the `dev` branch training PWGAN, then i looked into the tensorboard results, it seems that the spectrograms look weird. May i ask whether i did something wrong or i miss something?

I used the original `parallel_wavegan_config.json`.

![Screenshot 2020-09-02 at 6 02 30 PM](https://user-images.githubusercontent.com/11624203/91967981-92867380-ed46-11ea-9ff6-25dff8ec8fbe.png)

**Comment by george-roussos** [comment]
Can you give some details on your dataset and if this is training from scratch or finetuning? The figures show that there's been no learning.

**Comment by tsungruihon** [comment]
@george-roussos thanks george. My dataset is Indonesian language and i trained from scratch, which is from the origin wav datasets. Here's my config file.
```

{
"github_branch":"* dev",
    "run_name": "pwgan",
    "run_description": "parallel-wavegan training",

    // AUDIO PARAMETERS
    "audio":{
        "fft_size": 1024,         // number of stft frequency levels. Size of the linear spectogram frame.
        "win_length": 1024,      // stft window length in ms.
        "hop_length": 256,       // stft window hop-lengh in ms.
        "frame_length_ms": null, // stft window length in ms.If null, 'win_length' is used.
        "frame_shift_ms": null,  // stft window hop-lengh in ms. If null, 'hop_length' is used.

        // Audio processing parameters
        "sample_rate": 22050,   // DATASET-RELATED: wav sample-rate. If different than the original data, it is resampled.
        "preemphasis": 0.0,     // pre-emphasis to reduce spec noise and make it more structured. If 0.0, no -pre-emphasis.
        "ref_level_db": 0,     // reference level db, theoretically 20db is the sound of air.

        // Silence trimming
        "do_trim_silence": true,// enable trimming of slience of audio as you load it. LJspeech (false), TWEB (false), Nancy (true)
        "trim_db": 60,          // threshold for timming silence. Set this according to your dataset.

        // MelSpectrogram parameters
        "num_mels": 80,         // size of the mel spec frame.
        "mel_fmin": 50.0,        // minimum freq level for mel-spec. ~50 for male and ~95 for female voices. Tune for dataset!!
        "mel_fmax": 7600.0,     // maximum freq level for mel-spec. Tune for dataset!!
        "spec_gain": 1.0,         // scaler value appplied after log transform of spectrogram.

        // Normalization parameters
        "signal_norm": true,    // normalize spec values. Mean-Var normalization if 'stats_path' is defined otherwise range normalization defined by the other params.
        "min_level_db": -100,   // lower bound for normalization
        "symmetric_norm": true, // move normalization to range [-1, 1]
        "max_norm": 4.0,        // scale normalization to range [-max_norm, max_norm] or [0, max_norm]
        "clip_norm": true,      // clip normalized values into the range.
	"stats_path": "/home/data1/peter/tts_data/indonesia_experiment/scale_stats.npy"
        //"stats_path": "/home/erogol/Data/LJSpeech-1.1/scale_stats.npy"    // DO NOT USE WITH MULTI_SPEAKER MODEL. scaler stats file computed by 'compute_statistics.py'. If it is defined, mean-std based notmalization is used and other normalization params are ignored
    },

    // DISTRIBUTED TRAINING
    // "distributed":{
    //     "backend": "nccl",
    //     "url": "tcp:\/\/localhost:54321"
    // },

    // MODEL PARAMETERS
    "use_pqmf": true,

    // LOSS PARAMETERS
    "use_stft_loss": true,
    "use_subband_stft_loss": false,  // USE ONLY WITH MULTIBAND MODELS
    "use_mse_gan_loss": true,
    "use_hinge_gan_loss": false,
    "use_feat_match_loss": false,  // use only with melgan discriminators

    // loss weights
    "stft_loss_weight": 0.5,
    "subband_stft_loss_weight": 0.5,
    "mse_G_loss_weight": 2.5,
    "hinge_G_loss_weight": 2.5,
    "feat_match_loss_weight": 25,

    // multiscale stft loss parameters
    "stft_loss_params": {
        "n_ffts": [1024, 2048, 512],
        "hop_lengths": [120, 240, 50],
        "win_lengths": [600, 1200, 240]
    },

    // subband multiscale stft loss parameters
    "subband_stft_loss_params":{
        "n_ffts": [384, 683, 171],
        "hop_lengths": [30, 60, 10],
        "win_lengths": [150, 300, 60]
    },

    "target_loss": "avg_G_loss",  // loss value to pick the best model to save after each epoch

    // DISCRIMINATOR
    "discriminator_model": "parallel_wavegan_discriminator",
    "discriminator_model_params":{
        "num_layers": 10
    },
    "steps_to_start_discriminator": 200000,      // steps required to start GAN trainining.1

    // GENERATOR
    "generator_model": "parallel_wavegan_generator",
    "generator_model_params": {
        "upsample_factors":[4, 4, 4, 4],
        "stacks": 3,
        "num_res_blocks": 30
    },

    // DATASET
    "data_path": "/home/data/peter/tts_data/indonesia_experience/wavs/",
    "feature_path": null,
    "seq_len": 25600,
    "pad_short": 2000,
    "conv_pad": 0,
    "use_noise_augment": false,
    "use_cache": true,

    "reinit_layers": [],    // give a list of layer names to restore from the given checkpoint. If not defined, it reloads all heuristically matching layers.

    // TRAINING
    "batch_size": 6,       // Batch size for training. Lower values than 32 might cause hard to learn attention. It is overwritten by 'gradual_training'.

    // VALIDATION
    "run_eval": true,
    "test_delay_epochs": 10,  //Until attention is aligned, testing only wastes computation time.
    "test_sentences_file": null,  // set a file to load sentences to be used for testing. If it is null then we use default english sentences.

    // OPTIMIZER
    "epochs": 10000,                // total number of epochs to train.
    "wd": 0.0,                // Weight decay weight.
    "gen_clip_grad": -1,      // Generator gradient clipping threshold. Apply gradient clipping if > 0
    "disc_clip_grad": -1,     // Discriminator gradient clipping threshold.
    "lr_scheduler_gen": "MultiStepLR",   // one of the schedulers from https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
    "lr_scheduler_gen_params": {
        "gamma": 0.5,
        "milestones": [100000, 200000, 300000, 400000, 500000, 600000]
    },
    "lr_scheduler_disc": "MultiStepLR",   // one of the schedulers from https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
    "lr_scheduler_disc_params": {
        "gamma": 0.5,
        "milestones": [100000, 200000, 300000, 400000, 500000, 600000]
    },
    "lr_gen": 1e-4,                  // Initial learning rate. If Noam decay is active, maximum learning rate.
    "lr_disc": 1e-4,

    // TENSORBOARD and LOGGING
    "print_step": 25,       // Number of steps to log traning on console.
    "print_eval": false,     // If True, it prints loss values for each step in eval run.
    "save_step": 25000,      // Number of training steps expected to plot training stats on TB and save model checkpoints.
    "checkpoint": true,     // If true, it saves checkpoints per "save_step"
    "tb_model_param_stats": false,     // true, plots param stats per layer on tensorboard. Might be memory consuming, but good for debugging.

    // DATA LOADING
    "num_loader_workers": 4,        // number of training data loader processes. Don't set it too big. 4-8 are good values.
    "num_val_loader_workers": 4,    // number of evaluation data loader processes.
    "eval_split_size": 10,

    // PATHS
    "output_path": "/home/data1/peter/tts_vocoder/TTS/mozilla_voice_tts/vocoder/pwgan_output/"
}


```

**Comment by erogol** [comment]
I am not sure what is wrong, I could not replicate the problem with my own PWGAN training.

**Comment by tsungruihon** [comment]
@erogol @george-roussos  

After setting the `stats_path` into `null`, the results is below. It seems that the learning processing is quite slow. The model could not learn the melspec well. The Eval melspec figure is quite blurred.

![Screenshot 2020-09-09 at 3 52 37 PM](https://user-images.githubusercontent.com/11624203/92570659-bef53f00-f2b4-11ea-8f92-9785bad67b45.png)


![Screenshot 2020-09-09 at 3 52 21 PM](https://user-images.githubusercontent.com/11624203/92570646-bac92180-f2b4-11ea-9b2a-5bbdff0ede8f.png)

**Comment by george-roussos** [comment]
That's weird. What can you tell us about the dataset? Do you have any samples of it?

**Comment by tsungruihon** [comment]
@george-roussos that's an Indonesia datasets. I could provide few samples. Thanks for helping. I am not sure whether the weird results come from the `AUDIO PARAMETERS` setting in config files.

[Indonesian_Samples.zip](https://github.com/mozilla/TTS/files/5193619/Indonesian_Samples.zip)

**Comment by george-roussos** [comment]
At 1M steps, the PWGAN should be pretty good, if not very. At 100K steps you should be at least able to hear the voice. Maybe you can try this config.

    {
    "github_branch":"* dev",
    "run_name": "pwgan",
    "run_description": "parallel-wavegan training",

    // AUDIO PARAMETERS
    "audio":{
        "fft_size": 1024,         // number of stft frequency levels. Size of the linear spectogram frame.
        "win_length": 1024,      // stft window length in ms.
        "hop_length": 256,       // stft window hop-lengh in ms.
        "frame_length_ms": null, // stft window length in ms.If null, 'win_length' is used.
        "frame_shift_ms": null,  // stft window hop-lengh in ms. If null, 'hop_length' is used.

        // Audio processing parameters
        "sample_rate": 22050,   // DATASET-RELATED: wav sample-rate. If different than the original data, it is resampled.
        "preemphasis": 0.98,     // pre-emphasis to reduce spec noise and make it more structured. If 0.0, no -pre-emphasis.
        "ref_level_db": 0,     // reference level db, theoretically 20db is the sound of air.

        // Silence trimming
        "do_trim_silence": true, // enable trimming of slience of audio as you load it. LJspeech (false), TWEB (false), Nancy (true)
        "trim_db": 50,          // threshold for timming silence. Set this according to your dataset.

        // MelSpectrogram parameters
        "num_mels": 80,         // size of the mel spec frame.
        "mel_fmin": 50.0,        // minimum freq level for mel-spec. ~50 for male and ~95 for female voices. Tune for dataset!!
        "mel_fmax": 7500.0,     // maximum freq level for mel-spec. Tune for dataset!!
        "spec_gain": 20.0,         // scaler value appplied after log transform of spectrogram.

        // Normalization parameters
        "signal_norm": true,    // normalize spec values. Mean-Var normalization if 'stats_path' is defined otherwise range normalization defined by the other params.
        "min_level_db": -100,   // lower bound for normalization
        "symmetric_norm": true, // move normalization to range [-1, 1]
        "max_norm": 4.0,        // scale normalization to range [-max_norm, max_norm] or [0, max_norm]
        "clip_norm": true,      // clip normalized values into the range.
        "stats_path": null //"/home/georgios.roussos/MI_shortened_sils/scale_stats.npy"    // DO NOT USE WITH MULTI_SPEAKER MODEL. scaler stats file computed by 'compute_statistics.py'. If it is defined, mean-std based notmalization is used and other normalization params are ignored
    },

    // DISTRIBUTED TRAINING
//     "distributed":{
//         "backend": "nccl",
//        "url": "tcp:\/\/localhost:54321"
//     },

    // MODEL PARAMETERS
    "use_pqmf": true,

    // LOSS PARAMETERS
    "use_stft_loss": true,
    "use_subband_stft_loss": false,  // USE ONLY WITH MULTIBAND MODELS
    "use_mse_gan_loss": true,
    "use_hinge_gan_loss": false,
    "use_feat_match_loss": false,  // use only with melgan discriminators

    // loss weights
    "stft_loss_weight": 0.5,
    "subband_stft_loss_weight": 0.5,
    "mse_G_loss_weight": 2.5,
    "hinge_G_loss_weight": 2.5,
    "feat_match_loss_weight": 25,

    // multiscale stft loss parameters
    "stft_loss_params": {
        "n_ffts": [1024, 2048, 512],
        "hop_lengths": [120, 240, 50],
        "win_lengths": [600, 1200, 240]
    },

    // subband multiscale stft loss parameters
    "subband_stft_loss_params":{
        "n_ffts": [384, 683, 171],
        "hop_lengths": [30, 60, 10],
        "win_lengths": [150, 300, 60]
    },

    "target_loss": "avg_G_loss",  // loss value to pick the best model to save after each epoch

    // DISCRIMINATOR
    "discriminator_model": "parallel_wavegan_discriminator",
    "discriminator_model_params":{
        "num_layers": 10
    },
    "steps_to_start_discriminator": 200000,      // steps required to start GAN trainining.1

    // GENERATOR
    "generator_model": "parallel_wavegan_generator",
    "generator_model_params": {
        "upsample_factors":[4, 4, 4],
        "stacks": 3,
        "num_res_blocks": 30
    },

    // DATASET
    "data_path": "/home/dataset/",
    "feature_path": null,
    "seq_len": 25600,
    "pad_short": 2000,
    "conv_pad": 0,
    "use_noise_augment": false,
    "use_cache": true,

    "reinit_layers": [],    // give a list of layer names to restore from the given checkpoint. If not defined, it reloads all heuristically matching layers.

    // TRAINING
    "batch_size": 6,       // Batch size for training. Lower values than 32 might cause hard to learn attention. It is overwritten by 'gradual_training'.
    "sampling_rates": [22050],

    // VALIDATION
    "run_eval": true,
    "test_delay_epochs": 6,  //Until attention is aligned, testing only wastes computation time.
    "test_sentences_file": null,  // set a file to load sentences to be used for testing. If it is null then we use default english sentences.

    // OPTIMIZER
    "epochs": 10000,                // total number of epochs to train.
    "wd": 0.0,                // Weight decay weight.
    "gen_clip_grad": -1,      // Generator gradient clipping threshold. Apply gradient clipping if > 0
    "disc_clip_grad": -1,     // Discriminator gradient clipping threshold.
    "lr_scheduler_gen": "MultiStepLR",   // one of the schedulers from https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
    "lr_scheduler_gen_params": {
        "gamma": 0.5,
        "milestones": [100000, 200000, 300000, 400000, 500000, 600000]
    },
    "lr_scheduler_disc": "MultiStepLR",   // one of the schedulers from https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
    "lr_scheduler_disc_params": {
        "gamma": 0.5,
        "milestones": [100000, 200000, 300000, 400000, 500000, 600000]
    },
    "lr_gen": 1e-4,                  // Initial learning rate. If Noam decay is active, maximum learning rate.
    "lr_disc": 1e-4,

    // TENSORBOARD and LOGGING
    "print_step": 25,       // Number of steps to log traning on console.
    "print_eval": false,     // If True, it prints loss values for each step in eval run.
    "save_step": 5000,      // Number of training steps expected to plot training stats on TB and save model checkpoints.
    "checkpoint": true,     // If true, it saves checkpoints per "save_step"
    "tb_model_param_stats": false,     // true, plots param stats per layer on tensorboard. Might be memory consuming, but good for debugging.

    // DATA LOADING
    "num_loader_workers": 8,        // number of training data loader processes. Don't set it too big. 4-8 are good values.
    "num_val_loader_workers": 8,    // number of evaluation data loader processes.
    "eval_split_size": 10,

    // PATHS
    "output_path": "/home/dataset/"
    }

**Comment by tsungruihon** [comment]
@george-roussos thanks George. So you mean whatever add `stats_path` or not, would not affect huge effect on the result, at least would not generate weird result ?

**Comment by george-roussos** [comment]
The sound is very good, so there is something else that is wrong. Are all files 22050 mono?

The stats file is about normalization relative to the dataset values. So if you do not use it, it should still be fine. You can try the config I pasted.

**Comment by tsungruihon** [comment]
@george-roussos really thanks George. I will try as you said. And will let you know the results as soon as possible.

**Comment by tsungruihon** [comment]
@george-roussos  It's that normal that the `avg_G_adv_loss` is a horizon line ?

![Screenshot 2020-09-10 at 2 06 22 PM](https://user-images.githubusercontent.com/11624203/92687842-d5f86780-f36e-11ea-9578-f6f715617243.png)
![Screenshot 2020-09-10 at 2 08 20 PM](https://user-images.githubusercontent.com/11624203/92687986-1821a900-f36f-11ea-9bb9-4576113814ad.png)

**Comment by george-roussos** [comment]
It is, yes. It will change when the discriminator kicks in. Looks much healthier now. Hope it works better. 😀

**Comment by tsungruihon** [comment]
@george-roussos Really thanks George. I will keep you update.

**Comment by tsungruihon** [comment]
@george-roussos Hey George, here's the update. The sound seems trembling. And may i ask that how could i judge whether the loss is acceptable ? 


[532k_vocoder_evalAudio.zip](https://github.com/mozilla/TTS/files/5223983/532k_vocoder_evalAudio.zip)
![Screenshot 2020-09-15 at 5 37 52 PM](https://user-images.githubusercontent.com/11624203/93194337-8d7be800-f77a-11ea-8fbb-7f113b81473f.png)
![Screenshot 2020-09-15 at 5 38 01 PM](https://user-images.githubusercontent.com/11624203/93194354-92409c00-f77a-11ea-94f5-80084b23f41c.png)

**Comment by erogol** [comment]
``` how could i judge whether the loss is acceptable ?```

listening the results is the best approach and testing checkpoints on real examples.

**Comment by tsungruihon** [comment]
@erogol thanks erogol. How do you think my evalAudio example ?

**Comment by tsungruihon** [comment]
@erogol  @george-roussos I tried to combine `TTS` and `PWGAN`, but the results seems strange. Here's my `TTS`'s `config.json`.

```
{
"github_branch":"* master",
"restore_path":"tts/taco_output/indonesian-test1-September-09-2020_10+12AM-daf9c7a/checkpoint_200000.pth.tar",
    "model": "Tacotron2",
    "run_name": "indonesian-test1",
    "run_description": "tacotron2 with ddc and batch-normalization",

    // AUDIO PARAMETERS
    "audio":{
        // stft parameters
        "fft_size": 1024,         // number of stft frequency levels. Size of the linear spectogram frame.
        "win_length": 1024,      // stft window length in ms.
        "hop_length": 256,       // stft window hop-lengh in ms.
        "frame_length_ms": null, // stft window length in ms.If null, 'win_length' is used.
        "frame_shift_ms": null,  // stft window hop-lengh in ms. If null, 'hop_length' is used.

        // Audio processing parameters
        "sample_rate": 22050,   // DATASET-RELATED: wav sample-rate.
        "preemphasis": 0.98,     // pre-emphasis to reduce spec noise and make it more structured. If 0.0, no -pre-emphasis.
        "ref_level_db": 20,     // reference level db, theoretically 20db is the sound of air.

        // Silence trimming
        "do_trim_silence": true,// enable trimming of slience of audio as you load it. LJspeech (true), TWEB (false), Nancy (true)
        "trim_db": 60,          // threshold for timming silence. Set this according to your dataset.

        // Griffin-Lim
        "power": 1.5,           // value to sharpen wav signals after GL algorithm.
        "griffin_lim_iters": 60,// #griffin-lim iterations. 30-60 is a good range. Larger the value, slower the generation.

        // MelSpectrogram parameters
        "num_mels": 80,         // size of the mel spec frame.
        "mel_fmin": 50.0,        // minimum freq level for mel-spec. ~50 for male and ~95 for female voices. Tune for dataset!!
        "mel_fmax": 7500.0,     // maximum freq level for mel-spec. Tune for dataset!!
        "spec_gain": 20.0,

        // Normalization parameters
        "signal_norm": true,    // normalize spec values. Mean-Var normalization if 'stats_path' is defined otherwise range normalization defined by the other params.
        "min_level_db": -100,   // lower bound for normalization
        "symmetric_norm": true, // move normalization to range [-1, 1]
        "max_norm": 4.0,        // scale normalization to range [-max_norm, max_norm] or [0, max_norm]
        "clip_norm": true,      // clip normalized values into the range.
        "stats_path": null    // DO NOT USE WITH MULTI_SPEAKER MODEL. scaler stats file computed by 'compute_statistics.py'. If it is defined, mean-std based notmalization is used and other normalization params are ignored
    },

    // VOCABULARY PARAMETERS
    // if custom character set is not defined,
    // default set in symbols.py is used
    // "characters":{
    //     "pad": "_",
    //     "eos": "~",
    //     "bos": "^",
    //     "characters": "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!'(),-.:;? ",
    //     "punctuations":"!'(),-.:;? ",
    //     "phonemes":"iyɨʉɯuɪʏʊeøɘəɵɤoɛœɜɞʌɔæɐaɶɑɒᵻʘɓǀɗǃʄǂɠǁʛpbtdʈɖcɟkɡqɢʔɴŋɲɳnɱmʙrʀⱱɾɽɸβfvθðszʃʒʂʐçʝxɣχʁħʕhɦɬɮʋɹɻjɰlɭʎʟˈˌːˑʍwɥʜʢʡɕʑɺɧɚ˞ɫ"
    // },

    // DISTRIBUTED TRAINING
    "distributed":{
        "backend": "nccl",
        "url": "tcp:\/\/localhost:54321"
    },

    "reinit_layers": [],    // give a list of layer names to restore from the given checkpoint. If not defined, it reloads all heuristically matching layers.

    // TRAINING
    "batch_size": 16,       // Batch size for training. Lower values than 32 might cause hard to learn attention. It is overwritten by 'gradual_training'.
    "eval_batch_size":16,
    "r": 7,                 // Number of decoder frames to predict per iteration. Set the initial values if gradual training is enabled.
    "gradual_training": [[0, 7, 16], [1, 5, 16], [50000, 3, 16], [130000, 2, 16], [290000, 1, 16]], //set gradual training steps [first_step, r, batch_size]. If it is null, gradual training is disabled. For Tacotron, you might need to reduce the 'batch_size' as you proceeed.
    "loss_masking": true,         // enable / disable loss masking against the sequence padding.
    "ga_alpha": 10.0,        // weight for guided attention loss. If > 0, guided attention is enabled.
    "apex_amp_level": null, // level of optimization with NVIDIA's apex feature for automatic mixed FP16/FP32 precision (AMP), NOTE: currently only O1 is supported, and use "O1" to activate.

    // VALIDATION
    "run_eval": true,
    "test_delay_epochs": 10,  //Until attention is aligned, testing only wastes computation time.
    "test_sentences_file": null,  // set a file to load sentences to be used for testing. If it is null then we use default english sentences.

    // OPTIMIZER
    "noam_schedule": false,        // use noam warmup and lr schedule.
    "grad_clip": 1.0,              // upper limit for gradients for clipping.
    "epochs": 100000,                // total number of epochs to train.
    "lr": 0.0001,                  // Initial learning rate. If Noam decay is active, maximum learning rate.
    "wd": 0.000001,                // Weight decay weight.
    "warmup_steps": 4000,          // Noam decay steps to increase the learning rate from 0 to "lr"
    "seq_len_norm": false,         // Normalize eash sample loss with its length to alleviate imbalanced datasets. Use it if your dataset is small or has skewed distribution of sequence lengths.

    // TACOTRON PRENET
    "memory_size": -1,             // ONLY TACOTRON - size of the memory queue used fro storing last decoder predictions for auto-regression. If < 0, memory queue is disabled and decoder only uses the last prediction frame.
    "prenet_type": "bn",           // "original" or "bn".
    "prenet_dropout": false,       // enable/disable dropout at prenet.

    // TACOTRON ATTENTION
    "attention_type": "original",  // 'original' or 'graves'
    "attention_heads": 4,          // number of attention heads (only for 'graves')
    "attention_norm": "sigmoid",   // softmax or sigmoid.
    "windowing": false,            // Enables attention windowing. Used only in eval mode.
    "use_forward_attn": false,     // if it uses forward attention. In general, it aligns faster.
    "forward_attn_mask": false,    // Additional masking forcing monotonicity only in eval mode.
    "transition_agent": false,     // enable/disable transition agent of forward attention.
    "location_attn": true,         // enable_disable location sensitive attention. It is enabled for TACOTRON by default.
    "bidirectional_decoder": false,  // use https://arxiv.org/abs/1907.09006. Use it, if attention does not work well with your dataset.
    "double_decoder_consistency": false,  // use DDC explained here https://erogol.com/solving-attention-problems-of-tts-models-with-double-decoder-consistency-draft/
    "ddc_r": 7,                           // reduction rate for coarse decoder.

    // STOPNET
    "stopnet": true,               // Train stopnet predicting the end of synthesis.
    "separate_stopnet": true,      // Train stopnet seperately if 'stopnet==true'. It prevents stopnet loss to influence the rest of the model. It causes a better model, but it trains SLOWER.

    // TENSORBOARD and LOGGING
    "print_step": 25,       // Number of steps to log training on console.
    "tb_plot_step": 100,    // Number of steps to plot TB training figures.
    "print_eval": false,     // If True, it prints intermediate loss values in evalulation.
    "save_step": 10000,      // Number of training steps expected to save traninpg stats and checkpoints.
    "checkpoint": true,     // If true, it saves checkpoints per "save_step"
    "tb_model_param_stats": false,     // true, plots param stats per layer on tensorboard. Might be memory consuming, but good for debugging.

    // DATA LOADING
    "text_cleaner": "english_cleaners",
    "enable_eos_bos_chars": false, // enable/disable beginning of sentence and end of sentence chars.
    "num_loader_workers": 8,        // number of training data loader processes. Don't set it too big. 4-8 are good values.
    "num_val_loader_workers": 8,    // number of evaluation data loader processes.
    "batch_group_size": 0,  //Number of batches to shuffle after bucketing.
    "min_seq_len": 6,       // DATASET-RELATED: minimum text length to use in training
    "max_seq_len": 600,     // DATASET-RELATED: maximum text length

    // PATHS
    "output_path": "/data2/data/peter/TTS_test_2/TTS/mozilla_voice_tts/tts/taco_output/",

    // PHONEMES
    "phoneme_cache_path": "../../Mozilla-TTS/vctk-test/",  // phoneme computation is slow, therefore, it caches results in the given folder.
    "use_phonemes": false,           // use phonemes instead of raw characters. It is suggested for better pronounciation.
    "phoneme_language": "en-us",     // depending on your target language, pick one from  https://github.com/bootphon/phonemizer#languages

    // MULTI-SPEAKER and GST
    "use_speaker_embedding": false,      // use speaker embedding to enable multi-speaker learning.
    "use_external_speaker_embedding_file": false, // if true, forces the model to use external embedding per sample instead of nn.embeddings, that is, it supports external embeddings such as those used at: https://arxiv.org/abs /1806.04558
    "external_speaker_embedding_file": "../../speakers-vctk-en.json", // if not null and use_external_speaker_embedding_file is true, it is used to load a specific embedding file and thus uses these embeddings instead of nn.embeddings, that is, it supports external embeddings such as those used at: https://arxiv.org/abs /1806.04558
    "use_gst": false,       			    // use global style tokens
    "gst":	{			                // gst parameter if gst is enabled
        "gst_style_input": null,        // Condition the style input either on a
                                        // -> wave file [path to wave] or
                                        // -> dictionary using the style tokens {'token1': 'value', 'token2': 'value'} example {"0": 0.15, "1": 0.15, "5": -0.15}
                                        // with the dictionary being len(dict) <= len(gst_style_tokens).
        "gst_embedding_dim": 512,
        "gst_num_heads": 4,
        "gst_style_tokens": 10
	},

    // DATASETS
    "datasets":   // List of datasets. They all merged and they get different speaker_ids.
        [
            {
                "name": "ljspeech",
                "path": "/data2/data/peter/tts_data/indonesia_experience/",
                //"meta_file_train": ["p225", "p234", "p238", "p245", "p248", "p261", "p294", "p302", "p326", "p335", "p347"], // for vtck if list, ignore speakers id in list for train, its useful for test cloning with new speakers
                "meta_file_train": "train_data_v1.csv",
                "meta_file_val": "val_data_v1.csv"
            }
        ]
}


```

Here's my `TTS` tensorboard.

![Screenshot 2020-09-24 at 6 20 04 PM](https://user-images.githubusercontent.com/11624203/94132941-93687c00-fe92-11ea-80eb-cf2500fa5700.png)
 

[PWGAN_sample.wav.zip](https://github.com/mozilla/TTS/files/5275191/PWGAN_sample.wav.zip)

**Comment by tsungruihon** [comment]
@erogol @george-roussos hello my friends, here's the update. Hope you would listen the sample and share some advices. Thanks.

[TTS_340k_PWGAN_957k.wav.zip](https://github.com/mozilla/TTS/files/5358772/TTS_340k_PWGAN_957k.wav.zip)

**Comment by george-roussos** [comment]
Hi, can you post the TTS and PWGAN configs? This sounds okay, but also it depends on the quality of your dataset, how you trained the TTS so the spectrogram quality affects PWGAN results etc.

**Comment by tsungruihon** [comment]
@george-roussos Hi george, thanks for reply. Here's the TTS and PWGAN config, which i actually followed the TTS pretrained TTS and PWGAN config file shown on notebooks.  

[tts_vocoder_config.zip](https://github.com/mozilla/TTS/files/5363791/tts_vocoder_config.zip)

Really appreciate for your help.

**Comment by tsungruihon** [comment]
@george-roussos @erogol  Hey my friends, i would like to update the experiment process. Now i am trying to train from GTA which from tacotron2's output with the same config above. Here's the tensorboard. To my surprise, the training process is much slower than the process which trained from original mels. And also the `avg_G_gen_loss` behaves much more struggle.

![Screenshot 2020-10-16 at 9 10 23 AM](https://user-images.githubusercontent.com/11624203/96201679-ca144c80-0f8f-11eb-822c-25060a98467d.png)

**Comment by tsungruihon** [comment]
@erogol @george-roussos  Here's the tensorboard audio sample. Please check it. Thanks a lot.

[Step 148014-EvalAudio_Sample.wav.zip](https://github.com/mozilla/TTS/files/5390324/Step.148014-EvalAudio_Sample.wav.zip)

**Comment by SanjaESC** [comment]
> @george-roussos Hi george, thanks for reply. Here's the TTS and PWGAN config, which i actually followed the TTS pretrained TTS and PWGAN config file shown on notebooks.
> 
> [tts_vocoder_config.zip](https://github.com/mozilla/TTS/files/5363791/tts_vocoder_config.zip)
> 
> Really appreciate for your help.

Is there a reason, that you only start the discriminator training at 600k steps?

**Comment by tsungruihon** [comment]
@SanjaESC Yes, it might be. I was intent to lower the `avg_G_gen_loss `, but now it seems that it is almost converged.

**Comment by tsungruihon** [comment]
@erogol @george-roussos Here's the regular update process.  It seems that training PWGAN from GTA is easier to come with converge than training from original mels. Now the `avg_G_gen_loss` almost stays at 0.6052. Look forward to continue lower it in the follow training process.

![Screenshot 2020-10-19 at 11 20 25 AM](https://user-images.githubusercontent.com/11624203/96397888-17492600-11fd-11eb-891b-d643fb9c68d6.png)

**Comment by george-roussos** [comment]
Hi, how does it sound?

**Comment by tsungruihon** [comment]
@george-roussos  hi george, morning. Here's the eval audio in tensorboard. Please check. [step 313622-individualAudio.wav.zip](https://github.com/mozilla/TTS/files/5405667/step.313622-individualAudio.wav.zip)

**Comment by george-roussos** [comment]
I still think the samples from clean spectrogram sounds a bit better. If you find it doesn't work eventually, try introducing the D from 100K steps and set the D's LR to 0.00005. You can also try mean-var in both TTS and GAN.

**Comment by tsungruihon** [comment]
Wow! Thanks George advices. I will try and let you know. Thanks again.

George <notifications@github.com> 于2020年10月20日周二 下午3:00写道：

**Comment by george-roussos** [comment]
@tsungruihon how did you extract ground truth? I tried using the notebook ExtractTTS spectrograms, but I get 

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-26-22e1b9432cf3> in <module>
     26 
     27         mask = sequence_mask(text_lengths)
---> 28         mel_outputs, postnet_outputs, alignments, stop_tokens = model.forward(text_input, text_lengths, mel_input)
     29 
     30         # compute loss

ValueError: too many values to unpack (expected 4)`

**Comment by george-roussos** [comment]
@tsungruihon can you tell us how you extracted ground truth alignments and if you got any errors? I extracted them using TTSpectrogram, but when starting training, I get 

```
assert mel.shape[-1] * self.hop_len == audio.shape[-1], f' [!] {mel.shape[-1] * self.hop_len} vs {audio.shape[-1]}
AssertionError:  [!] 104960 vs 104750
```

**Comment by tsungruihon** [comment]
@george-roussos sorry for the late update.  I just use the `ExtractTTSpectrogram` notebook in `notebooks` folder. I didn't change anything and just ran the code. By the way, the tacotron model i used which is trained from the latest branch. I wonder whether the `inference` code version matter.

The problem `ValueError: too many values to unpack (expected 4)` i have encountered before is because i found that the model forward function is changed, so i have to modify the outputs. 

The problem `ValueError: empty range for randrange() (0,0, 0)` is which i haven't encounter yet. Maybe erogol @erogol could give us a hint ?
