### ISSUE TITLE
Set speaker to male in Tacotron-iter-185K pretrained model

### ISSUE THREAD

**Issue by angoodkind** [mozilla/TTS#509]
I am using Mozilla TTS to generate short audio files. I followed the tutorial [here](https://blog.rasa.com/how-to-build-a-voice-assistant-with-open-source-rasa-and-mozilla-tools/), but just #4 about implementing TTS. 

The tutorial instructs you to download the `config.json` and `best_model.pth.tar`files from the Google Drive directory.

Is this pretrained model only a female voice, or is there somewhere to change that? Alternatively, is there another pretrained model with a male voice?

**Comment by nmstoker** [comment]
I guess you just stumbled on the other tutorial but it would've been better to look at the wiki and repo details here first

As this looks more like a discussion point than a bug, probably best you raise it on the [Discourse channel here](https://discourse.mozilla.org/c/tts/) although if you look over the wiki & repo you'll likely figure out the answer yourself and save someone the time of helping you :slightly_smiling_face:

**Comment by angoodkind** [comment]
Do you have any suggestions about exactly where on the wiki or repo to look? I had tried reading them over, but I guess I read the wrong parts.

**Comment by erogol** [comment]
There is no way to change the gender unfortunately.
