### ISSUE TITLE
Sudden error

### ISSUE THREAD

**Issue by Crazyjoedevola** [mozilla/TTS#510]
Traceback (most recent call last):
  File "/content/TTS/TTS/bin/train_tts.py", line 705, in <module>
    main(args)
  File "/content/TTS/TTS/bin/train_tts.py", line 555, in main
    checkpoint = torch.load(args.restore_path, map_location='cpu')
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 584, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 842, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'mozilla_voice_tts'

**Comment by erogol** [comment]
you need to reinstall the module as i changed the name from mozilla_voice_tts to old TTS after changed plans of Mozilla on the speech tech.

**Comment by Crazyjoedevola** [comment]
I had problems using the already trained models with the new repository. It seems they are also looking for the mozilla_voice_tts module. Do I have to retrain all models in order to use the latest version?

**Comment by erogol** [comment]
I am able to load any pre-trained model. It might be something about your setup. If you share the model file, I can also try.

**Comment by erogol** [comment]
I was able to reproduce the error. Now I tried to solve with the recent commit. As you use ```load_checkpoint()``` it should handle the mismatch.
