### ISSUE TITLE
setup.py and requirements.txt not working

### ISSUE THREAD

**Issue by taran9873** [mozilla/TTS#514]
I have python 3.8.5 installed and I tried running 
`python setup.py develop`
during running I got error

> AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'
and then another error
`During handling of the above exception, another exception occurred:

`Traceback (most recent call last):
  File "setup.py", line 89, in <module>
    setup(
  File "C:\Users\tarandeep singh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\tarandeep singh\AppData\Local\Programs\Python\Python38-32\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\tarandeep singh\AppData\Local\Programs\Python\Python38-32\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\tarandeep singh\AppData\Local\Programs\Python\Python38-32\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 55, in run
    setuptools.command.develop.develop.run(self)
  File "C:\Users\tarandeep singh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\develop.py", line 38, in run
    self.install_for_development()
`

i also tried `pip install -r requirements.txt`

`$ pip install -r requirements.txt
ERROR: Could not find a version that satisfies the requirement torch>=1.5 (from -r requirements.txt (line 1)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=1.5 (from -r requirements.txt (line 1))
`

**Comment by Dumpling97** [comment]
The `pip install -r requirements.txt` runs normal for me but I still get the same error.

**Comment by karkirowle** [comment]
In the https://gist.github.com/erogol/97516ad65b44dbddb8cd694953187c5b, somebody already solved this problem by

    pip install -r requirements.txt  # error from Tensorflow about numpy version
    pip uninstall numpy
    pip install numpy==1.18.5
    pip install -r requirements.txt  # now it works
    python setup.py install  # it works!`

Pip doesn't really check dependencies in the same way as conda, so the most definite way to avoid this problem would be using a conda environment, which is recommended in the install. Most likely TF needs 1.18.5 and another package states a later NumPy version as a dependency, which results in a reinstall.

**Comment by lypanov** [comment]
No anaconda available on aarch64 alas so not very useful for me. Shame it can't be used out of the box without serious dependencies.

**Comment by erogol** [comment]
This is not an conda etc. issue. Probably pytorch and TF were not releasing for Python 3.8.5 before. Now it should be fixed. 

And also please read the README where we indicate the supported platforms and python versions. We were not supporting Python 3.8 at the time.
