### ISSUE TITLE
Python 3.7 - Training on custom data does not load wavs

### ISSUE THREAD

**Issue by Stanley80** [mozilla/TTS#515]
Training on my own data returns

 > Using CUDA:  False
 > Number of GPUs:  0
 > Git Hash: 540d811
 > Experiment folder: /Users/davidecangelosi/Desktop/workspace/venvMoz/TTS/davide_tests/output_train/Davide-September-15-2020_12+53PM-540d811
 > Setting up Audio Processor...
 | > sample_rate:44100
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:1.0
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:50.0
 | > mel_fmax:8000.0
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > stats_path:None
 | > hop_length:256
 | > win_length:1024
 > Using model: Tacotron2

 > Model has 57981844 parameters

 > EPOCH: 0/1000

 > Number of output frames: 7

 > DataLoader initialization
 | > Use phonemes: False
 | > Number of instances : 398
 | > Max length sequence: 73
 | > Min length sequence: 2
 | > Avg length sequence: 27.168341708542712
 | > Num. instances discarded by max-min (max=153, min=6) seq limits: 17
 | > Batch group size: 0.

 > TRAINING (2020-09-15 12:53:07) 
 ! Run is removed from /Users/davidecangelosi/Desktop/workspace/venvMoz/TTS/davide_tests/output_train/Davide-September-15-2020_12+53PM-540d811
Traceback (most recent call last):
  File "TTS/bin/train.py", line 705, in <module>
    main(args)
  File "TTS/bin/train.py", line 617, in main
    global_step, epoch, amp, speaker_mapping)
  File "TTS/bin/train.py", line 143, in train
    for num_iter, data in enumerate(data_loader):
  File "/Users/davidecangelosi/Desktop/workspace/venvMoz/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/Users/davidecangelosi/Desktop/workspace/venvMoz/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 971, in _next_data
    return self._process_data(data)
  File "/Users/davidecangelosi/Desktop/workspace/venvMoz/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/Users/davidecangelosi/Desktop/workspace/venvMoz/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/Users/davidecangelosi/Desktop/workspace/venvMoz/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/Users/davidecangelosi/Desktop/workspace/venvMoz/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/davidecangelosi/Desktop/workspace/venvMoz/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/davidecangelosi/Desktop/workspace/venvMoz/TTS/TTS/tts/datasets/TTSDataset.py", line 172, in __getitem__
    return self.load_data(idx)
  File "/Users/davidecangelosi/Desktop/workspace/venvMoz/TTS/TTS/tts/datasets/TTSDataset.py", line 117, in load_data
    wav = np.asarray(self.load_wav(wav_file), dtype=np.float32)
  File "/Users/davidecangelosi/Desktop/workspace/venvMoz/TTS/TTS/tts/datasets/TTSDataset.py", line 75, in load_wav
    audio = self.ap.load_wav(filename)
  File "/Users/davidecangelosi/Desktop/workspace/venvMoz/TTS/TTS/utils/audio.py", line 324, in load_wav
    x, sr = sf.read(filename)
  File "/Users/davidecangelosi/Desktop/workspace/venvMoz/lib/python3.7/site-packages/soundfile.py", line 373, in read
    subtype, endian, format, closefd) as f:
  File "/Users/davidecangelosi/Desktop/workspace/venvMoz/lib/python3.7/site-packages/soundfile.py", line 740, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/Users/davidecangelosi/Desktop/workspace/venvMoz/lib/python3.7/site-packages/soundfile.py", line 1265, in _open
    "Error opening {0!r}: ".format(self.name))
  File "/Users/davidecangelosi/Desktop/workspace/venvMoz/lib/python3.7/site-packages/soundfile.py", line 1455, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening '/Users/davidecangelosi/Desktop/workspace/venvMoz/TTS/davide_tests/data/davide/wavs/\ufeff1.wav': System error.

This is my config

{
    "model": "Tacotron2",
    "run_name": "Davide",
    "run_description": "tacotron2 with ddc and batch-normalization",

    // AUDIO PARAMETERS
    "audio":{
        // stft parameters
        "fft_size": 1024,         // number of stft frequency levels. Size of the linear spectogram frame.
        "win_length": 1024,      // stft window length in ms.
        "hop_length": 256,       // stft window hop-lengh in ms.
        "frame_length_ms": null, // stft window length in ms.If null, 'win_length' is used.
        "frame_shift_ms": null,  // stft window hop-lengh in ms. If null, 'hop_length' is used.

        // Audio processing parameters
        "sample_rate": 44100,   // DATASET-RELATED: wav sample-rate.
        "preemphasis": 1.0,     // pre-emphasis to reduce spec noise and make it more structured. If 0.0, no -pre-emphasis.
        "ref_level_db": 20,     // reference level db, theoretically 20db is the sound of air.

        // Silence trimming
        "do_trim_silence": true,// enable trimming of slience of audio as you load it. LJspeech (true), TWEB (false), Nancy (true)
        "trim_db": 60,          // threshold for timming silence. Set this according to your dataset.

        // Griffin-Lim
        "power": 1.5,           // value to sharpen wav signals after GL algorithm.
        "griffin_lim_iters": 60,// #griffin-lim iterations. 30-60 is a good range. Larger the value, slower the generation.

        // MelSpectrogram parameters
        "num_mels": 80,         // size of the mel spec frame.
        "mel_fmin": 50.0,        // minimum freq level for mel-spec. ~50 for male and ~95 for female voices. Tune for dataset!!
        "mel_fmax": 8000.0,     // maximum freq level for mel-spec. Tune for dataset!!
        "spec_gain": 20.0,

        // Normalization parameters
        "signal_norm": true,    // normalize spec values. Mean-Var normalization if 'stats_path' is defined otherwise range normalization defined by the other params.
        "min_level_db": -100,   // lower bound for normalization
        "symmetric_norm": true, // move normalization to range [-1, 1]
        "max_norm": 4.0,        // scale normalization to range [-max_norm, max_norm] or [0, max_norm]
        "clip_norm": true,      // clip normalized values into the range.
        "stats_path": null    // DO NOT USE WITH MULTI_SPEAKER MODEL. scaler stats file computed by 'compute_statistics.py'. If it is defined, mean-std based notmalization is used and other normalization params are ignored
    },

    // VOCABULARY PARAMETERS
    // if custom character set is not defined,
    // default set in symbols.py is used
    // "characters":{
    //     "pad": "_",
    //     "eos": "~",
    //     "bos": "^",
    //     "characters": "ːʒʧʦʃɲʎʤʣABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!'(),-.:;? ",
    //     "punctuations":"!'(),-.:;? ",
    //     "phonemes":"iyɨʉɯuɪʏʊeøɘəɵɤoɛœɜɞʌɔæɐaɶɑɒᵻʘɓǀɗǃʄǂɠǁʛpbtdʈɖcɟkɡqɢʔɴŋɲɳnɱmʙrʀⱱɾɽɸβfvθðszʃʒʂʐçʝxɣχʁħʕhɦɬɮʋɹɻjɰlɭʎʟˈˌːˑʍwɥʜʢʡɕʑɺɧɚ˞ɫ"
    // },

    // DISTRIBUTED TRAINING
    "distributed":{
        "backend": "nccl",
        "url": "tcp:\/\/localhost:54321"
    },

    "reinit_layers": [],    // give a list of layer names to restore from the given checkpoint. If not defined, it reloads all heuristically matching layers.

    // TRAINING
    "batch_size": 32,       // Batch size for training. Lower values than 32 might cause hard to learn attention. It is overwritten by 'gradual_training'.
    "eval_batch_size":16,
    "r": 7,                 // Number of decoder frames to predict per iteration. Set the initial values if gradual training is enabled.
    "gradual_training": [[0, 7, 64], [1, 5, 64], [500, 3, 32], [1300, 2, 32], [2900, 1, 32]], //set gradual training steps [first_step, r, batch_size]. If it is null, gradual training is disabled. For Tacotron, you might need to reduce the 'batch_size' as you proceeed.
    "loss_masking": true,         // enable / disable loss masking against the sequence padding.
    "ga_alpha": 10.0,        // weight for guided attention loss. If > 0, guided attention is enabled.
    "apex_amp_level": null, // level of optimization with NVIDIA's apex feature for automatic mixed FP16/FP32 precision (AMP), NOTE: currently only O1 is supported, and use "O1" to activate.

    // VALIDATION
    "run_eval": true,
    "test_delay_epochs": 10,  //Until attention is aligned, testing only wastes computation time.
    "test_sentences_file": null,  // set a file to load sentences to be used for testing. If it is null then we use default english sentences.

    // OPTIMIZER
    "noam_schedule": false,        // use noam warmup and lr schedule.
    "grad_clip": 1.0,              // upper limit for gradients for clipping.
    "epochs": 1000,                // total number of epochs to train.
    "lr": 0.0001,                  // Initial learning rate. If Noam decay is active, maximum learning rate.
    "wd": 0.000001,                // Weight decay weight.
    "warmup_steps": 4000,          // Noam decay steps to increase the learning rate from 0 to "lr"
    "seq_len_norm": true,         // FalseNormalize eash sample loss with its length to alleviate imbalanced datasets. Use it if your dataset is small or has skewed distribution of sequence lengths.

    // TACOTRON PRENET
    "memory_size": -1,             // ONLY TACOTRON - size of the memory queue used fro storing last decoder predictions for auto-regression. If < 0, memory queue is disabled and decoder only uses the last prediction frame.
    "prenet_type": "bn",           // "original" or "bn".
    "prenet_dropout": false,       // enable/disable dropout at prenet.

    // TACOTRON ATTENTION
    "attention_type": "original",  // 'original' or 'graves'
    "attention_heads": 4,          // number of attention heads (only for 'graves')
    "attention_norm": "sigmoid",   // softmax or sigmoid.
    "windowing": false,            // Enables attention windowing. Used only in eval mode.
    "use_forward_attn": false,     // if it uses forward attention. In general, it aligns faster.
    "forward_attn_mask": false,    // Additional masking forcing monotonicity only in eval mode.
    "transition_agent": false,     // enable/disable transition agent of forward attention.
    "location_attn": true,         // enable_disable location sensitive attention. It is enabled for TACOTRON by default.
    "bidirectional_decoder": false,  // use https://arxiv.org/abs/1907.09006. Use it, if attention does not work well with your dataset.
    "double_decoder_consistency": true,  // use DDC explained here https://erogol.com/solving-attention-problems-of-tts-models-with-double-decoder-consistency-draft/
    "ddc_r": 7,                           // reduction rate for coarse decoder.

    // STOPNET
    "stopnet": true,               // Train stopnet predicting the end of synthesis.
    "separate_stopnet": true,      // Train stopnet seperately if 'stopnet==true'. It prevents stopnet loss to influence the rest of the model. It causes a better model, but it trains SLOWER.

    // TENSORBOARD and LOGGING
    "print_step": 25,       // Number of steps to log training on console.
    "tb_plot_step": 100,    // Number of steps to plot TB training figures.
    "print_eval": false,     // If True, it prints intermediate loss values in evalulation.
    "save_step": 50,      // Number of training steps expected to save traninpg stats and checkpoints.
    "checkpoint": true,     // If true, it saves checkpoints per "save_step"
    "tb_model_param_stats": false,     // true, plots param stats per layer on tensorboard. Might be memory consuming, but good for debugging.

    // DATA LOADING
    "text_cleaner": "phoneme_cleaners",
    "enable_eos_bos_chars": false, // enable/disable beginning of sentence and end of sentence chars.
    "num_loader_workers": 4,        // number of training data loader processes. Don't set it too big. 4-8 are good values.
    "num_val_loader_workers": 4,    // number of evaluation data loader processes.
    "batch_group_size": 0,  //Number of batches to shuffle after bucketing.
    "min_seq_len": 6,       // DATASET-RELATED: minimum text length to use in training
    "max_seq_len": 153,     // DATASET-RELATED: maximum text length

    // PATHS
    "output_path": "/Users/davidecangelosi/Desktop/workspace/venvMoz/TTS/davide_tests/output_train",

    // PHONEMES
    "phoneme_cache_path": "/Users/davidecangelosi/Desktop/workspace/venvMoz/TTS/davide_tests/",  // phoneme computation is slow, therefore, it caches results in the given folder.
    "use_phonemes": false,           // use phonemes instead of raw characters. It is suggested for better pronounciation.
    "phoneme_language": "en-us",     // depending on your target language, pick one from  https://github.com/bootphon/phonemizer#languages

    // MULTI-SPEAKER and GST
    "use_speaker_embedding": false,      // use speaker embedding to enable multi-speaker learning.
    "use_external_speaker_embedding_file": false, // if true, forces the model to use external embedding per sample instead of nn.embeddings, that is, it supports external embeddings such as those used at: https://arxiv.org/abs /1806.04558
    "external_speaker_embedding_file": "davide_tests/speakers-Davide.json", // if not null and use_external_speaker_embedding_file is true, it is used to load a specific embedding file and thus uses these embeddings instead of nn.embeddings, that is, it supports external embeddings such as those used at: https://arxiv.org/abs /1806.04558
    "use_gst": true,       			    // use global style tokens
    "gst":	{			                // gst parameter if gst is enabled
        "gst_style_input": null,        // Condition the style input either on a
                                        // -> wave file [path to wave] or
                                        // -> dictionary using the style tokens {'token1': 'value', 'token2': 'value'} example {"0": 0.15, "1": 0.15, "5": -0.15}
                                        // with the dictionary being len(dict) <= len(gst_style_tokens).
        "gst_embedding_dim": 512,
        "gst_num_heads": 4,
        "gst_style_tokens": 10
	},

    // DATASETS
    "datasets":   // List of datasets. They all merged and they get different speaker_ids.
        [
            {
                "name": "davide",
                "path": "/Users/davidecangelosi/Desktop/workspace/venvMoz/TTS/davide_tests/data/davide",
                "meta_file_train": "metadata_train.csv",
                "meta_file_val": "metadata_val.csv"
            }
        ]
}

I double checked the wavs path but it is ok. 

Can someone help me please?

Thank you very much for your amazing work

**Comment by erogol** [comment]
why is there a back-slash in file path ?
```/Users/davidecangelosi/Desktop/workspace/venvMoz/TTS/davide_tests/data/davide/wavs/\ufeff1.wav```

**Comment by Stanley80** [comment]
Hello Erogol,
yes, I noticed the backslash. The wav files are 1.wav 2.wav and so on . 
IT seems that TTS adds \ufeff before the filename.

I don't know How it can happen.

In my metadata.csv files names are correctly indicated and no backslash  is reported.

**Comment by erogol** [comment]
put a breakpoint in dataloader and check where it comes from. it is nothing i see in any of my runs. probably there is something weird on your side.

**Comment by SanjaESC** [comment]
> yes, I noticed the backslash. The wav files are 1.wav 2.wav and so on .
> IT seems that TTS adds \ufeff before the filename.

Check this https://github.com/clld/clldutils/issues/65#issuecomment-344953000
and this https://stackoverflow.com/a/15137601

**Comment by Stanley80** [comment]
I resolved the issue.  

My metadata files were not encoded in Unicode UTF-8, thus, the decoding procedure did not pass checks.

Now, I saved my metadata files using Unicode UTF-8 encoding and the problems are gone.

Thank you very much  for your help. Erogol and SanjaESC +1
