### ISSUE TITLE
Tacotron2 decoder has internally hard-coded stop_threshold=0.5, which leads to unexpected model interruption

### ISSUE THREAD

**Issue by ksofiyuk** [mozilla/TTS#522]
Following the issue #521, which I think was closed too early without appropriate discussion. And I don't really agree that it isn't a bug, if it can be completely fixed just by changing an internal hard-coded threshold.

I found [hard-coded threshold](https://github.com/mozilla/TTS/blob/540d811dd52b5598a7cd21cbbcf197b0bfbeab62/TTS/tts/layers/tacotron2.py#L157) in Tacotron2 Decoder. Its value is 0.5. I guess it is too low and makes the model too sensitive for stopping, especially for long complex sentences. In my experiments, increasing the threshold to 0.7 fully resolves the problem without any noticeable side effects.

In my view, this variable can be separated between training and inference modes, and its value should be increased at least for inference to prevent model interruptions. Or at least this threshold shouldn't be internally hard-coded without any description.

**Comment by erogol** [comment]
I guess you can change it before inference.

```python
model.decoder.stop_threshold = 0.7
# run inference
```

Would that work for you ?

**Comment by ksofiyuk** [comment]
Yes, I wrote exactly the same line in my code. But I think it don't cancel what I say above. I experimented with voicing of scientific articles and the fail rate exceeds 2-3% there due to plenty of complex sentences, and I think it's a very big flaw for out-of-box behavior. So default value 0.5 is not very good and without digging up the sources it is hard to realize the reason.

**Comment by george-roussos** [comment]
As Eren mentioned, this occurs because the model is not 100% robust, which happens because the open source dataset (LJSpeech) is a compilation from different audiobooks. This means there are pauses where they are not marked in the text and commas that are not kept by the narrator (she doesn't stop). All these things affect training and inference and may be mitigated with different data. A good quality set (with no background noise, absolute match in transcriptions and pauses only in punctuation), would easily get you synthesis of up to 5K characters with minimal, or no statistical errors. And the self_stop variable would not matter. Some datasets are just not good enough.

**Comment by tekinek** [comment]
I remember it was 0.7 in early version  of this repo.  
With my dataset, 0.7 leads to non-stopping-decoder more often than 0.5. I ended up with 0.55 which works best for me. So this threshold is somehow dataset related. (Silences without proper marking is common in my dataset)

**Comment by dipjyoti92** [comment]
@erogol 

I tried training LJspeech with the commit c7296b3 that you mentioned [here](https://erogol.com/solving-attention-problems-of-tts-models-with-double-decoder-consistency/). In that commit, stop_threshold was set to 0.7.
Once, it is trained, I tried synthesizing the long utterance that you shared [here](https://erogol.github.io/ddc-samples/).
However, the trained model could not generate the whole sentence but gets abruptly stopped. Can you
please suggest which commit you used to synthesize the long sentences? Also, can you suggest any ideas why I am unable
to generate the exact same long sentences that you provided [here](https://erogol.github.io/ddc-samples/)?
