### ISSUE TITLE
bidirectional_decoder isn't working

### ISSUE THREAD

**Issue by WeberJulian** [mozilla/TTS#524]
Hi,
I'm trying to train a model on the french part of mailabs without the phonems. DDC's attention didn't converge so I taught I'll use bidirectional_decoder. When I changed "double_decoder_consistency": false and "bidirectional_decoder": true I'm getting the error :
```
Traceback (most recent call last):
  File "train_tts.py", line 705, in <module>
    main(args)
  File "train_tts.py", line 617, in main
    global_step, epoch, amp, speaker_mapping)
  File "train_tts.py", line 162, in train
    text_input, text_lengths, mel_input, mel_lengths, speaker_ids=speaker_ids, speaker_embeddings=speaker_embeddings)
  File "/home/ubuntu/miniconda3/envs/dev2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/lib/TTS/TTS/tts/models/tacotron2.py", line 133, in forward
    decoder_outputs_backward, alignments_backward = self._backward_pass(mel_specs, encoder_outputs, input_mask)
  File "/home/ubuntu/lib/TTS/TTS/tts/models/tacotron_abstract.py", line 143, in _backward_pass
    self.speaker_embeddings_projected)
  File "/home/ubuntu/miniconda3/envs/dev2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 4 positional arguments but 5 were given

```
Is bidirectional_decoder still supported or is it obsolete since ddc ?
here is my [config.json](http://pastebin.fr/65909) and use_forward_attn and DDC works when y run train_tts.py.

**Comment by george-roussos** [comment]
Have you tried a run with phonemes and basic_cleaner? So it will not turn the special characters to ASCII.

**Comment by erogol** [comment]
It should work, if doesn't there is a bug.

**Comment by WeberJulian** [comment]
> Have you tried a run with phonemes and basic_cleaner? So it will not turn the special characters to ASCII.

Thanks for the suggestion but it isn't relevant to fixing the bug is it ?

**Comment by george-roussos** [comment]
No sorry. Well, you could always give it a go, because if the phonemes are not turnt to ASCII, the model would not be confused, when it sees "c" in text and different pronunciation in audio (because of all special characters being turnt to "c"). So it might converge and you may not need bidirectional. It has happened to me in the past. 😀

**Comment by erogol** [comment]
it should be fixed by now.
