### ISSUE TITLE
librosa.util.exceptions.ParameterError: Target size (38) must be at least input size (1100)

### ISSUE THREAD

**Issue by nowingnet** [mozilla/TTS#53]
After running the server( python3 server/server.py -c server/conf.json),
I tried to test text through web browser.

But, Message  "librosa.util.exceptions.ParameterError: Target size (38) must be at least input size (1100)"  has occurred

Below is the full message.

File "tts/utils/audio.py", line 110, in _griffin_lim
    angles = np.exp(1j * np.angle(self._stft(y)))
  File "tts/utils/audio.py", line 124, in _stft
    y=y, n_fft=self.n_fft, hop_length=self.hop_length, win_length=self.win_length)
  File "tts/lib/python3.6/site-packages/librosa-0.5.1-py3.6.egg/librosa/core/spectrum.py", line 152, in stft
    fft_window = util.pad_center(fft_window, n_fft)
  File "tts/lib/python3.6/site-packages/librosa-0.5.1-py3.6.egg/librosa/util/utils.py", line 287, in pad_center
    'at least input size ({:d})').format(size, n))
librosa.util.exceptions.ParameterError: Target size (38) must be at least input size (1100)

**Comment by 752377941** [comment]
I have the same problem as this. Can u tell me how to resolve it?

**Comment by erogol** [comment]
I don't know what is it in particular. It does not seem to be TTS problem but librosa.

**Comment by bckang77** [comment]
I found that the problem was sequence to call the function.

in audio.py
self.ap = AudioProcessor(
            config.sample_rate,
            config.num_mels,
            config.min_level_db,
            config.frame_shift_ms,
            config.frame_length_ms,
            config.ref_level_db,
            config.num_freq,
            config.power,
            config.preemphasis, <= this is the wrong sequence ...
           griffin_lim_iters=60)

**Comment by erogol** [comment]
Ohh see. Thx for flagging it. But server part of the code only warranted for the server branch. Sorry about it. If it is always welcome to have a nice looking PR :+1:

**Comment by gg4u** [comment]
Can you explain what preemphasis does and what does it mean by "wrong sequence" ?

I am using librosa for part of  research project, it is used in a library I am using, but don't have background in signal processing, thanks.

I noticed that if I skip the parameter preemphasis, I don't have the error ParameterError anymore, but I wonder if it was meant to be used on purpose..
