### ISSUE TITLE
PR: Use german_transliterate as German cleaner lib

### ISSUE THREAD

**Issue by repodiac** [mozilla/TTS#535]
Hi,

@thorstenMueller just let me know that external cleaners for French have been integrated. Since we for quite some time are using my German cleaner lib `german_transliterate` in the German TTS project, I suggest to integrate it into Mozilla TTS as well for German language.

It can be integrated as any other `pip` resource except it needs the git interface:

`pip install git+https://github.com/repodiac/german_transliterate`

Here is a snippet for code integration for **phoneme-based** cleaning:

```
from german_transliterate.core import GermanTransliterate

# use these setting for PHONEMIC ENCODINGS as input
cleaned_text =  GermanTransliterate(replace={';': ',', ':': ' '}, sep_abbreviation=' -- ').transliterate(raw_text)
```

or these for **character-based** cleaning:

```
from german_transliterate.core import GermanTransliterate
ops = {'acronym_phoneme', 'accent_peculiarity', 'amount_money', 'date', 'timestamp',
        'weekday', 'month', 'time_of_day', 'ordinal', 'special', 'math_symbol', 'spoken_symbol'}

# use none or your own for other purposes than phonemic encoding and do not use 'spoken_symbol' or 'acronym_phoneme'
cleaned_text =  GermanTransliterate(transliterate_ops=list(ops-{'spoken_symbol', 'acronym_phoneme'})).transliterate(raw_text)
```

More information to be found on the github README page: https://github.com/repodiac/german_transliterate

**Comment by thorstenMueller** [comment]
@repodiac Would it be an idea to publish ypur code as pip module in official (https://pypi.org/) repo? It then could be added to requirements.txt without any additional struggeling.

**Comment by repodiac** [comment]
don't worry - it works the same! just put an entry `git+https://github.com/repodiac/german_transliterate` into the common `requirements.txt` :-)

PS: right now, it is too error-prone and too much efforts to keep track with a pypi package, additionally.

**Comment by SanjaESC** [comment]
@repodiac Would it make sense to change your repository to a global transliterate repository so that others can commit / extend it with new languages?

**Comment by repodiac** [comment]
sure, any contribution welcome (I think the commiting parties have to be set on the team by me then for long term contributions, or a simple PR would suffice for a single contribution, as well). However, the repo is not solely limited to be used for (Mozilla) TTS preprocessing, though -- it is and should be useful in a more general sense.
