### ISSUE TITLE
Using yaml or toml to manage config?

### ISSUE THREAD

**Issue by houqp** [mozilla/TTS#538]
Hi, thoughts on switching to yaml/toml for config management? that way, we won't have to use a custom JSON dialect to manage comments in config.

**Comment by nmstoker** [comment]
There was some discussion a little while back about this on the forum here: https://discourse.mozilla.org/t/best-config-for-tacotron2-training/42526/4?u=nmstoker

Also as this isn't really a bug as such, it's probably better taken up on the forum too rather than in an issue here.

**Comment by houqp** [comment]
Hi @nmstoker thanks for the link. I took a look at it and looks like it mostly focuses on logically reorganizing the current configs while I am focusing on the serialization format.

The reason I asked this question in github issue is I am interested in submitting a PR to implement the change, but would like to know if this is the kind of change that would be accepted by the project maintainers.

**Comment by erogol** [comment]
I don't know how it is useful in practice except conforming to json syntax. 

I am more inclined to define template config classes for each model and define default values then overwrite these values with config files to make the entry easier for beginners.

**Comment by houqp** [comment]
yeah, I think config template is a separate issue. I don't see any harm in adding optional support for yaml config though, it won't solve the beginner issue, but makes config editing/linting easier for developers because it they will now be able to leverage standard toolings.
