### ISSUE TITLE
Where is the newest model

### ISSUE THREAD

**Issue by jinfagang** [mozilla/TTS#54]
I download the 272976 iter model, and run notebooks `synthesis.py` got error:

```
RuntimeError: Error(s) in loading state_dict for Tacotron:
	Missing key(s) in state_dict: "encoder.cbhg.cbhg.conv1d_banks.0.conv1d.weight", "encoder.cbhg.cbhg.conv1d_banks.0.bn.weight", "encoder.cbhg.cbhg.conv1d_banks.0.bn.bias", "encoder.cbhg.cbhg.conv1d_banks.0.bn.running_mean", "encoder.cbhg.cbhg.conv1d_banks.0.bn.running_var", "encoder.cbhg.cbhg.conv1d_banks.1
```

**Comment by erogol** [comment]
You need to use the given commit point for the model, next to it on the table. If still there is a problem then it is a bug. I plan waiting to integrate neural vocoder before the next model release.

**Comment by erogol** [comment]
It was a bug. I updated the table and uploaded a new model. Hope it'd work for you.

**Comment by jinfagang** [comment]
@erogol Many thanks for your help and your test. I'll using the updated model.
