### ISSUE TITLE
[Help needed] TTS Community Survey - Let us know your feedback 

### ISSUE THREAD

**Issue by erogol** [mozilla/TTS#541]
I've created this short survey to have a better understanding of the TTS community, and use cases of Mozilla TTS. 

This way we can plan the future of the project in more clarity and prioritize the work in an order that would serve the community in a more effective way.

If you use Mozilla TTS please spare your 5 mins and let us know what you think.

https://docs.google.com/forms/d/e/1FAIpQLSfSZuQzfWghgwzmv-i7BP0r5s-5JmVF-qncnkvJroAfW7YO8A/viewform?usp=sf_link

**Comment by thorstenMueller** [comment]
Hey @erogol .
Nice survey.
What do you think on changing the question "What do you like to improve the most in Mozilla TTS?" to a multiple selection field? I'd more preferred options and had to put them in the free text field in the end of the form.

**Comment by erogol** [comment]
I wanted to pinpoint the most wanted feature. Multi-selection might allow people to be less selective.

**Comment by thorstenMueller** [comment]
That's true. Or maybe lead to submit the form multiple times.
I checked "my most wanted" feature and posted additional 2 nice to have in the comment box in the end.
