### ISSUE TITLE
Update documentation and config files

### ISSUE THREAD

**Issue by ayush-1506** [mozilla/TTS#544]
https://github.com/mozilla/TTS#training-and-fine-tuning-lj-speech mentions the file `train.py`, which doesn't exist anymore (looks like it has been replaced by train_tts.py). Perhaps the documentation needs to be updated.

Also faced a few more issues while getting the tacotron-2 model to train on my dataset. (missing variables from `config.json`).

Let me know if you'd like me to open a PR for fixing all the issues.

**Comment by erogol** [comment]
Feel free send a PR as you like.
