### ISSUE TITLE
TFlite and Double Decoder Consistency

### ISSUE THREAD

**Issue by CMS256** [mozilla/TTS#547]
Hi,

I think there might be a bug with TFlite: It doesn't seem to have Double Decoder Consistency, the results at the bottom of this [notebook](https://colab.research.google.com/drive/1RXCK8iNY7rNZRFopCagEjJ74HBgdWUOo?usp=sharing)(TFLite) differ greatly from this [notebook](https://colab.research.google.com/drive/1LgQpdbgLHjyjTxgs6LHaKH_yl0luxkhT?usp=sharing)(TF+DDC).
It is using the same models and configs from the DDC notebook.

Is it a limitation in TFLite, or is it unintended?

What I have tried:
1: Running this [notebook ](https://colab.research.google.com/drive/1GjOSE5tDz2rA_ndIKxr4VNtE0kk_gwmM?usp=sharing)with the provided TFLite models.
2: Generate the TFLite models myself using this [second notebook](https://colab.research.google.com/drive/10Ns09RHd70j9-wWvIKj0xI-d_sAjs2NI?usp=sharing). It crashes at _"3 Text to speech generation"_ because of a version mismatch, but I export the models to the first notebook.

Any suggestions/ideas?

**Comment by erogol** [comment]
Sorry for the long delay in the answer. TFLite only supports the raw Tacotron2 model. Before converting the DDC model to TFLite you need to remove all additional layers used for training of the DDC model (coarse decoder).
