### ISSUE TITLE
Ground Truth alignments using ExtractTTSSspectrogram are not working

### ISSUE THREAD

**Issue by george-roussos** [mozilla/TTS#550]
Hi,

I tried to extract ground truth spectrograms to train PWGAN and see if I can hopefully get better performance, so I used the ExtractTTSSpectrograms notebook to grab them, using my Tacotron2 model; however, when I try to start training I get an AssertionError

```
  File "/usr/lib/python3.6/random.py", line 199, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,0, 0)
```

even though the hop length is the same in both configs, as is everything else and I try to train with the exact same wavs I extracted ground truth alignments for. Has anybody else got this problem? Maybe I am doing something wrong (quite possibly). I made a change to the notebook (since the TTS is trained using DDC):

`mel_outputs, postnet_outputs, alignments, stop_tokens, decoder_outputs_backward, alignments_backward = model.forward(text_input, text_lengths, mel_input)`

**Comment by SanjaESC** [comment]
I think it's because some of the audio files are to short. I guess you would have to filter them out when computing the features.

**Comment by george-roussos** [comment]
Thanks, I thought the same after I opened the issue because I ran some debugging and it always happened with very short files 😀 I filtered them out and now it is training, I will report on results when it has trained.

**Comment by zainmujahid** [comment]
@george-roussos Can you please tell what threshold you used to filter out short wav files? I am stuck with the error "empty range for randrange() (0, 0, 0)", I found out by reading other issues that its because of short wav files but Idk which threshold (in seconds) to use, in order to filter them out so that I do not face this error.

Thanks.
