### ISSUE TITLE
ImportError: cannot import name 'setup_model'

### ISSUE THREAD

**Issue by MichaelMano3** [mozilla/TTS#557]
Hi,i want to use the DDC pre-trained model,but i get this error,i checked the file and there are no setup_model function in the utils.generic_utils.py ,how do i solve this?

Here is the log:
python3 testDDC.py
Traceback (most recent call last):
File “testDDC.py”, line 6, in
from TTS.utils.generic_utils import setup_model
ImportError: cannot import name ‘setup_model’

**Comment by SanjaESC** [comment]
What commit are you using?

In the current commit "setup_model" is located in TTS.tts.utils.generic_utils

**Comment by erogol** [comment]
I don't think you installed the project right.

**Comment by MichaelMano3** [comment]
problem solved when i change the "TTS.utils.generic_utils" to  “TTS.tts.utils.generic_utils”,and also need to change other import from TTS to TTS.tts
