### ISSUE TITLE
Should the `umap` requirement be `umap-learn`? 

### ISSUE THREAD

**Issue by krzim** [mozilla/TTS#558]
https://github.com/mozilla/TTS/blob/0cd222d4b727a98d583ba7df2af28c7d49c25380/requirements.txt#L24

If you attempt to train a new encoder model, it will choke with an attribute error:  `AttributeError: module 'umap' has no attribute 'UMAP'`. A quick google will land you at https://github.com/lmcinnes/umap/issues/24. I believe the requirement should be changed to `umap-learn` instead (considering I am currently training a model with it). Can anyone confirm that `umap` is not needed and that `umap-learn` is the correct replacement?

**Comment by nmstoker** [comment]
I think you're right. If you look in this file: https://github.com/mozilla/TTS/blob/master/TTS/speaker_encoder/requirements.txt
you will see that it has umap-learn which is consistent with the documentation for umap. I think the recent addition to the main requirements.txt file pointing to umap is simply an accident.
