### ISSUE TITLE
CPU training compatible

### ISSUE THREAD

**Issue by jinfagang** [mozilla/TTS#56]
For some poor people, we have to using CPU to train. I found this line codes not work on CPU:

```
 # forward pass
        mel_output, linear_output, alignments, stop_tokens = torch.nn.parallel.data_parallel(
            model, (text_input, mel_input, mask))
```
Just only this code. How to change it to make it run on CPU?

**Comment by ahv88** [comment]
I'm having the same problem - tried adding an argument `output_device=-1` but that leads to additional errors, so I'm not sure if that's the correct fix.

**Comment by erogol** [comment]
I've never tried CPU before, tommorow I'll and get back to you. However, if you remove ```torch.nn.parallel.data_parallel``` and use ```model(text_input, mel_input, mask)```you remove the gpu constraint from the model call. However, at an aother part of the code, there might be another GPU dependency.

**Comment by jinfagang** [comment]
@erogol Right. Since we have if use_cuda condition, we can take it into consideration of both train and inference on CPU and GPU. (Most of the time, CPU is just testing for code training process works fine, cause it's not always has a GPU on hand)

**Comment by erogol** [comment]
@jinfagang I updated the master, it should train on CPU. Reopen if doesn't.
