### ISSUE TITLE
No such file or directory: './scale_stats.npy' with DDC

### ISSUE THREAD

**Issue by MichaelMano3** [mozilla/TTS#563]
Hi,i want to use DDC model on local,not on google colab,and i have this issue,i definitely download scale_stats.npy in my DDC model folder.Can anyone help me sove this.Thanks!

Here is the log:

Hello from the pygame community. https://www.pygame.org/contribute.html
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:0
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:50.0
 | > mel_fmax:7600.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > stats_path:./scale_stats.npy
 | > hop_length:256
 | > win_length:1024
Traceback (most recent call last):
  File "CyberspeechDDC.py", line 71, in <module>
    ap = AudioProcessor(**TTS_CONFIG.audio)   
  File "/home/yang/deepspeech/TTS/TTS/utils/audio.py", line 81, in __init__
    mel_mean, mel_std, linear_mean, linear_std, _ = self.load_stats(stats_path)
  File "/home/yang/deepspeech/TTS/TTS/utils/audio.py", line 166, in load_stats
    stats = np.load(stats_path, allow_pickle=True).item()  #pylint: disable=unexpected-keyword-arg
  File "/home/yang/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: './scale_stats.npy'

**Comment by thorstenMueller** [comment]
Maybe it's a file location problem. Did you try using an absolute (full) path in config?

**Comment by george-roussos** [comment]
Hi, please try explicitly giving the full path to the file (you can try a pwd on Terminal). It should work then 😀

**Comment by khalilRhouma** [comment]
@MichaelMano3  maybe you should update the config file put` "stats_path"` in the config file to your new path

**Comment by thorstenMueller** [comment]
@MichaelMano3 - did you resolve your problem  ? If so, a small comment and closing the issue would be appreciated.
