### ISSUE TITLE
Phoneme_language 

### ISSUE THREAD

**Issue by xoxoxo13102020** [mozilla/TTS#564]
I want to train the model for Turkish language with my own dataset.I collected 23 hours of  audio from audiobook from the same artist. I split it as 16 bit PCM Mono wav sample rate 22Khz at intervals of 3-8 seconds. (I tried to create a dataset like LjSpeech.)
I know I need to change the config.json file for the training. But I did not understand exactly what to change. Could you please help about it?

Based on the sentence "If you use phonemes for training and your language is supported here, you don't need to do that." I think that Espeak has Turkish support, I think I can use Phonems from here, but I could not find how to do it.

// PHONEMES

"phoneme_cache_path": "/home/erogol/Models/phoneme_cache/", // phoneme computation is slow, therefore, it caches results in the given folder.
"use_phonemes": true, // use phonemes instead of raw characters. It is suggested for better pronounciation.
"phoneme_language": "en-us", // depending on your target language, pick one from https://github.com/bootphon/phonemizer#languages

Will it be sufficient to change the "phoneme_language": "en-us" part in the config file to "phoneme_language": "tr"? If you have a detailed document that will facilitate the training phase and training with my own data set, can you share it with me or could you give me information?

**Comment by george-roussos** [comment]
If your language has special characters, you will also need to change the cleaners to basic_cleaners, so they will not be transliterated. If Turkish has special pronunciation rules and you find TTS lacks in predicting correct pronunciation for novel words, you can look into replacing espeak with espeak-ng and using a custom pronunciation lexicon (if you can find one).

**Comment by xoxoxo13102020** [comment]
> If your language has special characters, you will also need to change the cleaners to basic_cleaners, so they will not be transliterated. If Turkish has special pronunciation rules and you find TTS lacks in predicting correct pronunciation for novel words, you can look into replacing espeak with espeak-ng and using a custom pronunciation lexicon (if you can find one).

**Thank you so much**, I checked espeak-ng also has Turkish support does it mean it has the pronunciation lexicon? and is that a true changing  (**"phoneme_language": "en-us"  ==> "phoneme_language": "tr"**)  @george-roussos
