### ISSUE TITLE
TTS/bin/train_encoder bad import

### ISSUE THREAD

**Issue by Sasha349** [mozilla/TTS#566]
At commit 0cd222d4b727a98d583ba7df2af28c7d49c25380
train_encoder script has wrong import:
from TTS.tts.utils.io import save_best_model - not working
from TTS.speaker_encoder.utils.generic_utils import save_best_model - work

Also requirements.txt contains umap, but umap-learn need for working TTS/speaker_encoder/utils/visual.py

**Comment by erogol** [comment]
this is fixed already.
