### ISSUE TITLE
multiband-melgan train time too long

### ISSUE THREAD

**Issue by tsungruihon** [mozilla/TTS#569]
May i ask why the `multiband-melgan` train epoch takes so long ? 

```
 --> TRAIN PERFORMACE -- EPOCH TIME: 27.26 sec -- GLOBAL_STEP: 4512
     | > avg_G_stft_loss_mg: 1.05284
     | > avg_G_stft_loss_sc: 0.59968
     | > avg_G_subband_stft_loss_mg: 0.89462
     | > avg_G_subband_stft_loss_sc: 0.61183
     | > avg_G_loss: 1.57948
     | > avg_G_gen_loss: 1.57948
     | > avg_G_adv_loss: 0.00000
     | > avg_loader_time: 6.54023
     | > avg_step_time: 0.28962
```

**Comment by george-roussos** [comment]
Try htop to see if CPU is a bottleneck (should show 100% usage on all CPUs). If it is, restart training with prefix OMP_NUM_THREADS=1 and then python3 etc.

**Comment by tsungruihon** [comment]
@george-roussos Hi George, long time no see. I tried to switch the training process on `GTX 1080ti` instead of `RTX 2080Ti`, then the problem solved.

**Comment by tsungruihon** [comment]
@george-roussos thanks george. I will try and let you know.

**Comment by tsungruihon** [comment]
@george-roussos Hi George, may i ask whether this horizontal line is normal ?
![Screenshot 2020-11-17 at 5 03 07 PM](https://user-images.githubusercontent.com/11624203/99368996-d412cd80-28f6-11eb-9afd-55f63185f73e.png)

**Comment by george-roussos** [comment]
Hi, this will go away gradually 🙂 Let us know what results you get!

**Comment by tsungruihon** [comment]
@george-roussos Thanks George. Sure i will share the results. :blush::blush:

**Comment by ysujiang** [comment]
> @george-roussos Hi George, may i ask whether this horizontal line is normal ?
> ![Screenshot 2020-11-17 at 5 03 07 PM](https://user-images.githubusercontent.com/11624203/99368996-d412cd80-28f6-11eb-9afd-55f63185f73e.png)

hello, Is this horizontal line disappeared? Is there any noise in your synthesized voices?

**Comment by tsungruihon** [comment]
@ysujiang It seems that the line will disappeared.

**Comment by tsungruihon** [comment]
@george-roussos @ysujiang Here's the periodic update sharing. 

![Screenshot 2020-11-26 at 8 33 26 AM](https://user-images.githubusercontent.com/11624203/100294608-43a54e80-2fc2-11eb-8cba-32737a8a59d9.png)
![Screenshot 2020-11-26 at 8 33 32 AM](https://user-images.githubusercontent.com/11624203/100294611-4738d580-2fc2-11eb-97e4-75c1ec7e93d7.png)

**Comment by tsungruihon** [comment]
@george-roussos @erogol  Hey george and erogol, here's the weekly update. Please hear the sample below and feel free to share your advice. Now i wonder whether should i adjust the `spec_gain` to `20` or not. 

![Screenshot 2020-11-30 at 2 39 28 PM](https://user-images.githubusercontent.com/11624203/100576885-f276c100-3319-11eb-9f18-9b3df6815532.png)
![Screenshot 2020-11-30 at 2 39 33 PM](https://user-images.githubusercontent.com/11624203/100576894-f73b7500-3319-11eb-9d42-a1914c2abd42.png)
[sample.zip](https://github.com/mozilla/TTS/files/5614154/sample.zip)

**Comment by george-roussos** [comment]
Hi, this sounds nice! What is your spec gain right now? I personally find 20.0 works very well for me.

**Comment by tsungruihon** [comment]
@george-roussos the sound actually not good enough for me. The spec gain in that experiment is 1. Now i am trying spec gain with 20. Hope will get better results. Will always let you know George.

**Comment by ysujiang** [comment]
> @george-roussos the sound actually not good enough for me. The spec gain in that experiment is 1. Now i am trying spec gain with 20. Hope will get better results. Will always let you know George.



> @george-roussos @erogol Hey george and erogol, here's the weekly update. Please hear the sample below and feel free to share your advice. Now i wonder whether should i adjust the `spec_gain` to `20` or not.
> 
> ![Screenshot 2020-11-30 at 2 39 28 PM](https://user-images.githubusercontent.com/11624203/100576885-f276c100-3319-11eb-9f18-9b3df6815532.png)
> ![Screenshot 2020-11-30 at 2 39 33 PM](https://user-images.githubusercontent.com/11624203/100576894-f73b7500-3319-11eb-9d42-a1914c2abd42.png)
> [sample.zip](https://github.com/mozilla/TTS/files/5614154/sample.zip)

@tsungruihon hi ，your synthesized voices sounds better than mine . This is my synthesized voice . Can you tell me how to adjust the parameters to eliminate the noise ? thank you very much!
[test_MBmelgan.zip](https://github.com/mozilla/TTS/files/5620004/test_MBmelgan.zip)

**Comment by tsungruihon** [comment]
@ysujiang Would you mind sharing your tensorboard ?

**Comment by ysujiang** [comment]
> @ysujiang Would you mind sharing your tensorboard ?

@tsungruihon hi , here is the the tensorboard showing. 
![image](https://user-images.githubusercontent.com/44495820/100703014-af7e2180-33dd-11eb-978f-5d4409b4eb0a.png)
![image](https://user-images.githubusercontent.com/44495820/100703287-2c110000-33de-11eb-99d1-983b2844e07b.png)
![image](https://user-images.githubusercontent.com/44495820/100703590-cb35f780-33de-11eb-9efc-1e3bc286eba1.png)
[step_200478.zip](https://github.com/mozilla/TTS/files/5620600/step_200478.zip)

**Comment by tsungruihon** [comment]
@ysujiang how long your dataset is ?

**Comment by ysujiang** [comment]
> @ysujiang how long your dataset is ?
@tsungruihon 
6.5h

**Comment by tsungruihon** [comment]
@ysujiang Looks like you could try erogol tutorial `https://github.com/erogol/TTS_recipes` and try to train again.

**Comment by ysujiang** [comment]
> https://github.com/erogol/TTS_recipes

Which branch are you running？the master or others？

**Comment by ysujiang** [comment]
> @ysujiang Looks like you could try erogol tutorial `https://github.com/erogol/TTS_recipes` and try to train again.

@tsungruihon Which branch are you running？the master or others？

**Comment by tsungruihon** [comment]
@ysujiang master.

**Comment by tsungruihon** [comment]
@george-roussos Hey George, may i ask that how many steps that your multi-melgan trained enough for good quality ?

**Comment by tsungruihon** [comment]
@george-roussos @erogol Hey george and erogol, here's the weekly update. Please hear the sample below and feel free to share your advice.  

I have stoped the experiment which starts discriminator training in 200k steps cause the loss seems goes higher and higher with the longer training. Here's the tensorboard and sample. 

[939k_steps_MultiMelGAN_Sample.wav.zip](https://github.com/mozilla/TTS/files/5664301/939k_steps_MultiMelGAN_Sample.wav.zip)

![Screenshot 2020-12-09 at 3 48 51 PM](https://user-images.githubusercontent.com/11624203/101600520-60b43580-3a36-11eb-921a-9ead3ddfd82b.png)

![Screenshot 2020-12-09 at 3 54 46 PM](https://user-images.githubusercontent.com/11624203/101600876-dfa96e00-3a36-11eb-8393-efb567119976.png)

Now i start a new experiment which starts discriminator training in 600k steps. Here's the tensorboard and sample. 

[687k_steps_MultiBand_MelGAN_Sample.wav.zip](https://github.com/mozilla/TTS/files/5664313/687k_steps_MultiBand_MelGAN_Sample.wav.zip)

![Screenshot 2020-12-09 at 3 52 38 PM](https://user-images.githubusercontent.com/11624203/101600639-935e2e00-3a36-11eb-9465-d28cfff52f6b.png)

![Screenshot 2020-12-09 at 3 55 17 PM](https://user-images.githubusercontent.com/11624203/101601032-1b443800-3a37-11eb-8235-2258c4b8341c.png)

Please hear the sample below and feel free to share your advice. Really appreciate. 

Regards,
Peter
