### ISSUE TITLE
Training stoped

### ISSUE THREAD

**Issue by xoxoxo13102020** [mozilla/TTS#577]
Training stopped at Epoch 999/1000 but I still could not get reasonable results at 60k from test autputs with custom datasets. What should I do?
And how could I start training again whre I left with checkpoints?

**Comment by thorstenMueller** [comment]
> And how could I start training again whre I left with checkpoints?

Check options (--continue_path and/or --restore_path) as described on Mozilla TTS Readme for that.
https://github.com/mozilla/tts#training-and-fine-tuning-lj-speech

**Comment by xoxoxo13102020** [comment]
Does it normal that I could not get reasonable results at 60k from test outputs? How was things in your stiation with german dataset? @thorstenMueller

**Comment by thorstenMueller** [comment]
60k from pure tacotron2 model training (gl vocoder) or 60k training steps from (which) vocoder?
We trained our german taco2 model for 460k steps and used a pwgan vocoder trained for 925k steps - leading to this quality level:

https://drive.google.com/file/d/1cDIq4QG6i60WjUYNT6fr2cpEjFQIi8w5/view?usp=sharing

**Comment by olafthiele** [comment]
Adding to @thorstenMueller, we could hear about 2/3 of the words at 60k. Not nice or always complete, but you could understand some words.

**Comment by erogol** [comment]
I close guessing the issue is addressed.
