### ISSUE TITLE
how to set `spec_gain ` value in config

### ISSUE THREAD

**Issue by tsungruihon** [mozilla/TTS#579]
May i ask that what the `spec_gain` field in config file works for, and how to set the value properly? 

I have noticed that in `LJSpeech` training demo, the `spec_gain` is set to `1.0`. But in the German dataset demo, the `spec_gain` is set to `20.0`

**Comment by erogol** [comment]
you need to find the right value fitting it to your dataset and checking specs visually.

**Comment by tsungruihon** [comment]
Thank you erogol. @erogol
