### ISSUE TITLE
Upload samples with MelGAN vocoder

### ISSUE THREAD

**Issue by NoamDev** [mozilla/TTS#583]
The samples linked from the readme were synthesized with WaveRNN.
But I hear that MelGAN is a lot faster.
Can someone upload samples generated with MelGAN so that one will be able to compare the quality of them?

**Comment by NoamDev** [comment]
So, no chance for that?

**Comment by erogol** [comment]
you can use try the model yourself either from the example notebooks (in Wiki) or using the ```tts``` command after installing with ```pip install TTS```
