### ISSUE TITLE
negative numbers are not pronounced correctly

### ISSUE THREAD

**Issue by Mic92** [mozilla/TTS#587]
i.e. -1 is pronounced the same as 1
The phonemizer backend/espeak is able to handle this correctly:

```
>>> phonemize("-1", njobs=1, backend='espeak', language="en-us", preserve_punctuation=True, language_switch='remove-flags')
'maɪnəs wʌn ' 
```

**Comment by erogol** [comment]
not pronounced correctly by what?

**Comment by Mic92** [comment]
see https://github.com/mozilla/TTS/issues/587

**Comment by Mic92** [comment]
This was solved.
