### ISSUE TITLE
Error compiling: "error compiling cython file"

### ISSUE THREAD

**Issue by Aaaamu** [mozilla/TTS#589]
Hi there, when trying to compile, following the [build instructions](https://github.com/mozilla/TTS/wiki/Build-instructions-for-server) I run into the following error.

`python setup.py bdist_wheel --checkpoint ../checkpoint_630000.pth.tar --model_config ../config.json
Embedding model in wheel file...
Compiling ./TTS/tts/layers/glow_tts/monotonic_align/core.pyx because it changed.
Compiling ./TTS/lib/python3.8/site-packages/Cython/Utility/TestCyUtilityLoader.pyx because it changed.
Compiling ./TTS/lib/python3.8/site-packages/Cython/Utility/TestCythonScope.pyx because it changed.
Compiling ./TTS/lib/python3.8/site-packages/Cython/Utility/CpdefEnums.pyx because it changed.
Compiling ./TTS/lib/python3.8/site-packages/Cython/Utility/CppConvert.pyx because it changed.
Compiling ./TTS/lib/python3.8/site-packages/Cython/Utility/MemoryView.pyx because it changed.
Compiling ./TTS/lib/python3.8/site-packages/Cython/Utility/CConvert.pyx because it changed.
Compiling ./TTS/lib/python3.8/site-packages/Cython/Runtime/refnanny.pyx because it depends on /home/user/local/moz-tts/TTS/lib/python3.8/site-packages/Cython/Includes/cpython/type.pxd.
Compiling ./TTS/lib/python3.8/site-packages/numpy/random/_examples/cython/extending.pyx because it changed.
Compiling ./TTS/lib/python3.8/site-packages/numpy/random/_examples/cython/extending_distributions.pyx because it changed.
Compiling ./lib/python3.8/site-packages/Cython/Utility/TestCyUtilityLoader.pyx because it changed.
Compiling ./lib/python3.8/site-packages/Cython/Utility/TestCythonScope.pyx because it changed.
Compiling ./lib/python3.8/site-packages/Cython/Utility/CpdefEnums.pyx because it changed.
Compiling ./lib/python3.8/site-packages/Cython/Utility/CppConvert.pyx because it changed.
Compiling ./lib/python3.8/site-packages/Cython/Utility/MemoryView.pyx because it changed.
Compiling ./lib/python3.8/site-packages/Cython/Utility/CConvert.pyx because it changed.
Compiling ./lib/python3.8/site-packages/Cython/Runtime/refnanny.pyx because it changed.
Compiling ./lib/python3.8/site-packages/numpy/random/_examples/cython/extending.pyx because it changed.
Compiling ./lib/python3.8/site-packages/numpy/random/_examples/cython/extending_distributions.pyx because it changed.
[ 1/19] Cythonizing ./TTS/lib/python3.8/site-packages/Cython/Utility/CConvert.pyx

Error compiling Cython file:
\------------------------------------------------------------
...
    PyTypeObject *Py_TYPE(obj)
    bint PyMapping_Check(obj)
    object PyErr_Format(exc, const char *format, ...)

@cname("{{funcname}}")
cdef {{struct_type}} {{funcname}}(obj) except *:
    ^
\------------------------------------------------------------

TTS/lib/python3.8/site-packages/Cython/Utility/CConvert.pyx:11:5: Expected an identifier, found '{'

Error compiling Cython file:
\------------------------------------------------------------
...
    PyTypeObject *Py_TYPE(obj)
    bint PyMapping_Check(obj)
    object PyErr_Format(exc, const char *format, ...)

@cname("{{funcname}}")
cdef {{struct_type}} {{funcname}}(obj) except *:
     ^
\------------------------------------------------------------

TTS/lib/python3.8/site-packages/Cython/Utility/CConvert.pyx:11:6: Syntax error in C variable declaration
Traceback (most recent call last):
  File "setup.py", line 123, in <module>
    ext_modules=find_cython_extensions(),
  File "setup.py", line 64, in find_cython_extensions
    exts = cythonize(find_pyx(path), language_level=3)
  File "/home/user/local/moz-tts/TTS/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1102, in cythonize
    cythonize_one(*args)
  File "/home/user/local/moz-tts/TTS/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1225, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: ./TTS/lib/python3.8/site-packages/Cython/Utility/CConvert.pyx
`

**Comment by thorstenMueller** [comment]
Hello @Aaaamu .
Did you see this simlar issue (https://github.com/mozilla/TTS/issues/543#issuecomment-717277045)?

Do you use venv environment? If so, do not set venv environment within repo directory. Instead set it outside the TTS folder. That should fix this issue.

**Comment by Aaaamu** [comment]
Hi thorsten,
thanks for your reply. I read the thread you referenced. To be honest, i would need more detailed instructions on how to set venv environment somewhere else.  it is the first time i meet venv Or any of this in-depth python stuff. I had to install venv and cython and some other component via pip, after correponding errors when trying to build for the first time.

... actually now i think i got it:

The builde instructons tell to "Create a python environment for the build: 

`cd TTS; virtualenv -p python3 . ; source bin/activate`"

So it would be this step that produces the error? I could do instead 
`
mkdir TTS/virtualenv

cd TTS/virtualenv; virtualenv -p python3 . ; source bin/activate`

And then run the line of code to build from that folder?

Maybe this could be corrected in the instructions then?!

Best,
Aamu



Am 5. Dezember 2020 10:49:25 MEZ schrieb "Thorsten Müller" <notifications@github.com>:
>Hello @Aaaamu .
>Did you see this simlar issue
>(https://github.com/mozilla/TTS/issues/543#issuecomment-717277045)?
>
>Do you use venv environment? If so, do not set venv environment within
>repo directory. Instead set it outside the TTS folder. That should fix
>this issue.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mozilla/TTS/issues/589#issuecomment-739153916

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by thorstenMueller** [comment]
Hi @Aaaamu .

No problem. I'm no python expert at all, too.
I'm not sure if instructions are primarily for server installation, but let's check if it works with following steps before think about changing the instructions.

Try the following:

* mkdir ~/speechtest
* cd ~/speechtest
* python3 -m venv .
* source ./bin/activate
* pip install pip --upgrade
* git clone https://github.com/mozilla/TTS.git
* cd TTS
* pip install -r requirements.txt
* python setup.py develop

"speechtest" in your userhome is just an example and you can use every path in your filesystem.

**Comment by thorstenMueller** [comment]
Any updates on this @Aaaamu?
If problem is solved please close this issue.

**Comment by rajpratyush** [comment]
@Aaaamu can you briefly describe your system configuration and platform on which you are working ?? is it conda??

**Comment by Aaaamu** [comment]
Am 01.02.21 um 14:18 schrieb Pratyush Raj:
