### ISSUE TITLE
synthesizer wav length

### ISSUE THREAD

**Issue by ramilrg** [mozilla/TTS#59]
Hi,
while testing with ljspeech model I found that a maximum wav file length is 12s, generated by synthesizer. Is it limited by trained dataset initially or has any options to change it?

**Comment by erogol** [comment]
If you plan to run the model for very long sequnces you ned to change the line below, so the decoder can generate more time steps. It was set before to reduce the memory usage of the model.
https://github.com/mozilla/TTS/blob/master/layers/tacotron.py#L279
