### ISSUE TITLE
gradual training makes stop loss increase by the time

### ISSUE THREAD

**Issue by lucashueda** [mozilla/TTS#598]
I am training a gst module with default configs just with use_gst = true. The gradual training is the same as the default config of tacotron2, going from r=7 to r=1 by around 70k steps per r decreasing. 

I notice that now in step 130k my stopnet loss is incresing and , consequently, making decoder reaching max_step every time. 

Is there any tip to deal with it? someone already experienced something like that? is it better to train with a fixed r?

**Comment by erogol** [comment]
There was a discussion on discourse about it. 

But the easier solution is training without gradual training.
