### ISSUE TITLE
High Quality Audio Samples?

### ISSUE THREAD

**Issue by PetrochukM** [mozilla/TTS#6]
Do you have audio samples of similar quality to:
https://google.github.io/tacotron/publications/tacotron/index.html 

Thanks!

**Comment by erogol** [comment]
In progress, I had the model but removed it accidentally. Retraining it. After that, I plan to release some samples.

**Comment by PetrochukM** [comment]
@erogol Thank you!

**Comment by claytonblythe** [comment]
I am interested in this as well!

**Comment by erogol** [comment]
Here is a simple example: https://soundcloud.com/user-565970875/tts-ljspeech-val-13585
It is generated by a text from the validation set. So it is identical to test time experience.

**Comment by claytonblythe** [comment]
Great thank you for adding the sample! Great work. This is pretty decent,  I'm excited to follow this repo and contribute if I can find time/alignment with work

**Comment by erogol** [comment]
One more here after more training 

https://soundcloud.com/user-565970875/tts-ljspeech-val-35000

**Comment by erogol** [comment]
I added things to readme so I close this.

**Comment by PetrochukM** [comment]
@erogol Hi There! Was this generated with a Wavenet vocoder or?

**Comment by erogol** [comment]
@PetrochukM no it is griffin-lim (if I wrote it right) :)
