### ISSUE TITLE
How to train a male voice?

### ISSUE THREAD

**Issue by jinfagang** [mozilla/TTS#60]
How train a male voice?

**Comment by erogol** [comment]
There needs to be no particular change. Just give the data and train. However, one good sanity check is to try your audio processing parameters by using Griffin-Lim algorithm on your raw melspecs. If GL gives good synthesis without the network, you are ready to go with those parameters.

**Comment by jinfagang** [comment]
@erogol Does there any plan to support training on some other dataset not only with LJ? such as [CMU](http://festvox.org/cmu_arctic/)

**Comment by erogol** [comment]
@jinfagang soon I am going to update the master including a more generic data loader scheme. It would give you a very easy way to adapt any dataset you have by only writing a small adapter function. However, even now, if you shape your dataset's metafile as in LJSpeech, you are ready to use TTS.

**Comment by jinfagang** [comment]
@erogol Hoping for that. the most painess thing is to preprocess the data, cause if that thing goes any wrong, than the entire model are just ruined

**Comment by erogol** [comment]
@jinfagang you just need to parse the txt file the rest is done by the dataloader. So it shouldn't be a worrisome.
