### ISSUE TITLE
Pretrained Model for 9cf474a

### ISSUE THREAD

**Issue by GuntaButya** [mozilla/TTS#604]
Super hard work navigating the Models and getting one that works with the current version: 9cf474a

Please help? What model will work with : 9cf474a

I am wanting English please. Thank You!

**Comment by erogol** [comment]
every model release has the corresponding commit attached to it on the table.

**Comment by GuntaButya** [comment]
Forward Compatible? So future Versions of the Commits are in the older Models?
All the Models are older is only reason I ask.
Thank You!

**Comment by GuntaButya** [comment]
Ten Four, was hoping to use current, but that's ok, Thank You!
