### ISSUE TITLE
use stats_path is better than not?

### ISSUE THREAD

**Issue by ysujiang** [mozilla/TTS#609]
will the sound quality be improved when stats is used?

**Comment by erogol** [comment]
it results in stable training runs for my experience

**Comment by ysujiang** [comment]
> it results in stable training runs for my experience

how about wavegrad model? is it also better that used stats_path?

**Comment by erogol** [comment]
> > it results in stable training runs for my experience
> 
> @erogol how about wavegrad model? is it also better that used stats_path?

i did not compare.
