### ISSUE TITLE
!! Commit before training to get the commit hash.

### ISSUE THREAD

**Issue by sheikhma3** [mozilla/TTS#61]
~\TTS\utils\generic_utils.py in get_commit_hash()
     35     except:
     36         raise RuntimeError(
---> 37             " !! Commit before training to get the commit hash.")
     38     commit = subprocess.check_output(['git', 'rev-parse', '--short',
     39                                       'HEAD']).decode().strip()

RuntimeError:  !! Commit before training to get the commit hash.

I am facing the above issue after running the train.py. How to resolve this issue ?

**Comment by reuben** [comment]
Commit your changes.

**Comment by sheikhma3** [comment]
> Commit your changes.
Thanks @reuben But i dont have any change. As i am just running it for the first time.

**Comment by erogol** [comment]
@sheikhma3 probably you changed the config.json for your run.
