### ISSUE TITLE
The volume of the generated voice gradually decreases

### ISSUE THREAD

**Issue by ysujiang** [mozilla/TTS#614]
sometimes the volume of the generated voice gradually decreases. here is the voice . 
Anyone know the reasons? 
And How to make the model generate voice with the same volume ?
[wav.zip](https://github.com/mozilla/TTS/files/5774386/wav.zip)

**Comment by erogol** [comment]
It is impossible to point the exact reason with no details but you can try to enable sound normalization by adding ```do_sound_norm: true``` to config.json.
