### ISSUE TITLE
No Audio Output

### ISSUE THREAD

**Issue by captionthis** [mozilla/TTS#616]
Hello.

So I'm fairly new to this whole TTS thing and seem to be running into a decent amount of problems but this one has me considerably stumped compared to the other issues I've been having. 

Before I explain what the issue is, I'll explain what I have already done, briefly. 

I am trying to use the notebook DDC_TTS_and_ParallelWaveGAN_Example.ipynb in Python because I am wanting to tweak some of the code myself and change it to more of my liking. I've got everything working and running without any errors but It seems to not be able to produce any actual audio. 

The output of the code is posted below:
![Output Image](https://user-images.githubusercontent.com/23108204/104157048-59c36e80-53b8-11eb-91e4-b14bb5ed2bd7.jpg)

As you can see, I am not getting any actual errors but it still does not seem to want to produce any audio so I am here seeking help in which any help is appreciated. I'm sorry in advance and truly understand if there might be a quick and subtle solution to this or if this may seem stupid in any way to even why I'm doing this but there is a method to the madness. So, any advice and input is greatly appreciated. 

Thank you in advance!

**Comment by SanjaESC** [comment]
How are you running the notebook?

**Comment by captionthis** [comment]
> How are you running the notebook?

A little bit of ctrl+c and ctrl+v into my Python IDE. (Copied the notebook code into Visual Studio Code)

**Comment by erogol** [comment]
You need to run it on a real notebook running since it places the output audio to the GUI. Or you need to update the code to write an output file.
