### ISSUE TITLE
Import error check_config_tts

### ISSUE THREAD

**Issue by luis-vera** [mozilla/TTS#617]
Hi, I am trying to train my model from scratch, but the message of Python was the folloring (I haven't changed the original code of the project) 

python TTS/bin/train_tacotron.py --config_path TTS/tts/configs/config.json

Traceback (most recent call last):
  File "TTS/bin/train_tacotron.py", line 18, in <module>
    from TTS.tts.utils.generic_utils import check_config_tts, setup_model
ImportError: cannot import name 'check_config_tts' from 'TTS.tts.utils.generic_utils' (C:\Users\luisv\anaconda3\envs\TF2\lib\site-packages\tts-0.0.4-py3.8.egg\TTS\tts\utils\generic_utils.py)

**Comment by thorstenMueller** [comment]
* Are you using dev or master branch?
* Maybe Windows might be a problem - could you try it using a linux system?
* Did you run setup.py install / develop?

**Comment by luis-vera** [comment]
Hi. I am using master branch and I am running setup.py install (with Anaconda environment named TF2)

This is the trace now:

(TF2) C:\Users\luisv\Documents\MozillaTTS-master2\TTS>python TTS/bin/train_tacotron.py --config_path TTS/tts/configs/config.json
2021-01-19 16:36:00.668750: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2021-01-19 16:36:00.668938: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
 > Using CUDA:  False
 > Number of GPUs:  0
Traceback (most recent call last):
  File "TTS/bin/train_tacotron.py", line 689, in <module>
    c = load_config(args.config_path)
  File "C:\Users\luisv\anaconda3\envs\TF2\lib\site-packages\tts-0.0.8+907cb98-py3.8-win-amd64.egg\TTS\utils\io.py", line 38, in load_config
    input_str = f.read()
  File "C:\Users\luisv\anaconda3\envs\TF2\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 3006: character maps to <undefined>

**Comment by erogol** [comment]
I don't think the error is on TTS but TF.

**Comment by luis-vera** [comment]
Hi again. I could resolve the error. File config.json had some chars that Window didn't recognize. 

I am new at this area. So, How can I preprocess my dataset (M-AILABS es_ES) so I get numpy files of it.  I only found the classes in dataset directory but how can I use it to get 'scale_stats.npy'?

Thanks a lot

**Comment by thorstenMueller** [comment]
If your goal is to compute statistics to get scale_stats.npy file (_"stats_path" param in config.json_) you can run
```
./TTS/bin/compute_statistics.py --config_path /path/to/config.json --out_path /path/to/scale_stats.npy
```

**Comment by luis-vera** [comment]
HI. I executed your code but I found the following error:

RuntimeError: Error opening '../LJSpeech-1.1/wavs\\PANESI.wav': Error in WAV file. Bad 'PEAK' chunk.

What's "PEAK" chunk? Thanks a lot for your help.

**Comment by erogol** [comment]
I don't think once again it is not TTS related. Please direct it to the chat or discourse.
