### ISSUE TITLE
Dont Know why this exception is occuring

### ISSUE THREAD

**Issue by sheikhma3** [mozilla/TTS#62]
![tts issue1](https://user-images.githubusercontent.com/10981535/48335381-5a003c00-e67f-11e8-8fe6-e03d09358122.png)

Please guide me. I am having this exception and unable to resolve it. Before this i have 2 commented two checks in the code 
1. TTS\utils\generic_utils.py

def remove_experiment_folder(experiment_path):
    """Check folder if there is a checkpoint, otherwise remove the folder"""

    checkpoint_files = glob.glob(experiment_path + "/*.pth.tar")
    file=open(r'c:/Py_log.txt','w')
    file.write(experiment_path)
    file.close()
    if len(checkpoint_files) < 1:
        if os.path.exists(experiment_path):
            **#shutil.rmtree(experiment_path)**
            print(" ! Run is removed from {}".format(experiment_path))
    else:
        print(" ! Run is kept in {}".format(experiment_path))

2. TTS\utils\generic_utils.py
def create_experiment_folder(root_path, model_name, debug):
    """ Create a folder with the current date and time """
    date_str = datetime.datetime.now().strftime("%B-%d-%Y_%I+%M%p")
    
    

Removed the check for Get Commit hash. Due to exception over there too.

**Comment by erogol** [comment]
solved ?
