### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by wjqkkky** [mozilla/TTS#622]
Hi! There is already a similar issue, but It's not exactly the same as mine.
I use the latest master branch.
Firstly, I trained the model from scratch, it's ok.
But when I try to continue to train from checkpoint use `python TTS/bin/distribute.py --script train_vocoder_wavegrad.py --continue_path ../checkpoints/wavegrad-private-January-19-2021_10+16AM-d481fa2/`, I got RuntimeError.
> > Using CUDA:  True
 > Number of GPUs:  4
 > Training continues for ../checkpoints/wavegrad-private-January-19-2021_10+16AM-d481fa2/best_model.pth.tar
   >  Mixed precision is enabled
 > Loading wavs from: /data2/datasets/wavs_all
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:True
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:None
 | > preemphasis:0.98
 | > griffin_lim_iters:None
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:8000.0
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:30
 | > do_sound_norm:False
 | > stats_path:None
 | > hop_length:256
 | > win_length:1024
 > Generator Model: wavegrad
 > Restoring Model...
 > Restoring Optimizer...
 > Restoring LR Scheduler...
 > Restoring AMP Scaler...
 > Model restored from step 20864
 > WaveGrad has 15827106 parameters

 > EPOCH: 0/10000

 > TRAINING (2021-01-20 09:16:06) 
Traceback (most recent call last):
  File "/data2/wavegrad_mozilla/TTS/TTS/bin/train_vocoder_wavegrad.py", line 501, in <module>
    main(args)
  File "/data2/wavegrad_mozilla/TTS/TTS/bin/train_vocoder_wavegrad.py", line 400, in main
    epoch)
  File "/data2/wavegrad_mozilla/TTS/TTS/bin/train_vocoder_wavegrad.py", line 137, in train
    scaler.step(optimizer)
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/amp/grad_scaler.py", line 294, in step
    retval = optimizer.step(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/optim/lr_scheduler.py", line 67, in wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/optim/adam.py", line 99, in step
    exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:2 and cpu!

Here is my environment：
> Package                Version             Location                                         
absl-py                0.11.0              
asn1crypto             0.24.0              
astroid                2.4.2               
astunparse             1.6.3               
attrdict               2.0.1               
attrs                  20.3.0              
audioread              2.1.9               
bokeh                  1.4.0               
cachetools             4.1.1               
cardboardlint          1.3.0               
certifi                2020.11.8           
cffi                   1.14.3              
chardet                3.0.4               
click                  7.1.2               
clldutils              3.5.4               
colorlog               4.6.2               
cryptography           2.1.4               
csvw                   1.8.0               
cycler                 0.10.0              
Cython                 0.29.21             
dataclasses            0.8                 
decorator              4.4.2               
filelock               3.0.12              
Flask                  1.1.2               
future                 0.18.2              
fuzzywuzzy             0.18.0              
gast                   0.3.3               
gdown                  3.12.2              
google-auth            1.23.0              
google-auth-oauthlib   0.4.2               
google-pasta           0.2.0               
grpcio                 1.33.2              
h5py                   2.10.0              
idna                   2.6                 
importlib-metadata     2.0.0               
inflect                5.0.2               
isodate                0.6.0               
isort                  4.3.21              
itsdangerous           1.1.0               
Jinja2                 2.11.2              
joblib                 0.17.0              
Keras-Preprocessing    1.1.2               
keyring                10.6.0              
keyrings.alt           3.0                 
kiwisolver             1.3.1               
lazy-object-proxy      1.4.3               
librosa                0.7.2               
llvmlite               0.31.0              
Markdown               3.3.3               
MarkupSafe             1.1.1               
matplotlib             3.3.3               
mccabe                 0.6.1               
nose                   1.3.7               
numba                  0.48.0              
numpy                  1.17.4              
oauthlib               3.1.0               
opencv-python          3.4.8.29            
opt-einsum             3.3.0               
packaging              20.4                
pandas                 1.1.4               
phonemizer             2.2.1               
Pillow                 6.2.1               
pip                    19.3.1              
protobuf               3.14.0              
pyasn1                 0.4.8               
pyasn1-modules         0.2.8               
pycparser              2.20                
pycrypto               2.6.1               
pygobject              3.26.1              
pylint                 2.5.3               
pyparsing              2.4.7               
pysbd                  0.3.3               
PySocks                1.7.1               
python-dateutil        2.8.1               
pytz                   2020.4              
pyworld                0.2.12              
pyxdg                  0.25                
PyYAML                 5.3.1               
regex                  2020.11.13          
requests               2.25.0              
requests-oauthlib      1.3.0               
resampy                0.2.2               
rfc3986                1.4.0               
rsa                    4.6                 
scikit-learn           0.23.2              
scipy                  1.4.1               
SecretStorage          2.3.1               
segments               2.1.3               
setuptools             50.3.2              
six                    1.15.0              
SoundFile              0.10.3.post1        
tabulate               0.8.7               
tensorboard            2.4.0               
tensorboard-plugin-wit 1.7.0               
tensorboardX           2.1                 
tensorflow             2.3.1               
tensorflow-estimator   2.3.0               
termcolor              1.1.0               
tf-estimator-nightly   2.3.0.dev2020062301 
threadpoolctl          2.1.0               
toml                   0.10.2              
torch                  1.6.0               
torchvision            0.4.2               
tornado                6.1                 
tqdm                   4.51.0              
TTS                    0.0.6+566ad2e      
typed-ast              1.4.1               
typing-extensions      3.7.4.3             
umap                   0.1.1               
umap-learn             0.4.6               
Unidecode              0.4.20              
uritemplate            3.0.1               
urllib3                1.26.2              
Werkzeug               1.0.1               
wheel                  0.30.0              
wrapt                  1.12.1              
zipp                   3.4.0

Does anybody know how to solve this? Thanks a lot!

**Comment by wjqkkky** [comment]
I use the latest master branch.

**Comment by SanjaESC** [comment]
Move https://github.com/mozilla/TTS/blob/54139f6333194330b1efbda9c6c78f82e14a0d60/TTS/bin/train_vocoder_wavegrad.py#L381-L383

before 

https://github.com/mozilla/TTS/blob/54139f6333194330b1efbda9c6c78f82e14a0d60/TTS/bin/train_vocoder_wavegrad.py#L348

**Comment by erogol** [comment]
Can you send a PR for this if it is a common problem?
