### ISSUE TITLE
Wavegrad training from scratch

### ISSUE THREAD

**Issue by oytunturk** [mozilla/TTS#626]
Hi,

I'm running into an issue while trying to train the Wavegrad model from scratch using 'train-clean-100' subset of LibriTTS on one GPU. Any suggestions to try? Thanks in advance!

My config file is [here](https://drive.google.com/file/d/1-n8681f4CXr3Z-GGs8wu_CPt9cflreoU/view?usp=sharing).
GPU: Titan X (Pascal), 12196MiB memory
NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2

**The error:**

 > Using CUDA:  True
 > Number of GPUs:  1
 > Git Hash: 6437fe7
 > Experiment folder: /dat/training/oturk/task_tts/mozilla_multispeaker_wavegrad_libritts/TTS_repo/ot_models/wavegrad_train_vctk+libritts/wavegrad-libritts-train-clean-100-January-26-2021_11+06AM-6437fe7
 > Loading wavs from: /dat/corpora/OpenSLR/SLR60/LibriTTS/train-clean-100
Total files found --> TRAIN = 32980, EVAL = 256
 > Setting up Audio Processor...
 | > sample_rate:24000
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:0
 | > fft_size:1024
 | > power:None
 | > preemphasis:0.0
 | > griffin_lim_iters:None
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:50.0
 | > mel_fmax:7600.0
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > stats_path:None
 | > hop_length:256
 | > win_length:1024
 > Generator Model: wavegrad
 > WaveGrad has 15827106 parameters

 > EPOCH: 0/10000

 > TRAINING (2021-01-26 11:06:36) 
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [67,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [25,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "/dat/training/oturk/task_tts/mozilla_multispeaker_wavegrad_libritts/TTS_repo/TTS/bin/train_vocoder_wavegrad.py", line 518, in <module>
    main(args)
  File "/dat/training/oturk/task_tts/mozilla_multispeaker_wavegrad_libritts/TTS_repo/TTS/bin/train_vocoder_wavegrad.py", line 417, in main
    epoch)
  File "/dat/training/oturk/task_tts/mozilla_multispeaker_wavegrad_libritts/TTS_repo/TTS/bin/train_vocoder_wavegrad.py", line 116, in train
    noise, x_noisy, noise_scale = model.compute_y_n(x)
  File "/dat/training/oturk/task_tts/mozilla_multispeaker_wavegrad_libritts/TTS_repo/TTS/vocoder/models/wavegrad.py", line 110, in compute_y_n
    noise_scale = l_a + torch.rand(y_0.shape[0]).to(y_0) * (l_b - l_a)
RuntimeError: CUDA error: device-side assert triggered

**Comment by erogol** [comment]
This should be fixed under the dev branch.
