### ISSUE TITLE
Need to train on Other languages?

### ISSUE THREAD

**Issue by sheikhma3** [mozilla/TTS#63]
Hello, English synthesis is so good. I really appreciate your effort. I need to know if i want to train it for other languages like (Hindi, Urdu, Arabic) what should be changed in the code and parameters ? As i have the data of around 5-6 hours for each language. What results should i expect ? And is this data enough ? I have Only text and audio files how should i create dataset from this so that this can be run on our code and we could train a model for us. 
Thanks.

**Comment by shubhamchauhan** [comment]
@sheikhma3 Do you know of any good dataset which can be used for Hindi TTS?

**Comment by sheikhma3** [comment]
@shubhamchauhan  I currently have for urdu. Our organization have created it by own. It is about 5-6 hours of data,

**Comment by erogol** [comment]
@sheikhma3 Honestly I only tested on LJSpeech dataset extensively. It has 24 hours of recordings. You might consider to finetune a English trained model. So I don't really know what would be the performance with shorter datasets. Given the pronunciation errors with LJSpeech dataset, you might experience more of these. 

In terms of code, you need to change utils.text according to your language. utils.text.symbols is the most important part. I would review the whole folder before I start to train. Also, It would be a great PR to include your language for others.

**Comment by sheikhma3** [comment]
@erogol I am so glad that you are so active to help the community. Thank you so much for your help. Its always been encouraging. I have changed in util.text. Can i show you the changes so that you could verify it and i can start the training.? I would love to add my languages for others. Thanks

**Comment by sheikhma3** [comment]
@erogol Please help me in resolving this error. When i try to fine tune the pre build model which is best_model.pth.tar. Now I am planning to run it in with my training file. 


Traceback (most recent call last):
  File "train.py", line 507, in <module>
    main(args)
  File "train.py", line 414, in main
    model.load_state_dict(checkpoint['model'])
  File "/home/kamran/anaconda3/envs/deepSpeech_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Tacotron:
	size mismatch for embedding.weight: copying a param of torch.Size([150, 256]) from checkpoint, where the shape is torch.Size([149, 256]) in current model.

**Comment by erogol** [comment]
@sheikhma3 which branch is it you use and which checkpoint ?

**Comment by erogol** [comment]
Please re-open if you need it.
