### ISSUE TITLE
Model archive format

### ISSUE THREAD

**Issue by davidak** [mozilla/TTS#633]
You released the models as rar archives. I think it's the worst choice since it's a proprietary format. Even plain zip would be better.

I think the best choice would be xz, since it take lot computing to compress, but few to extract. That's a good thing since it's only compressed once and extracted many times.

But thanks for the release!

**Comment by erogol** [comment]
good point. I've not thought about it. I'll change that.

**Comment by erogol** [comment]
now all zipped.
