### ISSUE TITLE
dead links on the wiki

### ISSUE THREAD

**Issue by kirianguiller** [mozilla/TTS#634]
Hey, thanks for this amazing works.

I just wanted to let you know that the links in this wiki page (https://github.com/mozilla/TTS/wiki/Dataset) are dead (especially the link redirecting to CheckSpectrograms,  AnalyzeDataset and dataset/preprocess.py.).

**Comment by erogol** [comment]
thx!! I fixed them by unlinking them.  

I forgot to update the links for the notebooks. So you can find them in the notebooks folder.

**Comment by kirianguiller** [comment]
Yes I found them, thanks !
