### ISSUE TITLE
train_vocoder_wavernn.py have no model.generate function 

### ISSUE THREAD

**Issue by 13777469818** [mozilla/TTS#638]
In the process of waveRNN training,  on line 293 of the train_vocoder_wavernn.py file，use the model.generate function to create wav. But  there is no such method in the wavernn.py file . It's a Bug?!

**Comment by NarutoUA** [comment]
@erogol It still fails because of inference() arguments mismatch in train_vocoder_wavernn.py:

  File "tts/bin/train_vocoder_wavernn.py", line 294, in evaluate
    use_cuda
TypeError: inference() takes 5 positional arguments but 6 were given

**Comment by erogol** [comment]
better if you send a fix.

**Comment by gerazov** [comment]
Here's a fix - it's a bit involved as also the synthesis reported errors. In short:
- both `train` and `evaluate` in `train_vocoder_wavernn.py` now cast the `ground_mel` to Tensor and to GPU if `cuda`
- restructured `vocoder/utils/generic_utils.py` by integrating `setup_wavernn` within `setup_generator` even though technically it's an autoregressive model. This keeps `load_vocoder` in `TTS/utils/synthesizer.py` in tact. An additional `generator_model` is in turn added to the `wavernn` config `json`. I think this makes sense as it keeps all vocoders under one hood. If not the vocoder model check could be moved to `load_vocoder`.
- included a bit of an ugly workaround that avoids `capitalize` for `WaveRNN` to preserve the class name as is.
- changed the `inference` function to allow it to run with a single input argument when called by `tts` in `synthesizer`.
