### ISSUE TITLE
param issue in Synthesizer.load_model() function when calling AudioProcessor(...) 

### ISSUE THREAD

**Issue by dvbfuns** [mozilla/TTS#65]
when setup the test server using "python server/server.py ..." to start flask server to test,  there is an error reported that the n_fft size is too small, however, the n_fft is correct set in config.json.  tracing back, found there is an minor issue in Synthesizer.load_model() function when calling AudioProcessor(...),   there might be some param addition/remove happened in the function which caused the param item not match.  
to resolve this, simply do the calling like:
self.ap = AudioProcessor(
            sample_rate = config.sample_rate,
            num_mels = config.num_mels,
            min_level_db = config.min_level_db,
            frame_shift_ms = config.frame_shift_ms,
            frame_length_ms = config.frame_length_ms,
            ref_level_db = config.ref_level_db,
            num_freq = config.num_freq,
            power =config.power,
            preemphasis = config.preemphasis,
            griffin_lim_iters=60)

**Comment by erogol** [comment]
It is already updates as in dev branch. You can check that out. Soon will be merged. And server should also work with dev.
