### ISSUE TITLE
[dev branch] tb_loader referenced before assignement

### ISSUE THREAD

**Issue by kirianguiller** [mozilla/TTS#655]
Hello guys,

On dev branch, when training a model using multiple gpus, we get the following error : 

Traceback (most recent call last):
  File "/root/projects/speech/mozilla-TTS_dev/TTS/bin/train_tacotron.py", line 649, in <module>
    args, model_type='tacotron')
  File "/root/projects/speech/mozilla-TTS_dev/TTS/utils/arguments.py", line 204, in process_args
    return c, out_path, audio_path, c_logger, tb_logger
UnboundLocalError: local variable 'tb_logger' referenced before assignment

This is because, when using multiple gpus, the function [process_arg](https://github.com/mozilla/TTS/blob/216945e6538d7d046ce22c284aed5a92359dee52/TTS/utils/arguments.py#L109)  will be call with different values of the parameter "rank". When rank >= 1, [the following if statement](https://github.com/mozilla/TTS/blob/216945e6538d7d046ce22c284aed5a92359dee52/TTS/utils/arguments.py#L176) will not be applied and the function will [return an unassigned tb_loader](https://github.com/mozilla/TTS/blob/216945e6538d7d046ce22c284aed5a92359dee52/TTS/utils/arguments.py#L200).

PS : here my training command line : CUDA_VISIBLE_DEVICES="0,1" python TTS/bin/distribute.py --script train_tacotron.py --config_path /tank/models/tts/mozilla-TTS/tacotron2-DCC/chinese_mandarin/config_baker_dca.json
But the problem come from the if statement I guess

**Comment by erogol** [comment]
should work now ;)
