### ISSUE TITLE
Training on Nancy Dataset

### ISSUE THREAD

**Issue by erogol** [mozilla/TTS#66]
Nancy dataset seems to have silence at the beginning and ending for a certain frame. TTS works well but trimming these might improve things.

Below is the result after 120K iterations. 

![index](https://user-images.githubusercontent.com/1402048/48914118-d1ea1580-ee7a-11e8-8dd7-d073461de078.png)

**Comment by erogol** [comment]
Much better results compared to LJSpeech dataset, however, we are not able to hare our model or results due to license issues.

**Comment by MorganCZY** [comment]
![step-150000-align](https://user-images.githubusercontent.com/33675916/70696970-ad6c1000-1cff-11ea-89e4-70b73e0c080b.png)
I trained T2(tensorflow version) on Nancy but got an alignment like this. Do you have any ideas about it?
