### ISSUE TITLE
not taking "restore_path" into account from config.json

### ISSUE THREAD

**Issue by kirianguiller** [mozilla/TTS#663]
Hi,

When continuing training, mozilla-tts is not taking into account if any "restore_path" is present in the _config.json_ file. I've seen that this restore_path could be given as an command line argument.

Is it a desired behavior to not take into account this config.json argument ? If not, I've added a fix in [in my dev branch](https://github.com/kirianguiller/TTS/commit/7862537917fa8b484c20b56752f8cb9c6f036f6c)

**Comment by erogol** [comment]
@gerazov can you check that? I think it might be about your part :)

**Comment by erogol** [comment]
restore_path should be provided as a console argument. The one in the config.json is to see the model history.

**Comment by kirianguiller** [comment]
Ok ! I got confused and thought it could also act as a config parameter. I am closing the issue. thanks !
