### ISSUE TITLE
Stuttering on specific final words

### ISSUE THREAD

**Issue by newsbubbles** [mozilla/TTS#669]
There is a stuttering and almost a ... rehearsal of the last couple of words or part of a word happening. I have a wav file preview of this issue and placed the files in a repository: https://github.com/newsbubbles/tts_bugs ... the examples in question are 110.wav and 153.wav ... they are from a session reading a story on /r/nosleep  It happens at the end of specific texts and I'm not sure exactly why.  Could this be something to do with a config option I can change, or is it something which is part of the model?

I'm using tacotron2-DCA and Multiband Melgan as model and config respectively.

I'm running on an Asus with Ryzen 7 4k series and Radeon GPU using the non-gpu version of tts.  I made a script that performs the same as synthesize.py

model_path = path + 'tts_models--en--ljspeech--tacotron2-DCA/model_file.pth.tar'
config_path = path + 'tts_models--en--ljspeech--tacotron2-DCA/config.json'
vocoder_path = path + 'vocoder_models--en--ljspeech--mulitband-melgan/model_file.pth.tar'
vocoder_config_path = path + 'vocoder_models--en--ljspeech--mulitband-melgan/config.json'

**Comment by DaGeek247** [comment]
I have a similar issue with the following phrase;
`Alice's Adventures in Wonderland, by Lewis Carroll`
If i append a a period to the end of it, it will not stutter, but without that period it will go on for another good ten seconds.

**Comment by erogol** [comment]
@newsbubbles can you share the sentences in text form that cause the shuttering?

@DaGeek247 It is normal since all the the sentences in the dataset has punctuations in the end, the model doesn't know when to stop with no punctuation. A simple trick is adding dot to the end always.

**Comment by newsbubbles** [comment]
I fixed it by simply making sure each phrase had a period or some punctuation at the end of it.  Thanks everyone!
