### ISSUE TITLE
Train Tacotron with r=1 for better mel-spectrograms.

### ISSUE THREAD

**Issue by erogol** [mozilla/TTS#67]

**Comment by yweweler** [comment]
I have two spare V100's at the moment and are experimenting with the code base.
@erogol I could run some experiments if there is any interest from from your side.

In case this is of interest we could agree on a dataset and a set of parameters you would like to test.
Ideally a rather demanding configuration as I am still trying to eradicate some bottlenecks.

**Comment by erogol** [comment]
Lucky you. 2 spare V100s sounds quite amazing!! And thx for asking to help.

right now, I try to solve #50  to make TTS work with r=1. I plan to run different experiments targeting this. If you like to, we could cooperate at this front.

there is also relatively old tacotron2 branch. It is a much larger model and targets mel-specs only. It was really hard and slow to experiment and therefore I keep it dormant. So that might be better for you if you like to go for a more demanding model with your monsters. I'd say, It would be easy to rebase the branch with the current master.

I work on LJSpeech dataset. Based on my experiments Nancy gives much better results but LJSpeech has more flexible licensing. 

If you have any other option in mind, we can also talk about.

**Comment by themikem** [comment]
I have V100s, Titan Vs and Titan RTXs I can throw at this as well if it will help bootstrap Tacotron2 and move toward r=1.

I'm familiar with the tacotron2 branch - I have experimented with it a bit.

Let me know - I'm doing a bit of much-needed system maintenance for the next few days, but should have systems online Friday to start crunching if you want to rebase tc2.  Standing by.

**Comment by erogol** [comment]
@themikem Thx for proposing your help,maybe you can follow the conversation #50 . This is the most important issue to be solved to make TTS compatible with neural vocoders.

**Comment by erogol** [comment]
I trained tacotron2 with r=2 but dropout issue is still exist
