### ISSUE TITLE
sound quality

### ISSUE THREAD

**Issue by bayethiernodiop** [mozilla/TTS#672]
<b>Hi, Do you think that these sound quality are enougn to train tacotron model, I am having bad synthetised audio like these after 40 000 iterations</b> 
samples from training : 
https://soundcloud.com/thierno-ibrahima-diop/8bd525552ab756366d8c4035c0fbfffa27e76ca26e0d55d966fff860727d99a3
https://soundcloud.com/thierno-ibrahima-diop/3fd71e2c5a9afa3ac27c956748ce9d34d6e4230e49195196bf252b953976908a
https://soundcloud.com/thierno-ibrahima-diop/ccfc4f9e2cfa627e5cfdca3134c3e5ef2283f91b041644b5f53ee8112263ba35
https://soundcloud.com/thierno-ibrahima-diop/ba425ecc188c9b1646f4c47da051a62f44b969e7e7374cce90067d2f51127364

synthetised samples (during evaluation):
https://soundcloud.com/thierno-ibrahima-diop/testsentence-0
https://soundcloud.com/thierno-ibrahima-diop/testsentence-1
https://soundcloud.com/thierno-ibrahima-diop/testsentence-2

thanks for your help

**Comment by WeberJulian** [comment]
Hi, I'm no expert but the quality seem a bit low to me. The samples you shared seemed very short. Do you have a good distribution of sentence length ? Also, did you train the model from scratch ?
