### ISSUE TITLE
Problem with German Model

### ISSUE THREAD

**Issue by gklasen** [mozilla/TTS#673]
Currently i am trying to setup multiple models with master branch (Time of writing  [2edab4](https://github.com/mozilla/TTS/commit/2edab4b3f9b5ad4352126ba6d52878b71d8e2cb3) ).

I successfully could use Tacotron2 DDC both for English and French from [released Models](https://github.com/mozilla/TTS/wiki/Released-Models).

But when i try to run the german one from there, i get following error:

> Traceback (most recent call last):
>   File "./TTS/TTS/bin/synthesize.py", line 218, in <module>
>     main()
>   File "./TTS/TTS/bin/synthesize.py", line 177, in main
>     synthesizer = Synthesizer(model_path, config_path, vocoder_path, vocoder_config_path, args.use_cuda)
>   File "/usr/local/lib/python3.7/dist-packages/TTS/utils/synthesizer.py", line 47, in __init__
>     use_cuda)
>   File "/usr/local/lib/python3.7/dist-packages/TTS/utils/synthesizer.py", line 93, in load_tts
>     self.tts_model.load_checkpoint(tts_config, tts_checkpoint, eval=True)
>   File "/usr/local/lib/python3.7/dist-packages/TTS/tts/models/tacotron_abstract.py", line 125, in load_checkpoint
>     state = torch.load(checkpoint_path, map_location=torch.device('cpu'))
>   File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 595, in load
>     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
>   File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 774, in _legacy_load
>     result = unpickler.load()
> ModuleNotFoundError: No module named 'mozilla_voice_tts'

As discussed [here](https://discourse.mozilla.org/t/using-a-model-trainned-back-when-the-module-was-named-mozilla-voice-tts/67970), this already was a problem somewhere in the past, but it seems it is still valid for an edge-case?

**Comment by thorstenMueller** [comment]
I trained a german DDC model some month ago before the big TTS code refactoring. A dirty workaround could be to copy TTS directory (_the inner one inside the cloned TTS folder_).
> cp -r TTS mozilla_voice_tts

This might work and lead to an error about "german phoneme cleaner". But one step after another.

**Comment by gklasen** [comment]
Unfortunately, that is not working out. Copied it into the inner folder, but same error.

**Comment by gklasen** [comment]
Unfortunately, the problem still occurs. Copied as to told, rebuilt the model, with the same result.

**Comment by lpierron** [comment]
For me it works, with Python3.8.6 and commit: 5dbb48d 

I just added the line: ` "gst_use_speaker_embedding": false `in `gst` group of `config.json`

See the `requirements.txt` file and the audio result (https://sndup.net/9kwz) .

[requirements.txt](https://github.com/mozilla/TTS/files/6069545/requirements.txt)

**Comment by gklasen** [comment]
I already did that without success. Is similar behavior possible with the commit id i mentioned (current master)?

**Comment by lpierron** [comment]
Success with Python 3.7.9 and commit 2edab4b on Mac OS Big Sur 11.2.1, clean Python install with `venv`.

Just added: `export CFLAGS=-Ilib/python3.7/site-packages/numpy/core/include` before running `python3 setup.py install`  and after upgrading `pip`.

**Comment by gklasen** [comment]
I got it working now as well, but as part of a docker file, this is still failing.

> ENV CFLAGS=-I/usr/local/lib/python3.7/dist-packages/numpy/core/include
> RUN python3.7 -m pip install /app/TTS/models/de/TTS-0.0.9.2-cp37-cp37m-linux_x86_64.whl

**Comment by gklasen** [comment]
@lpierron did you have the same error with "torch" within the master branch, before exporting the CFLAGS?
