### ISSUE TITLE
Problem with Graves and Dynamic Convolution Attention

### ISSUE THREAD

**Issue by nicemanis** [mozilla/TTS#675]
Hi, I am testing the `GravesAttention` and `MonotonicDynamicConvolutionAttention` from this repository together with the Nvidia's Tacotron 2 implementation, with the goal to find a way how to improve the model's robustness.

However, so far I have not been able to reach any successful alignment. The model would have alredy converged to something useful with the original attention method.

The Graves attention looks like this:
![image](https://user-images.githubusercontent.com/9463816/109663117-6a03f880-7b74-11eb-9eb1-9e7a309906b2.png)

and the DCA attention looks like this:
![image](https://user-images.githubusercontent.com/9463816/109663182-7ee08c00-7b74-11eb-8b77-9fe59935fc97.png)

What could be the possible cause of this? Has anyone managed to successfully train a model with either Graves or DCA?

**Comment by erogol** [comment]
It is possible to train DCA and Graves with no problem. And the problem it is harder when you try to combine both repos.

I'd suggest you try the TTS and make it work then move to wherever you like after that.

**Comment by nicemanis** [comment]
Thanks for the reply. I managed to get it working with the mozilla/TTS repository, although, the result is not great yet (I am using a custom dataset) and sometimes the training crashes with `RuntimeError:  [!] NaN loss with decoder_loss.`, especially if I use `"signal_norm": true`.

Do you have any suggestions for implementing this together with the Nvidia/Tacotron2? Are there any key differences that you can point out, which should be considered?

The Mozilla's OriginalAttention implementation works well together with the Nvidia's Tacotron 2 implementation. Is it possible to interchange the attention without changing the rest of the model/hparams?

**Comment by nicemanis** [comment]
I compared the OriginalAttention implementations and noticed some differences in the masking and normalization:

Mozilla/TTS
```
# apply masking
if mask is not None:
  attention.data.masked_fill_(~mask, self._mask_value)

...

# normalize attention values
if self.norm == "softmax":
  alignment = torch.softmax(attention, dim=-1)
```

Nvidia/Tacotron2
```
if mask is not None:
  alignment.data.masked_fill_(mask, self.score_mask_value)

attention_weights = F.softmax(alignment, dim=1)
```

If I use the Mozilla's attention implementation together with the Nvidia's Tacotron 2, it produces `nan` values. Why is the mask inverted in the Mozilla's case?

EDIT: I noticed that Nvidia's implementation already applies the tilde op when computing the mask:
```
self.initialize_decoder_states(memory, mask=~get_mask_from_lengths(memory_lengths))
```
