### ISSUE TITLE
CUDA Out of Memory 

### ISSUE THREAD

**Issue by luis-vera** [mozilla/TTS#677]
Hi:

If I buy more RAM to my PC, Could be the error message "CUDA out of memory" solved? 

Thanks a lot

**Comment by te0006** [comment]
Sorry but this message refers to the RAM of your GPU card, which cannot be upgraded.
The only thing you might try is to experiment with other model parameters.
What type of GPU do you have? Older GPUs and especially "mobile" ones (i.e. in laptops) may simply be too RAM-limited to have any chance of coping with the complex models discussed here.

**Comment by luis-vera** [comment]
I am using GeForce RTX 2080 Ti Rev.A

**Comment by oytunturk** [comment]
What’s your training data? You may want to reduce max sequence length in the config file. Longer recordings and text require more memory.

**Comment by luis-vera** [comment]
My training data is LJSpeech-1.1 for scratch at this first time. After that, I try with my own corpus.

Now because of this error I am using 850 epochs against 1000. Training falls at 870/1000 step 99

**Comment by oytunturk** [comment]
I'd try reducing max_seq_len in the config and/or also not using r=1 for the final stages assuming you are reducing r progressively using "gradual_training" parameter. Setting r=2 may resolve it.

**Comment by luis-vera** [comment]
OK. I am training with r=2 for the final stages. When I reduced max_seq_len I got an error index out of range in the first epoch

Thanks a lot

**Comment by zainmujahid** [comment]
For me the solution was reducing "max_seq_len"
