### ISSUE TITLE
Resuming transfer learning causes previous learning to be lost

### ISSUE THREAD

**Issue by GuyPaddock** [mozilla/TTS#679]
Just completed 1,000 iterations of transfer learning from the LJSpeech Tacotron DDC data set via this command:
```
python ./TTS/bin/train_tacotron.py --restore_path /home/guy/my_project/Models/ljspeech-tac2-June-23-2020_01+32PM-ccba431/checkpoint_130000.pth.tar --config_path /home/guy/my_project/config.json
```

Then I tried continuing training with:
```
python ./TTS/bin/train_tacotron.py --continue_path /home/guy/my_project/Models/ddc-March-07-2021_11+23AM-547bfc4/
```

But, instead of continuing from where we left off, it started all over again from the LJSpeech data set, losing the last several hours of training (bad on me for not backing it up...).

Looking at the `config.json` file, I think I see the problem:
```json
{
"github_branch":"* dev",
"restore_path":"/home/guy/my_project/Models/ddc-March-07-2021_11+23AM-547bfc4/best_model.pth.tar",
"characters":{"pad": "_", "eos": "~", "bos": "^", "characters": "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!'(),-.:;? ", "punctuations": "!'(),-.:;? ", "phonemes": "iyɨʉɯuɪʏʊeøɘəɵɤoɛœɜɞʌɔæɐaɶɑɒᵻʘɓǀɗǃʄǂɠǁʛpbtdʈɖcɟkɡqɢʔɴŋɲɳnɱmʙrʀⱱɾɽɸβfvθðszʃʒʂʐçʝxɣχʁħʕhɦɬɮʋɹɻjɰlɭʎʟˈˌːˑʍwɥʜʢʡɕʑɺɧʲɚ˞ɫ"},
"github_branch":"* dev",
"restore_path":"/home/guy/my_project/Models/ljspeech-tac2-June-23-2020_01+32PM-ccba431/checkpoint_130000.pth.tar",
...
}
```

It looks like the `restore_path` from the original LJSpeech file is overwriting the `restore_path` for the project. Consequently, we lose the data unless we manually edit the file.

**Comment by lexkoro** [comment]
> it started all over again from the LJSpeech data set, losing the last several hours of training

what do you mean by losing the last several hours of training? are the files gone?

**Comment by GuyPaddock** [comment]
> what do you mean by losing the last several hours of training? are the files gone?

Yes.
* The global step number being reported in the output started over from 130000.
* The best model from the original training was overwritten with a new one based on the restarted training.
* The test sentence files for each batch started to be overwritten with new files.
* A new Tensorboard events file was created alongside the original events file, and since the step number restarted, this lead to overlapping data appearing in the charts.
