### ISSUE TITLE
How to prepare TTS-synthesized mel-spectrograms for vocoder training?

### ISSUE THREAD

**Issue by dimitry12** [mozilla/TTS#682]
Given a custom trained TTS, I want to train a vocoder. I want to use teacher-forced mel-spectrograms generated by TTS for vocoder training, as they do in Tacotron2 paper or as @erogol does in https://github.com/mozilla/TTS/issues/26#issuecomment-473099095

First, is there a script or a notebook for generating teacher-forced mel-spectrograms given a TTS model?

Second, once these mel-spectrograms are generated, is https://github.com/mozilla/TTS/blob/c65712426aa8fe18a6b40b71a9a6b2c9681e9ec2/TTS/vocoder/configs/wavegrad_libritts.json#L64 the right place to point vocoder to it?

**Comment by lexkoro** [comment]
> First, is there a script or a notebook for generating teacher-forced mel-spectrograms given a TTS model?

https://github.com/mozilla/TTS/blob/master/notebooks/ExtractTTSpectrogram.ipynb should be a good start

> Second, once these mel-spectrograms are generated, is the right place to point vocoder to it?

Yes that should be correct

**Comment by dimitry12** [comment]
@SanjaESC thank you!
