### ISSUE TITLE
 # load the model model.load_state_dict(cp['model'],strict=False)

### ISSUE THREAD

**Issue by sheikhma3** [mozilla/TTS#69]
Error Occuring. On latest Changeset
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-56-8d4d39cbb982> in <module>()
      1 
      2 # load the model
----> 3 model.load_state_dict(cp['model'],strict=False)

~\AppData\Local\Continuum\Anaconda3\lib\site-packages\torch\nn\modules\module.py in load_state_dict(self, state_dict, strict)
    717         if len(error_msgs) > 0:
    718             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
--> 719                                self.__class__.__name__, "\n\t".join(error_msgs)))
    720 
    721     def parameters(self):

RuntimeError: Error(s) in loading state_dict for Tacotron:
	size mismatch for embedding.weight: copying a param of torch.Size([150, 256]) from checkpoint, where the shape is torch.Size([149, 256]) in current model.

**Comment by erogol** [comment]
Which model is it to lead?

**Comment by sheikhma3** [comment]
best_model.pth.tar.

**Comment by erogol** [comment]
@sheikhma3 I mean is it your own model or one of the checkpoints we share.

**Comment by sheikhma3** [comment]
one you shared

**Comment by erogol** [comment]
which one is this? It seems like checkpoint has more characters in its vocabulary. It's supposed to be 149.
