### ISSUE TITLE
Pip install TTS does not work python39.2

### ISSUE THREAD

**Issue by krperry** [mozilla/TTS#694]
I did 

pip install TTS 

Says it can not find a version that satisfies.  This is on Windows 10 with 64 bit python.  Note I also tried on raspberry PI but it said it couldn't find torch.    
<b>Questions</b> will not be answered here!!

Help is much more valuable if it's shared publicly, so that more people can benefit from it.

Please consider posting on [TTS Discourse](https://discourse.mozilla.org/c/tts) page or matrix [chat room](https://matrix.to/#/!KTePhNahjgiVumkqca:matrix.org?via=matrix.org) if your issue is not directly related to TTS development (Bugs, code updates etc.).

You can also check https://github.com/mozilla/TTS/wiki/FAQ for common questions and answers.

Happy posting!

https://discourse.mozilla.org/c/tts

**Comment by JoakimCh** [comment]
Same problem on Linux Debian (pip 20.3.4, python 3.9)
Terrible...

**Comment by Codes4Fun** [comment]
According to the readme, it only supports python versions less than 3.9, and equal to or above 3.6.

I have managed to install it under Windows 10 using python 3.8.9

I am still trying to figure out how to use it, so I have no idea if it will works under Windows 10

**Comment by erogol** [comment]
for the latest version of TTS I suggest moving to :frog:[CoquiTTS](https://github.com/coqui-ai/TTS) 

Some issues related to Win10 are fixed there.

**Comment by avaer** [comment]
☝️ that did not work either for me \(same error).

**Comment by ddevault** [comment]
This issue has been manually reopened because it's still a problem. It will be reopened again if the problem persists.
