### ISSUE TITLE
Reduce processing time

### ISSUE THREAD

**Issue by mrNicky** [mozilla/TTS#697]
If anyone, have any ideas on to reduce processing time. 20 secondes for me, between running command and saving wav output. 
with a one line sentence. 

I used default tts command like this:

`tts --text "blabla wha. . .."`

```
> tts_models/en/ljspeech/tacotron2-DDC is already downloaded.
 > vocoder_models/en/ljspeech/hifigan_v2 is already downloaded.
 > Using model: Tacotron2
 > Generator Model: hifigan_generator
Removing weight norm...
 > Text:  blablablablablablablablablablablablablablablablablablablablablablablablablablablablablabla
 > Text splitted to sentences.
 > Processing time: 8.45993447303772
 > Real-time factor: 0.6050886026393558
 > Saving output to tts_output.wav
```

**Comment by erogol** [comment]
if you use ```tts``` by ```pip install TTS```, you already use [CoquiTTS](https://github.com/coqui-ai/TTS)

So I suggest moving there and raise the issue since Moz TTS is not actively maintained anymore.
