### ISSUE TITLE
Models saved twice on Windows

### ISSUE THREAD

**Issue by jonas-klesen** [mozilla/TTS#698]
Bug: Models are saved twice on Windows.

Description: I was just doing inference, and then checked the tts directory for the models. It looks like this:
![image](https://user-images.githubusercontent.com/19559859/115934162-ae36b980-a490-11eb-830f-a33c70ea5d99.png)

In both of the subfolders of tts/, we find the model. But additionally, in each of them, there is another subfolder with the same name that also contains the model. Model files have the same hash. This leads to double the memory consumption.

Reproduce:
1) Install on Windows
2) Command line: tts --text "Guten Tag" --model_name tts_models/de/thorsten/tacotron2-DCA --vocoder_name vocoder_models/de/thorsten/wavegrad --out_path Desktop/test.wav
3) Open explorer, go to tts directory, in my case C:\Users\userName\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\tts\

**Comment by erogol** [comment]
Try using coqui TTS  https://github.com/coqui-ai/TTS

Moz TTS is not maintained anymore and this problem is probably fixed there.

**Comment by jonas-klesen** [comment]
Thanks!
