### ISSUE TITLE
Tacotron or Tacotron2?

### ISSUE THREAD

**Issue by PetrochukM** [mozilla/TTS#7]
Hi,

Curious question. This repository is named "tacotron"; therefore, are you implementing tacotron or tacotron-2. From my understanding, it's easier to implement the tacotron-2 architecture and it is of higher quality!

Thanks!

**Comment by erogol** [comment]
I started with tacotron but now it is a variant. On master branch the only difference is the attention module and how it is connected to precious layers but other branches have different architectures
