### ISSUE TITLE
Train TTS with phonemes

### ISSUE THREAD

**Issue by erogol** [mozilla/TTS#70]
**Note:** One can train phoneme model using dev-phoneme branch.
Due to some hard words like "echo, focus, epitomize", it is worthy to try phonemes over raw characters.

**Comment by erogol** [comment]
I go with epitran as phonem transliterator.

On LJSpeech, training with phonemes makes a real difference for pronunciation. The effect is observed on attention mask and pace of convergence. The attention mask is much cleaner and it gets shape faster. 

However, it couldn't get on par synthesis quality with the best LJSpeech model. That might be reason by the low quality and echoing recording of LJSpeech

**Comment by erogol** [comment]
Inference time attention mask just after 9K iterations.
![screenshot_2019-01-07 tensorboard](https://user-images.githubusercontent.com/1402048/50770848-037f3a80-1289-11e9-92cb-47fc760d770f.png)

**Comment by PetrochukM** [comment]
Have you considered this? https://github.com/cmusphinx/g2p-seq2seq

**Comment by erogol** [comment]
I think Phonemized did a good job. It is able to generalize over certain rules and it gave a very solid model.
