### ISSUE TITLE
Strange voice end of 'hello'.

### ISSUE THREAD

**Issue by hebo1982** [mozilla/TTS#702]
python3 synthesize.py --text "hello" \
    --model_path tts_models--en--ljspeech--tacotron2-DCA/model_file.pth.tar \
    --config_path tts_models--en--ljspeech--tacotron2-DCA/config.json \
    --out_path . \
    --vocoder_path vocoder_models--en--ljspeech--mulitband-melgan/model_file.pth.tar \
    --vocoder_config_path vocoder_models--en--ljspeech--mulitband-melgan/config.json

I got the wav file what has a long strange voice.

[hello.wav.zip](https://github.com/mozilla/TTS/files/6397941/hello.wav.zip)

**Comment by hebo1982** [comment]
But i input "hello."  with a dot  just be ok.

**Comment by erogol** [comment]
I suggest you move over [:frog: TTS ](https://github.com/coqui-ai/TTS). Mozilla TTS is not maintained anymore (at least ATM).

**Comment by hebo1982** [comment]
> I suggest you move over [🐸 TTS ](https://github.com/coqui-ai/TTS). Mozilla TTS is not maintained anymore (at least ATM).

well, thanks u
