### ISSUE TITLE
Input from file

### ISSUE THREAD

**Issue by wyattscarpenter** [mozilla/TTS#704]
Great project! But it would be much more useful if it could read a text file instead of just the argument from the command line! To harmonize with --out_path, perhaps you could supply a command-line option --in_path.

**Comment by emilonpt** [comment]
I'm seconding the above - would be very useful for longer format text.

**Comment by emilonpt** [comment]
@wyattscarpenter  - I created a pull request #711 which worked on my machine - might help you?

**Comment by wyattscarpenter** [comment]
@emilonpt Oh, thanks! I created a bash script https://github.com/wyattscarpenter/util/blob/master/tts-file to work around the problem before I decided this tool wasn't appropriate for my use case, but this is way better!

**Comment by erogol** [comment]
Unfortunately, this project is not maintained anymore. 

Feel free to move over 🐸 Coqui-TTS https://github.com/coqui-ai/TTS which is the actively developed hard fork. 

Disclaimer - I am the creator of both of the projects.

**Comment by wyattscarpenter** [comment]
Moved issue to https://github.com/coqui-ai/TTS/issues/748
