### ISSUE TITLE
ZeroDivisionError on empty text

### ISSUE THREAD

**Issue by wyattscarpenter** [mozilla/TTS#705]
`tts.exe --text ""` results in the following error message:
```
print(f" > Real-time factor: {process_time / audio_time}")
ZeroDivisionError: float division by zero
```

**Comment by erogol** [comment]
You can't run a model with an empty text.

Unfortunately, this project is not maintained anymore. 

Feel free to move over 🐸 Coqui-TTS https://github.com/coqui-ai/TTS which is the actively developed hard fork. 

Disclaimer - I am the creator of both of the projects.

**Comment by wyattscarpenter** [comment]
I'm glad to hear there is an actively developed fork! Have you considered archiving this project, and/or shouting the fork out in the readme?

**Comment by erogol** [comment]
We have no control or relation with this repo. It is up to Mozilla to decide.

**Comment by wyattscarpenter** [comment]
Issue moved to https://github.com/coqui-ai/TTS/issues/749
