### ISSUE TITLE
utils/io.py cannot load config.json due to encoding error (and 1 more)

### ISSUE THREAD

**Issue by UnforeseenOcean** [mozilla/TTS#707]
Hello, this could be a mistake on my end but it is not listed anywhere on the wiki so I thought this might be a bug.

While using the Jupyter Lab (loading `PhonemeCoverage.ipynb`), the `config.json` will not load because the encoding defaults to `cp949`, which is a regional codec for Korea. 
![IMG1621737121](https://user-images.githubusercontent.com/11834016/119246462-c8ada100-bbbc-11eb-9148-a9de4f132ff8.png)

~~I tried forcing it to read it as UTF-8 text to no avail (this could well be my mistake too)~~
![IMG1621738188](https://user-images.githubusercontent.com/11834016/119246485-feeb2080-bbbc-11eb-8273-8f854d87d89d.png)
(Edit: it's `with open(config_path, encoding='utf-8', mode="r") as f:`, not what's shown in the image. This issue is fixed, please ignore)

On `CheckSpectrogram.ipynb` the notebook fails because it cannot find the module `tts`.

Is this a bug, or a misconfiguration?

Currently using:
- Anaconda (Python 3.7)
- Windows 10
- Latest release of Jupyter Lab for Python 3.7
- Have run `setup.py`

**Comment by erogol** [comment]
Unfortunately, this project is not maintained anymore. 

Feel free to move over 🐸 Coqui-TTS https://github.com/coqui-ai/TTS which is the actively developed hard fork. 

Disclaimer - I am the creator of both of the projects.
