### ISSUE TITLE
support chinese language

### ISSUE THREAD

**Issue by yuzhoufengg2** [mozilla/TTS#708]
I want to txt translation voice, mozilla/TTS support chinese language?

**Comment by small-tou** [comment]
tts --text "可以的亲虽然有点bug" \
    --model_name "tts_models/zh-CN/baker/tacotron2-DDC-GST" \
    --vocoder_name "vocoder_models/universal/libri-tts/fullband-melgan" \
    --out_path xx.wav

**Comment by ghost** [comment]
> tts --text "可以的亲虽然有点bug"
> --model_name "tts_models/zh-CN/baker/tacotron2-DDC-GST"
> --vocoder_name "vocoder_models/universal/libri-tts/fullband-melgan"
> --out_path xx.wav

为什么我安装显示我pip找不到TTS？

**Comment by erogol** [comment]
The example command above uses CoquiTTS  

Unfortunately, Mozilla TTS project is not maintained anymore. 

Feel free to move over 🐸 Coqui-TTS https://github.com/coqui-ai/TTS which is the actively developed hard fork. 

Disclaimer - I am the creator of both of the projects.
