### ISSUE TITLE
Demo server link on https://github.com/mozilla/TTS/wiki/FAQ is broken

### ISSUE THREAD

**Issue by curiousbee2020** [mozilla/TTS#709]
Get a 404 when I click on the demo server link under How can I test a trained model?

**Comment by erogol** [comment]
Unfortunately, this project is not maintained anymore. 

Feel free to move over 🐸 Coqui-TTS https://github.com/coqui-ai/TTS which is the actively developed hard fork. 

Disclaimer - I am the creator of both of the projects.
