### ISSUE TITLE
Empty .wav files

### ISSUE THREAD

**Issue by Wayne-wonderai** [mozilla/TTS#714]
I tried to train LJspeech  following the step by [example](https://gist.github.com/erogol/97516ad65b44dbddb8cd694953187c5b), but using docker method for environment control. The training steps works well, but output "test audios/n/TestSentence.wav" are all empty soundtracks, did anyone know how to solve this problem?

Screenshot of .wav files opened by audacity. ![](https://i.imgur.com/eLfFxbk.png)

**Comment by oytunturk** [comment]
If I remember correctly, TTS outputs are floating point numbers between
-1.0,1.0. You need to convert them to 16-bit PCM to visualize in Audacity.
Sox may work for the conversion or you can change the corresponding code in
Mozilla TTS to do the correct scaling.
