### ISSUE TITLE
ruslan tacotron2-DDC download link is broken

### ISSUE THREAD

**Issue by egorgam** [mozilla/TTS#720]
Hi!

This link is not available: https://github.com/coqui-ai/TTS/releases/download/v0.0.10/tts_models--ru--ruslan--tacotron2-DDC.zip

Because it, if I trying to use this model with tts, I have this exception "zipfile.BadZipFile: File is not a zip file"

**Comment by Sadam1195** [comment]
It has been removed due to the license conflict.
