### ISSUE TITLE
SyntaxError: Non-ASCII character '\xc3' in file setup.py

### ISSUE THREAD

**Issue by Dardan1410** [mozilla/TTS#724]
Hello, can somebody maybe help me?
When i try to run setup.py i get SyntaxError: Non-ASCII character '\xc3' in file setup.py on line 99, but no encoding declared.
On line 99 is {    author='Eren Gölge'  }
![error](https://user-images.githubusercontent.com/64430003/130240664-bf5f9904-ab4f-430e-9d43-da595b22197f.png)
![Screenshot from 2021-08-19 15-17-06](https://user-images.githubusercontent.com/64430003/130240678-345321d5-64fc-439a-a826-76fe6ae63aaf.png) 
,Does anyone know how to fix this problem?

**Comment by rootbid** [comment]
According to [PEP 263](https://www.python.org/dev/peps/pep-0263/)

> Python will default to ASCII as standard encoding if no other encoding hints are given.
> To define a source code encoding, a magic comment must be placed into the source files either as first or second line in the file, such as:
> `# coding=<encoding name>`

Try adding `# coding=utf-8` in the second line of the file.
