### ISSUE TITLE
Wrong pronunciation of short forms words like 'USA', 'UN' , 'MSN'

### ISSUE THREAD

**Issue by Nimesh1993** [mozilla/TTS#729]
I tried to test with ljspeech tacotron2-DDC English model for below text:
"Short form of country names, USA stands for united states of america, UN stands for united nations , UK stands for united kingdom, ANN stands for artificial neural networks, MSN stands for microsoft networks."

It is pronouncing all short forms like 'USA', 'UN' , 'MSN', 'ANN', 'UK' in wrong way. Check the attached output.zip file.
[output.zip](https://github.com/mozilla/TTS/files/7217440/output.zip)

Is there any way to resolve this type of issue?

**Comment by m-toman** [comment]
Check out https://github.com/mozilla/TTS/blob/master/TTS/tts/utils/text/abbreviations.py
