### ISSUE TITLE
Windows 10 RuntimeError: failed to load espeak library [WinError 193] during training

### ISSUE THREAD

**Issue by bondi7** [mozilla/TTS#735]
Hey!

When training Tacotron 2 model on Windows 10, I can't use Linux unfortunately, the following error appears:

> RuntimeError: failed to load espeak library: [WinError 193] %1 is not a valid Win32 application

The error appears when calling the `phonemize` function.

I have already installed SourceForge's eSpeak for Windows and followed instructions on https://github.com/bootphon/phonemizer/issues/44 and https://github.com/mozilla/TTS/issues/148 .

Currently my system variables contain:

`PATH=C:\Program Files (x86)\eSpeak\command_line\`

`PHONEMIZER_ESPEAK_PATH=C:\Program Files (x86)\eSpeak\command_line\espeak.exe`

`PHONEMIZER_ESPEAK_LIBRARY=C:\Program Files (x86)\eSpeak\TTSApp.exe`

Thanks for the help!

**Comment by Jzow** [comment]
@bondi7 hi , I refer to this setting but still report an error. Can you check it for me? Thank you very much for my issue: #742

**Comment by SmartManoj** [comment]
bump
