### ISSUE TITLE
Archive unmaintained TTS repo

### ISSUE THREAD

**Issue by JRMeyer** [mozilla/TTS#745]
👋 Hello!

It seems that `mozilla/TTS` is no longer actively maintained, but there's no explicit message to users. Current and new users continue to send PRs and open issues with the expectation that the project is still active.

Github actually offers a nice, built-in solution for projects which are no longer actively maintained: archiving. As the [github docs](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories) explain:

>You can archive a repository to make it read-only for all users and indicate that it's no longer actively maintained. You can also unarchive repositories that have been archived.

This way, the code is still available to everyone, but sets expectations for users that there will be no updates.

It might also be helpful to include a link in the README to [the actively maintained fork of TTS](https://github.com/coqui-ai/TTS).

**Comment by makerjackie** [comment]
up
