### ISSUE TITLE
Garbage Collection issue

### ISSUE THREAD

**Issue by MultiTrickFox** [mozilla/TTS#746]
My code is simple: (nothing out of the ordinary)

wav, alignment, _, _ = synthesis(
            model,
            sentence,
            voice_config,
            use_gpu, # -> false.
            voice_processor,
            speaker_id = None,
            d_vector = my_dvector,
            style_wav = None,
            language_id = 0,
            enable_eos_bos_chars = voice_config.enable_eos_bos_chars,
            use_griffin_lim = True,
            do_trim_silence = False,
        ).values()

I notice that after running this code multiple times (in a loop), the next runs always add on to the memory (tested on ubuntu latest and osx). I could post the memory screenshots here but it is trivial to observe. How could I overcome this? Any help would be appreciated, thank you..

**Comment by JRMeyer** [comment]
you should take a look at #745
