### ISSUE TITLE
Language independent text processing with text-to-unicode conversion.

### ISSUE THREAD

**Issue by erogol** [mozilla/TTS#75]
TTS might be language agnostic, it the given text is processed by unicode representation instead of characters. That would give a much flexible solution for different languages without changing code.

**Comment by BlueTaurus** [comment]
doing it too for urdu dataset...

**Comment by erogol** [comment]
@BlueTaurus it is in the backlog, I've not yet started, unfortunately. But great, you give a hand.

**Comment by kurianbenoy** [comment]
I was planning to create a TTS system for Malayalam @ergol. Will it be possible to create such a TTS system based on Neural network based like this repository?

**Comment by erogol** [comment]
I don't know if the language has special properties but should be possible with TTS.

**Comment by alex73** [comment]
"Language-independent TTS" - does it mean "IPA-based TTS" ? (International Phonetic Alphabet)

**Comment by erogol** [comment]
No that was supposed to be Unicode based. But IPA is already enabled.

**Comment by richardburleigh** [comment]
I'm curious how IPA works so well despite being converted to ASCII. Is there some magic I'm missing? I haven't checked but I imagine there would be some duplication of phonemes that unicode could solve.

**Comment by sachaarbonel** [comment]
[sentencepiece](https://github.com/google/sentencepiece) might be a good candidate to solve this

**Comment by reuben** [comment]
IPA is not converted to ASCII, it's mapped to integer labels. This issue is talking about training a model that takes Unicode text directly, without phonemization. Example: https://arxiv.org/abs/1811.09021

**Comment by richardburleigh** [comment]
Thanks for the reply @reuben! I got the impression from [this line in cleaners.py](https://github.com/mozilla/TTS/blob/7eb291cae64d5510f847af1d8216af4f2c6f4c2f/utils/text/cleaners.py#L93), which ends up running the text through unidecode. Either way, love the progress on this.
