### ISSUE TITLE
parser.add_argument sets unexpected default for '--data_path'

### ISSUE THREAD

**Issue by yweweler** [mozilla/TTS#76]
In train.py (master branch) the argument parser does set a rather unusual data_path as default.
https://github.com/mozilla/TTS/blob/3a72d75ecd3ffcbd95130b3f6004338bd2cea17d/train.py#L480-L481

Because there is always a data_path set in the arguments the data_path from the config is overriden
https://github.com/mozilla/TTS/blob/3a72d75ecd3ffcbd95130b3f6004338bd2cea17d/train.py#L494-L495

This yields to a rather unexpected crash of the application as the default path makes no sense.

My suggestion would be to just remove the default.

**Comment by erogol** [comment]
fixed. Thx !! All these small bugs cause big headaches.

**Comment by erogol** [comment]
I'll update the master soon. it will be there.
