### ISSUE TITLE
Problems training on a cached dataset

### ISSUE THREAD

**Issue by yweweler** [mozilla/TTS#78]
I am able to train on the LJ Speech v1.1 dataset without a problem when loading the raw audio files.

However, in order to accelerate training I want to use the pre-calculated features.
The actual pre-calculation worked seamlessly.
After extracting the features I changed the `dataset_path` to point to the cache folder, set `dataset_loader` to `TTSDatasetCached` and `dataset` to `tts_cached`.
Finally I let `meta_file_train` point to the generated `tts_metadata.csv` file.

Sadly when trying to train I run into the following error:
```python
...
| > Number of instances : 12000
 | > Max length sequence 188
 | > Min length sequence 6
 | > Avg length sequence 99.34648854961831
 | > 0 instances are ignored by min_seq_len (0)
 | > Batch group shuffling is active.
 | > Epoch 0/1000
Traceback (most recent call last):
  File "train.py", line 513, in <module>
    main(args)
  File "train.py", line 452, in main
    scheduler, ap, epoch)
  File "train.py", line 101, in train
    mel_input = mel_input.cuda(non_blocking=True)
RuntimeError: Source tensor must be contiguous.
```

Due to the following I am not sure if the current master code is meant to work:
https://github.com/mozilla/TTS/blob/3a72d75ecd3ffcbd95130b3f6004338bd2cea17d/datasets/TTSDatasetCached.py#L15-L16

@erogol , could you give me a hint?

**Comment by erogol** [comment]
easy fix is ```mel_input.contiguous()``` before the error line. I'll check for an permanent fix. Thx for pointing out.

**Comment by yweweler** [comment]
Thanks for the tip.

In case others come and don't know know what @erogol means: 
```python
mel_input = mel_input.contiguous()
mel_input = mel_input.cuda(non_blocking=True)
...
linear_input = linear_input.contiguous()
linear_input = linear_input.cuda(non_blocking=True)
```

**Comment by erogol** [comment]
I fixed this permanently on dev branch soon to be merged.
