### ISSUE TITLE
Could you please add some step-by-step instructions to convert text to speech from command line without using the outdated notebooks?

### ISSUE THREAD

**Issue by shyamalschandra** [mozilla/TTS#79]
I installed all the packages in Google Colab with GPU support following the instructions on the README.txt and the notebook but am unable to finish converting a piece of text into speech.

Could you please add another notebook with Colab support with everything in it or at least tell me how to execute the testing from command line without any python notebook?

I can do it myself but I don't want to waste time if someone else can do it faster.

**Comment by erogol** [comment]
After a small airport nerding 
https://colab.research.google.com/drive/1yUUBzdlavefXj3WRgK1SuWyJf92ME9_m

**Comment by ytang0024** [comment]
Thanks Eren, this is very helpful,

**Comment by tarekegn2020** [comment]
hi all..i see there is no helpful TTs development guide in google colab as long as I searched  except erogol's guide.Thanks sir.I tried to follow this guide...how about  validation and test steps.I am trying to implement TTs in new language .I am new for this issue again.

**Comment by nmstoker** [comment]
@tarekegn2020 - have you looked at the [wiki](https://github.com/mozilla/TTS/wiki)?

If that doesn't help I would recommend looking over the code in the repo itself and discussions in the [Discourse forum](https://discourse.mozilla.org/c/tts). Reading the code / folder layout is the best way to get the general hang of things and then if there are points you don't pick up from the wiki and discussions, then ask a question on the forum (don't forget to include context though!) With the project undergoing continuing development, it is likely that things will change often, so there's isn't (yet) a zero effort path for you but things continue to improve and with this being open source you can always contribute as you learn more yourself 🙂
