### ISSUE TITLE
Inference time metrics? 

### ISSUE THREAD

**Issue by claytonblythe** [mozilla/TTS#8]
Hello, I am very interested in this project, I am looking for a pytorch implementation of Tacotron/Tacotron2/WaveNet and may wish to contribute. Do you have any metrics on forward-pass time for inference on new text? I am looking to export a PyTorch model into Caffe2 and run it on a mobile platform.

**Comment by erogol** [comment]
Hi @claytonblythe. Always welcome any contributors. 

I do not have exact measures for inference yet. I am still working on the training part. I share once I have any.

The caveat of using Onnx to convert things to Caffe2 (if it is your plan) is it does not support RNN layers yet. So we have a plan to change the network architecture and make it RNN free for the sake of better mobilization. However, not in progress yet.

**Comment by claytonblythe** [comment]
That is good to know, I was not aware. I probably won't be at that stage for a while, but making it into an API with Flask or something similar would be awesome as well once you get to that point (longer term).

**Comment by erogol** [comment]
To give a small update, the following code takes 5.02 secs on a GPU already training another model.
```
sentence = "The human voice is the most perfect instrument of all."
alignment = tts(model, sentence, CONFIG, use_cuda, ap)
```
