### ISSUE TITLE
Noise in Test Files

### ISSUE THREAD

**Issue by mmomin93** [mozilla/TTS#81]
I am trying to train the Mozilla TTS on CPU (RAM 32GB) for the same dataset i.e., LJSpeech with the same config but the test files generated during training contains noise only.

**Comment by erogol** [comment]
How long did you train? Pls share your tensor board plots to see if something is wrong.

**Comment by mmomin93** [comment]
Will this TTS work fine with Urdu language ?

**Comment by mmomin93** [comment]
> How long did you train? Pls share your tensor board plots to see if something is wrong.

Problem with LJ Speech dataset was resolved. I got better output files.
