### ISSUE TITLE
NameError: name 'model_dict' is not defined

### ISSUE THREAD

**Issue by zfallahnejad** [mozilla/TTS#91]
I want to resume training from the last saved checkpoint, but this error happened. 
You can see my code in [this notebook](https://colab.research.google.com/drive/1kBGsfCGeLDLSUvaGrPsa_Zkvzme62rrX):

```
Traceback (most recent call last):
  File "train.py", line 513, in <module>
  main(args)
  File "train.py", line 408, in main
    for k, v in checkpoint['model'].items() if k in model_dict
  File "train.py", line 408, in <dictcomp>
    for k, v in checkpoint['model'].items() if k in model_dict
NameError: name 'model_dict' is not defined
```

**Comment by yweweler** [comment]
The master branch had a problem restoring the model.
I created a PR to fix it for now.

**Comment by erogol** [comment]
@yweweler I'd suggest you to use dev branch, I'll soon update the master.

**Comment by zfallahnejad** [comment]
Thanks, I used dev branch. Now I can resume training from the last saved checkpoint without any kind of error but training start from first epoch. 
You can see my code in [this notebook](https://colab.research.google.com/drive/1u22G1U6x4BIH6gtFcFFbRpZD-F9KlHjz)

**Comment by erogol** [comment]
@zfallahnejad epoch value is pecific to the new run but if you pay attention to "global step", it continues from the restored model. Do you think, epoch needs to follow the same convension?

**Comment by zfallahnejad** [comment]
Sorry, I didn't see "GlobalStep" so I wasn't expecting to see the epoch value starting from zero. Thanks again.

**Comment by erogol** [comment]
@zfallahnejad np :)
