### ISSUE TITLE
ParameterError: Audio buffer is not finite everywhere

### ISSUE THREAD

**Issue by zfallahnejad** [mozilla/TTS#96]
I want to train TTS for non-English audios. I trained a model for 5 epochs and test it using "Benchmark.ipynb", but this error happened. Do you have any solution for this problem? I would appreciate it if you could help me figure this out. You can see my code in [this link](https://colab.research.google.com/drive/1XODquiosMLhkB9STqVfAtqR2VcSG1Bgz).

**Comment by erogol** [comment]
5 epochs are not probably enough and the network outputs are out of the range. Let it train more and try again. Something would be visible around 25k iterations with larger enough dataset. Let me know the result.

**Comment by erogol** [comment]
@zfallahnejad I skimmed your code. Itlookslike your dataset is small. I'm not sure this size would be enough. Also at the validation phase keep an eye on "Decoder stopped with 'max_decoder_steps". It means, your model did not learn enough, and even it doesn't know where to stop in voice synthesis. You can only have good results after this line disappears.

**Comment by zfallahnejad** [comment]
You're right. Five epochs are not enough. I just want to make sure that there is no error, then I will train for more epochs.
I have 4692 audio files along with their transcripts in my dataset. I used 10 different audiobooks from 10 different speakers to prepare this dataset. Audio files vary in length from 1.5 to 10 seconds and have a total length of approximately 8.5 hours. I want to use this dataset for training a Speech-to-Text model like `deepspeech`. Then, I decided to take a subset of these audio files which belongs to a single speaker and train a Text-to-Speech model like TTS. I take 915 audio files (5769 seconds) of my dataset and trained 'TTS' for a few epoch as you saw before. I read somewhere that "two hours of dataset is enough for `wavenet` to generate crystal clear quality of audio", so I thought this subset can be good enough for the first try. What do you think? How much hours of dataset required to train a TTS model and produce good quality of voice?

**Comment by erogol** [comment]
I suggest you to use a single speaker dataset . I never tried TTS with multiple speakers yet. Until speaker embedding is implemented, it does not really make sense. I think, if you can find a single speaker dataset 8.5 hours would be enough for simple sentences but beyond that needs more data. My experience tells > 20 hours for a solid model depending on recording quality, word vocabulary size and so.

If you need to use the data at hand, then you can introduce a new layer which takes the user ID as an input to differentiate speakers. That would be quite easy to implement. If you are opt to, I can also provide some help for your questions.

**Comment by zfallahnejad** [comment]
Sorry. I forgot to mention such an important detail in my previous post. I take 915 audio files (5769 seconds) of my dataset which belongs to a single speaker.

**Comment by erogol** [comment]
so then it is too small to train a strong model. Try TTS, would be interesting to see on such a small dataset but I'd not keep a validation split. Hope it works at least to a level. 

If you are probing a european language dataset with no success, you can check http://www.caito.de/2019/01/the-m-ailabs-speech-dataset/

**Comment by ntsourakis** [comment]
I have trained the system using the LJSpeech-1.1 dataset for 500 epochs. I has taken few days to finish on a Intel(R) Xeon(R) Gold 5115 CPU @ 2.40GHz with a GeForce GTX TITAN.

Here is the last lines of the output:

\| > EPOCH END -- GlobalStep:187500  AvgTotalLoss:0.10175  AvgLinearLoss:0.04881  AvgMelLoss:0.04307  AvgStopLoss:0.00987  EpochTime:531.70  AvgStepTime:1.42              > DataLoader initialization                                                                                                                                                 \| > Data path: ../LJSpeech-1.1/                                                                                                                                             \| > Cached dataset: False                                                                                                                                                   \| > Number of instances : 1100                                                                                                                                              \| > Max length sequence: 182                                                                                                                                                \| > Min length sequence: 15                                                                                                                                                 \| > Avg length sequence: 99.0990909090909                                                                                                                                   \| > 0 instances are ignored (0)                                                                                                                                             \| > Validation                                                                                                                                                                \| > TotalLoss: 0.12232   LinearLoss: 0.04829   MelLoss:0.05317  StopLoss: 0.02086                                                                                           \| > TotalLoss: 0.12300   LinearLoss: 0.04788   MelLoss:0.05245  StopLoss: 0.02267                                                                                           \| > TotalLoss: 0.10996   LinearLoss: 0.04798   MelLoss:0.05263  StopLoss: 0.00936                                                                                           \| > TotalLoss: 0.10535   LinearLoss: 0.04762   MelLoss:0.05094  StopLoss: 0.00680                                                                                         \| > Train Loss: 0.04881   Validation Loss: 0.04796
--

However, running the Benchmark.ipynb notebook gives me:

"ParameterError: Audio buffer is not finite everywhere".

Any ideas what is going wrong or how to debug the problem?

**Comment by erogol** [comment]
@ntsourakis have you checked your results on Tensorboard ? I think your model is not trained well, especially attention part so it cannot generalize for test cases.

**Comment by erogol** [comment]
@ntsourakis how about attention plots for test sentences? 

Benchmark.ipynb works for me if I train on master branch. If there is something wrong should be easy to fix about some missing parameter or wrong argument.

Documentation stuff necessary you are right but mostly I work alone on this repo and cannot find among things. At some point, I hope.

**Comment by ntsourakis** [comment]
@erogol where do I find the attention plots for the test sentences? The only relevant info is something like the following:
![image](https://user-images.githubusercontent.com/7830603/52345889-9513d080-2a1e-11e9-8423-aa4eab3fb851.png)

I had to do few changes in the Benchmark.ipynb but the problem persists. E.g.:
CONFIG.num_freq -> CONFIG.audio['num_freq']

Anyway, for the time being I can use the TTS server to check the quality of my model.

Is it possible to generate a new run in the google drive? The one for LJSpeech-1.1 is not well alligned with the current version of the repo.

Of course any kind of documentation would be more than welcome!

**Comment by erogol** [comment]
@ntsourakis not these. on ```images``` tab

**Comment by ntsourakis** [comment]
This one?
![image](https://user-images.githubusercontent.com/7830603/52368483-cb694400-2a4e-11e9-9bf9-d588d20a319f.png)

**Comment by erogol** [comment]
@ntsourakis it does not seem bad but not the best either. I don't know in that case. The error states that the predicted values are out of range to be converted to audio.

**Comment by ntsourakis** [comment]
Thanks, it's not straightforward to decipher these plots without any documentation or reference plots. I am building another model with more epochs to compare.

**Comment by DrHaqkiem** [comment]
> @erogol I'm now trying with Mandarin Chinese, and found the result is really good ! But when at training and synthesis stages, `Decoder stopped with 'max_decoder_steps'` will sometimes occurs, and when at synthesis process, the server will be dead for a long time and the synthesis result cannot stop correctly.
> 
> Below is the log for training process:
> 
> ```
> > Using CUDA:  True
>  > Number of GPUs:  1
>  > Git Hash: b859eae
>  > Experiment folder: /media/disk1/TTS/keep/January-03-2019_11+38AM-TTS-master-b859eae
>  > Setting up Audio Processor...
>  | > fft size: 2048, hop length: 275, win length: 1102
>  | > Audio Processor attributes.
>    | > bits:None
>    | > sample_rate:22050
>    | > num_mels:80
>    | > min_level_db:-100
>    | > frame_shift_ms:12.5
>    | > frame_length_ms:50
>    | > ref_level_db:20
>    | > num_freq:1025
>    | > power:1.5
>    | > preemphasis:0.97
>    | > griffin_lim_iters:60
>    | > signal_norm:True
>    | > symmetric_norm:False
>    | > mel_fmin:0
>    | > mel_fmax:None
>    | > max_norm:1.0
>    | > clip_norm:True
>    | > do_trim_silence:True
>    | > n_fft:2048
>    | > hop_length:275
>    | > win_length:1102
>  | > Number of characters : 51
>  | > Num output units : 1025
> 
>  > Starting a new training
>  | > Model has 7058562 parameters
>  > Reading CNSpeech from - /media/disk1/DATASET/CNSpeech/
>  | > Number of instances : 9000
>  | > Max length sequence 200
>  | > Min length sequence 13
>  | > Avg length sequence 93.11644444444444
>  | > 0 instances are ignored by min_seq_len (0)
>  | > Batch group shuffling is active.
>  | > Epoch 0/1000
>    | > Step:9/281  GlobalStep:10  TotalLoss:0.31358  LinearLoss:0.14928  MelLoss:0.16430  StopLoss:0.60997  GradNorm:0.02703  GradNormST:1.89179  AvgTextLen:43.2  AvgSpecLen:144.8  StepTime:0.43  LR:0.000100
>    | > Step:19/281  GlobalStep:20  TotalLoss:0.29276  LinearLoss:0.14594  MelLoss:0.14682  StopLoss:0.56585  GradNorm:0.04390  GradNormST:2.43824  AvgTextLen:47.7  AvgSpecLen:156.8  StepTime:0.45  LR:0.000100
>    | > Step:29/281  GlobalStep:30  TotalLoss:0.27572  LinearLoss:0.14271  MelLoss:0.13302  StopLoss:0.60033  GradNorm:0.04548  GradNormST:1.57598  AvgTextLen:51.4  AvgSpecLen:162.5  StepTime:0.44  LR:0.000100
>    | > Step:39/281  GlobalStep:40  TotalLoss:0.26377  LinearLoss:0.13612  MelLoss:0.12764  StopLoss:0.64101  GradNorm:0.03810  GradNormST:0.76415  AvgTextLen:54.6  AvgSpecLen:186.6  StepTime:0.62  LR:0.000100
>    | > Step:49/281  GlobalStep:50  TotalLoss:0.25467  LinearLoss:0.12817  MelLoss:0.12650  StopLoss:0.63877  GradNorm:0.05581  GradNormST:0.41530  AvgTextLen:60.1  AvgSpecLen:198.5  StepTime:0.68  LR:0.000100
>    | > Step:59/281  GlobalStep:60  TotalLoss:0.24978  LinearLoss:0.12397  MelLoss:0.12581  StopLoss:0.48963  GradNorm:0.04008  GradNormST:1.05105  AvgTextLen:62.4  AvgSpecLen:199.7  StepTime:0.53  LR:0.000100
>    | > Step:69/281  GlobalStep:70  TotalLoss:0.23655  LinearLoss:0.11566  MelLoss:0.12089  StopLoss:0.62434  GradNorm:0.03411  GradNormST:0.88288  AvgTextLen:65.2  AvgSpecLen:204.8  StepTime:0.55  LR:0.000100
>    | > Step:79/281  GlobalStep:80  TotalLoss:0.23702  LinearLoss:0.11433  MelLoss:0.12270  StopLoss:0.55823  GradNorm:0.05801  GradNormST:0.34955  AvgTextLen:67.7  AvgSpecLen:214.4  StepTime:0.51  LR:0.000100
>    | > Step:89/281  GlobalStep:90  TotalLoss:0.23241  LinearLoss:0.11184  MelLoss:0.12058  StopLoss:0.59327  GradNorm:0.06232  GradNormST:0.73756  AvgTextLen:72.8  AvgSpecLen:222.0  StepTime:0.57  LR:0.000100
>    | > Step:99/281  GlobalStep:100  TotalLoss:0.23217  LinearLoss:0.11108  MelLoss:0.12109  StopLoss:0.46195  GradNorm:0.12620  GradNormST:0.81689  AvgTextLen:75.3  AvgSpecLen:234.3  StepTime:0.53  LR:0.000100
>    | > Step:109/281  GlobalStep:110  TotalLoss:0.23085  LinearLoss:0.10913  MelLoss:0.12172  StopLoss:0.47107  GradNorm:0.10292  GradNormST:0.66130  AvgTextLen:79.0  AvgSpecLen:240.3  StepTime:0.62  LR:0.000100
>    | > Step:119/281  GlobalStep:120  TotalLoss:0.22867  LinearLoss:0.10656  MelLoss:0.12211  StopLoss:0.47815  GradNorm:0.05386  GradNormST:0.48172  AvgTextLen:82.5  AvgSpecLen:263.8  StepTime:0.66  LR:0.000100
>    | > Step:129/281  GlobalStep:130  TotalLoss:0.23043  LinearLoss:0.10624  MelLoss:0.12419  StopLoss:0.43647  GradNorm:0.06916  GradNormST:0.87679  AvgTextLen:88.8  AvgSpecLen:280.8  StepTime:0.64  LR:0.000100
>    | > Step:139/281  GlobalStep:140  TotalLoss:0.22583  LinearLoss:0.10452  MelLoss:0.12131  StopLoss:0.51509  GradNorm:0.06729  GradNormST:0.41707  AvgTextLen:92.6  AvgSpecLen:287.2  StepTime:0.74  LR:0.000100
>    | > Step:149/281  GlobalStep:150  TotalLoss:0.22673  LinearLoss:0.10274  MelLoss:0.12399  StopLoss:0.59148  GradNorm:0.07088  GradNormST:0.77709  AvgTextLen:95.6  AvgSpecLen:298.8  StepTime:0.75  LR:0.000100
>    | > Step:159/281  GlobalStep:160  TotalLoss:0.22766  LinearLoss:0.10236  MelLoss:0.12529  StopLoss:0.53763  GradNorm:0.13571  GradNormST:0.33606  AvgTextLen:98.9  AvgSpecLen:307.1  StepTime:0.72  LR:0.000100
>    | > Step:169/281  GlobalStep:170  TotalLoss:0.22344  LinearLoss:0.09926  MelLoss:0.12418  StopLoss:0.49793  GradNorm:0.09214  GradNormST:0.31860  AvgTextLen:104.6  AvgSpecLen:324.0  StepTime:0.79  LR:0.000100
>    | > Step:179/281  GlobalStep:180  TotalLoss:0.22356  LinearLoss:0.09969  MelLoss:0.12386  StopLoss:0.49297  GradNorm:0.11090  GradNormST:0.28762  AvgTextLen:107.0  AvgSpecLen:334.0  StepTime:0.79  LR:0.000100
>    | > Step:189/281  GlobalStep:190  TotalLoss:0.22403  LinearLoss:0.10047  MelLoss:0.12356  StopLoss:0.70635  GradNorm:0.08995  GradNormST:2.37392  AvgTextLen:109.8  AvgSpecLen:340.9  StepTime:0.91  LR:0.000100
>    | > Step:199/281  GlobalStep:200  TotalLoss:0.22054  LinearLoss:0.09909  MelLoss:0.12144  StopLoss:0.54920  GradNorm:0.11654  GradNormST:0.95267  AvgTextLen:112.8  AvgSpecLen:344.8  StepTime:0.80  LR:0.000100
>    | > Step:209/281  GlobalStep:210  TotalLoss:0.21871  LinearLoss:0.09816  MelLoss:0.12055  StopLoss:0.46979  GradNorm:0.07364  GradNormST:0.37350  AvgTextLen:118.3  AvgSpecLen:362.6  StepTime:0.84  LR:0.000100
>    | > Step:219/281  GlobalStep:220  TotalLoss:0.22021  LinearLoss:0.09806  MelLoss:0.12215  StopLoss:0.40316  GradNorm:0.08723  GradNormST:0.49727  AvgTextLen:121.2  AvgSpecLen:386.9  StepTime:0.90  LR:0.000100
>    | > Step:229/281  GlobalStep:230  TotalLoss:0.22061  LinearLoss:0.09774  MelLoss:0.12287  StopLoss:0.56612  GradNorm:0.06141  GradNormST:1.46494  AvgTextLen:125.0  AvgSpecLen:390.9  StepTime:0.88  LR:0.000100
>    | > Step:239/281  GlobalStep:240  TotalLoss:0.21717  LinearLoss:0.09754  MelLoss:0.11963  StopLoss:0.45739  GradNorm:0.04648  GradNormST:0.59407  AvgTextLen:129.4  AvgSpecLen:404.6  StepTime:0.89  LR:0.000100
>    | > Step:249/281  GlobalStep:250  TotalLoss:0.21590  LinearLoss:0.09740  MelLoss:0.11850  StopLoss:0.40397  GradNorm:0.09705  GradNormST:0.58960  AvgTextLen:137.3  AvgSpecLen:434.3  StepTime:1.04  LR:0.000100
>    | > Step:259/281  GlobalStep:260  TotalLoss:0.21147  LinearLoss:0.09599  MelLoss:0.11549  StopLoss:0.36240  GradNorm:0.07264  GradNormST:0.72113  AvgTextLen:141.8  AvgSpecLen:442.6  StepTime:0.87  LR:0.000100
>    | > Step:269/281  GlobalStep:270  TotalLoss:0.20992  LinearLoss:0.09562  MelLoss:0.11429  StopLoss:0.36009  GradNorm:0.06833  GradNormST:0.60456  AvgTextLen:146.2  AvgSpecLen:447.5  StepTime:0.94  LR:0.000100
>    | > Step:279/281  GlobalStep:280  TotalLoss:0.20996  LinearLoss:0.09533  MelLoss:0.11464  StopLoss:0.36099  GradNorm:0.09024  GradNormST:0.67806  AvgTextLen:154.1  AvgSpecLen:481.7  StepTime:1.11  LR:0.000100
>    | > EPOCH END -- GlobalStep:282  AvgTotalLoss:0.74423  AvgLinearLoss:0.11106  AvgMelLoss:0.12538  AvgStopLoss:0.50779  EpochTime:197.81  AvgStepTime:0.70
>  > Reading CNSpeech from - /media/disk1/DATASET/CNSpeech/
>  | > Number of instances : 545
>  | > Max length sequence 186
>  | > Min length sequence 24
>  | > Avg length sequence 102.23119266055046
>  | > 0 instances are ignored by min_seq_len (0)
>  | > Validation
>    | > TotalLoss: 0.82989   LinearLoss: 0.10864   MelLoss:0.14082  StopLoss: 0.58043  
>    | > TotalLoss: 0.47506   LinearLoss: 0.09723   MelLoss:0.12011  StopLoss: 0.25771  
> /root/miniconda3/envs/pytorch/lib/python3.6/site-packages/librosa/util/utils.py:1725: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
>   if np.issubdtype(x.dtype, float) or np.issubdtype(x.dtype, complex):
>    | > Decoder stopped with 'max_decoder_steps
>    | > Decoder stopped with 'max_decoder_steps
>    | > Decoder stopped with 'max_decoder_steps
>    | > Decoder stopped with 'max_decoder_steps
>  | > Train Loss: 0.11106   Validation Loss: 0.09869
>  | > Best model saving with loss 0.11106 : /media/disk1/fangke/TextToSpeech/LearnStopTTS/TTS/../keep/January-03-2019_11+38AM-TTS-master-b859eae/best_model_49632.pth.tar
>  > Reading CNSpeech from - /media/disk1/DATASET/CNSpeech/
>  | > Number of instances : 9000
>  | > Max length sequence 200
>  | > Min length sequence 13
>  | > Avg length sequence 93.11644444444444
>  | > 0 instances are ignored by min_seq_len (0)
>  | > Batch group shuffling is active.
> | > Epoch 1/1000
> ```
> 
> I skimmed your implementation and still confused how could it happens, and how to solve it.

Hi, i just want to ask. Did you just proceed with the training even when the 
**_Decoder stopped with 'max_decoder_steps_** still occur ? how was the result/model with such error ?

i really need to know your outcomes regarding this issue :)

**Comment by MuruganR96** [comment]
@DrHaqkiem  sir, i also facing same issue.
```
the training even when the
**Decoder stopped with 'max_decoder_steps** still occur ? how was the result/model with such error ?
```
is it affected the model performance or not? :)
